Fix #10081 - Use fetchWithCache to retrieve and store basic gas estimates
MetaMask/metamask-extension pull request #10098
Opened 2020-12-17 14:24 UTC by darkwing

Fixes: #10081

Explanation:  It appears we're currently fetching basic gas estimates and storing the result along with last fetched time, and then doing expiration validation, when `fetchWithCache` can do all of this for us.

WIP

2021-01-22 04:06 UTC, Gudahtt requested changes
This looks great! Looks pretty close to ready after a rebase.

2021-01-22 04:06 UTC, Gudahtt commented on ui/app/ducks/gas/gas.duck.js
> -      (await getStorageItem('BASIC_PRICE_ESTIMATES_LAST_RETRIEVED')) ||
Should we add a migration to remove these old cached values? :thinking: I'm not sure when they'd ever get cleared out otherwise.

2021-01-22 04:06 UTC, Gudahtt commented on ui/app/ducks/gas/gas.duck.js
> +  console.log(
Nit: leftover `console.log`

2021-01-22 04:06 UTC, Gudahtt commented on ui/app/ducks/gas/gas.duck.js
> +  console.log(
One more below as well.

2021-01-22 04:06 UTC, Gudahtt commented on ui/app/ducks/gas/gas.duck.js
> -export function resetCustomGasState() {
I was about to ask why this was removed as well, but I think I see now. It's dead code.

2021-02-05 16:20 UTC, darkwing commented
Superceded by https://github.com/MetaMask/metamask-extension/pull/10384

2021-02-05 16:20 UTC, closed without merging