Update `ko` localized messages
MetaMask/metamask-extension pull request #10266
Opened 2021-01-23 04:42 UTC by Gudahtt

These translations were provided by Lionbridge.

2021-01-25 22:34 UTC, Gudahtt commented
If any community contributors would like to help review this PR, it would be greatly appreciated!

I'll tag anyone here that has contributed in the past: @x86kernel @bowbowbow @nujabes403 @hackmod @neutiyoo 

I wanted to give you all the opportunity to provide feedback because we owe our current translations to you. Please don't feel obliged if you don't have the time to review, and please let me know if you'd like me to stop tagging you for reviews in the future.

Thanks!

2021-01-26 01:51 UTC, neutiyoo requested changes

2021-01-26 01:51 UTC, neutiyoo commented on app/_locales/ko/messages.json
> +    "message": "자금 시간이 너무 김"
'자금' -> '잠금'

2021-01-26 01:55 UTC, nujabes403 commented
LGTM

2021-01-26 04:17 UTC, Gudahtt commented on app/_locales/ko/messages.json
> +    "message": "자금 시간이 너무 김"
Thanks, updated!
```suggestion
    "message": "잠금 시간이 너무 김"
```

2021-01-26 04:56 UTC, neutiyoo requested changes

2021-01-26 04:56 UTC, neutiyoo commented on app/_locales/ko/messages.json
> +  },
We are replacing `$1` with `Never` which is the value from `metametricsCommitmentsBoldNever`.
For example, `"$1 collect your full IP address"` will be `"Never collect your full IP address"`. This makes sense.

However, in Korean, we are replacing `$1` with `안 함` which is the value from `metametricsCommitmentsBoldNever`.

a) `$1은(는) 전체 IP 주소를 수집하지 않습니다.`
b) `안 함은(는) 전체 IP 주소를 수집하지 않습니다.`

and the a) will be the b) after `$1` is replaced with `안 함`.

In the case, the sentence won't make sense as I see it.

A possible solution can be the following:

we set `$1` as `하지 않습니다` and change the related ones as the following

- `전체 IP 주소를 수집$1.` (`전체 IP 주소를 수집하지 않습니다.`)
- `키, 주소, 거래, 잔액, 해시 또는 개인 정보를 수집$1.` (`키, 주소, 거래, 잔액, 해시 또는 개인 정보를 수집하지 않습니다.`)
- `수익을 위해 데이터를 판매$1.` (`수익을 위해 데이터를 판매하지 않습니다.`)

2021-01-26 06:14 UTC, neutiyoo requested changes

2021-01-26 06:14 UTC, neutiyoo commented on app/_locales/ko/messages.json
> +  },
## Background

We are replacing `$1` with `Never` which is the value from `metametricsCommitmentsBoldNever`.
For example, `"$1 collect your full IP address"` will be `"Never collect your full IP address"`. This makes sense.

## Problem
However, in Korean localization, we are replacing `$1` with `안 함` which is the value from `metametricsCommitmentsBoldNever`.

a) `$1은(는) 전체 IP 주소를 수집하지 않습니다.`
b) `안 함은(는) 전체 IP 주소를 수집하지 않습니다.`

The a) will be the b) after `$1` is replaced with `안 함`.
In the case, the sentence won't make sense as I see it.

## Solution
Therefore, the following should be changed:
- `metametricsCommitmentsBoldNever`
- `metametricsCommitmentsNeverCollectIP`
- `metametricsCommitmentsNeverCollectKeysEtc`
- `metametricsCommitmentsNeverSellDataForProfit`

A possible solution can be the following:

we can set `$1` as `하지 않습니다` and change the related ones as the following:

- `전체 IP 주소를 수집$1.` (`전체 IP 주소를 수집하지 않습니다.`)
- `키, 주소, 거래, 잔액, 해시 또는 개인 정보를 수집$1.` (`키, 주소, 거래, 잔액, 해시 또는 개인 정보를 수집하지 않습니다.`)
- `수익을 위해 데이터를 판매$1.` (`수익을 위해 데이터를 판매하지 않습니다.`)

2021-01-26 18:19 UTC, Gudahtt commented on app/_locales/ko/messages.json
> +  },
Great catch!

Either one of those options seem fine to me :thinking: Which do you think would be more idiomatic/commonplace?

2021-01-26 23:24 UTC, neutiyoo commented on app/_locales/ko/messages.json
> +  },
The second one looks good to me.

2021-01-27 00:06 UTC, neutiyoo requested changes

2021-01-27 03:22 UTC, neutiyoo commented on app/_locales/ko/messages.json
> +  },
I realized that solution B and C do not emphasize the negation so I came up with a A solution.
Unlike B or C, A emphasizes the negation with `절대` and is more close to the original one.

Therefore, the solution A is the more idiomatic one IMO.

2021-01-27 03:38 UTC, neutiyoo commented on app/_locales/ko/messages.json
> +  },
I realized that the previous solutions I mentioned(solution B and C) do not emphasize the negation.

Hence, I came up with the solution **A**.
Unlike B or C, A emphasizes the negation with `절대` making the meaning more close to the original one.

Therefore, the solution A is the correct and idiomatic one IMO.

2021-01-27 16:52 UTC, Gudahtt commented on app/_locales/ko/messages.json
> +  },
Great, thanks!

I have applied solution A in 0cb1ae01a530bd1508540ed02a0a2c96d115e7ea - let me know if I've made a mistake anywhere.

2021-01-27 17:02 UTC, Gudahtt commented on app/_locales/ko/messages.json
> +  },
Thanks! I've applied the first solution you suggested here: 71a9f57c696db63891bc7f710696f284f6ee9afa

Please let me know if I've made a mistake, or if you think solution 2 would be more appropriate.

2021-01-28 00:20 UTC, neutiyoo submitted a review, later dismissed
LGTM

2021-02-02 14:52 UTC, merged

2021-02-02 14:56 UTC, Gudahtt commented
This PR has been rebased onto `develop` before merging to ensure that the `yourSigRequested` message was not present (it was removed in #10300).

Thanks again for the review!