Allow editing transaction amount after clicking max (#8475)
MetaMask/metamask-extension pull request #10278
Opened 2021-01-25 02:00 UTC by adonesky1

Fixes: #8475

Explanation:  Removes maxModeOn prop from UnitInput component which when true disabled the input. Per request on issue #8475, removing the maxModeOn flag allows users to edit currency input when transaction max button is selected.

Manual testing steps:  
  - Enter send flow for Eth
  - Click Max
  - Edit on send amount input should be enabled

2021-01-25 03:12 UTC, adonesky1 commented
> **CLA Signature Action:**
> 
> Thank you for your submission, we really appreciate it. We ask that you read and sign our [Contributor License Agreement](https://metamask.io/cla.html) before we can accept your contribution. You can sign the CLA by just by adding a comment to this pull request with this exact sentence:
> 
> > _**I have read the CLA Document and I hereby sign the CLA**_
> 
> By commenting with the above message you are agreeing to the terms of the CLA. Your account will be recorded as agreeing to our CLA so you don't need to sign it again for future contributions to this repository.
> 
> **0** out of **1** committers have signed the CLA.
> ❌ @adonesky1

I have read the CLA Document and I hereby sign the CLA

2021-01-25 13:33 UTC, Gudahtt requested changes
Thanks for the contribution! There are a couple of tasks left to finishing this:

* The prop `maxModeOn` is still being passed into `currency-input.component` from `currency-input.contiainer`. Could you removed this unusued prop from the container component?

* Max mode remains toggled after the user edits the gas amount, which doesn't seem ideal. Ideally max mode would toggle when the user edited the gas amount, so that the user could click "Max" again and go back to the maximum amount. This is probably easiest to accomplish by editing [this change handler](https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/pages/send/send-content/send-amount-row/send-amount-row.component.js#L96).

Additionally, the CLA bot requires you to state that you agree to the CLA by making a comment with _just that phrase_. That last attempt didn't work because you included a quote of the CLA bot comment.

2021-01-26 04:49 UTC, adonesky1 commented
Thanks for your feedback @Gudahtt!

Regarding this piece:
> * Max mode remains toggled after the user edits the gas amount, which doesn't seem ideal. Ideally max mode would toggle when the user edited the gas amount, so that the user could click "Max" again and go back to the maximum amount. This is probably easiest to accomplish by editing [this change handler](https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/pages/send/send-content/send-amount-row/send-amount-row.component.js#L96).

I'm completely new to this codebase so I could very well be missing something but won't the AdvancedGasInputs need to toggle off maxMode in their change handler(s) to produce the desired behavior you describe?

Thanks!

2021-01-26 04:49 UTC, adonesky1 commented
I have read the CLA Document and I hereby sign the CLA

2021-01-26 13:04 UTC, Gudahtt commented
>I'm completely new to this codebase so I could very well be missing something but won't the AdvancedGasInputs need to toggle off maxMode in their change handler(s) to produce the desired behavior you describe?

I was thinking of the _amount_ field, not the gas fields. That's an interesting point though :thinking: Maybe it should toggle when gas is edited as well? I think we should leave it for now so that it matches the behaviour of the token send, but that's something worth considering in the upcoming confirmation screen redesign.

But about that request to update the change handler - sorry, you can disregard it completely! I just realized that `maxMode` is _already_ being untoggled in that handler (via `updateAmount`), so the behaviour I requested is already present. My mistake.

So all that's left now is to get rid of the unused prop.

2021-01-27 16:11 UTC, Gudahtt commented
Almost there! The e2e tests can be tricky to debug, so I looked into this one. The last test failure is caused by an assertion in our e2e tests that (for some reason) ensures the input element is disabled. That line should be removed.

From line 311 of `metamask-ui.spec.js`:
```
assert.equal(await inputAmount.isEnabled(), false)
```

2021-01-27 16:17 UTC, adonesky1 commented
Ah thanks @Gudahtt! Will do!

2021-01-27 16:43 UTC, Gudahtt approved these changes
LGTM, great work! I've tested this, and it appears that this now works the same for ETH sends as it already did for token transfers. The amount can be freely edited after clicking max.

2021-01-27 16:43 UTC, merged