Porting MetaMask for Safari 14
MetaMask/metamask-extension pull request #10426
Opened 2021-02-12 02:31 UTC by xlab

Updates: #8879

Explanation:  

This PR should ignite interest in the _official_ support and builds of the extension for Safari 14.

The extension works fine, except (obviously) HW devices are unsupported, also some styles are not rendering pixel-perfectly.

2021-02-12 15:45 UTC, brad-decker commented
@xlab -- when you say "obviously no HW device support" could you elaborate? 😬

2021-02-19 09:12 UTC, deegital commented
> @xlab -- when you say "obviously no HW device support" could you elaborate? 😬

afaik due to runtime.onConnectExternal is not available in safari (& ff and edge)

2021-02-20 09:30 UTC, xlab commented
> @xlab -- when you say "obviously no HW device support" could you elaborate? 😬

I meant "out of the box" since most of the plugin works just fine after conversion, HW support is not explicitly available since WebUSB standard is not implemented in Safari at all. Not sure about UDF option, but ledger connection just errored out when I tried.

I am not well familiar with these extensions yet, but I assume the companion app that is native (in Swift) could provide the necessary HID integration that is exposed to the web part using some kind of IPC bridge.

2021-03-03 22:41 UTC, darkwing requested changes
This is an interesting proof of concept.  I was eventually able to see the icon in my Safari browser (yay!) but while trying to use our test dapp (https://metamask.github.io/test-dapp/), I was seeing an empty window when trying to get permissions:

<img width="1015" alt="Notification" src="https://user-images.githubusercontent.com/46655/109882243-3346e480-7c3f-11eb-92de-085f7d8863c2.png">

I'm also not seeing any useful error messages anywhere so I'm sort of stuck as to the current problem.

2021-03-04 18:29 UTC, darkwing commented
Thank you for putting the effort into this @xlab!  I was able to build and launch! 👍 

I tried this out and a big blocker seems to be that the MetaMask popup doesn't appear when trying to connect accounts in our test dapp (https://metamask.github.io/test-dapp/).

I'll shift this to a draft PR and am excited to see any progress you make on this!  🥇

2021-03-04 19:41 UTC, xlab commented
Hmm, sometimes when that happens (very rarely for me) a refresh of the background page helps:
<img width="513" alt="Screenshot 2021-03-04 at 20 37 31" src="https://user-images.githubusercontent.com/477998/110020146-85643480-7d29-11eb-8176-806aa934ceb5.png">
(click it and in the Inspector -> Refresh)

It works fine for me on the page you've shared. Btw, thanks for this test page! But yeah, since the background page sometimes crashes, it's might be not ready to release to public. But in my case this almost never happens and I use the extension freely for the apps.

There is work required to enable HW wallets. I actually don't have much time to work on this, so this draft can be a good starting point for anybody participating in this effort.

2021-05-12 03:48 UTC, bitweedx64 commented
<img width="1112" alt="截屏2021-05-12 上午11 48 06" src="https://user-images.githubusercontent.com/83109252/117915471-ed318f80-b317-11eb-9fad-af268d0451f6.png">

In my case, the errors are what shows above.
Hopes this feedback helps : )

2021-05-12 07:01 UTC, bitweedx64 commented
<img width="1149" alt="Screen Shot 2021-05-12 at 3 00 58 PM" src="https://user-images.githubusercontent.com/83109252/117932412-e8c6a000-b332-11eb-9782-125a5762712e.png">
It can't run, and get this error as result.

2021-06-05 15:03 UTC, xlab commented
Hey guys I've updated the safari "port" of extension to `v9.5.9`, works fine on Safari `Version 14.1.1 (16611.2.7.1.4)`

Except that the Ledger Live bridge is not working, because security disallows to connect from remote HTTPS host to localhost's WebSocket:

<img width="1181" alt="Screenshot 2021-06-05 at 17 08 20" src="https://user-images.githubusercontent.com/477998/120896011-3aa7d080-c628-11eb-8923-d9edeed6bc03.png">

```
[blocked] The page at https://metamask.github.io/eth-ledger-bridge-keyring/ was not allowed to run insecure content from ws://localhost:8435/.
```

Any idea how this can be resolved? Also, why external host?

2021-06-05 15:04 UTC, xlab commented
@bitweedx64 I've disabled lockdown for Safari branch, for now

2021-06-23 07:57 UTC, dvcrn commented
I wanted to give this a go to see if I could get the ws connection working but I'm also not able to properly run this. Not getting past the white window when clicking on the extension

2022-01-15 19:19 UTC, byoriolserra commented
I am very interested in your contribution @xlab . So if I understand correctly, the MetaMask Team would need to sign the extension officially in the Safari Extensions Store so that the user doesn't have to create it themselves nor have to enable development settings every time they launch Safari?

2022-01-17 16:06 UTC, xlab commented
> So if I understand correctly, the MetaMask Team would need to sign the extension officially in the Safari Extensions Store

Yeah they need to publish it to the store, otherwise there is no sense to use dev mode, as it's always reset during browser restart. And we cannot publish, as crypto-related extensions are allowed only from established names, I cannot publish my own fork.

But this issue aside, simply using the converter won't help to avoid rare issues mentioned in this thread above.

1) Websocket https stuff
2) Occasional hiccups of the background worker
3) Some styling issues (minor bug)

2022-01-22 13:47 UTC, iMonZ commented
> > So if I understand correctly, the MetaMask Team would need to sign the extension officially in the Safari Extensions Store
> 
> Yeah they need to publish it to the store, otherwise there is no sense to use dev mode, as it's always reset during browser restart. And we cannot publish, as crypto-related extensions are allowed only from established names, I cannot publish my own fork.
> 
> But this issue aside, simply using the converter won't help to avoid rare issues mentioned in this thread above.
> 
> 1. Websocket https stuff -> [Porting MetaMask for Safari 14 #10426 (comment)](https://github.com/MetaMask/metamask-extension/pull/10426#issuecomment-855252529)
> 2. Occasional hiccups of the background worker -> [Porting MetaMask for Safari 14 #10426 (comment)](https://github.com/MetaMask/metamask-extension/pull/10426#issuecomment-790879135)
> 3. Some styling issues (minor bug)

Who is the responsible person to publish this extension?

2022-01-29 09:41 UTC, BrentMifsud commented
any updates on this?

2022-02-16 20:48 UTC, philiparpin commented
Any updates here? I'm also very interested in this :)

2022-09-24 09:52 UTC, Jax0rz commented
Any update for Safari?

2023-08-03 14:05 UTC, closed without merging