Update v9.1.0 changelog
MetaMask/metamask-extension pull request #10526
Opened 2021-02-26 00:08 UTC by tmashuang

[Original auto-generated changelog](https://gist.github.com/tmashuang/f08f65bf90f7df8411c1d274f527223b). 

Removed non-user facing issues and re-summarized some of the descriptions.

2021-02-26 00:13 UTC, gigilove2001 approved these changes

2021-02-26 00:14 UTC, gigilove2001 approved these changes

2021-02-26 15:38 UTC, darkwing commented
So far so good but I don't want to approve until that PR is out of draft.  What is our practice for change logs when it comes to changes without an issue, because have plenty of those?

2021-02-26 17:16 UTC, brad-decker requested changes

2021-02-26 17:16 UTC, brad-decker commented on CHANGELOG.md
> +- [#9724](https://github.com/MetaMask/metamask-extension/pull/9724): Add custom network RPC method.
9724 is listed twice.

2021-03-01 18:00 UTC, brad-decker approved these changes

2021-03-01 18:34 UTC, merged