Convert useSwapsEthToken hook to a selector
MetaMask/metamask-extension pull request #10568
Opened 2021-03-03 10:38 UTC by danjm

The `useSwapsEthToken` does not need to be a hook, as it does not rely on other hooks (with the exception of useSelector, the need for which can just be met with a selector). It can be simplified to being a selector. This will also make it easier to use in more contexts (as it won't need to follow the rules of hooks)

2021-03-03 15:46 UTC, brad-decker requested changes
Is the hook file still being used after this? it doesn't appear to be removed in this PR.

2021-03-03 15:46 UTC, brad-decker commented on ui/app/selectors/selectors.js
> +import {
Review note: this is just the code from the hook, now as a selector, it doesn't appear to be modified except in name, and that it is now a selector that expects state as an argument.

2021-03-03 15:46 UTC, brad-decker commented on ui/app/selectors/selectors.js
> + * selected account's ETH balance, as expected by the Swaps API.
This doc block now should probably have a @param given it expects state.

2021-03-03 17:58 UTC, ryanml approved these changes, later dismissed
++

2021-03-03 23:57 UTC, danjm commented
@brad-decker your comments are addressed in the latest commit

2021-03-04 06:30 UTC, koosy79 approved these changes

2021-03-04 12:23 UTC, brad-decker approved these changes

2021-03-04 17:16 UTC, merged