✏️ open url of etherscan
MetaMask/metamask-extension pull request #11218
Opened 2021-06-01 18:42 UTC by jasonzhouu

Fixes: #
the param of _viewOnEtherscan is url of tx in etherscan, instead of txid.

Explanation:  
open url of tx in etherscan

2021-06-04 19:46 UTC, Gudahtt commented
Thanks for the contribution! Could you run `yarn lint:fix` to fix the lint errors?

2021-06-29 21:07 UTC, jasonzhouu commented
I have read the CLA Document and I hereby sign the CLA

2021-07-01 04:12 UTC, jasonzhouu commented
@Gudahtt Thank you for reply! fixed.

2021-09-10 18:30 UTC, brad-decker requested changes
One minor thing then we can get this landed .sorry for the delay @jasonzhouu

2021-09-10 18:30 UTC, brad-decker commented on yarn.lock
> +  version "1.0.30001241"
[Q] was this a necessary change? If not could we remove it and rebase?

2021-11-05 20:43 UTC, darkwing commented
Superceded by https://github.com/MetaMask/metamask-extension/pull/12609

2021-11-05 20:43 UTC, closed without merging