Add confirm-encryption-public-key component to Storybook
MetaMask/metamask-extension pull request #11227
Opened 2021-06-03 05:21 UTC by EtDu

- Adds `confirm-encryption-public-key` component to Storybook. 
- Modifies the actual component use pull the account from props instead of state because it otherwise doesn't update on account change.

2021-06-03 05:59 UTC, Alanling888 approved these changes, later dismissed

2021-06-03 18:44 UTC, SirJosh1987 approved these changes

2021-06-03 18:45 UTC, SirJosh1987 approved these changes, later dismissed

2021-06-15 21:26 UTC, kumavis requested changes
@EtDu looks like it needs a rebase to deconflict and get a dep update

2021-06-23 03:45 UTC, closed without merging