Add gas constnats
MetaMask/metamask-extension pull request #11248
Opened 2021-06-07 19:34 UTC by brad-decker

First PR breaking up from #10965 - This one just adds gas constants for 21000 and 100000 that are shared throughout the app.

2021-06-07 22:13 UTC, darkwing commented on jsconfig.json
> +  "exclude": ["node:console"]
Is this supposed to be in this PR?  Seems out of place.

2021-06-07 22:13 UTC, darkwing commented on test/stub/tx-meta-stub.js
> +        gas: GAS_LIMITS,
I think this needs to be `GAS_LIMITS.SIMPLE`

2021-06-07 22:15 UTC, darkwing requested changes
I think I spotted an incorrect variable and an extra modified file, so marking as Request Changes.

2021-06-08 14:26 UTC, brad-decker commented
thanks @darkwing, ready for another review.

2021-06-08 15:05 UTC, darkwing approved these changes

2021-06-08 15:25 UTC, merged