Prevent propType errors in for TransactionIcon statuses
MetaMask/metamask-extension pull request #11316
Opened 2021-06-15 22:04 UTC by darkwing

While looking at the send flow for EIP1559, I spotted a console error about 'confirmed' and 'submitted' not being valid status.  Fixing this.

2021-06-15 23:25 UTC, ryanml submitted a review, later dismissed
++

2021-06-16 14:02 UTC, brad-decker requested changes
While this solves the propType error... 

this status isn't mapped...

2021-06-16 14:02 UTC, brad-decker commented on ui/components/app/transaction-icon/transaction-icon.js
> +    TRANSACTION_STATUSES.CONFIRMED,
these statuses are not dealt with and default to the OK_COLOR which is fine for confirmed, but needs to be PENDING_COLOR for submitted. I'm also unsure why we have a mix of individual statuses and group statuses in this map but that's a story for a different day. If we just add SUBMITTED: PENDING_COLOR to the status color map that'll be sufficient for now.

2021-06-16 14:43 UTC, brad-decker approved these changes

2021-06-23 23:19 UTC, adonesky1 approved these changes

2021-06-23 23:39 UTC, merged