Add 'isInput' prop to make Chip wrap an input element
MetaMask/metamask-extension pull request #11392
Opened 2021-06-25 20:28 UTC by adonesky1

Explanation:  Adds `isInput` prop to Chip component to make it wrap an input. We would like to reuse the chip component for Backup Confirmation of Recovery Phrase stage of the new onboarding flow:
<img width="624" alt="Screen Shot 2021-06-25 at 3 25 21 PM" src="https://user-images.githubusercontent.com/34557516/123481581-90d5b700-d5c9-11eb-903c-46ed743fc1d7.png">

Storybook:
<img width="329" alt="Screen Shot 2021-06-25 at 3 28 44 PM" src="https://user-images.githubusercontent.com/34557516/123481919-08a3e180-d5ca-11eb-933c-7bbbd4eef36d.png">

2021-06-25 20:49 UTC, brad-decker requested changes
I probably overdid it with the suggestions, and it might fail lint if you accept them all, so feel free to accept these or make the changes locally yourself. This is awesome but we'll want to track the value of the input outside of the Chip so we need to be able to pass the value in and get a update when it changes.

2021-06-25 20:49 UTC, brad-decker commented on ui/components/ui/chip/chip.js
> +  isInput,
I think you'll likely want the value to be accessible outside of this chip, so might I suggest:

```suggestion
inputValue,
setInputValue,
```

2021-06-25 20:49 UTC, brad-decker commented on ui/components/ui/chip/chip.js
> +  const [inputValue, setInputValue] = useState('');
```suggestion

```

2021-06-25 20:49 UTC, brad-decker commented on ui/components/ui/chip/chip.js
> +      {isInput && (
```suggestion
      {inputValue && (
```

2021-06-25 20:49 UTC, brad-decker commented on ui/components/ui/chip/chip.js
> +            setInputValue(e.target.value);
```suggestion
            setInputValue && setInputValue(e.target.value);
```

2021-06-25 20:49 UTC, brad-decker commented on ui/components/ui/chip/chip.js
> +  isInput: PropTypes.bool,
```suggestion
  inputValue: PropTypes.string,
  setInputValue: PropTypes.function,
```

2021-06-25 20:49 UTC, brad-decker commented on ui/components/ui/chip/chip.stories.js
> +  <Chip isInput borderColor={select('borderColor', COLORS, COLORS.UI3)} />
```suggestion
  <Chip inputValue={inputValue} setInputvalue={setInputValue} borderColor={select('borderColor', COLORS, COLORS.UI3)} />
```

2021-06-25 20:49 UTC, brad-decker commented on ui/components/ui/chip/chip.stories.js
> +
```suggestion
  const [inputValue, setInputValue] = useState('');
```

2021-06-25 21:01 UTC, adonesky1 commented
> I probably overdid it with the suggestions, and it might fail lint if you accept them all, so feel free to accept these or make the changes locally yourself. This is awesome but we'll want to track the value of the input outside of the Chip so we need to be able to pass the value in and get a update when it changes.

Yeah I originally had it like this and then made it stateful with the intention to pass in the setters/value when it was used. But that was dumb...

2021-06-25 21:08 UTC, brad-decker commented
Actually now that I'm thinking about it, we already have a children prop on this component, considering that the styles are not at all required to be on the chip itself, why not do something like the following:

```
const ChipWithInput = () => {
  return (
    <Chip>
      {... your input related code}
    </Chip>
   );
```

That way we don't overcomplicate the Chip Component? Just a suggestion

2021-06-25 21:49 UTC, brad-decker commented on ui/components/ui/chip/chip-with-input.js
> +    <Chip className={className} borderColor={borderColor}>
[req] lets add 'chip--with-input' to className, just in case we need to modify any styles in the future from the main component.

2021-06-25 22:15 UTC, brad-decker approved these changes, later dismissed
LGTM, just a nit

2021-06-25 22:15 UTC, brad-decker commented on ui/components/ui/chip/index.js
> +export { default } from './chip';
unnecessary change?

2021-06-28 13:57 UTC, adonesky1 commented on ui/components/ui/chip/index.js
> +export { default } from './chip';
fixed 💯

2021-06-28 14:43 UTC, brad-decker requested changes
sorry one minor suggestion on making style slightly more specific.

2021-06-28 14:43 UTC, brad-decker commented on ui/components/ui/chip/chip.scss
> +  &__input {
one more minor change req:

make this &--with-input &__input {

just so that the styles are specific to the ChipWithInput component

2021-06-28 15:22 UTC, brad-decker approved these changes

2021-06-28 20:03 UTC, ryanml approved these changes
lgtm!

2021-06-28 21:09 UTC, merged