Add connected-sites component to Storybook
MetaMask/metamask-extension pull request #11415
Opened 2021-06-29 07:05 UTC by EtDu

- Adds `connected-sites` component to Storybook

2021-07-06 14:18 UTC, brad-decker requested changes

2021-07-06 14:18 UTC, brad-decker commented on ui/pages/connected-sites/connected-sites.stories.js
> +  title: 'Confirmation Screens',
[REQ] Probably needs a title update

2021-07-27 17:39 UTC, EtDu commented on ui/pages/connected-sites/connected-sites.stories.js
> +  title: 'Confirmation Screens',
yes good catch

2021-08-12 17:02 UTC, darkwing approved these changes, later dismissed

2021-08-30 22:55 UTC, kumavis approved these changes

2021-08-30 22:56 UTC, merged