Add confirm-token-transaction-base component to Storybook
MetaMask/metamask-extension pull request #11414
Opened 2021-06-29 06:50 UTC by EtDu

- Adds `confirm-token-transaction-base` component to Storybook

2021-06-29 14:49 UTC, darkwing requested changes
`console.log` needs removal

2021-07-06 14:16 UTC, brad-decker approved these changes

2021-07-06 14:17 UTC, brad-decker requested changes

2021-07-06 14:17 UTC, brad-decker commented on ui/pages/confirm-token-transaction-base/confirm-token-transaction-base.stories.js
> +  console.log('kresna', metamask);
```suggestion
```

2021-08-12 17:05 UTC, darkwing approved these changes

2021-08-17 05:33 UTC, merged