Setting tx param type before signing transactions
MetaMask/metamask-extension pull request #11497
Opened 2021-07-10 05:54 UTC by ryanml

Fixes MetaMask/metamask-extension#11491

2021-07-10 06:57 UTC, SirJosh1987 approved these changes

2021-07-10 13:11 UTC, brad-decker requested changes
One minor req, thanks for taking this one on!

2021-07-10 13:11 UTC, brad-decker commented on app/scripts/controllers/transactions/index.js
> +    const type = isEIP1559Transaction(txMeta)
One final thing I forgot is that we should honor the type provided by dapps if they set type themselves.

2021-07-12 16:45 UTC, brad-decker commented on app/scripts/controllers/transactions/index.js
> +    const type = isEIP1559Transaction(txMeta)
oh i see that the type parameter is set *before* the spread of txParams so this is already cared for!

2021-07-12 16:45 UTC, brad-decker approved these changes

2021-07-12 20:21 UTC, adonesky1 approved these changes

2021-07-12 20:26 UTC, merged