Fix #11695 - Prevent maxFee and maxPriorityFee imbalance
MetaMask/metamask-extension pull request #11700
Opened 2021-07-30 23:53 UTC by darkwing

Fixes: #11695

2021-07-31 00:15 UTC, danjm commented on app/_locales/en/messages.json
> +    "message": "Max fee must be larger than max priority fee"
Perhaps this should say `"Max fee cannot be lower than max priority fee"`, because it can be equal, not just "larger"

2021-07-31 00:38 UTC, danjm approved these changes

2021-07-31 01:27 UTC, danjm approved these changes

2021-07-31 04:02 UTC, danjm requested changes
There is a case in which this doesn't work: if the max priority fee is set so high that there would also be a `editGasMaxPriorityFeeHigh` warning, then the `editGasMaxPriorityFeeHigh` warning will show, and the save button will not be disabled.

2021-07-31 17:16 UTC, danjm approved these changes

2021-08-01 15:12 UTC, dan437 approved these changes

2021-08-02 14:07 UTC, merged