Update contract address validation in Swaps for different networks
MetaMask/metamask-extension pull request #11845
Opened 2021-08-16 14:32 UTC by dan437

## Explanation
We now check in Swaps if a contract address is in our list of allowed contract addresses for active network. If our API would ever be compromised, we will have this additional validation on the client-side to prevent swaps against an invalid contract address.

## Manual testing steps
  - Successfully swap tokens on different networks

2021-08-18 16:47 UTC, darkwing submitted a review, later dismissed
Looks good and works well!

2021-08-19 16:52 UTC, darkwing approved these changes, later dismissed

2021-08-24 15:41 UTC, danjm commented on shared/constants/swaps.js
> +  [RINKEBY_CHAIN_ID]: WETH_CONTRACT_ADDRESS,
Will the `WETH_CONTRACT_ADDRESS` work on rinkeby? WETH probably has a different address on rinkeby...

2021-08-24 15:42 UTC, danjm commented on shared/constants/swaps.js
> +  [RINKEBY_CHAIN_ID]: WETH_CONTRACT_ADDRESS,
yeah, this might be the token on rinkeby: https://rinkeby.etherscan.io/token/0xc778417e063141139fce010982780140aa0cd5ab

2021-08-24 15:59 UTC, danjm requested changes
Only one concern that I mention in my comment. The rest of the PR looks good.

2021-08-25 11:20 UTC, danjm submitted a review, later dismissed

2021-09-08 11:26 UTC, danjm approved these changes, later dismissed

2021-09-08 18:04 UTC, danjm approved these changes

2021-09-08 18:05 UTC, darkwing approved these changes

2021-09-08 18:08 UTC, merged