Locale en message fix- not connected this site"
MetaMask/metamask-extension pull request #12064
Opened 2021-09-10 10:18 UTC by parseb

Fixes: #
* Added missing word to. 
* Edited **onnectedAccountsEmptyDescription**  message. 
Explanation:  

Web3 sites are likely applications, mostly SPAs. Avoinding the word _site_ (3 in one message.)

 ___
- "message": "MetaMask is not connected this site. To connect to a web3 site, find the connect button on their site."
+ "message": "MetaMask is not connected to this page. If this is a web3 application, find and click the connect button."

___
I have read the CLA Document and I hereby sign the CLA.

2021-09-10 10:23 UTC, parseb commented
I have read the CLA Document and I hereby sign the CLA

2021-09-10 11:49 UTC, aitorla commented
I have read the CLA Document and I hereby sign the CLA

2021-09-10 20:38 UTC, brad-decker requested changes
Thanks for the contribution. I have a suggestion that was collab'd with our design/ux team so we can merge if it is accepted. Also not sure why the bot didn't pick up your CLA signing so hopefully when CI runs again you'll get a green check.

2021-09-10 20:38 UTC, brad-decker commented on app/_locales/en/messages.json
> +    "message": "MetaMask is not connected to this page. If this is a web3 application, find and click the connect button."
[REQ] We appreciate your recommendations for copy changes! Definitely want to get that bug fixed, but we would like to keep the 'site' vernacular versus page, application, etc. 

```suggestion
    "message": "MetaMask is not connected to this site. To connect to a web3 site, find and click the connect button."
```

2021-09-12 18:08 UTC, parseb commented
I think there' something wrong with my local configuration that somehow adds two accounts as authors.

2021-09-13 16:00 UTC, darkwing approved these changes

2021-09-17 17:34 UTC, parseb commented
I have read the CLA Document and I hereby sign the CLA.

2021-09-22 16:09 UTC, darkwing commented
Sorry the clabot is giving you issues @parseb !  If you're having issues, maybe you could open a second pull request?

2021-09-22 17:36 UTC, brad-decker approved these changes

2021-09-22 17:37 UTC, brad-decker commented
@parseb if you rebase / squash into one commit under the parseb username it should be good.

2021-09-23 09:35 UTC, parseb commented
Moved to #12186

2021-09-23 09:35 UTC, closed without merging