Add amount-max-button to Storybook
MetaMask/metamask-extension pull request #12078
Opened 2021-09-13 01:13 UTC by EtDu

2021-09-13 15:07 UTC, darkwing requested changes

2021-09-13 15:07 UTC, darkwing commented on ui/pages/send/send-content/send-amount-row/amount-max-button/amount-max-button.stories.js
> +  console.log('state', isDraftTransactionInvalid);
Nit: Remove console.log

2021-09-29 18:43 UTC, brad-decker approved these changes

2021-09-30 17:07 UTC, darkwing approved these changes

2021-10-06 17:33 UTC, darkwing approved these changes

2021-10-14 18:41 UTC, closed without merging