Add send-amount-row to Storybook
MetaMask/metamask-extension pull request #12080
Opened 2021-09-13 01:22 UTC by EtDu

2021-09-13 15:00 UTC, darkwing requested changes

2021-09-13 15:00 UTC, darkwing commented on ui/pages/send/send-content/send-amount-row/send-amount-row.stories.js
> +  console.log('tokens', store.getState());
Nit: Remove `console.log`

2021-09-28 16:19 UTC, adonesky1 commented on ui/pages/send/send-content/send-amount-row/send-amount-row.stories.js
> +    />
```suggestion
 <div style={{ maxWidth: '500px' }}>
      <SendAmountRow
        amount={text('Amount', '100000000000000')}
        inError={boolean('In Error', false)}
        asset={asset}
      />
    </div>
```

Without somehow containing this I'm seeing this:
![Screen Shot 2021-09-28 at 11 19 15 AM](https://user-images.githubusercontent.com/34557516/135126339-c559eaf4-4e42-4c96-ad68-e7c975516bdd.png)

2021-09-29 03:07 UTC, EtDu commented
@adonesky1 Suggestion applied. Will provide boxes for future components

2021-09-30 17:07 UTC, darkwing submitted a review, later dismissed

2021-09-30 20:20 UTC, adonesky1 commented
@EtDu looks like this might need a little rebase/lint care 😄

2021-10-01 17:15 UTC, adonesky1 commented
@EtDu possibly not but do we want to hook up the MaxButton to do something in Storybook?

2021-10-01 17:22 UTC, adonesky1 commented on ui/pages/send/send-content/send-amount-row/send-amount-row.stories.js
> +        asset={asset}
maybe we could add 
```
updateSendAmount={action('Update Send Amount')}
```
?

2021-10-14 18:41 UTC, closed without merging