Fix spinner issue on seed word request
MetaMask/metamask-extension pull request #1225
Opened 2017-03-21 14:00 UTC by Zanibas

Fixes #1033 by adding an action to hide the spinner within an error conditional.

2017-03-21 14:35 UTC, danfinlay approved these changes
LGTM, caught another possible instance of the same bug.

2017-03-21 14:35 UTC, flyswatter commented on ui/app/actions.js
>          if (err) return dispatch(actions.displayWarning(err.message))
Could this line cause the same sort of bug?

2017-03-21 14:46 UTC, Zanibas commented on ui/app/actions.js
>          if (err) return dispatch(actions.displayWarning(err.message))
Should we just have default behavior for when we display a warning to hide the loading indicator?

2017-03-21 14:46 UTC, Zanibas commented on ui/app/actions.js
>          if (err) return dispatch(actions.displayWarning(err.message))
I don't see any cases where this would be a problem--we always want to return user control as soon as we have the need to display a warning...right?

2017-03-21 14:57 UTC, flyswatter commented on ui/app/actions.js
>          if (err) return dispatch(actions.displayWarning(err.message))
I agree, that would help mitigate this. Could add it to the showWarning reducer.

2017-03-21 16:16 UTC, Zanibas commented
Check dis out

2017-03-21 19:55 UTC, danfinlay requested changes
I think that last commit may have reintroduced bugs by not hiding loading indication on success.  Please clarify?

2017-03-21 19:55 UTC, flyswatter commented on ui/app/actions.js
> +      // dispatch(actions.hideLoadingIndication())
Do we really want to comment this out?  What if there is not an error?  Does `showAccountsPage` also hide loading indication?

2017-03-21 19:55 UTC, flyswatter commented on ui/app/actions.js
> +      // dispatch(actions.hideLoadingIndication())
Do we really want to comment this out?  What if there is not an error?  Does `showAccountDetail` also hide loading indication?

2017-03-21 20:36 UTC, Zanibas commented on ui/app/actions.js
> +      // dispatch(actions.hideLoadingIndication())
Whoops I just missed this one.

2017-03-22 03:35 UTC, danfinlay requested changes
One more possible bug spot.

2017-03-22 03:35 UTC, flyswatter commented on ui/app/actions.js
> -      dispatch(actions.hideLoadingIndication())
Here again, probably removed it but need it for success case.

2017-03-22 22:32 UTC, danfinlay approved these changes
Yay!

2017-03-22 22:32 UTC, merged