Implement Network Switcher designs
MetaMask/metamask-extension pull request #12260
Opened 2021-09-30 23:07 UTC by segun

Fixes: #11473 

Explanation:  

Improve the current network switcher.

[Stories and notes](https://www.notion.so/7af6f9afb8634469ac881acb0c9fd9b4?v=92f5f9ccb9804651a29cea4e313428b5&p=792db403977f49afad30a21e8f47402b)

Designs are ready [here](https://www.figma.com/file/F8NVM9pM8RpIe3YNbHsk5r/Switch-Network?node-id=54%3A364)

Manual testing steps:  
  - 
  - 
  -

2021-10-20 20:58 UTC, mcmire submitted a review, later dismissed
LGTM.

2021-10-21 08:48 UTC, danjm requested changes
Only one comment

2021-10-26 01:27 UTC, danjm approved these changes

2021-10-26 01:28 UTC, danjm submitted a review, later dismissed
LGTM

2021-10-28 08:53 UTC, danjm approved these changes

2021-10-28 19:18 UTC, brad-decker approved these changes

2021-10-28 19:31 UTC, merged