Extracting out error and warning code from useGasFeeInputs hook
MetaMask/metamask-extension pull request #12283
Opened 2021-10-05 19:26 UTC by jpuri

Fixes: #

Explanation:  

Manual testing steps:  
  - 
  - 
  -

2021-10-12 14:26 UTC, danjm requested changes
Great work overall. Adding a number of comments here

2021-10-15 13:23 UTC, danjm approved these changes
LGTM! Great work!

2021-10-15 18:37 UTC, darkwing approved these changes

2021-10-15 18:43 UTC, adonesky1 approved these changes
Awesome work Jyoti! Thanks for cleaning this up so much!

2021-10-18 11:55 UTC, merged