Fix/ux papercuts account details issue #12292
MetaMask/metamask-extension pull request #12399
Opened 2021-10-19 09:48 UTC by igorms-cons

Fixes: 
Updating account details modal view
(new branch for CLA issues)

Issue: https://github.com/MetaMask/metamask-extension/issues/12292

2021-10-19 14:31 UTC, david0xd submitted a review, later dismissed
Looks good. 
As agreed on the way with requirements related to the figma.
Fore more info consult: https://github.com/MetaMask/metamask-extension/issues/12292

2021-10-21 12:15 UTC, david0xd submitted a review, later dismissed

2021-10-21 20:06 UTC, darkwing requested changes

2021-11-01 10:12 UTC, danjm reviewed
LGTM, just need to fix e2e tests

2021-11-02 10:48 UTC, igorms-cons commented
> LGTM, just need to fix e2e tests

@danjm  fixed

2021-11-04 06:56 UTC, danjm submitted a review, later dismissed

2021-11-05 14:08 UTC, darkwing approved these changes, later dismissed

2021-11-05 14:43 UTC, adonesky1 commented on ui/components/ui/qr-code/qr-code.js
> +import copyToClipboard from 'copy-to-clipboard';
we have a hook `useCopyToClipBoard` that we should probably use here instead?

2021-11-05 14:44 UTC, adonesky1 requested changes
On small thing!

2021-11-05 17:03 UTC, adonesky1 approved these changes
LGTM!

2021-11-05 17:32 UTC, igorms-cons commented
@danjm  @adonesky1  all good, thx!

2021-11-08 14:38 UTC, darkwing approved these changes

2021-11-09 10:58 UTC, danjm approved these changes

2021-11-09 10:58 UTC, merged