Fix/ux papercuts transaction details issue #12295
MetaMask/metamask-extension pull request #12401
Opened 2021-10-19 13:22 UTC by igorms-cons

Fixes:

Updating account details modal view

Issue: https://github.com/MetaMask/metamask-extension/issues/12295

2021-10-19 13:25 UTC, igorms-cons commented
Also on the issue #12295 it was mentioned to pay attention to the format dat (24:40 instead of 00:40). Of course i did not tried to send a transaction at midnight but when i tested with a milli timestamp between 0:00am and 1:am, the format was good.

2021-10-20 08:39 UTC, david0xd submitted a review, later dismissed
Looks good.

2021-10-20 11:47 UTC, mhasanagic commented
Retested - verified by QA

2021-10-21 11:33 UTC, david0xd approved these changes

2021-10-21 21:02 UTC, darkwing approved these changes

2021-10-29 13:21 UTC, danjm requested changes

2021-11-02 08:34 UTC, igorms-cons commented on ui/components/ui/sender-to-recipient/sender-to-recipient.component.js
> -          <span>{addressOnly ? `${t('to')}: ` : ''}</span>
yes!

2021-11-02 09:53 UTC, igorms-cons commented on ui/components/ui/sender-to-recipient/sender-to-recipient.component.js
> -          <span>{addressOnly ? `${t('to')}: ` : ''}</span>
On the figma the label "_to_" disappeared. 
You want me to keep it then?

2021-11-02 09:54 UTC, igorms-cons commented on ui/components/ui/sender-to-recipient/sender-to-recipient.component.js
> -          <span>{addressOnly ? `${t('to')}: ` : ''}</span>
like I removed "_from_" line 74

2021-11-03 15:26 UTC, danjm commented on ui/components/ui/sender-to-recipient/sender-to-recipient.component.js
> -          <span>{addressOnly ? `${t('to')}: ` : ''}</span>
oh, I thought that change wasn't being made in others parts of the app, but I can see that it is, okay, what you have is fine

2021-11-03 15:26 UTC, danjm approved these changes

2021-11-03 15:26 UTC, merged