Organize Storybook Components
MetaMask/metamask-extension pull request #12424
Opened 2021-10-21 16:01 UTC by EtDu

This PR aims to classify and visually organise all storybook components.

Each component is sorted exactly how it appears in the project.

fixes #12551

2021-10-21 20:40 UTC, georgewrmarshall requested changes
This is looking good! I like the use of `'App/'`, `'UI/` and `'Pages'/` groupings. I think nesting any further may reduce discoverability? Also some of the groupings do not make complete sense to me e.g. `'UI/Modal/Actionable Message'`

I would suggest at least for this first run only having one level of groupings reflect the location of the stories in the app. This will help:

- Find stories more easily
- Understand how the code is organized 

Could we remove any nesting of groups further than `'App/'`, `'UI/` and `'Pages'/`?

So it would look something like

```
title: 'FOLDER_NAME/COMPONENT_NAME'
```

At least for this addition. We may be able to identify further nested groupings in future but for now I think this change will already make a huge difference!

2021-10-28 19:10 UTC, brad-decker approved these changes

2021-10-29 18:01 UTC, georgewrmarshall commented
@EtDu also if we could fix this warning about duplicate story titles

<img width="645" alt="Screen Shot 2021-10-26 at 11 28 54 AM" src="https://user-images.githubusercontent.com/8112138/139481457-b80ac9f9-035b-4a63-b5a2-031599ef8bd6.png">

2021-10-29 18:16 UTC, jj-crypto approved these changes

2021-10-29 18:16 UTC, jj-crypto approved these changes

2021-11-01 16:27 UTC, georgewrmarshall reviewed
This looks excellent. Nice work! 💯  Just flagged one page but everything else looks great!

2021-11-01 16:27 UTC, georgewrmarshall commented on ui/pages/settings/settings.stories.js
> +  title: 'Pages/Send/Settings Page',
Should this be 
```suggestion
  title: 'Pages/Settings',
```

2021-11-01 16:37 UTC, georgewrmarshall commented
I've also created this issue #12551 if you want to include it in this PR? Also fine as separate.

2021-11-02 00:53 UTC, EtDu commented
> I've also created this issue #12551 if you want to include it in this PR? Also fine as separate.

good to go

2021-11-02 16:12 UTC, georgewrmarshall approved these changes
LGTM! Nice work 💯

2021-11-02 16:22 UTC, georgewrmarshall commented
To fix your lint issue just change `Base` story in `toggle-button.stories.js` to `DefaultStory`. Sorry I forgot I updated that one https://github.com/MetaMask/metamask-extension/blob/develop/ui/components/ui/toggle-button/toggle-button.stories.js#L13

2021-11-07 14:05 UTC, merged