[WIP] Introduce QRSigner into Metamask - sign
MetaMask/metamask-extension pull request #12468
Opened 2021-10-25 07:18 UTC by soralit

## Description: 
This PR is the second step to introduce QR based signer into MetaMask: supporting sign transactions and messages with QR based signer.
## Changes: 
1. Add `QRHardwareSignRequest` component under `QRHardwarePopover` to watch and show QR-based transactions.
2. Add methods in `metamask-controller` to interact with `QRHardwareKeyring`.
3. Modify `home.component` to make QR-based transaction popover shows/disappears in a right way. 

## New Dependencies: 
1. [@keystonehq/bc-ur-registry-eth](https://github.com/KeystoneHQ/keystone-airgaped-base/tree/master/packages/ur-registry-eth): this package is one data schema of Ethereum related data based on bc-ur. Reference: https://github.com/KeystoneHQ/Keystone-developer-hub/blob/main/research/ethereum-qr-data-protocol.md
2. [qrcode.react](https://github.com/zpao/qrcode.react): This package is used to generate and display QRCode image
3. [uuid](https://github.com/uuidjs/uuid): We use this package to encode/decode sign-request-id as we defined in `bc-ur-registry-eth`

#### Relating PR: https://github.com/MetaMask/metamask-extension/pull/12065

2021-10-25 20:21 UTC, darkwing requested changes
I've left a few code styling comments and will continue testing user testing over the coming days!

2021-10-26 06:31 UTC, jj-crypto submitted a review, later dismissed

2021-11-01 02:21 UTC, soralit commented
![image](https://user-images.githubusercontent.com/44085950/139612613-dd172c6f-3bb1-4082-9313-d18fa8e9eaa8.png)
Hey @darkwing @holantonela , I use the component `PageContainerFooter` to refine the ui. How do you like it now?

2021-11-01 14:39 UTC, holantonela commented
> I use the component `PageContainerFooter` to refine the ui. How do you like it now?

Excellent! The footer looks appropriated now. Please, let's include some padding between the text containers and the QR. Added a reference [here](https://drive.google.com/file/d/1c77i1xOL0_ia4vF-Tif5i5OPwEbQrfWL/view?usp=sharing).

2021-11-02 01:35 UTC, closed without merging