Ledger WebHID What's New popup
MetaMask/metamask-extension pull request #12501
Opened 2021-10-27 18:33 UTC by danjm

Adds a What's New notification for Ledger Live users, instructing them that they can now connect with WebHID

![Screenshot from 2021-10-27 15-59-54](https://user-images.githubusercontent.com/7499938/139125898-61127ad6-8923-4fde-a659-5866d3a969fb.png)

2021-10-29 13:51 UTC, darkwing requested changes
One tiny bit of feedback

2021-10-29 14:53 UTC, darkwing submitted a review, later dismissed

2021-10-29 23:59 UTC, jj-crypto submitted a review, later dismissed

2021-11-01 10:51 UTC, jj-crypto approved these changes, later dismissed

2021-11-01 16:28 UTC, mcmire commented on app/_locales/en/messages.json
> +    "message": "You can go to the Advanced tab of settings and switch the 'Preferred Ledger Connection Type' to 'WebHID'.",
Other than this, what do you think about dropping the "You can go to..." and just saying "Go to..."?

2021-11-02 08:43 UTC, danjm commented on app/_locales/en/messages.json
> +    "message": "You can go to the Advanced tab of settings and switch the 'Preferred Ledger Connection Type' to 'WebHID'.",
There is a help article linked from the advanced tab in settings

The wording has been updated in 0fb7ff3ec to reflect the above suggestion and a suggestion from marketing

2021-11-02 17:07 UTC, tmashuang approved these changes, later dismissed
lgtm the notification shows with newly, and preexisting, connected ledger accounts via ledger live.

2021-11-02 18:24 UTC, jpuri approved these changes, later dismissed
LGTM

2021-11-03 16:26 UTC, danjm commented on app/_locales/en/messages.json
> +    "message": "Ledger connection improvement.",
```suggestion
    "message": "Ledger connection improvement",
```

2021-11-03 16:34 UTC, danjm commented on ui/selectors/selectors.js
> +  const supportsWebHid = Boolean(window.navigator.hid);
Apparently we may stop using the `in` operator soon: https://github.com/MetaMask/eth-ledger-bridge-keyring/pull/106#discussion_r718939285

So I will change this to an `undefined` check

2021-11-03 16:34 UTC, danjm commented on ui/selectors/selectors.js
> +  const supportsWebHid = Boolean(window.navigator.hid);
```suggestion
  const supportsWebHid = window.navigator.hid !== undefined;
```

2021-11-03 21:18 UTC, mcmire approved these changes
Updates look good!

2021-11-03 21:25 UTC, darkwing approved these changes

2021-11-03 22:07 UTC, ryanml approved these changes

2021-11-03 22:35 UTC, merged