Allow injection in IFrames + dynamic IFrames
MetaMask/metamask-extension pull request #1259
Opened 2017-03-26 12:07 UTC by sponnet

When working with DAPPS that open Iframes - web3 is not injected there. These small changes fix this, and inject a web3 instance in every iframe that gets opened on page-start , and also on dynamically generated iframes.

We needed this for out TrellEth project 

https://twitter.com/sponnet/status/845100360540794880
https://press.swarm.city/meet-trelleth-73affcb82d02#.zhzcq2nhq
https://github.com/trelleth 

I hope this could get modified in the main MetaMask product. It would open up much possibilities !

2017-03-26 13:48 UTC, GriffGreen approved these changes
Looks pretty straight forward :-)

2017-03-26 14:53 UTC, danfinlay requested changes
Curious about a change to the default injection logic. We just modified this so it would stop injecting Inc xml, and this looks like it might hit other files.

2017-03-26 14:53 UTC, flyswatter commented on app/scripts/contentscript.js
> +    return true
This line would attempt to inject in any file without a doctyoe. What types of files are those? Surely HTML is already covered with line 74?

2017-03-26 14:53 UTC, flyswatter commented on app/manifest.json
> +      "all_frames": true
This looks simple enough.

2017-03-26 15:57 UTC, sponnet commented on app/scripts/contentscript.js
> +    return true
Iframes apparently return null as a doctype in this function.

2017-03-26 16:01 UTC, sponnet commented on app/scripts/contentscript.js
> +    return true
I'll try to make and add an example site URL  that opens the different situations in where iframes could be opened. Then you can check that they effectively don't send along a doctype. But I agree that this injection logic is there for a reason. If XML files actually send a doctype , they shouldn't be affected by this change tho.

2017-03-26 16:01 UTC, sponnet commented on app/scripts/contentscript.js
> +    return true
I'll try to make and add an example site URL  that opens the different situations in where iframes could be opened. Then you can check that they effectively don't send along a doctype. But I agree that this injection logic is there for a reason. If XML files actually send a doctype , they shouldn't be affected by this change tho.

2017-03-26 16:22 UTC, kingflurkel commented on app/scripts/contentscript.js
> +    return true
Sponnet likes to say things twice :)

2017-03-26 16:26 UTC, sponnet commented on app/scripts/contentscript.js
> +    return true
The importance of TrellEth cannot be overstated :)

2017-03-26 17:13 UTC, kumavis commented
@sponnet @kingflurkel can you tell us more about your use case, and TrellEth?

2017-03-26 22:53 UTC, kingflurkel commented
https://press.swarm.city/meet-trelleth-73affcb82d02
@kumavis

2017-03-26 22:54 UTC, kingflurkel commented
@kumavis We create this as a trello powerup, a sort of plugin. It works by injecting customizable iframes in trello when needed.

2017-03-26 23:43 UTC, kumavis commented on app/scripts/contentscript.js
> +    return true
`document.doctype` has really poor support in general it seems

2017-03-27 06:28 UTC, sponnet commented
The use of iframes in the trello power ups is mandatory, it's part of how their plugin architecture works.

Besides that IMHO it would make sense to look for a better implementation of the isAllowedSuffix function that also detects the mime type in an iframe. ( Ex opening an XML file in an iframe ) 

This pr works when the main window provides the doctype , then it only injects in HTML doctype. I haven't noticed mupliple injections in non iframe containing pages using this change.

2017-03-27 18:15 UTC, flyswatter commented
Fixes #1223

2017-03-27 18:15 UTC, kumavis commented
I'm willing to merge this and wait for push back from the community

2017-03-27 18:20 UTC, kumavis commented
maybe we can add an iframe detection? `top !== window` or something

http://stackoverflow.com/questions/326069/how-to-identify-if-a-webpage-is-being-loaded-inside-an-iframe-or-directly-into-t

2017-03-27 23:15 UTC, danfinlay approved these changes
Alright, I can't think of any more situations this will go poorly in, let's try it, and see if anyone complains.

If you guys make some ethereum-enabled Trello powerup, we might have to switch to Trello.

2017-03-28 00:38 UTC, flyswatter commented
It seems like our continuous integration tests aren't able to test off of someone else's remote?  I'm going to pull this & resubmit as a separate PR.

2017-03-28 00:52 UTC, merged

2017-03-28 00:52 UTC, flyswatter commented
Merged in #1271.  Weird CI issues prevented merging this PR.