Transition fixes
MetaMask/metamask-extension pull request #1296
Opened 2017-03-30 20:33 UTC by Zanibas

Look at that beauty:
- The first-time transitions are a lot better now. A lot better.
- Transitions between the account detail screen and other screens is now smoother (no more of that jumping)

Fixes #670

2017-03-30 20:34 UTC, Zanibas commented
Still requires our tests to pass--not sure what's going on, would like to pair on this.

2017-03-30 20:38 UTC, danfinlay approved these changes
The code looks good.  I want that animation... Ok fine I'm pulling.  This is exciting.

2017-03-30 20:38 UTC, flyswatter commented on ui/app/accounts/index.js
> -              paddint: '10px',
lol how

2017-03-30 20:38 UTC, flyswatter commented on ui/app/actions.js
> -        forceUpdateMetamaskState(dispatch)
ooooo

2017-03-30 20:42 UTC, danfinlay requested changes
Opened an existing vault for the first time, saw seed word screen with no seed words.

The first time controller is defaulting to first time, even though it's adding new data to the schema.

Need to add a migration to set `firstTime` to false if a vault exists already.

2017-04-05 20:39 UTC, Zanibas commented
Closing in favor of breaking these changes into separate parts for better debugging.

2017-04-05 20:39 UTC, closed without merging