Tx insights fixes
MetaMask/metamask-extension pull request #12988
Opened 2021-12-06 20:15 UTC by danjm

Fixes issues Dec 2: 1, 2 and 3, and Dec 6: 5 and 6, in the v10.8.0 RC doc

2021-12-06 22:18 UTC, darkwing requested changes

2021-12-06 22:18 UTC, darkwing commented on ui/components/app/transaction-list-item-details/transaction-list-item-details.component.js
> +                <Disclosure title="Activity log" size="small">
Nit: needs localization

2021-12-06 23:15 UTC, danjm commented on ui/components/app/transaction-list-item-details/transaction-list-item-details.component.js
> +                <Disclosure title="Activity log" size="small">
fixed in bad0de1ce

2021-12-06 23:16 UTC, darkwing approved these changes, later dismissed

2021-12-07 00:42 UTC, adonesky1 submitted a review, later dismissed
LGTM!

2021-12-07 01:15 UTC, georgewrmarshall submitted a review, later dismissed
LGTM! Read through [doc](https://docs.google.com/document/d/1vy-i_UdG4SbmmKenXwY6ih30lAuFU6SQfRaG_QmKjAc/edit#) and have tested that:

1. Empty activity log is hidden on receive transaction ✅ 
<img width="933" alt="Screen Shot 2021-12-07 at 2 00 10 PM" src="https://user-images.githubusercontent.com/8112138/144947630-03178d40-412a-4e52-91f8-6e6bb06c0d37.png">

2. Correct method name shown ✅ 
<img width="472" alt="Screen Shot 2021-12-07 at 2 03 53 PM" src="https://user-images.githubusercontent.com/8112138/144947673-0396741e-ca55-480d-a962-ad475dbe275b.png">

3. Cursor is not pointer on error messages

https://user-images.githubusercontent.com/8112138/144947955-99d782e1-6091-4d34-874c-c7a3aaee83cb.mov


https://user-images.githubusercontent.com/8112138/144947969-10c30628-7352-4bee-a7a0-31dd05ee7eed.mov

2021-12-07 02:05 UTC, danjm commented
@darkwing @georgewrmarshall @adonesky1 I just pushed one more commit that fixes the last issue to do with transaction insights "Swaps and Simple Send txs have 404 error code in Transaction Data in Tx details."

2021-12-07 05:31 UTC, georgewrmarshall approved these changes
lgtm

2021-12-07 15:06 UTC, darkwing approved these changes

2021-12-07 15:12 UTC, merged