Fix typo in conversion.utils.js
MetaMask/metamask-extension pull request #12998
Opened 2021-12-07 12:44 UTC by eltociear

specificy -> specificity

2021-12-07 14:32 UTC, darkwing requested changes

2021-12-08 04:39 UTC, eltociear commented
@darkwing Thanks!

2021-12-08 14:18 UTC, Gudahtt commented on shared/modules/conversion.utils.js
> +    throw new Error('Must specificity valid base');
```suggestion
    throw new Error('Must specify valid base');
```

2021-12-08 14:19 UTC, Gudahtt approved these changes
LGTM! @darkwing I have committed the change you suggested

2021-12-08 15:55 UTC, darkwing approved these changes

2021-12-08 15:57 UTC, merged