Improvements for multi-layer fee UX
MetaMask/metamask-extension pull request #13547
Opened 2022-02-08 06:52 UTC by danjm

Fixes #13541
Fixes #13542
Fixes #13543
Fixes #13544

https://user-images.githubusercontent.com/7499938/152933848-2f8af31e-8d14-44ee-a7e6-a57de4476677.mp4

2022-02-08 13:21 UTC, danjm commented on ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
> -            !isMultiLayerFeeNetwork && (
No code changes here except the removal of `!isMultiLayerFeeNetwork && ` and then all the code having to change indentation

2022-02-16 20:13 UTC, darkwing commented
We need to run the `yarn verify-scripts:fix` command but this looks and works great!

2022-03-06 23:16 UTC, bdresser commented
@danjm @darkwing thank you for putting this PR together! Anything we can help with around testing / QA to help get it over the finish line?

2022-03-21 16:32 UTC, darkwing requested changes

2022-03-21 16:32 UTC, darkwing commented on ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
> +                hideLabel={false && !useNativeCurrencyAsPrimaryCurrency}
Looks like leftover debug?

2022-03-23 18:29 UTC, danjm commented on ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
> +                hideLabel={false && !useNativeCurrencyAsPrimaryCurrency}
yes, nice catch

2022-03-29 13:08 UTC, darkwing approved these changes

2022-03-29 15:20 UTC, adonesky1 commented
Also is there some reason we don't show the **Total L2 Gas Fees** on the transaction details view?

2022-03-29 15:24 UTC, adonesky1 commented on ui/ducks/send/send.js
> +        error.message.includes('gas required exceeds allowance'));
Is this redundant? Or are `gas required exceeds allowance` and `gas required exceeds allowance or always failing transaction` separate and different error messages?

2022-03-29 15:30 UTC, adonesky1 commented on ui/pages/confirm-transaction-base/confirm-transaction-base.component.js
> +            <div className="confirm-page-container-content__currency-container test">
is `test` supposed stay there in the className?

2022-03-29 15:32 UTC, adonesky1 reviewed
A few questions/comments

2022-03-29 15:43 UTC, brad-decker approved these changes

2022-03-29 19:21 UTC, merged