Success page
MetaMask/metamask-extension pull request #13570
Opened 2022-02-09 14:50 UTC by VSaric

fixes: #13444

**Explanation:**  Success page. 

**Screencast:**

https://user-images.githubusercontent.com/92527393/153225485-d23a4c46-6b6c-4eb1-8cb0-fd3d525beb82.mov

2022-02-14 13:45 UTC, mirjanaKukic commented
Verified by QA

2022-02-18 14:36 UTC, brad-decker requested changes

2022-02-23 16:31 UTC, adonesky1 approved these changes
LGTM!

2022-02-23 16:39 UTC, brad-decker approved these changes

2022-02-23 16:41 UTC, merged