[UPDATE] NFT Auto-detect copy change to align with mobile
MetaMask/metamask-extension pull request #13655
Opened 2022-02-16 19:24 UTC by sethkfman

Explanation:  Updated copy to align with improved mobile copy for NFT auto-detect

Related: https://github.com/MetaMask/metamask-mobile/pull/3762

2022-02-16 20:55 UTC, darkwing approved these changes

2022-02-17 14:48 UTC, PeterYinusa approved these changes

2022-02-17 15:43 UTC, adonesky1 requested changes
@sethkfman we already [have language similar to this](https://github.com/MetaMask/metamask-extension/blob/fa467d1b8cdce0e5690497baf1c2568df0385e1a/app/_locales/en/messages.json#L3512) under the `AutoDetect NFTs` preferences. In this PR you're adding this description about the risks of auto-detection to the preference that is only about using OpenSea's API. Perhaps we want to tweak the AutoDetect NFT's language but I think it should be under that preference and not under Enable OpenSea's API

2022-08-16 20:44 UTC, brad-decker commented
@sethkfman is this something we should close or do you still see a need for this change?

2022-11-04 17:36 UTC, brad-decker commented
Closing, if this is something we still want we can reopen the PR and update it. Thanks @sethkfman and @adonesky1

2022-11-04 17:36 UTC, closed without merging