Write down your SRP page fixes
MetaMask/metamask-extension pull request #13729
Opened 2022-02-23 08:55 UTC by filipsekulic

Fixes: https://github.com/MetaMask/metamask-extension/issues/13457

Screenshot: 

<img width="1512" alt="Screenshot 2022-02-23 at 09 45 48" src="https://user-images.githubusercontent.com/92310504/155287373-aed88498-4532-4ca2-a86c-833b5448ad8d.png">

Screencast:

https://user-images.githubusercontent.com/92310504/155287404-b11b0eeb-051d-4c37-ad91-1fecaf4115b4.mov

2022-02-24 12:22 UTC, mirjanaKukic commented
Verified by QA

2022-02-24 21:03 UTC, darkwing requested changes, later dismissed

2022-02-25 11:46 UTC, filipsekulic commented on ui/pages/onboarding-flow/recovery-phrase/review-recovery-phrase.js
> +          <div className="recovery-phrase__footer--copy-and-hide">
Fixed in: b090fe4585b5248eeb1ef6233dd7701ad667ef69

2022-02-25 13:28 UTC, jpuri approved these changes, later dismissed

2022-02-28 17:20 UTC, AndreySttar commented on app/_locales/en/messages.json
> +    "message": "Hide the Seed phrase"
S

2022-02-28 17:37 UTC, AndreySttar commented on ui/pages/onboarding-flow/recovery-phrase/review-recovery-phrase.js
> +          <div className="recovery-phrase__footer--copy-and-hide">
Y

2022-02-28 17:38 UTC, AndreySttar commented
b090fe4585b5248eeb1ef6233dd7701ad667ef69

2022-03-01 08:29 UTC, filipsekulic commented on app/_locales/en/messages.json
> +    "message": "Hide the Seed phrase"
Fixed in: 89e82d9b54e553974dc264304c834aad8eb91f76

2022-03-02 15:03 UTC, adonesky1 approved these changes
LGTM

2022-03-07 18:30 UTC, jpuri approved these changes

2022-03-07 18:36 UTC, adonesky1 requested changes
Sorry just looped back and noticed possible redundancy?

2022-03-08 15:37 UTC, adonesky1 commented on ui/pages/onboarding-flow/recovery-phrase/review-recovery-phrase.js
> +  const [hiddenPhrase, setHiddenPhrase] = useState(false);
Ok makes sense.

2022-03-08 15:37 UTC, adonesky1 approved these changes

2022-03-08 15:38 UTC, merged