Improve the flex property of network form
MetaMask/metamask-extension pull request #13781
Opened 2022-02-27 13:42 UTC by ForestTigerKing

Explanation:  
When editing the network, the text of "Delete" “Cancel” “Save” button to be displayed as multiple lines,  such as Chinese and Japanese.  I improve the flex property of network form  from "flex: 1 0" to "flex: 1 0 auto".  Although it can not completely solve this problem, it has improved a lot.

Before modified：
![813f4194d6b518adf579bd5d52a7ba0](https://user-images.githubusercontent.com/35363592/155884757-44255a2d-e883-4f0c-af32-28f3b38c7ee6.png)
![281d2a1b61058c89fbbdbfed35914a3](https://user-images.githubusercontent.com/35363592/155884776-3625e2e8-b245-4085-858c-51045569110d.png)
After modified：
![220ee5d3a69ae5aeefe75114e834f78](https://user-images.githubusercontent.com/35363592/155884789-860c6c18-a9bf-436b-b27b-0039704abe16.png)
![26f0b68af5a533d4f0f7175985176a4](https://user-images.githubusercontent.com/35363592/155884797-6455c0ae-a0c2-4bdb-bcff-4700347ea6c4.png)

2022-03-01 15:18 UTC, darkwing approved these changes
Thank you @ForestTigerKing !

2022-03-01 16:57 UTC, digiwand approved these changes
🙌

2022-03-01 17:09 UTC, digiwand requested changes
Oops, sorry. On the way to double-check the changes before merging this in, I realized it can cause another issue. Let's see update this fix another way.

<img width="1464" alt="Screenshot 2022-03-01 at 2 04 05 PM" src="https://user-images.githubusercontent.com/20778143/156214838-b8ff6e68-eb7a-4bef-9627-14cc505bf4df.png">

2022-03-05 10:02 UTC, ForestTigerKing commented
@digiwand   thank you，i got it，see if we can solve it in other ways.

2022-05-17 20:50 UTC, digiwand commented
@ForestTigerKing 

Hello 👋  I am closing this PR to propose a new PR solution here https://github.com/MetaMask/metamask-extension/pull/14733

2022-05-17 20:50 UTC, closed without merging