added e2e test for token add approve action
MetaMask/metamask-extension pull request #13797
Opened 2022-03-01 15:33 UTC by mirjanaKukic

Resolves [#11136](https://github.com/MetaMask/metamask-extension/issues/11136)
This covers features merged in https://github.com/MetaMask/metamask-extension/pull/13674

2022-03-07 18:07 UTC, PeterYinusa commented
> @PeterYinusa Until we have the ability to configure blockchain state for each test run (e.g. to have a token contract deployed to ganache before the selenium tests start) we will have to build up state as is done in the various `it` blocks here. To move this PR forward, would you prefer that we group multiple test cases together into the same `it` block (knowing that we will refactor later once we add the aforementioned capability), or preserve the distinct test cases for clarity (even though it includes lots of duplicated code and some wasted e2e test run time)?

Yes, I agree we should group multiple test cases into the same `it` block

2022-04-14 08:45 UTC, mirjanaKukic commented
Just to mention, as part of this PR removed only 'Approves a custom token from dapp' and 'Approves a custom token from dapp when no gas value is specified' from metamask-ui.spec.js file. Had to leave 'Add a custom token from a dapp' since other tests in this file depend on it. 
Other tests from metamask-ui.spec.js file will be removed in next PRs for refactoring.

2022-04-22 14:35 UTC, PeterYinusa requested changes

2022-04-22 14:35 UTC, PeterYinusa commented on test/e2e/tests/custom-token-add-approve.spec.js
> +          fixtures: 'imported-account',
Can we use the `connected-state` fixture, instead of using `imported-account` fixture and the `connectDappWithExtensionPopup` method?

2022-04-22 14:35 UTC, PeterYinusa commented on test/e2e/tests/custom-token-add-approve.spec.js
> +          const addButton = await driver.findClickableElement({
can we just use `clickElement` here, as it calls `findClickableElement` under the hood? It doesn't look like addButton is used anywhere else

2022-04-22 14:35 UTC, PeterYinusa commented on test/e2e/tests/custom-token-add-approve.spec.js
> +          const importButton = await driver.findClickableElement({
same as above

2022-04-22 14:35 UTC, PeterYinusa commented on test/e2e/tests/custom-token-add-approve.spec.js
> +          await connectDappWithExtensionPopup(driver);
same as above

2022-04-22 14:35 UTC, PeterYinusa commented on test/e2e/tests/custom-token-add-approve.spec.js
> +          await connectDappWithExtensionPopup(driver);
same as above

2022-04-22 14:35 UTC, PeterYinusa commented on test/e2e/tests/custom-token-add-approve.spec.js
> +          await connectDappWithExtensionPopup(driver);
same as above

2022-05-05 13:22 UTC, mirjanaKukic commented
Fixed all requested changes

2022-05-16 20:18 UTC, PeterYinusa approved these changes

2022-05-16 20:25 UTC, darkwing approved these changes

2022-07-18 14:11 UTC, brad-decker commented
Updating branch and will merge when tests pass.

2022-07-18 15:12 UTC, merged