Dark Mode: ENS Input
MetaMask/metamask-extension pull request #13916
Opened 2022-03-11 17:44 UTC by darkwing

Fixes the ENS input for dark mode.

2022-03-14 21:00 UTC, mcmire reviewed
Checked your commit and seems pretty straightforward.

2022-03-15 20:09 UTC, georgewrmarshall requested changes
Looking good! A couple suggestions

2022-03-15 20:09 UTC, georgewrmarshall commented on app/phishing.html
> +        font-size: 12pt;
Not sure if it's need or will be covered in our main stylesheet but to be safe add 

```suggestion
        font-size: 12pt;
        color: var(--color-text-default);
```

2022-03-15 21:51 UTC, georgewrmarshall requested changes
Ah I just realized this PR is based off of the general background PR. Left a lot of updates. @GuillaumeRx

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/app/confirm-page-container/confirm-page-container-navigation/index.scss
> +    color: var(--color-icon-default);
```suggestion
    color: var(--color-text-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/app/connected-accounts-list/index.scss
> +    color: var(--color-icon-default);
```suggestion
    color: var(--color-text-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/app/connected-accounts-permissions/index.scss
> +  color: var(--color-icon-default);
```suggestion
  color: var(--color-text-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/app/connected-status-indicator/index.scss
> +    border-color: var(--color-icon-default);
```suggestion
    border-color: var(--color-border-default);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/app/connected-status-indicator/index.scss
> +    color: var(--color-icon-default);
```suggestion
    color: var(--color-text-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/app/connected-status-indicator/index.scss
> +    background-color: var(--color-background-default);
Can just leave it the same as hover we don't have a color for this. Really it should be using the secondary type Button component

```suggestion
    background-color: var(--color-background-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/app/edit-gas-fee-popover/edit-gas-item/index.scss
> +  color: var(--color-icon-default);
```suggestion
  color: var(--color-text-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/app/edit-gas-fee-popover/edit-gas-item/index.scss
> +    color: var(--color-icon-default);
```suggestion
    color: var(--color-text-default);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/app/menu-bar/index.scss
> +    color: var(--color-icon-default);
```suggestion
    color: var(--color-text-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/app/selected-account/index.scss
> +      background-color: var(--color-background-default);
Just keep it as alternative
```suggestion
      background-color: var(--color-background-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/app/transaction-breakdown/transaction-breakdown-row/index.scss
> +  color: var(--color-icon-default);
```suggestion
  color: var(--color-text-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/app/transaction-list-item/index.scss
> +    color: var(--color-icon-default);
```suggestion
    color: var(--color-text-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/app/transaction-list-item/index.scss
> +    color: var(--color-icon-default);
```suggestion
    color: var(--color-text-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/app/transaction-list-item/index.scss
> +    color: var(--color-icon-default);
```suggestion
    color: var(--color-text-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/app/transaction-list/index.scss
> +    color: var(--color-text-default);
```suggestion
    color: var(--color-text-muted);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/ui/nickname-popover/index.scss
> +      color: var(--colro-icon-default);
```suggestion
      color: var(--color-text-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/ui/page-container/index.scss
> +    color: var(--color-icon-default);
```suggestion
    color: var(--color-text-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/ui/page-container/index.scss
> +    color: var(--color-icon-default);
```suggestion
    color: var(--color-text-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/components/ui/update-nickname-popover/index.scss
> +      color: var(--color-icon-default);
```suggestion
      color: var(--color-text-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/css/itcss/components/network.scss
> +  border: 1px solid var(--color-border-default);
```suggestion
  border: 1px solid var(--color-border-muted);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/css/itcss/components/network.scss
>  }
Might be able to remove this file

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/pages/create-account/index.scss
> +    color: var(--color-icon-default);
```suggestion
    color: var(--color-text-alternative);
```

2022-03-15 21:51 UTC, georgewrmarshall commented on ui/pages/send/send.scss
> +      color: var(--color-icon-default);
```suggestion
      color: var(--color-text-alternative);
```

2022-03-16 10:22 UTC, darkwing commented
I've addressed all feedback from Guillaume's PR on my `general-background-dark-mode` branch.

2022-03-16 10:35 UTC, darkwing commented
Superceded by https://github.com/MetaMask/metamask-extension/pull/13984

2022-03-16 10:35 UTC, closed without merging