Better 712 errors
MetaMask/metamask-extension pull request #13939
Opened 2022-03-14 21:45 UTC by shanejonas

fixes #5690 

to test:

you can use the playground to make an invalid 712 request (make sure you use your own `address`):

```
{
    "jsonrpc": "2.0",
    "method": "eth_signTypedData_v4",
    "params": [
        "0x30746D407B71C1CBc159dC6355D1B949F2F3e2Cf",
        "{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"Person\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"wallet\",\"type\":\"address\"}],\"Mail\":[{\"name\":\"from\",\"type\":\"Person\"},{\"name\":\"to\",\"type\":\"Person\"},{\"name\":\"contents\",\"type\":\"string\"}]},\"primaryType\":\"Mail\",\"domain\":{\"name\":\"Ether Mail\",\"version\":\"1\",\"chainId\":1,\"verifyingContract\":\"0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC\"},\"messages\":{\"from\":{\"name\":\"Cow\",\"wallet\":\"0x30746D407B71C1CBc159dC6355D1B949F2F3e2Cf\"},\"to\":{\"name\":\"Bob\",\"wallet\":\"0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB\"},\"contents\":\"Hello, Bob!\"}}"
    ],
    "id": 0
}
```

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/364566/158266634-0e3965d2-deff-455a-9b58-7270275a9c1d.png">

2022-03-14 23:32 UTC, rekmarks approved these changes, later dismissed
LGTM!

2022-03-15 09:16 UTC, Gtonizuka submitted a review, later dismissed

2022-03-15 13:07 UTC, darkwing commented on app/scripts/lib/typed-message-manager.js
> +            -32602,
I hate to ask but should we create a constants file where we name RPC error codes with descriptive vars?  `-32602` is a magic number and most engineers wouldn't immediately know what that represents.

2022-03-16 18:15 UTC, seaona commented
@shanejonas the e2e-chrome test is failing due to an old issue non related to your commits. For passing the checks and have a clean test run, you'd need to pull the last develop.
Let me know if you have any question. Thank you!

2022-03-16 21:31 UTC, darkwing approved these changes

2022-03-16 22:21 UTC, brad-decker approved these changes

2022-03-16 22:27 UTC, merged

2022-03-16 22:30 UTC, rekmarks requested changes
`ethErrors.rpc.invalidParams` is a function that returns a new `invalidParams` error.

2022-03-16 22:30 UTC, rekmarks commented on app/scripts/lib/typed-message-manager.js
> +          );
```suggestion
          throw new ethErrors.rpc.invalidParams({
            message: 'Signing data must conform to EIP-712 schema. See https://git.io/fNtcx.',
            data: validation.errors.map((v) => v.message.toString()),
          });
```