Add a new fiat onboarding option via MoonPay
MetaMask/metamask-extension pull request #13934
Opened 2022-03-14 16:25 UTC by dan437

## Explanation
Add a new fiat onboarding option via MoonPay for these networks: Ethereum, BNB Chain, Polygon, Avalanche, Celo

**TODOs**
- Update an apiKey and URLs for production, currently it's only for sandbox

## Testing
- Open the extension
- Click on the `Buy` button
- Click on `Continue to MoonPay` for each of the supported networks

## Screenshots
Fiat onboarding options for Ethereum:
![image](https://user-images.githubusercontent.com/80175477/158216143-3bc5a6bd-3c29-4537-abad-1c80da1c8756.png)

MoonPay:
![image](https://user-images.githubusercontent.com/80175477/158216222-b46f561a-f9ae-4221-b6a2-4528140bcb6a.png)

2022-03-15 04:19 UTC, georgewrmarshall reviewed
Looking good. Could add the moonpay svg as a component so it will work with darkmode.

2022-03-15 04:19 UTC, georgewrmarshall commented on app/images/moonpay.svg
> +<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" width="1920" height="349.9062" viewBox="0 0 1920 349.9062"><defs><style>.cls-1{fill:#7d00ff;}</style></defs><g id="MP_LOGO" da
Would be good to add this as a logo component like these [#13953](https://github.com/MetaMask/metamask-extension/pull/13953) so it works with darkmode

2022-03-15 19:24 UTC, georgewrmarshall requested changes
Looking good! I've made some updates in [this branch on this commit](https://github.com/MetaMask/metamask-extension/commit/9d397e3e158d0b3deb9d8a08db9e23839762a649) as some suggestions. Otherwise LGTM. I haven't tested the functionality as I don't have access to the api key but once those changes are added it's good from a UI perspective! Thanks @dan437

2022-03-15 20:18 UTC, dan437 commented on ui/components/ui/logo/index.scss
> +.logo-moonpay {
Why not to have default values here and overwrite it in consuming components or via props if needed?

2022-03-15 21:54 UTC, georgewrmarshall commented on ui/components/ui/logo/index.scss
> +.logo-moonpay {
We could have it as default props. But that is what `size` which updates width is supposed to take care off.

2022-03-16 14:38 UTC, georgewrmarshall reviewed
Looks great! One tiny change that was my fault to begin with so apologies for that. Once that change is up I'll approve!!

2022-03-16 14:38 UTC, georgewrmarshall commented on ui/components/ui/logo/logo-moonpay.js
> +      fill={color}
Oh this is my bad sorry! I think `fill={color}` just needs to go in the path that the color concerns

```suggestion
```

2022-03-16 14:39 UTC, georgewrmarshall commented on ui/components/ui/logo/logo-moonpay.js
> +      fill={color}
Removed on my local still looks good.

<img width="372" alt="Screen Shot 2022-03-16 at 7 38 58 AM" src="https://user-images.githubusercontent.com/8112138/158615427-04f5dc37-f83b-43a5-9214-f9f5bf9ff4d8.png">

2022-03-16 18:34 UTC, georgewrmarshall approved these changes
UI LGTM!! Please also get a dev to review the api implementation. Nice work 💯

2022-03-16 19:17 UTC, darkwing approved these changes

2022-03-21 09:26 UTC, merged