Convert UrlIcon knobs and actions to controls / args
MetaMask/metamask-extension pull request #13981
Opened 2022-03-16 08:00 UTC by bestony

## Explanation

Convert UrlIcon knobs and actions to controls / args

fixed #13067

## More information

* Fixes: #13067

## Screenshots/Screencaps

![image](https://user-images.githubusercontent.com/13283837/158543423-c4bea51c-6d29-496f-9e45-af1633bac888.png)

![image](https://user-images.githubusercontent.com/13283837/158543442-886da721-711b-4ac5-a182-dad4fbe8ee07.png)

2022-03-16 18:42 UTC, georgewrmarshall requested changes
You the best @bestony! Thanks for the contribution. Made a couple suggestions.

2022-03-16 18:42 UTC, georgewrmarshall commented on ui/components/ui/url-icon/url-icon.stories.js
> +    url: { description: 'Icon File URL', control: 'text' },
Let's keep the control names the same as the prop names. I think that should help educated devs on the component api quicker.

```suggestion
    name: { control: 'text' },
    url: { control: 'text' },
```

2022-03-16 18:42 UTC, georgewrmarshall commented on ui/components/ui/url-icon/url-icon.stories.js
> +  return <UrlIcon name={args.name} url={args.url} />;
The `DefaultStory` should accept all available `argTypes`. I usually just spread the `...args` but there has been some concern about when we convert to typescript so we can just declare them here too.

```suggestion
  return <UrlIcon name={args.name} url={args.url} className={args.className} fallbackClassName={fallbackClassName} />;
```

2022-03-17 13:51 UTC, bestony reviewed
done @georgewrmarshall

2022-03-17 15:07 UTC, georgewrmarshall approved these changes, later dismissed
lgtm! Thanks again for the contribution! 💯

2022-03-22 09:51 UTC, bestony commented
Hi,@ryanml, can you review my pull request?

2022-03-31 00:58 UTC, darkwing approved these changes, later dismissed

2022-03-31 17:27 UTC, georgewrmarshall approved these changes

2022-03-31 17:31 UTC, brad-decker approved these changes

2022-03-31 18:30 UTC, merged