Dark mode: Settings / Contacts colors
MetaMask/metamask-extension pull request #13988
Opened 2022-03-16 11:22 UTC by darkwing

<img width="732" alt="Settings1" src="https://user-images.githubusercontent.com/46655/158579096-87b4b294-499e-48a7-9ba0-eb61a8bc46cc.png">

2022-03-16 11:38 UTC, digiwand submitted a review, later dismissed
LGTM!

2022-03-16 15:13 UTC, georgewrmarshall requested changes
Looking good! A couple of suggestions

<img width="1406" alt="Screen Shot 2022-03-16 at 8 08 32 AM" src="https://user-images.githubusercontent.com/8112138/158623436-c2e0d765-1a7e-4bbf-b118-3e6628097cc5.png">
<img width="1440" alt="Screen Shot 2022-03-16 at 8 11 26 AM" src="https://user-images.githubusercontent.com/8112138/158623442-a509527a-9287-4367-b037-a583142a45a1.png">

2022-03-17 15:06 UTC, georgewrmarshall approved these changes

2022-03-17 17:40 UTC, GuillaumeRx approved these changes

2022-03-17 18:03 UTC, merged