Dark Mode: Settings Search Bar
MetaMask/metamask-extension pull request #13997
Opened 2022-03-16 16:22 UTC by darkwing

<img width="517" alt="MoreSearch" src="https://user-images.githubusercontent.com/46655/158638105-8f4d23ef-e96c-4b16-8ce2-48bd0919217e.png">
<img width="582" alt="SettingsSearcher" src="https://user-images.githubusercontent.com/46655/158638112-e27afdca-0d01-430a-8142-0ebde6080833.png">

2022-03-17 14:00 UTC, GuillaumeRx requested changes

2022-03-17 17:05 UTC, darkwing commented on ui/pages/settings/index.scss
> -        background: var(--color-background-default);
This must've been a rebase conflict, my mistake!

2022-03-18 13:23 UTC, GuillaumeRx requested changes

2022-03-18 13:23 UTC, GuillaumeRx commented on ui/pages/settings/settings-search/settings-search.js
> +    'var(--color-icon-default)',
```suggestion
    'var(--color-icon-muted)',
```

2022-03-18 13:23 UTC, GuillaumeRx commented on ui/pages/settings/settings-search/settings-search.js
> +      setSearchIconColor('var(--color-text-default)');
```suggestion
      setSearchIconColor('var(--color-icon-default)');
```

2022-03-18 14:16 UTC, GuillaumeRx approved these changes

2022-03-18 15:39 UTC, georgewrmarshall approved these changes
lgtm

2022-03-18 17:35 UTC, merged