Dark Mode: Send flow inputs
MetaMask/metamask-extension pull request #14006
Opened 2022-03-16 17:49 UTC by darkwing

TODO: Still needs the swap icon to be light

<img width="431" alt="SendySend" src="https://user-images.githubusercontent.com/46655/158654993-31fbbc3f-f435-455f-9a08-0f83a5938ede.png">

2022-03-17 14:13 UTC, GuillaumeRx requested changes

2022-03-17 14:13 UTC, GuillaumeRx commented on ui/css/itcss/components/send.scss
> +      border: 1px solid var(--color-border-default);
```suggestion
      border: 1px solid var(--color-border-muted);
```

2022-03-17 14:13 UTC, GuillaumeRx commented on ui/css/itcss/components/send.scss
> +      border: 1px solid var(--color-border-default);
```suggestion
      border: 1px solid var(--color-border-muted);
```

2022-03-17 17:01 UTC, darkwing commented
Updated!

2022-03-17 17:52 UTC, GuillaumeRx submitted a review, later dismissed
LGTM !

2022-03-19 00:40 UTC, georgewrmarshall approved these changes

2022-03-21 13:49 UTC, GuillaumeRx approved these changes

2022-03-21 13:52 UTC, NiranjanaBinoy approved these changes

2022-03-21 13:55 UTC, merged