Remove the useSegmentContext function from metametrics.new.js
MetaMask/metamask-extension pull request #14013
Opened 2022-03-17 10:28 UTC by VSaric

fixes: #13768

## Explanation
Remove the `useSegmentContext` function from `metametrics.new.js` and create new file for `useMetaMetrics` hook.

2022-03-18 15:39 UTC, brad-decker requested changes

2022-03-18 15:39 UTC, brad-decker commented on ui/hooks/useMetaMetrics.js
> +export function useMetaMetrics() {
[REQ] This name doesn't match the outcome, or rather it gives the impression that this in some way is "using" MetaMetrics.... after talking with a few others, lets use `useSegmentContext` as it is the best name for the outcome.

2022-03-20 01:35 UTC, brad-decker submitted a review, later dismissed

2022-03-22 12:17 UTC, mirjanaKukic commented
Verified by QA

2022-03-25 06:51 UTC, digiwand submitted a review, later dismissed

2022-03-25 13:28 UTC, brad-decker approved these changes

2022-03-25 13:32 UTC, digiwand approved these changes

2022-03-25 14:26 UTC, merged