Dark Mode: Permissions container
MetaMask/metamask-extension pull request #14077
Opened 2022-03-21 18:05 UTC by darkwing

Pretty straightforward

<img width="1091" alt="Connect" src="https://user-images.githubusercontent.com/46655/159336278-751ff256-b231-4dfb-aaf7-6144d49d46ec.png">

2022-03-21 19:35 UTC, mcmire commented on ui/components/app/permission-page-container/index.scss
> -  &__header {
This was unused, I gather?

2022-03-21 19:36 UTC, mcmire commented
@darkwing Mind posting a video of switching between light/dark modes?

2022-03-22 04:35 UTC, georgewrmarshall approved these changes

2022-03-22 18:48 UTC, GuillaumeRx requested changes
You're missing some colors

![image](https://user-images.githubusercontent.com/13910212/159553902-284673f3-3230-471f-b67c-0d0ffc5aebca.png)
![image](https://user-images.githubusercontent.com/13910212/159553956-629bd81c-4bdf-4943-a8f9-f66e9659f033.png)

2022-03-22 18:56 UTC, georgewrmarshall submitted a review, later dismissed

2022-03-22 20:25 UTC, darkwing commented on ui/components/app/permission-page-container/index.scss
> -  &__header {
Yep!  Couldn't find it.

2022-03-22 20:30 UTC, georgewrmarshall approved these changes, later dismissed

2022-03-22 20:43 UTC, darkwing commented
@GuillaumeRx Are you sure?  I'm seeing good stuff:
<img width="604" alt="perms" src="https://user-images.githubusercontent.com/46655/159572467-1f42a1d8-90cc-4cdf-b02e-e574c6c4e356.png">

2022-03-22 20:59 UTC, GuillaumeRx submitted a review, later dismissed
There is something weird with the storybook build, the colors are updated.

2022-03-23 15:07 UTC, GuillaumeRx approved these changes

2022-03-23 15:24 UTC, georgewrmarshall approved these changes

2022-03-23 15:40 UTC, merged