Dark Mode : Advanced gas fee
MetaMask/metamask-extension pull request #14073
Opened 2022-03-21 17:09 UTC by GuillaumeRx

## More information

* Fixes #13719

## Screenshots/Screencaps

![Screenshot 2022-03-21 180207](https://user-images.githubusercontent.com/13910212/159326749-07a5d4f1-9390-4fb8-b0d5-9733df4782fb.png)
![Screenshot 2022-03-21 180253](https://user-images.githubusercontent.com/13910212/159326755-7c3316cc-ca35-46df-8b4b-0e63c5431110.png)

2022-03-21 17:26 UTC, darkwing approved these changes, later dismissed

2022-03-21 17:40 UTC, georgewrmarshall requested changes
Looks good! Just one suggestion on the input border color

2022-03-21 17:40 UTC, georgewrmarshall commented on ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/priority-fee-input/index.scss
> +  border-top: 1px solid var(--color-border-muted);
If this is an input I think it should use `var(--color-border-default)`? `var(--color-border-muted)` should be used for low priority borders such as dividers where the user doesn't interact with them.

2022-03-22 15:14 UTC, darkwing approved these changes

2022-03-22 15:21 UTC, georgewrmarshall approved these changes

2022-03-22 17:04 UTC, merged