Dark Mode: Transaction statuses
MetaMask/metamask-extension pull request #14092
Opened 2022-03-21 23:39 UTC by darkwing

Basic color translations for red, green, orange for transaction statuses.

2022-03-21 23:40 UTC, darkwing commented
This diff is wild; it might be easier to just pull down the file and look.  Geez.

2022-03-22 04:28 UTC, georgewrmarshall submitted a review, later dismissed

2022-03-22 12:14 UTC, digiwand requested changes, later dismissed
I think we are missing the `&--rejected` selector

2022-03-22 14:25 UTC, brad-decker submitted a review, later dismissed

2022-03-22 15:27 UTC, georgewrmarshall approved these changes, later dismissed

2022-03-22 18:59 UTC, georgewrmarshall submitted a review, later dismissed

2022-03-23 14:50 UTC, GuillaumeRx submitted a review, later dismissed

2022-03-23 16:20 UTC, darkwing commented
Rebased!

2022-03-23 16:25 UTC, georgewrmarshall submitted a review, later dismissed

2022-03-23 22:18 UTC, georgewrmarshall approved these changes

2022-03-23 23:43 UTC, GuillaumeRx approved these changes

2022-03-24 02:28 UTC, merged