Integration of the Rave Names Fantom Name System into Address prompts.
MetaMask/metamask-extension pull request #14128
Opened 2022-03-22 22:13 UTC by Pokesi

[redone]

Explanation:
Integration of the Rave Names FNS into MetaMask's address prompts. Using ethers along with the `rpc.ftm.tools` RPC router to resolve owned names. This comes at no detriment to ENS resolution, or any other part of MetaMask, or development.

Rave Names is a 100% decentralized Web3 username system on Fantom. Any enquiries can be made by replying to this PR or by sending an email to `dev@fantoms.art`, or by sending a direct message to us on twitter @rave_names or https://github.com/FantomsOpera.

Manual testing steps:

- `yarn dist`
- `Click 'Send' at the homescreen to take you to the address prompt screen`
- `Type in z.ftm, which should resolve to 0x3e522051A9B1958Aa1e828AC24Afba4a551DF37d, the public deployer address.`
- `Then, type in randomz.eth which should resolve to the same address.`

Again, feel free to contact us through email or twitter.

2022-03-29 22:27 UTC, Pokesi commented
Just as a side note, this does not add any dependencies!

2022-06-03 17:26 UTC, darkwing requested changes

2022-06-03 17:26 UTC, darkwing commented on ui/ducks/ens.js
> +          console.log(address);
These will need to be removed before merging.

2022-06-03 17:26 UTC, darkwing commented on ui/ducks/ens.js
> +          address = await resolveFnsName(trimmedEnsName);
Could we do:

```
[address] =  await resolveFnsName(trimmedEnsName);
 
```

2022-11-03 14:12 UTC, closed without merging