Fix migrator
MetaMask/metamask-extension pull request #1414
Opened 2017-05-11 08:52 UTC by frankiebee

as i was writing my own migration I noticed that the migration would run but the localStorage would not update so i fixed that here 
the issue was on line:19
`.then(() => versionedData)`
this seemed to be returning the original versionedData that was supplied as an argument to the function instead of the migratedData. I also swapped out  asyncQ.eachSeries for asyncQ.waterfall so that results of previous migrations if any are used in the next migration that is run.

2017-05-11 15:51 UTC, kumavis commented
Thats a pretty serious bug. Can you add a test that fails without this change?

2017-05-11 16:10 UTC, frankiebee commented
yup I'll do that now

2017-05-12 00:07 UTC, kumavis requested changes
good find

the code is rather tricky to follow

im sure we can find a more straightforward and readable way to run the migrations

2017-05-12 00:07 UTC, kumavis commented on app/scripts/lib/migrator/index.js
> +      .then((migratedData) => Promise.resolve(migratedData))
`.then((migratedData) => Promise.resolve(migratedData))`
this can be removed - doesnt do anything

2017-05-12 20:11 UTC, kumavis commented
yeah thats about as clean as it gets w/o es7. went with es7!  rejoice! now we can use that where ever we want

2017-05-12 20:11 UTC, closed without merging