MetaMetrics: add segment.identify
MetaMask/metamask-extension pull request #14195
Opened 2022-03-24 22:27 UTC by digiwand

## Explanation

Fixes https://github.com/MetaMask/metamask-extension/issues/13529

## More information

## Screenshots/Screencaps

## Manual testing steps

2022-03-25 13:55 UTC, brad-decker commented on app/scripts/controllers/metametrics.js
> +  };
If we allow `Date` objects as input to the .identify method then we'll need to convert them to strings before sending to segment.

2022-03-25 17:05 UTC, brad-decker requested changes

2022-03-25 17:05 UTC, brad-decker commented on ui/store/actions.js
> +
For MVP I think we can skip making this method available to the UI

2022-03-28 23:20 UTC, brad-decker requested changes
LGTM! Only thing to do is uncomment the call to .identify in handleMetaMaskStateUpdate

2022-03-31 00:15 UTC, brad-decker submitted a review, later dismissed
Yay LGTM

2022-03-31 14:05 UTC, brad-decker approved these changes

2022-03-31 15:12 UTC, georgewrmarshall approved these changes

2022-03-31 15:16 UTC, georgewrmarshall reviewed
Apologies only saw the spelling fix. As I don't have context going to remove myself as a reviewer. Github was doing something weird 


https://user-images.githubusercontent.com/8112138/161090023-df693f76-67cf-4bbc-a596-196c91591c20.mov

2022-03-31 15:31 UTC, brad-decker commented
@georgewrmarshall
![EyxhFqCvQhVrW](https://user-images.githubusercontent.com/4448075/161093160-93ec5b0b-0e13-4610-8eb4-91a3f8c1bfe3.gif)

2022-03-31 19:21 UTC, merged