Update v10.13.0 changelog
MetaMask/metamask-extension pull request #14257
Opened 2022-03-30 05:29 UTC by ryanml

2022-03-30 14:23 UTC, brad-decker approved these changes

2022-04-01 11:44 UTC, danjm commented on CHANGELOG.md
> +- Add token list aggregattor to token details page ([#14051](https://github.com/MetaMask/metamask-extension/pull/14051))
"Add token list aggregattor to token details page" this is still behind feature flag, and so should not be in the changelog yet

2022-04-01 11:45 UTC, danjm commented on CHANGELOG.md
> +    - "Send max" doesn't work on Optimism
`"Send max" doesn't work on Optimism` -> `Fix 'Send max' button when on the Optimism network`

2022-04-01 11:46 UTC, danjm commented on CHANGELOG.md
> +    - Show currency estimate alongside ETH on Optimism
`Show currency estimate alongside ETH on Optimism` -> `Show fiat currency estimates alongside ETH estimates on multi-layer fee networks`

2022-04-01 11:47 UTC, danjm commented on CHANGELOG.md
> +    - Combine L1+L2 gas when using Optimism
`Combine L1+L2 gas when using Optimism` -> `Display L1+L2 gas fees as a combined total on multi-layer fee networks`

2022-04-01 11:51 UTC, danjm commented on CHANGELOG.md
> +- Fixed issue where the "lock screen" shows up briefly between the "create password" screen and the success screen ([#14111](https://github.com/MetaMask/metamask-extension/pull/14111))
`Fixed issue where the "lock screen" shows up briefly between the "create password" screen and the success screen` is behind a feature toggle and shouldn't be included

2022-04-01 11:54 UTC, danjm commented on CHANGELOG.md
> +- Add space between sentences in insufficient currency warning ([#14019](https://github.com/MetaMask/metamask-extension/pull/14019))
I suggest moving `Add space between sentences in insufficient currency warning` to "Changed" and changing the description to `Add buy modal link to insufficient currency warning of all networks that have a fiat onramp, and update spacing in the warning's copy`

2022-04-01 11:55 UTC, danjm commented on CHANGELOG.md
> +- Fix missing insufficient funds error for token sends ([#14026](https://github.com/MetaMask/metamask-extension/pull/14026))
`Fix missing insufficient funds error for token sends` was part of a previous release

2022-04-01 11:59 UTC, danjm requested changes
Suggested some changes

2022-04-01 11:59 UTC, danjm commented
Also, this changelog should include dark mode

2022-04-04 09:51 UTC, ryanml commented
Suggested changes have been implemented @danjm

2022-04-06 15:00 UTC, danjm approved these changes

2022-04-06 15:00 UTC, merged