Update version parsing to allow rollback release
MetaMask/metamask-extension pull request #14288
Opened 2022-03-30 23:58 UTC by Gudahtt

## Explanation

When we want to rollback a release on Chrome, sometimes we use the fourth part of the version for the rollback release. This is because the Chrome web stores does not directly allow rolling back, but instead requires us to re-submit the release we want to roll back to with a higher version number.

The manifest version parsing now allows for a fourth version part.

The comments have also been updated to be more descriptive, and to fix a minor inaccuracy.

## Manual testing steps

- Try adding a fourth part to the version number in `package.json` (e.g. "v10.12.2.1").
- Ensure that the extension can connect to dapps, that there are no background console errors, and that the "About" page renders the version properly.

2022-03-31 06:48 UTC, ryanml submitted a review, later dismissed

2022-04-04 15:12 UTC, darkwing requested changes
Tiniest, most infuriating nit ever.

2022-04-04 15:12 UTC, darkwing commented on app/scripts/platforms/extension.js
> +      // field on Chrome for for non-main builds (i.e. Flask, Beta) because we want to show the
`for for`

2022-04-04 15:16 UTC, Gudahtt commented on app/scripts/platforms/extension.js
> +      // field on Chrome for for non-main builds (i.e. Flask, Beta) because we want to show the
```suggestion
      // field on Chrome for non-main builds (i.e. Flask, Beta) because we want to show the
```

2022-04-04 15:17 UTC, Gudahtt commented on app/scripts/platforms/extension.js
> +      // field on Chrome for for non-main builds (i.e. Flask, Beta) because we want to show the
Thanks!

2022-04-06 17:49 UTC, darkwing approved these changes

2022-05-03 16:06 UTC, brad-decker approved these changes
LGTM. Tested locally as well.

2022-05-03 16:48 UTC, merged