Dark Mode: Fix QR display
MetaMask/metamask-extension pull request #14312
Opened 2022-03-31 19:15 UTC by darkwing

<img width="1124" alt="QRCode" src="https://user-images.githubusercontent.com/46655/161131556-58cf7de0-1ca0-4b95-ade9-f1519b26606a.png">

2022-03-31 20:09 UTC, georgewrmarshall requested changes
I think it's worth creating a css variable and adding a comment so we don't accidentally change it in future e.g.
```
--qr-code-white-background: '#fff'; // DO NOT CHANGE NEEDED FOR QR CODE TO WORK
```

2022-04-01 17:05 UTC, darkwing commented
Updated!

2022-04-01 17:27 UTC, georgewrmarshall approved these changes

2022-04-01 17:31 UTC, GuillaumeRx approved these changes

2022-04-01 18:46 UTC, digiwand approved these changes

2022-04-01 19:53 UTC, merged