Convert knobs and actions to controls/args ConfirmEncryptionPublicKey story
MetaMask/metamask-extension pull request #14319
Opened 2022-03-31 21:30 UTC by FrancisBehnen

## Explanation
Changes the deprecated knobs and actions in `confirm-encryption-public-key/confirm-encryption-public-key.stories.js` to controls.

I have opted to keep one custom `@storybook/addon-actions` action() call, to the history object, such that the history.push() does not result in a console error but shows up as a action in the actions tab.

Fixes #13070

## Manual testing steps
Run `yarn storybook`

2022-04-04 14:58 UTC, darkwing requested changes

2022-05-20 17:22 UTC, georgewrmarshall submitted a review, later dismissed
Fantastic work! Pending @darkwing's suggestion LGTM

2022-08-09 20:09 UTC, georgewrmarshall commented on ui/pages/confirm-encryption-public-key/confirm-encryption-public-key.stories.js
> +      name: metamask.accountArray[0].name,
updated https://github.com/MetaMask/metamask-extension/pull/14319/commits/1f21b02d3d8dc74691d8b105a85ffb739e4ae0fb

2022-08-09 20:12 UTC, georgewrmarshall submitted a review, later dismissed

2022-08-09 20:16 UTC, brad-decker approved these changes, later dismissed

2022-08-09 23:21 UTC, georgewrmarshall approved these changes

2022-08-09 23:48 UTC, brad-decker approved these changes

2022-08-10 15:04 UTC, darkwing approved these changes

2022-08-10 15:05 UTC, merged