Dark mode whats new
MetaMask/metamask-extension pull request #14346
Opened 2022-04-04 18:10 UTC by darkwing

This is the What's New block for dark mode.

2022-04-04 18:10 UTC, darkwing commented
Converting to draft as we could use an image.

2022-04-05 13:19 UTC, GuillaumeRx requested changes

2022-04-05 13:19 UTC, GuillaumeRx commented on ui/components/app/whats-new-popup/whats-new-popup.js
> +    },
I think you're missing the `updateViewedNotifications({ 12: true });` here

2022-04-05 13:41 UTC, GuillaumeRx approved these changes, later dismissed

2022-04-05 13:50 UTC, brad-decker approved these changes, later dismissed

2022-04-05 15:58 UTC, brad-decker approved these changes, later dismissed

2022-04-05 18:14 UTC, GuillaumeRx approved these changes

2022-04-05 19:44 UTC, georgewrmarshall approved these changes
LGTM. Did a visual check on my local

<img width="362" alt="Screen Shot 2022-04-05 at 12 43 35 PM" src="https://user-images.githubusercontent.com/8112138/161836820-bdcc0169-0ae9-49dc-abf7-62a99e218a24.png">

2022-04-05 19:55 UTC, merged