Fix for randomly resets of updated values in network edit form
MetaMask/metamask-extension pull request #14370
Opened 2022-04-06 07:08 UTC by amerkadicE

## Explanation

Currently, in the network edit form, the field value is resetting randomly

This is a problem because the selectedNetwork prop is updated randomly which will cause calling the resetForm function and all field variables will reset.

In order to solve this problem, this pull request will add a new state **isEditing** which will not allow resetting of the form if the user changes something in the input field.

## More information

Fixes #13168

## Screenshots/Screencaps

### After

<img width="986" alt="image" src="https://user-images.githubusercontent.com/97883527/161912323-13fa00c3-c79c-476a-a196-7b7ce1e66972.png">

## Manual testing steps

Add a chain on https://chainlist.org/ like Optimistic Ethereum
Go to Settings > Networks > [the chain you just added]
Try editing the RPC to be https://localhost:8871/.
Wait ~10 seconds
Notice that your updated settings didn't change.

Cancel, Delete, Save, and switching between networks should also be tested.

2022-04-06 10:32 UTC, mirjanaKukic commented
Verified by QA

2022-04-06 13:09 UTC, Gtonizuka commented
@amerkadicE I know this is still a draft but I think we could simplify the code quite a bit.

Look at https://github.com/MetaMask/metamask-extension/pull/13325/files
(not sure why TigerKing closed that PR but it is doing pretty much the same I think)

2022-04-06 15:46 UTC, amerkadicE commented
> @amerkadicE I know this is still a draft but I think we could simplify the code quite a bit.
> 
> Look at https://github.com/MetaMask/metamask-extension/pull/13325/files (not sure why TigerKing closed that PR but it is doing pretty much the same I think)
Hi @Gtonizuka, this PR will break the logic for switching between the networks. 
I updated my PR to look more similar to this one.

2022-06-02 14:29 UTC, darkwing approved these changes, later dismissed

2022-06-14 21:09 UTC, digiwand commented on ui/pages/settings/networks-tab/networks-form/networks-form.js
> +    setIsEditing(false);
In case onSubmit ends up failing, should we move this after the updates have been confirmed?

2022-06-14 21:11 UTC, darkwing commented
I think what you have makes sense but I'm seeing some weird jank when I test it out:

https://user-images.githubusercontent.com/46655/173689246-389ae40a-c408-4578-b294-9c44c9270622.mp4

Could you investigate if we could avoid the message weirdness upon save?

2022-06-14 21:13 UTC, darkwing requested changes, later dismissed
Noted the jank, hoping we can clean it up

2022-06-23 11:35 UTC, amerkadicE commented
> Noted the jank, hoping we can clean it up

It is fixed.

2022-07-28 04:03 UTC, danjm submitted a review, later dismissed

2022-07-29 19:20 UTC, brad-decker commented
@amerkadicE can you rebase this please and resolve conflicts?

2022-08-01 09:51 UTC, amerkadicE commented
@brad-decker Done

2022-08-17 15:14 UTC, adonesky1 approved these changes
LGTM

2022-08-17 16:15 UTC, digiwand approved these changes
LGTM2

2022-08-17 17:13 UTC, merged