Add snaps view search
MetaMask/metamask-extension pull request #14419
Opened 2022-04-08 20:40 UTC by hmalik88

Search for individual snaps is added with this PR. Route objects are created and merged with `SETTINGS_CONSTANTS` to create a list that includes snaps for the search list to display. No refs were used in this implementation as we're simply routing to the page itself, specific section search within a snap view page will be added in future iterations.

Testing:
- Run `yarn start --build-type flask` to create a build
- Load into chrome
- Install a snap (or more) via [snaplist](snaplist.org)
- In settings search, search for an installed snap using its name
- Observe changes

2022-04-18 17:29 UTC, darkwing submitted a review, later dismissed
Code is good and this worked great!  Awesome work!

2022-04-19 08:54 UTC, ritave requested changes

2022-04-19 14:04 UTC, ritave approved these changes

2022-04-19 14:51 UTC, darkwing approved these changes

2022-04-19 15:08 UTC, merged