Add decimals to gas price input
MetaMask/metamask-extension pull request #1443
Opened 2017-05-16 23:31 UTC by Zanibas

Giving users better control over their gas! Fixes #1412 

- Allows decimals in the gasPrice input
- Fixes the reset button

2017-05-17 06:54 UTC, kumavis requested changes

2017-05-17 06:54 UTC, kumavis commented on ui/app/components/pending-tx.js
> +  this.setState({ txData: cloneObj(txMeta) })
why are you cloning the txMeta? were there some side effects? (if so, maybe we should do this everywhere we use `setState`)

2017-05-17 06:54 UTC, kumavis commented on ui/app/components/pending-tx.js
> +}
lets use the `clone` module instead https://github.com/MetaMask/metamask-plugin/blob/master/package.json#L138

2017-05-17 07:22 UTC, flyswatter commented on ui/app/components/bn-as-decimal-input.js
> +  const newValue = value.toNumber(10) / scale
On this line, you are assuming that the input number fits in a JS number, which defeats the point of using BN.

I've added a test to demonstrate the problem, which highlights why this doesn't work for editing ether values, for example.

2017-05-17 07:22 UTC, danfinlay requested changes
I've added a test that this component should be able to pass.

2017-05-17 19:08 UTC, Zanibas commented
@flyswatter the test you wrote is failing due to a limitation of BN.js.

`Error: Number can only safely store up to 53 bits`

Will adjust the test to accommodate this  limitation.

2017-05-23 01:06 UTC, flyswatter commented
How is this going?

2017-05-23 21:27 UTC, Zanibas commented
Will polish this a bit later since the functions look pretty ugly, but the logic should theoretically work.

2017-05-24 17:14 UTC, Zanibas commented
Further fixes have been added that properly disable the submit button when invalid gas params are present.

2017-05-24 18:06 UTC, danfinlay approved these changes
Good job!

2017-05-24 18:11 UTC, kumavis approved these changes

2017-05-24 18:11 UTC, merged