Lint
MetaMask/metamask-extension pull request #14443
Opened 2022-04-14 11:34 UTC by Gtonizuka

## Screenshots/Screencaps

### Before

### After

## Manual testing steps

2022-04-14 15:39 UTC, shanejonas commented
I think we should remove the restricted part for now at least.

2022-04-14 15:39 UTC, shanejonas commented on app/scripts/lib/rpc-method-middleware/handlers/index.js
> +  wallet_getLanguage
if we want it to only be included in flask we should wrap this line with the:

```
///: BEGIN:ONLY_INCLUDE_IN(flask)
```

2022-04-28 08:06 UTC, FrederikBolding commented on app/scripts/lib/rpc-method-middleware/handlers/index.js
> +  walletgetLocale,
Perhaps this should be cased like ``walletGetLocale`?

2022-04-28 08:08 UTC, FrederikBolding commented on shared/constants/permissions.js
> +  wallet_getLocale: 'wallet_getLocale',
If it is restricted it needs to be added to https://github.com/MetaMask/metamask-extension/blob/8b9b9af13fabcef4882d4423e35acb4cd3aef4e9/ui/helpers/utils/permission.js

2022-04-28 13:32 UTC, brad-decker requested changes, later dismissed

2022-04-28 13:32 UTC, brad-decker commented on app/scripts/lib/rpc-method-middleware/handlers/get-locale.js
> +    });
[REQ] Unless there are specific props etc we want to track in RPC method handlers, the createRPCMethodTrackingMiddleware file sets up tracking for most RPC methods. If its important to know everytime this method is called (versus a sampling), we would add it to the USER_PROMPTED_EVENT_NAME_MAP in that file ... i don't believe it is necessary to capture every event in this case but I could be wrong.

2022-05-03 16:16 UTC, Gtonizuka commented
Moving this back into draft as we need more info from @rekmarks

2022-05-03 16:20 UTC, Gtonizuka commented on app/scripts/lib/rpc-method-middleware/handlers/get-locale.js
> +    if (hasPermission(MESSAGE_TYPE.GET_LOCALE)) {
Can you clarify why is this needed @rekmarks ?

2022-05-03 16:20 UTC, Gtonizuka commented on app/scripts/controllers/permissions/specifications.js
> +      permissionType: PermissionType.RestrictedMethod,
If `permissionType` is `restrictedMethod` why do we need `if(hasPermission...` in the rpc method implementation (i.e. handlers/get-locale.js below) @rekmarks

2022-06-15 21:53 UTC, BelfordZ commented on app/scripts/metamask-controller.js
> +          getWalletLocale: this.getWalletLocale.bind(this),
Should this be wrapped in `BEGIN:ONLY_INCLUDE_IN(flask)` ?

2022-06-15 22:07 UTC, BelfordZ commented
functionally it seems to work great. Nice work. Just left a q about the flask inclusion stuff, but otherwise lgtm!

2022-09-16 13:48 UTC, brad-decker commented
@BelfordZ @Gtonizuka do we still want this? If so can we get a rebase and another round of reviews? If not lets close it (for PR queue cleanliness)

2022-11-04 17:39 UTC, brad-decker commented
@Gtonizuka I am going to close this, if it ends up being something we want we should reopen and rebase it. Thanks!

2022-11-04 17:39 UTC, closed without merging