Dark Mode: Implement Metrics
MetaMask/metamask-extension pull request #14455
Opened 2022-04-15 16:55 UTC by darkwing

Initial implementation of metrics for themeing.

2022-04-15 23:03 UTC, brad-decker requested changes
Just some minor requests, looks good otherwise.

2022-04-15 23:03 UTC, brad-decker commented on shared/constants/metametrics.js
> +  THEME: 'theme',
[req] Please add the entries to the two jsdoc types related to traits for this entry.

2022-04-15 23:03 UTC, brad-decker commented on ui/pages/settings/experimental-tab/experimental-tab.component.js
> +                  event: 'Theme Change',
[req] similar to "Token Added" and "Clicked ...${x}" lets make this at least "Changed"

2022-04-15 23:03 UTC, brad-decker commented on ui/pages/settings/experimental-tab/experimental-tab.component.js
> +                    legacy_event: true,
[REQ] remove legacy_event, this is reserved for events that were a part of our old schema.

2022-04-18 13:44 UTC, jpuri commented on ui/pages/settings/experimental-tab/experimental-tab.component.js
> +              }}
I suspect an inline function here can cause re-rendering in `<Dropdown` `useCallback` may be a good idea here.

2022-04-18 15:02 UTC, brad-decker approved these changes

2022-04-18 16:07 UTC, danjm approved these changes

2022-04-18 16:31 UTC, merged