Stop storing request and response objects in the permission activity log
MetaMask/metamask-extension pull request #14485
Opened 2022-04-20 16:02 UTC by rekmarks

We currently store the JSON-RPC request and response objects in the permission activity log. The utility of doing this was always rather dubious, but never problematic. Until now.

In Flask, as the restricted methods have expanded in number, user secrets may be included on JSON-RPC message objects. This PR removes these properties from the permission activity log, and adds a migration which does the same to existing log objects. We don't interact with the log objects anywhere in our codebase, but we don't want unexpected properties to cause errors in the future should any log objects be retained.

This PR also updates relevant tests and test data. It makes a minor functional change to how a request is designated as a success or failure, but this should not change any behavior in practice.

2022-04-20 16:15 UTC, ritave requested changes

2022-04-20 16:15 UTC, ritave commented on app/scripts/controllers/permissions/permission-log.js
> +    entry.success = Reflect.hasOwnProperty.call(response, 'result');
This is not obvious in the code - please add a comment explaining

2022-04-20 16:15 UTC, ritave commented on app/scripts/controllers/permissions/permission-log.test.js
>  import nanoid from 'nanoid';
Please add a regression test confirming that there are specifically no `request` and `response` properties.

2022-04-20 16:48 UTC, ritave approved these changes, later dismissed
Minor change, don't need to see afterwards

2022-04-20 16:48 UTC, ritave commented on app/scripts/migrations/070.test.js
> +  it('should handle missing PermissionLogController', async () => {
Should also handle missing `PermissionLogController.permissionActivityLog`

2022-04-21 13:25 UTC, ritave approved these changes

2022-04-21 15:05 UTC, brad-decker approved these changes

2022-04-21 15:44 UTC, merged