Add QA migration guide
MetaMask/metamask-extension pull request #14544
Opened 2022-04-27 11:35 UTC by tmashuang

Adds QA migration guide to test migrations builds.

2022-04-28 16:25 UTC, darkwing commented on docs/QA_MIGRATIONS_GUIDE.md
> +  1. Create a new MetaMask build\* folder locally with the source files before the migration, and load it as an unpacked extension in Chrome\*. If the migration is in a pull request, then build the `
Nit but do we want `build/` for consistent directory references?  Do we also want to use the term `directory`?

2022-04-28 16:25 UTC, darkwing requested changes, later dismissed

2022-04-28 16:25 UTC, darkwing commented on docs/QA_MIGRATIONS_GUIDE.md
> +        ![gif of replacing files and reloading the extension](./assets/folder-file-replacement-build.gif)
Step 2 doesn't have an empty line above but this does.

2022-06-10 21:30 UTC, danjm approved these changes

2022-08-02 12:34 UTC, seaona approved these changes
LGTM! Great and v useful guide @tmashuang

2022-08-02 21:42 UTC, merged