Add fiat onboarding for AVAX and MATIC through Wyre
MetaMask/metamask-extension pull request #14683
Opened 2022-05-10 20:02 UTC by benlwyre

##Explanation
Add a new fiat onboarding option via Wyre for these networks: Polygon, Avalanche

##Testing
Open the extension
Click on the Buy button
Click on Continue to Wyre for each of the supported networks

##Screenshots
Fiat onboarding options for Avalanche:
![Screen Shot 2022-05-10 at 1 00 05 PM](https://user-images.githubusercontent.com/102182506/167712097-6593118b-fa62-49d9-ad52-f145071e87da.png)
![Screen Shot 2022-05-10 at 1 00 20 PM](https://user-images.githubusercontent.com/102182506/167712102-558a4ed7-20db-473f-88a9-6e5a70acaeb5.png)

2022-05-10 20:05 UTC, benlwyre commented
I have read the CLA Document and I hereby sign the CLA

2022-05-10 21:39 UTC, darkwing requested changes
Thank you @benlwyre !  Running `yarn lint:fix` will fix the linting issues!

2022-05-10 23:09 UTC, benlwyre commented
> Thank you @benlwyre ! Running `yarn lint:fix` will fix the linting issues!

thanks for the tip!

2022-05-11 17:07 UTC, benlwyre commented
> @benlwyre We're working on this issue -- it's an intermittent. Great work so far!

I think we've got it in a good place now, thank for all your help!

2022-05-16 18:16 UTC, benlwyre commented
@darkwing Changes made, thanks for working with me!

2022-05-17 18:49 UTC, darkwing approved these changes, later dismissed

2022-05-18 08:08 UTC, alaahd commented on app/scripts/lib/buy-url.js
> +  const chainNumber = parseInt(chainId, 16);
Non-blocking: we could rename the variable to be `networkId` instead of `chainNumber`

2022-05-18 08:11 UTC, alaahd commented on app/scripts/lib/buy-url.js
> +  const { wyre: { srn, currencyCode } = {} } = BUYABLE_CHAINS_MAP[chainId];
we could do the destructuring in two lines for better code readability. 
```suggestion
  const { wyre = {}} = BUYABLE_CHAINS_MAP[chainId];
  const { srn, currencyCode } = wyre;
 
```

2022-05-18 10:39 UTC, alaahd approved these changes, later dismissed

2022-05-18 16:09 UTC, benlwyre commented
Thanks for the review @alaahd !

2022-05-18 18:57 UTC, benlwyre commented
test-unit that fails does not look related to changes here, how should I proceed?

2022-05-19 14:32 UTC, darkwing submitted a review, later dismissed

2022-05-20 23:02 UTC, georgewrmarshall requested changes
Looking good! Just one suggestion about the ui component. Made some suggestions. 🙏

2022-05-26 20:22 UTC, benlwyre commented on ui/components/ui/logo/logo-wyre.js
>  export default LogoWyre;
@georgewrmarshall Thank you for the explanation and storybook example! This has been updated, you're absolutely right about how to handle this. Thanks for reviewing as well.

2022-05-26 22:18 UTC, georgewrmarshall approved these changes
Thanks for making that update! Excellent work! 💯  To fix failing tests I think a rebase from `develop` should do it!

2022-05-26 23:18 UTC, benlwyre commented
@georgewrmarshall Yep, got that in too. All tests looking good on my side. Thanks so much again.

2022-05-27 16:04 UTC, darkwing approved these changes

2022-05-27 16:04 UTC, merged