Convert knobs and actions to controls/args for MainQuoteSummary
MetaMask/metamask-extension pull request #14758
Opened 2022-05-21 01:05 UTC by Jordon-L

## Explanation
This PR converts the old knobs and actions to controls/args for the MainQuoteSummary component

## More Information

Fixes #13175 

## Screenshots/Screencaps

### Before

<img width="1440" alt="before" src="https://user-images.githubusercontent.com/46872554/169628296-648a8c15-999a-41b7-8472-12ccabb947fa.png">
<img width="1438" alt="before2" src="https://user-images.githubusercontent.com/46872554/169628301-271464b8-5742-4b54-bd0f-f4271d3c35c6.png">
### After

![after-controls](https://user-images.githubusercontent.com/46872554/169628327-2a0f0834-10d3-4d79-a384-b4c290930d62.png)

![after-readmeMDX](https://user-images.githubusercontent.com/46872554/169628330-97adcbea-beaa-431d-a35f-50e29e7a9dae.png)

## Manual Testing Steps
run `yarn storybook`

## Pre-Merge Checklist

- [ ] PR template is filled out
- [ ] Manual testing complete & passed
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** QA attention is required, "QA Board" label has been applied
- [ ] PR has been added to the appropriate release Milestone

2022-05-21 01:07 UTC, Jordon-L commented
I have read the CLA Document and I hereby sign the CLA

2022-05-21 01:15 UTC, Jordon-L commented
Should I remove the controls for sourceIconUrl and destinationIconUrl?

Screenshot:
![remove-control](https://user-images.githubusercontent.com/46872554/169628746-8cffe16d-6049-48d3-bf11-cd340856385b.png)

2022-05-23 13:56 UTC, darkwing requested changes
Tiny change requested, otherwise beautiful!  Thank you!

2022-05-23 18:13 UTC, Jordon-L commented on ui/pages/swaps/main-quote-summary/main-quote-summary.js
> +   * The ticker symbol for the source token
Thanks, I have added a "."

2022-05-24 20:10 UTC, darkwing approved these changes, later dismissed

2022-05-24 20:42 UTC, georgewrmarshall requested changes
Fantastic work! 2 tiny changes and I can approve. Thanks!

2022-05-24 20:42 UTC, georgewrmarshall commented on ui/pages/swaps/main-quote-summary/main-quote-summary.stories.js
> +DefaultStory.storyName = 'MainQuoteSummary';
We have a convention where the first story is always named "Default" then any proceeding stories are named with more context.

```suggestion
DefaultStory.storyName = 'Default';
```

2022-05-24 20:42 UTC, georgewrmarshall commented on ui/pages/swaps/main-quote-summary/main-quote-summary.stories.js
>        />
I think you will get a lint error here

```suggestion
      <MainQuoteSummary {...args} />
```

2022-05-24 21:53 UTC, Jordon-L commented
I have applied the changes. Thank you for the reviews.

2022-05-24 22:14 UTC, georgewrmarshall approved these changes, later dismissed
Excellent! 💯 Thanks for your contribution 🙏

2022-06-01 18:46 UTC, darkwing approved these changes

2022-06-01 19:19 UTC, darkwing requested changes
Ooops @Jordon-L , there are lint issues. Try `yarn lint:fix` to get those cleaned up!

2022-06-13 15:49 UTC, darkwing submitted a review, later dismissed

2022-06-13 18:56 UTC, georgewrmarshall approved these changes, later dismissed

2022-06-15 02:54 UTC, Jordon-L commented
Ok, thanks for letting me know.

2022-06-15 14:32 UTC, brad-decker approved these changes

2022-06-15 15:00 UTC, darkwing approved these changes

2022-06-15 15:43 UTC, merged