Handle an RPC provider delay in Swaps
MetaMask/metamask-extension pull request #14821
Opened 2022-06-01 15:46 UTC by dan437

## Explanation
**Return an estimated amount for a completed swap if an RPC provider has a delay**
Right now if an RPC provider has a delay with updating the `postTxBalance` field and the destination token is a native one, we show a user much lower amount, which is equal to the gas fee. Thanks to this PR we will show a user an estimated amount if the `postTxBalance` hasn't been updated.

**Create a recursive function for updating post tx balance**
If `preTxBalance` and `postTxBalance` are equal, we will try to fetch `postTxBalance` again multiple times.

## Testing
- Add the Polygon network with the following RPC, which is sometimes delayed: `https://polygon-rpc.com/`
- Try to swap some token into MATIC
- We sometimes show you an estimated amount first and then we make a tiny amount update within ~30s

2022-06-01 19:08 UTC, darkwing requested changes
Can we mock a test here?  I think this functionality could really use it.

2022-06-07 14:11 UTC, darkwing approved these changes

2022-06-07 19:24 UTC, adonesky1 commented on app/scripts/controllers/transactions/index.js
> +        this.updatePostTxBalance({
Seems unlikely but is there a world where we go through this recursively and they resolve out of order of when they were called and we end up with less fresh results?

2022-06-08 14:24 UTC, adonesky1 approved these changes
LGTM!

2022-06-08 14:32 UTC, merged