Handle error
MetaMask/metamask-extension pull request #14953
Opened 2022-06-15 09:19 UTC by filipsekulic

## Explanation
Fix the Sentry error for `eth_getBalance`.

## More Information
Fixes https://github.com/MetaMask/metamask-extension/issues/10851

## Screenshots/Screencaps

### Before

https://user-images.githubusercontent.com/92310504/173789548-7a09a2a9-562e-45af-b17e-debf9ed386d3.mov

### After

https://user-images.githubusercontent.com/92310504/173789772-d8e8157d-f7e2-485a-8685-37138a715488.mov

## Manual Testing Steps

1. Import a network (i.e. Fantom Opera). You can use [Chainlist](https://chainlist.org/).
2. Connect to that network.
3. Check how many accounts you have (`n` accounts).
4. Open background console.
5. Disconnect the Internet (from the Network tab).
6. Lock MM.
7. Click `Forgot Password` and wait for the error to be shown (disconnected).
8. Import your SRP and create a new password.
9. Create `n+1` accounts.
10. There is no `eth_getBalance` error in the background console.

2022-06-16 08:24 UTC, mirjanaKukic commented
Verified by QA

2022-06-16 15:23 UTC, darkwing commented
@brad-decker Do we want to move this logic to https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/metamask-controller.js#L2113-L2130 ?  Or is it best handled like this PR, only in specific places ?

2022-06-16 17:23 UTC, brad-decker commented
Placing the logic where you specified would not mitigate the failure here because we are calling into the provider, versus using the method on the metamask-controller. We probably want to bake some offline-support, or network-failure fallback/graceful failure into the provider stack *at some point* but for mitigating this particular issue I think the proposed solution is a good patch.

2022-06-16 22:30 UTC, darkwing requested changes
Made a small suggestion -- works great though!

2022-06-16 22:30 UTC, darkwing commented on app/scripts/lib/account-tracker.js
> +    let balance;
```suggestion
    let balance = '0x0';
```

2022-06-17 07:21 UTC, filipsekulic commented
Hey @darkwing! 
Thanks! Updated. 🙂

2022-06-17 07:34 UTC, filipsekulic commented on app/scripts/lib/account-tracker.js
> +      if (error.data.request.method === 'eth_getBalance') {
Fixed here: aaad1377a1bba0b96a47ab7a17f69541af851960

2022-06-22 12:53 UTC, darkwing approved these changes

2022-06-22 17:51 UTC, brad-decker approved these changes
LGTM

2022-07-18 15:50 UTC, merged