Snaps E2E Test Upgrades for the new test-snaps UI
MetaMask/metamask-extension pull request #14980
Opened 2022-06-17 22:39 UTC by bowensanders

Changes need to be made in order to make existing e2e tests work with the new test-snaps UI (see https://github.com/MetaMask/test-snaps/pull/40) 
This fixes both navigating through the pages as well as changes necessary to the refactor of class & id tags.

2022-06-23 16:23 UTC, bowensanders commented
These test are now working with, and can be co-deployed with https://github.com/MetaMask/test-snaps/pull/40

2022-07-06 09:22 UTC, FrederikBolding requested changes

2022-07-06 09:22 UTC, FrederikBolding commented on test/e2e/snaps/test-snap-bip-44.spec.js
> +        const snapButton = await driver.findElement('#snapId4');
This scrolls to `snapId4`, but we are currently working on `snapId3`, is this intentional? If so, we may need a better clarifying comment.

2022-07-06 09:22 UTC, FrederikBolding commented on test/e2e/snaps/test-snap-managestate.spec.js
> -        await driver.switchToWindowWithTitle('Test Snaps', windowHandles);
How come this isn't needed anymore?

2022-07-06 15:36 UTC, bowensanders commented on test/e2e/webdriver/driver.js
> +      PAGE_DOWN: '\uE00F',
testing artifact. Removing.

2022-07-06 15:38 UTC, bowensanders commented on test/e2e/webdriver/driver.js
> +      PAGE_DOWN: '\uE00F',
END was also an artifact, before you ask

2022-07-06 17:58 UTC, FrederikBolding approved these changes

2022-07-06 19:38 UTC, darkwing approved these changes

2022-07-06 22:22 UTC, merged