Reload on Lock
MetaMask/metamask-extension pull request #1502
Opened 2017-05-25 22:41 UTC by Zanibas

Fixes #1498 by adding extension reload functionality when locking MetaMask.

2017-05-26 20:12 UTC, frankiebee submitted a review, later dismissed

2017-05-26 20:12 UTC, frankiebee commented on app/scripts/metamask-controller.js
> +        this.platform.reload()
I would like us to avoid reloading from within the metamask controller and maybe instead emit a locked event and reload in background.js

2017-05-26 20:18 UTC, flyswatter commented on app/scripts/metamask-controller.js
> +        this.platform.reload()
That fits with our current design mantra that "the metamask controller is not platform dependent".

2017-05-31 00:31 UTC, flyswatter commented on app/scripts/background.js
> +  controller.on('locked', platform.reload.bind(platform))
I like that you've made it an event, so it's platform agnostic.

2017-05-31 00:31 UTC, flyswatter commented on CHANGELOG.md
> +- Locking MetaMask now restarts the extension.
Thanks for bumping changelog.

2017-05-31 00:32 UTC, flyswatter commented on test/integration/lib/first-time.js
> -  }).then(function() {
I wish there was a way to preserve this test. Maybe the `ui-dev.js` file could have an integration-test version of locking?

2017-05-31 00:35 UTC, danfinlay approved these changes
Okay I feel a little awkward about removing some integration test, but I see we have logic to ensure vault restoring elsewhere, so this doesn't look too destructive.

2017-05-31 02:10 UTC, kumavis commented
Let's overwrite the platform.reload rather than delete the test

2017-05-31 02:14 UTC, kumavis requested changes
Please don't delete the test - let's overwrite platform.reload

2017-05-31 02:20 UTC, kumavis commented
Also: main reason we wanted to do this was to clear nonce cache now that we don't reload on network
Turns out we do clear nonce cache by changing networks bc we recreate the provider
So we don't need to do this and maybe shouldnt

2017-05-31 03:23 UTC, flyswatter commented
I'm open to removing the "deploy blocker" tag on this issue, and coming back to this if it turns out to be necessary.

2017-05-31 18:44 UTC, kumavis commented
looks like we no long use `platform.reload` anywhere and the mascara platform does not currently support this. since what we are trying to do here is a platform specific action, we should follow our convention. we should:

1. remove the `reload` fn from the platform objs
2. reload via the platform obj, and allow mascara to noop it
3. for best consistency, do 1 AND not restart on lock

i personally prefer 2 as seen in my quick take on this here https://github.com/MetaMask/metamask-plugin/pull/1517

2017-05-31 21:32 UTC, flyswatter commented
This new `platform` folder & its contents is new to me. Previously `background.js` expressed the platform-specifics for the extension. Has that changed? Is `background.js` now used by multiple platforms?

I wouldn't want us to build this in a way that assumed every platform wants to reload when metamask is locked, that sounds like really hacky behavior. I just imagined this as a failsafe for the extension for now, since we want a way to clear any buggy caches.

2017-06-12 17:19 UTC, closed without merging