Capturing load time stats
MetaMask/metamask-extension pull request #15157
Opened 2022-07-07 19:07 UTC by jpuri

Fixes: #15141

Capture file load time stats for MV3

2022-07-08 12:30 UTC, segun requested changes

2022-07-08 12:30 UTC, segun commented on package.json
> +    "mv3:stats:chrome": "SELENIUM_BROWSER=chrome node test/e2e/mv3/stats.js",
```suggestion
    "mv3:stats:chrome": "SELENIUM_BROWSER=chrome ENABLE_MV3=true node test/e2e/mv3/stats.js",
```

2022-07-08 12:30 UTC, segun commented on test/e2e/webdriver/chrome.js
> +    // if (process.env.ENABLE_MV3 !== 'false') {
```suggestion
    if (process.env.ENABLE_MV3) {
```

2022-07-08 12:30 UTC, segun commented on test/e2e/webdriver/chrome.js
> +    // } else {
```suggestion
     } else {
         args.push('--log-level=3');
     }
```

2022-07-09 00:34 UTC, Milk1235 commented
> Fixes: #15141
> 
> Capture file load time stats for MV3

2022-07-11 17:02 UTC, segun approved these changes, later dismissed
LGTM

2022-07-11 18:51 UTC, brad-decker approved these changes, later dismissed

2022-07-19 09:10 UTC, seaona submitted a review, later dismissed
@jpuri I think we should update `package.json` to point into the new location and update the script name for mv3 test:

Now:
`"mv3:stats:chrome": "SELENIUM_BROWSER=chrome ENABLE_MV3=true node test/e2e/lavamoat-stats.js",`

Change needed:
`"mv3:stats:chrome": "SELENIUM_BROWSER=chrome ENABLE_MV3=true node test/e2e/mv3/stats.js",`

2022-07-19 23:33 UTC, brad-decker approved these changes

2022-07-20 07:09 UTC, segun approved these changes

2022-07-20 07:40 UTC, merged