DefinitionList story: convert knobs and actions to controls / args
MetaMask/metamask-extension pull request #15185
Opened 2022-07-11 19:50 UTC by wiserdor

## Explanation
Fixes #13060

deleted deprecated knobs and added argType with controllers and actions.

## More Information

## Screenshots/Screencaps

### Before

### After

## Manual Testing Steps

## Pre-Merge Checklist

- [ ] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [ ] PR is linked to the appropriate GitHub issue
- [ ] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [ ] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

2022-07-12 23:57 UTC, georgewrmarshall commented on ui/components/ui/definition-list/definition-list.stories.js
> +      defaultValue: SIZES.SM,
options arg type control should to be an array
```suggestion
      options: Object.values(SIZES),
      defaultValue: Object.values(SIZES.SM),
```

2022-07-13 00:00 UTC, georgewrmarshall requested changes
Looking good! Just have a few type issues. options should be an array. Also some other proptype errors in the console 

<img width="1440" alt="Screen Shot 2022-07-12 at 4 53 21 PM" src="https://user-images.githubusercontent.com/8112138/178618237-a04091a6-5dd9-44bd-a7b0-14a5e12101d6.png">

2022-07-13 18:03 UTC, wiserdor commented on ui/components/ui/definition-list/definition-list.stories.js
> +      defaultValue: SIZES.SM,
fixed and added argTypes for only relevant stories

2022-07-13 19:42 UTC, georgewrmarshall approved these changes
LGTM 💯 Thanks for the contribution @wiserdor 🙏

2022-07-20 11:28 UTC, NidhiKJha approved these changes

2022-07-20 18:58 UTC, merged