Added speed up metrics data for transaction events and properly track speed up type
MetaMask/metamask-extension pull request #15197
Opened 2022-07-12 11:14 UTC by adnansahovic

## Explanation

Added a new `originalType` property to `txMeta` in `createSpeedUpTransaction` and `transaction_speed_up` property is added in `properties` object in `_buildEventFragmentProperties`.  Transaction_speed_up is set to `true` when `txMeta.type` is `retry`, otherwise `transaction_speed_up` is set to `false`.

## More Information

* Fixes #15151

## Screenshots/Screencaps

### Before

### After

## Manual Testing Steps

2022-07-12 11:15 UTC, adnansahovic commented
I have read the CLA Document and I hereby sign the CLA

2022-07-12 16:42 UTC, darkwing submitted a review, later dismissed

2022-07-15 13:08 UTC, brad-decker requested changes

2022-07-15 13:08 UTC, brad-decker commented on app/scripts/controllers/transactions/index.js
> +      originalType: originalTxMeta.type,
Please modify shared/constants/transactions to reflect this new key on txMeta

2022-07-18 19:27 UTC, brad-decker requested changes

2022-07-18 19:27 UTC, brad-decker commented on shared/constants/transaction.js
> + * @property {string} originalType - The current original type of the
You should specify in which situations this will be present and what original type means,

2022-07-27 13:39 UTC, brad-decker approved these changes

2022-07-28 03:59 UTC, danjm approved these changes

2022-07-28 04:00 UTC, danjm commented
@darkwing can you review this again now that your comment is addressed?

2022-07-28 13:46 UTC, merged