added storybook controls for confirm send ether component
MetaMask/metamask-extension pull request #15235
Opened 2022-07-14 13:44 UTC by NidhiKJha

* Fixes #13072

### Before

<img width="1270" alt="Screenshot 2022-07-14 at 7 14 05 PM" src="https://user-images.githubusercontent.com/39872794/178996748-8799523d-1bc5-455e-b595-929272d8427f.png">

### After

<img width="1273" alt="Screenshot 2022-07-14 at 7 12 29 PM" src="https://user-images.githubusercontent.com/39872794/178996426-cef3a3fe-545d-4705-8892-e8c8bb80db71.png">

2022-07-18 20:15 UTC, georgewrmarshall commented on ui/pages/confirm-send-ether/confirm-send-ether.stories.js
> +});
Doesn't look like this is being used anywhere can we just remove it?

2022-07-18 20:17 UTC, georgewrmarshall commented on ui/pages/confirm-send-ether/confirm-send-ether.stories.js
> +  },
These don't look like the correct props? I think we can just remove.

```suggestion
```

2022-07-18 20:21 UTC, georgewrmarshall requested changes
Looks like we can clean this story up a little. I know the issue just says to convert the story from knobs to controls but we can probably clean it up a bit. Remove all the unnecessary code and let's merge haha. No need to add any other argtypes. It displays without them.

2022-07-18 20:21 UTC, georgewrmarshall commented on ui/pages/confirm-send-ether/confirm-send-ether.stories.js
>  import { store } from '../../../.storybook/preview';
Doesn't look like this is used? Can we remove?

```suggestion
```

2022-07-18 20:21 UTC, georgewrmarshall commented on ui/pages/confirm-send-ether/confirm-send-ether.stories.js
> +});
Doesn't look like this is used? Can we remove?

```suggestion
```

2022-07-18 20:21 UTC, georgewrmarshall commented on ui/pages/confirm-send-ether/confirm-send-ether.stories.js
> +};
Doesn't look like this is used can we remove?

```suggestion
```

2022-07-20 23:26 UTC, georgewrmarshall submitted a review, later dismissed

2022-07-21 22:02 UTC, kumavis approved these changes, later dismissed

2022-07-22 13:21 UTC, brad-decker approved these changes

2022-07-22 17:58 UTC, georgewrmarshall approved these changes

2022-07-22 17:58 UTC, merged