replaced Component API with Props
MetaMask/metamask-extension pull request #15324
Opened 2022-07-22 13:37 UTC by NidhiKJha

* Fixes #15309

2022-07-22 18:00 UTC, georgewrmarshall commented on .storybook/2.DOCUMENTATION.stories.mdx
> +// The mdx file to document Props and usage
Nit: props shouldn't have capital here
```suggestion
// The mdx file to document props and usage
```

2022-07-22 18:01 UTC, georgewrmarshall commented on ui/components/component-library/base-avatar/README.mdx
> +<ArgsTable of={BaseAvatar} />
This file shouldn't be in this PR :)

2022-07-22 18:02 UTC, georgewrmarshall requested changes
Just remove the base-avatar docs and one tiny copy change and this is good to go!

2022-07-22 20:24 UTC, georgewrmarshall approved these changes

2022-07-26 18:51 UTC, garrettbear approved these changes

2022-07-26 18:52 UTC, merged