ConfirmPage: use danger-primary button for setApproveForAll
MetaMask/metamask-extension pull request #15512
Opened 2022-08-09 17:08 UTC by digiwand

## Explanation

WIP - further design discussion is being had here: https://consensys.slack.com/archives/GTQAGKY5V/p1660061593025209?thread_ts=1659958204.365809&cid=GTQAGKY5V

## More Information

## Screenshots/Screencaps

<img width="669" alt="Screenshot 2022-08-09 at 11 10 15 PM" src="https://user-images.githubusercontent.com/20778143/183699050-977ca970-e87f-4c9a-8489-18395d92ffde.png">

## Manual Testing Steps

- send a `setApprovalForAll` transaction and observe a red, danger-primary "Confirm" button
- send any other transaction and observe a blue, primary "Confirm" button

### + If there are functional changes:

- [ ] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

2022-08-09 19:26 UTC, cygaar commented
Great to see, thanks for updating!

2022-08-09 20:21 UTC, adonesky1 commented
The language: `This should never be your default` might throw some users off, since almost no dapps will present users with a secondary option (say, to approve a single tokenId). I would find this language confusing. I think we should make the risks known and present it with the appropriate gravity of warning without suggesting that the user is missing some less risky option that very mainstream dapps likely don't offer

2022-08-09 20:22 UTC, adonesky1 requested changes
The language `This should never be your default` included in the warning might throw some users off, since almost no dapps will present users with a secondary option (say, to approve a single tokenId). I would find this language confusing. I think we should make the risks known and present it with the appropriate gravity of warning without suggesting that the user is missing some less risky option that very mainstream dapps likely don't offer. Open to being convinced otherwise though! cc @tayvano tagging you since I know you have strong opinions about security and the language we use to convey it.

2022-08-09 20:24 UTC, georgewrmarshall reviewed
Looks great! A couple tiny nit suggestions

2022-08-09 20:24 UTC, georgewrmarshall commented on app/_locales/en/messages.json
> +    "message": "You’re allowing access to all of your $1 NFTs plus any future NFTs in this collection. This should never be your default, no matter how secure a site may seem. Proceed with caution.",
I believe our general content guidelines are to use punctuation for any sentences that have proceeding sentences but not at the end of the last sentence? @coreyjanssen can you confirm?

```suggestion
    "message": "You’re allowing access to all of your $1 NFTs plus any future NFTs in this collection. This should never be your default, no matter how secure a site may seem. Proceed with caution",
```

2022-08-09 20:24 UTC, georgewrmarshall commented on ui/components/app/confirm-page-container/index.scss
> +    margin: 0.75rem 1rem;
I've been pushing for using pixel units for bounding box values just to save some cognitive load from Figma to code. There is a great article by Josh Comeau on this https://www.joshwcomeau.com/css/surprising-truth-about-pixels-and-accessibility/

```suggestion
    margin: 12px 16px;
```

2022-08-09 21:21 UTC, bschorchit commented
> The language This should never be your default included in the warning might throw some users off, since almost no dapps will present users with a secondary option (say, to approve a single tokenId). I would find this language confusing. I think we should make the risks known and present it with the appropriate gravity of warning without suggesting that the user is missing some less risky option that very mainstream dapps likely don't offer. Open to being convinced otherwise though! cc @tayvano tagging you since I know you have strong opinions about security and the language we use to convey it.

@adonesky1 what do you think about: "You're giving access to all your current and future <NFTname> NFTs. The other party might be able to transfer them from your wallet without further notice. Proceed with caution."
cc: @SayaGT @coreyjanssen

2022-08-09 21:44 UTC, adonesky1 commented
How about: "Bu clicking approve you are granting access to all of the NFTs you currently own on this contract and any NFTs on this contract you may acquire in the future, until you revoke this approval. The party to whom you're granting approval will be able to transfer your NFTs from your wallet without further notice. Proceed with caution" something like that... away from my computer right not so grammar could use some tweaking

2022-08-09 21:56 UTC, bschorchit commented
> How about: "By clicking approve you are granting access to all of the NFTs you currently own on this contract and any NFTs on this contract you may acquire in the future, until you revoke this approval. The party to whom you're granting approval will be able to transfer your NFTs from your wallet without further notice. Proceed with caution" something like that... away from my computer right not so grammar could use some tweaking

Sounds great to me!

2022-08-10 10:17 UTC, digiwand commented
Great call out and suggestion @adonesky1! Looks good to me. The first message was copied from a mock supplied in this [Slack thread](https://consensys.slack.com/archives/GTQAGKY5V/p1659966850991299?thread_ts=1659958204.365809&cid=GTQAGKY5V). 

I moved one comma and kept the rest the same:
> By clicking approve, you are granting access to all of the NFTs you currently own on this contract and any NFTs on this contract you may acquire in the future until you revoke this approval. The party to whom you're granting approval will be able to transfer your NFTs from your wallet without further notice. Proceed with caution.

Updated: https://github.com/MetaMask/metamask-extension/pull/15512/commits/5e0b148eee0a4d1a2a34366c7ebac34e7172fd8e

-- 

In regards to keeping or omitting the punctuation on the last sentence, we could do that in a follow-up PR if this PR gets approved before the final decision here. ref: https://github.com/MetaMask/metamask-extension/pull/15512#discussion_r941765206

2022-08-10 13:51 UTC, adonesky1 approved these changes
LGTM! Thanks @digiwand for picking up the contributor feedback here and moving this forward!

2022-08-10 14:38 UTC, darkwing approved these changes

2022-08-10 14:54 UTC, merged

2022-08-24 23:14 UTC, coreyjanssen commented
Apologies for not seeing this convo until today! (thanks @bschorchit!) Made a few edits to the proposed copy. Lmk if this works!

You're granting access to **all the NFTs on this contract**, including any you might own in the future. The party on the other end of this approval can transfer NFTs from your wallet at any time without asking you. **Proceed with caution.**

2022-08-28 03:19 UTC, digiwand commented
Hi @coreyjanssen, 

No problem! I like this update, and I'm up for updating this. One thing that I would miss from the copy that has been merged
> By clicking approve, you are granting access to all of the NFTs you currently own on this contract and any NFTs on this contract you may acquire in the future until you revoke this approval. The party to whom you're granting approval will be able to transfer your NFTs from your wallet without further notice. Proceed with caution.

is the mention that this contract is able to access the NFTs `until you revoke this approval.`. Is this something we could add in somehow? 

cc: @adonesky1 @bschorchit

2022-09-05 20:37 UTC, coreyjanssen commented
@digiwand sure thing! how's this?

You're granting access to **all the NFTs on this contract**, including any you might own in the future. The party on the other end can transfer NFTs from your wallet at any time without asking you until you revoke this approval. **Proceed with caution.**

2022-09-06 11:03 UTC, digiwand commented
Awesome!!! I think this is an A1 update! Thanks @coreyjanssen! :D

Updated here: https://github.com/MetaMask/metamask-extension/pull/15744