Mascara upkeep
MetaMask/metamask-extension pull request #1572
Opened 2017-06-08 23:47 UTC by frankiebee

- [X] reload pages when switching networks
- [X] reload page if ui is not present
- [X] update cswready event

2017-06-08 23:57 UTC, kumavis commented on mascara/src/ui.js
> +  let fourceReload = setTimeout(() => {
unused var `fourceReload`, please remove

2017-06-08 23:58 UTC, kumavis requested changes

2017-06-08 23:58 UTC, kumavis commented on app/scripts/background.js
> +  controller.on('locked', platform.reload.bind(platform))
im spinning in my grave

2017-06-08 23:59 UTC, kumavis commented
generally looks good

2017-06-09 00:08 UTC, flyswatter commented on app/scripts/background.js
> +  controller.on('locked', platform.reload.bind(platform))
Do we really think this is needed? It's kinda cool that we never crash the app on purpose anymore.

2017-06-09 00:09 UTC, frankiebee commented on app/scripts/background.js
> +  controller.on('locked', platform.reload.bind(platform))
i think i screwed up my git

2017-06-09 00:09 UTC, frankiebee commented on app/scripts/background.js
> +  controller.on('locked', platform.reload.bind(platform))
this shouldnt be in here

2017-06-12 17:36 UTC, kumavis approved these changes

2017-06-12 17:36 UTC, merged