Show 3box deprecation message in whats new
MetaMask/metamask-extension pull request #15763
Opened 2022-09-07 21:11 UTC by segun

## Explanation

3Box is being deprecated, this PR shows a message to 3box users that it will be deprecated, directing them to the replacement (Backup/Restore) functionality

## More Information

* Fixes #15595

## Screenshots/Screencaps

<img width="509" alt="Screenshot 2022-09-08 at 01 06 33" src="https://user-images.githubusercontent.com/44811/188980243-0a4d86e4-6fe6-4a4a-8654-434f2489add6.png">

## Manual Testing Steps

- Launch MetaMask
- If you have 3box syncing enabled, you should see the above in What's New Popup
- Else go to Settings > Advanced Settings > Sync data with 3Box (experimental) (Enable the toggle)
- Quit Browser
- Relaunch Browser
- Launch MetaMask
- You should see the above in What's New Popup

## Pre-Merge Checklist

- [ ] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [ ] PR is linked to the appropriate GitHub issue
- [ ] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [ ] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

2022-09-08 14:03 UTC, darkwing approved these changes, later dismissed

2022-09-08 18:46 UTC, brad-decker approved these changes

2022-09-08 18:46 UTC, brad-decker requested changes
Requesting changes for @coreyjanssen 's review

2022-09-09 00:09 UTC, segun commented
@kevinghim @coreyjanssen is the deprecation date okay?

2022-09-09 00:22 UTC, coreyjanssen commented
> @kevinghim @coreyjanssen is the deprecation date okay?

I'm assuming this is the date that 3Box is being deprecated? If so, it might make the most sense to add this inline with the body copy because as it is doesn't have much context for the user. Perhaps it would make sense to replace the word `soon `with `on 10/12/2022` or in `early October` (the latter if 10/12 isn't 100% definite).

2022-09-09 11:27 UTC, segun commented
@coreyjanssen okay, so we just need to define the deprecation date. @danjm @kevinghim

2022-09-09 16:45 UTC, danjm commented
@segun @coreyjanssen I think "in early October" is the best bet. We don't know the exact date

2022-09-09 16:46 UTC, danjm requested changes
Code looks good. Will approve when final copy adjustments are made

2022-09-09 16:52 UTC, coreyjanssen commented
Updated body copy, no need to display the date below: 

We're deprecating our 3Box data feature in early October. To backup and restore your wallet manually, use the "backup now" button in Advanced Settings.

2022-09-11 22:33 UTC, segun commented
> Code looks good. Will approve when final copy adjustments are made

Hi @danjm I noticed that when I turn on 3box and there's an error, it turns off the toggle. This means that it's possible that a 3box user won't be notified even if they had previously turned on the 3box toggle.

2022-09-12 14:56 UTC, danjm commented
> Hi @danjm I noticed that when I turn on 3box and there's an error, it turns off the toggle. This means that it's possible that a 3box user won't be notified even if they had previously turned on the 3box toggle.

@segun That's okay. We won't be able to notify all users anyway, because some may not log in before 3box is removed.

2022-09-13 14:37 UTC, danjm submitted a review, later dismissed
LGTM

2022-09-13 15:44 UTC, brad-decker approved these changes, later dismissed

2022-09-13 17:53 UTC, danjm approved these changes

2022-09-13 17:59 UTC, brad-decker approved these changes

2022-09-13 18:51 UTC, merged