Ensure data updates are debounced when updating the amount in the send screen
MetaMask/metamask-extension pull request #15820
Opened 2022-09-14 06:36 UTC by danjm

Fixes https://github.com/MetaMask/metamask-extension/issues/15445

2022-09-14 14:09 UTC, segun submitted a review, later dismissed

2022-09-14 14:55 UTC, brad-decker approved these changes, later dismissed

2023-04-27 01:42 UTC, legobeat approved these changes
@danjm it isn't clear to me how debouncing fixes the linked issue but it looks like a desired changed regardless.

2023-04-27 01:47 UTC, legobeat requested changes
@danjm it isn't clear to me how debouncing fixes the linked issue but it looks like a desired changed regardless so let's get this in.

Failing test has to be resolved:
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/44190/workflows/970dca7e-fd91-4e41-b46c-0456c6253656/jobs/1244864?invite=true#step-103-189

2023-06-20 18:24 UTC, closed without merging