Removing use of window object from sentry code
MetaMask/metamask-extension pull request #16022
Opened 2022-09-28 15:11 UTC by jpuri

Fixes # 15993

Sentry seemed to work well in MV3 with correct build configurations required by sentry code.

A possible flow was using window variable, the PR removes that as well.

2022-09-28 20:48 UTC, brad-decker commented
What are we losing by just removing the code?

2022-10-03 17:00 UTC, Gudahtt requested changes
This will break Sentry sourcemaps. The reports are rewritten to normalize stack traces across browsers, and bring them in-line with the sourcemaps we generate for each release.

2022-10-03 17:41 UTC, jpuri commented
@brad-decker , @Gudahtt : since window object is no longer available to service worker in MV3, this code will not work: https://github.com/MetaMask/metamask-extension/pull/16022/files#diff-a8c55d1ad0724e946c8c35114d6a298b74904accdddedff77e1b8ade2097fd65L229

I am not sure if we have an alternate way to fix sentry sourcemaps.

2022-10-04 17:44 UTC, jpuri commented on app/scripts/lib/setupSentry.js
> -  const filePath = origUrl.split(window.location.origin)[1];
The code will add extension info like `moz-extension://d676bdef-8993-1947-9af2-2d644db19eb5/home.html` or `'chrome-extension://fkjakconokebomphaccgecffpielpojl'` to the url.

We can check other ways to get extension detail, but I am not sure if this is very useful in error reporting.

2022-10-04 17:45 UTC, Gudahtt commented on app/scripts/lib/setupSentry.js
> -  const filePath = origUrl.split(window.location.origin)[1];
This code is doing the opposite of that; it's replacing the origin in stack traces, so that Sentry can link them with our uploaded sourcemaps.

2022-10-04 17:46 UTC, Gudahtt commented on app/scripts/lib/setupSentry.js
> -  const filePath = origUrl.split(window.location.origin)[1];
This can be updated to support service workers by using `globalThis` instead of `window`. The location API is still available.

2022-10-05 09:28 UTC, jpuri commented on app/scripts/lib/setupSentry.js
> -  const filePath = origUrl.split(window.location.origin)[1];
`globalThis` seems to have fixed the issue, thanks @Gudahtt

2022-10-05 14:03 UTC, Gudahtt approved these changes
LGTM!

2022-10-05 16:13 UTC, digiwand approved these changes

2022-10-05 17:17 UTC, merged