Feat/15951/add button secondary
MetaMask/metamask-extension pull request #16097
Opened 2022-10-05 19:07 UTC by garrettbear

## Explanation

Adding ButtonSecondary built off of ButtonBase. 

(similar to ButtonPrimary)

Sizes: SM, MD, & LG
Types: Normal (default) and Danger (enabled with danger prop = true) 

[Figma](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=2939%3A20593)

## More Information

- Fixes #15092 

## Screenshots/Screencaps

<img width="542" alt="Screen Shot 2022-10-05 at 11 51 24 AM" src="https://user-images.githubusercontent.com/26469696/194140851-8dc8f8dd-49e9-48a8-8c5c-e1425076492f.png">
<img width="222" alt="Screen Shot 2022-10-05 at 12 02 27 PM" src="https://user-images.githubusercontent.com/26469696/194141285-a357cf31-79e6-4be5-8d8a-4091d67e4076.png">

## Manual Testing Steps

`yarn test:unit:jest .ui/components/component-library/button-secondary/button-secondary.test.js`

## Pre-Merge Checklist

- [x] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [x] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

2022-10-05 19:40 UTC, georgewrmarshall reviewed
Some tiny suggestions otherwise 🔥🔥🔥

2022-10-05 19:40 UTC, georgewrmarshall commented on ui/components/component-library/button-secondary/README.mdx
> +The `ButtonSecondary` is an extension of `ButtonBase` to support primary styles.
Update copy
```suggestion
The `ButtonSecondary` is an extension of `ButtonBase` to support secondary styles.
```

2022-10-05 19:40 UTC, georgewrmarshall commented on ui/components/component-library/button-secondary/button-secondary.js
> +
nit: remove line break
```suggestion
```

2022-10-05 19:40 UTC, georgewrmarshall commented on ui/components/component-library/button-secondary/button-secondary.js
> +   */
I think we should use global `SIZES` const here
```suggestion
   * The possible size values for ButtonSecondary: 'SIZES.SM', 'SIZES.MD', 'SIZES.LG',
   * Default value is 'SIZES.MD'.
   */
```

2022-10-05 21:34 UTC, georgewrmarshall commented on ui/components/component-library/button-secondary/README.mdx
> +The `ButtonSecondary` is an extension of `ButtonBase` to support primary styles.
@garrettbear still need to complete this update?

2022-10-06 17:36 UTC, NidhiKJha requested changes
LGTM! 🔥🔥

2022-10-06 17:36 UTC, NidhiKJha commented on ui/components/component-library/button-secondary/button-secondary.stories.js
> +  </>
Nit: Do we need a fragment here?

2022-10-06 21:28 UTC, georgewrmarshall submitted a review, later dismissed
LGTM 🔥

2022-10-06 21:38 UTC, georgewrmarshall approved these changes

2022-10-07 05:51 UTC, NidhiKJha approved these changes

2022-10-07 15:50 UTC, merged