add box height and width responsive sizes
MetaMask/metamask-extension pull request #16111
Opened 2022-10-06 18:22 UTC by garrettbear

## Explanation

Box `height` and `width` accept an array of valid sizes to support a responsive layout. 

## More Information

Fixes: #16110 

## Screenshots/Screencaps

### Before & After Video

https://www.loom.com/share/dd41599bc3cc4b99baf4e7bab7c2d45f

## Manual Testing Steps

## Pre-Merge Checklist

- [x] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [x] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

2022-10-06 19:42 UTC, georgewrmarshall reviewed
Looks good! So stoked this is being fixed. Do we need to add any more unit tests?

2022-10-06 21:21 UTC, georgewrmarshall approved these changes, later dismissed
LGTM

2022-10-07 13:15 UTC, brad-decker requested changes, later dismissed

2022-10-07 13:15 UTC, brad-decker commented on ui/components/ui/box/box.js
> +const ValidJustifyContent = PropTypes.oneOf(JUSTIFY_CONTENT);
the Object.values() was dropped here which I think should be in place still?

2022-10-07 16:35 UTC, georgewrmarshall approved these changes

2022-10-09 23:51 UTC, georgewrmarshall reviewed
Would be sick to get some stories showing some layout options using the shorthand prop notation for withs

2022-10-10 15:54 UTC, NidhiKJha approved these changes

2022-10-10 17:59 UTC, merged