Fix/16207/text component storybook
MetaMask/metamask-extension pull request #16214
Opened 2022-10-14 17:58 UTC by garrettbear

## Explanation
Text component Storybook was broken due to an addition of `input` to the `ValidTags` array. To fix the input example needs to be properly formatted as an input element in the example. 

## More Information

* Fixes #16207

## Screenshots/Screencaps

### Before

<img width="1440" alt="195865604-25b285ad-2222-4719-b0e1-b4378cea835d" src="https://user-images.githubusercontent.com/26469696/195911094-7d890773-fa89-4e95-b087-dcb213758743.png">

### After

<img width="1047" alt="Screen Shot 2022-10-14 at 10 55 04 AM" src="https://user-images.githubusercontent.com/26469696/195911128-0eff8509-3d43-4be9-acc8-3bcf0a86bf0b.png">

## Manual Testing Steps

## Pre-Merge Checklist

- [X] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added _(Storybook render test still needed)_
- [X] PR is linked to the appropriate GitHub issue
- [X] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [X] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

2022-10-14 18:16 UTC, NidhiKJha requested changes

2022-10-14 18:16 UTC, NidhiKJha commented on ui/components/component-library/text/README.mdx
> +<Text as="input" placeholder="input"></Text>
Can we change it to `<Text as="input" placeholder="placeholder"/>`

2022-10-16 09:55 UTC, georgewrmarshall approved these changes
Thanks so much for this fix and apologies for creating the bug in the first place 🤦 🙇. Stories still don't seem to be showing up in the docs

<img width="1440" alt="Screen Shot 2022-10-16 at 11 54 40 AM" src="https://user-images.githubusercontent.com/8112138/196029146-edc46907-0dc8-4e6c-90cb-84ba8991af15.png">

2022-10-16 10:38 UTC, NidhiKJha approved these changes

2022-10-19 18:09 UTC, merged