Feat/16290/add button component
MetaMask/metamask-extension pull request #16305
Opened 2022-10-28 18:12 UTC by garrettbear

## Explanation

Unifying `ButtonPrimary`, `ButtonSecondary`, and `ButtonLink` to be `Button`. 

## More Information

Fixes: #16290 

## Screenshots/Screencaps

### After
<img width="553" alt="Screen Shot 2022-10-28 at 10 52 15 AM" src="https://user-images.githubusercontent.com/26469696/198703456-3364f2ab-e22b-44a4-b2f7-9e3cdb0e5bb6.png">

## Manual Testing Steps
`yarn test:unit:jest .ui/components/component-library/button/button.test.js `

## Pre-Merge Checklist

- [x] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [X] PR is linked to the appropriate GitHub issue
- [X] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [X] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

2022-10-28 21:12 UTC, georgewrmarshall requested changes
Looking good. Can we move all the ButtonBase updates into a separate PR for brevity?

2022-10-28 21:12 UTC, georgewrmarshall commented on ui/components/component-library/button/README.mdx
> +### This is a base component. It should not be used in your feature code directly but as a "base" for other UI components
Remove this
```suggestion
```

2022-10-28 21:12 UTC, georgewrmarshall commented on ui/components/component-library/button/README.mdx
> +The `Button` is the base component for buttons.
Update the description

```suggestion
The `Button` is used for user actions it unifies `ButtonPrimary`, `ButtonSecondary` and `ButtonLink`
```

2022-11-07 03:48 UTC, georgewrmarshall reviewed
Looking good! Left some small suggestions

2022-11-07 03:48 UTC, georgewrmarshall commented on ui/components/component-library/button-primary/button-primary.js
> +   * When true, ButtonSecondary color becomes Danger.
Should be ButtonPrimary?
```suggestion
   * When true, `ButtonPrimary` color becomes Danger.
```

2022-11-07 03:48 UTC, georgewrmarshall commented on ui/components/component-library/button/README.mdx
> +<Button type={BUTTON_TYPES.LINK}>Link Button</Button>
To be consistent with out naming should we just use the names verbatim?
```suggestion
<Button type={BUTTON_TYPES.PRIMARY}>Button Primary</Button>
<Button type={BUTTON_TYPES.SECONDARY}>Button Secondary</Button>
<Button type={BUTTON_TYPES.LINK}>Button Link</Button>
```

2022-11-07 03:48 UTC, georgewrmarshall commented on ui/components/component-library/button/button.js
> +  style: PropTypes.object,
Let's not promote the style prop in our components

```suggestion
```

2022-11-07 03:48 UTC, georgewrmarshall commented on ui/components/component-library/button/button.stories.js
> +
nit: remove line break
```suggestion
```

2022-11-07 03:48 UTC, georgewrmarshall commented on ui/components/component-library/button/button.stories.js
> +      Link Button
Let's update this text so it's consistent with our component naming
```suggestion
     Button Primary
    </Button>
    <Button type={BUTTON_TYPES.SECONDARY} {...args}>
      Button Secondary
    </Button>
    <Button type={BUTTON_TYPES.LINK} {...args}>
     Button Link
```

2022-11-07 03:48 UTC, georgewrmarshall commented on ui/components/component-library/button/README.mdx
> +The `Button` accepts all props below as well as all [Box](/docs/ui-components-ui-box-box-stories-js--default-story#props) component props
Let's add that it accepts all prop for the other button types as well

2022-11-08 18:18 UTC, georgewrmarshall submitted a review, later dismissed
LGTM! Just need to fix linting. 🚢 it 💯

2022-11-08 20:35 UTC, georgewrmarshall approved these changes

2022-11-09 15:09 UTC, NidhiKJha approved these changes

2022-11-09 21:55 UTC, merged