modified transaction complete popup
MetaMask/metamask-extension pull request #16300
Opened 2022-10-28 15:32 UTC by adnansahovic

## Explanation

Changed the text on popup for complete transaction.

## More Information

* Fixes #15759

## Screenshots/Screencaps

### Before
![188907813-0c312e2a-10ca-4d1e-95da-d1c6b9a90269](https://user-images.githubusercontent.com/63151811/198675171-2d4cc685-b7bc-44aa-a1b2-e2a9375da33a.png)

### After
<img width="353" alt="Screenshot 2022-10-28 at 16 05 10" src="https://user-images.githubusercontent.com/63151811/198675219-e50a1e9e-a631-4c96-bd27-2fe4b65aada2.png">

## Manual Testing Steps

1. Make a transaction on any chain except ethereum
2. You'll get a popup after the completion of transaction

2022-10-31 12:30 UTC, mirjanaKukic commented
Verified by QA

2022-11-21 15:11 UTC, brad-decker submitted a review, later dismissed

2022-11-21 15:11 UTC, brad-decker commented
@adnansahovic needs a rebase.

2022-11-30 05:39 UTC, jpuri commented on app/scripts/platforms/extension.js
> +    const view = getURLHostName(url).replace(/([.]\w+)$/u, '');
- Is this way of deriving view name from URL good enough ?
- `startCase(toLower(view))` this conversion can also be probably done here.

2022-12-01 15:07 UTC, brad-decker requested changes

2022-12-01 15:07 UTC, brad-decker commented on app/scripts/platforms/extension.js
> +      toLower(getURLHostName(url).replace(/([.]\w+)$/u, '')),
I have to agree with @jpuri on this one. Your screenshot for Mumbai PolygonScan makes it appear that this works with subdomains (mumbai) but then Ehterscan would have a 'www' proceeding it? And if I do a naive assertion on this regex statement in console: 

```
const y = new URL('https://mumbai.polygonscan.com/');
> undefined
y.hostname.replace(/([.]\w+)$/u, '')
> 'mumbai.polygonscan'
y.hostname.replace(/([.]\w+)$/ug, '')
> 'mumbai.polygonscan'
```

2022-12-13 18:06 UTC, brad-decker commented on app/scripts/platforms/extension.js
> +      toLower(getURLHostName(url).replace(/([.]\w+)$/u, '')),
I missed the call to 'startCase' which is the reason the magic works. Alright i'm good with this. Thanks for pushing back @adnansahovic

2022-12-13 18:06 UTC, brad-decker approved these changes

2023-01-04 14:25 UTC, jpuri approved these changes

2023-01-04 15:38 UTC, darkwing commented
Merging as there are two approvals!

2023-01-04 15:40 UTC, merged