Updating showClearButton prop name and making component dumber
MetaMask/metamask-extension pull request #16424
Opened 2022-11-09 01:12 UTC by georgewrmarshall

## Explanation

**What is the current state of things and why does it need to change?**
The current `TextField` component handles the clear button logic but this was actually breaking the component when `value` was changed outside of the `onChange` function. It also limits the flexibility of the component.

**What is the solution your changes offer and how does it work?**
- Updating the name of the `showClear` prop to `showClearButton` which is more specific
- Reducing the logic used inside of the component in favour of letting the engineer handle it for each usecase
- Updating the stories and docs to reflect these changes
- Updating unit tests to reflect these changes as well as improving the quality of the tests by using [userEvent](https://testing-library.com/docs/user-event/intro/)

## Screenshots/Screencaps

### Before

https://user-images.githubusercontent.com/8112138/200711673-51e703ed-93fd-4177-96ea-370a1c630866.mov

### After

https://user-images.githubusercontent.com/8112138/200711704-21401aeb-55c0-4954-9881-5eb7bb94a6d4.mov

## Manual Testing Steps

- Go to the latest build of storybook in this PR
- Search `TextField` in the search bar (make sure it's under the Component Library section)
- Check the controls and docs

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2022-11-09 01:21 UTC, georgewrmarshall commented on ui/components/component-library/text-field/text-field.js
> -  clearButtonIconProps: PropTypes.shape(Icon.PropTypes),
Removing `clearButtonIconProps` because this won't exist once the placeholder clear button is updated with `ButtonIcon`

2022-11-09 14:37 UTC, NidhiKJha requested changes
Just a small nit for tests

2022-11-09 14:37 UTC, NidhiKJha commented on ui/components/component-library/text-field/text-field.test.js
> +    await user.click(getByRole('button', { name: /clear/u }));
```suggestion
    await user.click(getByRole('button', { name: /Clear/u }));
```

2022-11-09 14:37 UTC, NidhiKJha commented on ui/components/component-library/text-field/text-field.test.js
> +    await user.click(getByRole('button', { name: /clear/u }));
```suggestion
    await user.click(getByRole('button', { name: /Clear/u }));
```

2022-11-09 14:37 UTC, NidhiKJha commented on ui/components/component-library/text-field/text-field.test.js
> +    expect(getByRole('button', { name: /clear/u })).toBeDefined();
```suggestion
    expect(getByRole('button', { name: /Clear/u })).toBeDefined();
```

2022-11-09 21:52 UTC, georgewrmarshall commented on ui/components/component-library/text-field/text-field.test.js
> +    await user.click(getByRole('button', { name: /clear/u }));
Fixed https://github.com/MetaMask/metamask-extension/pull/16424/commits/f3cb2c978e5d8b5771113637ad4ea7b7dae042a8

2022-11-09 21:52 UTC, georgewrmarshall commented on ui/components/component-library/text-field/text-field.test.js
> +    await user.click(getByRole('button', { name: /clear/u }));
Fixed https://github.com/MetaMask/metamask-extension/pull/16424/commits/f3cb2c978e5d8b5771113637ad4ea7b7dae042a8

2022-11-10 00:47 UTC, garrettbear submitted a review, later dismissed

2022-11-10 01:38 UTC, georgewrmarshall commented on ui/components/component-library/text-field/text-field.test.js
>      const { getByRole } = render(
When running these tests locally you may run into this propType issue it's a known issue and I have an open PR that with the gracious help of @Gudahtt we are still trying to work through https://github.com/MetaMask/metamask-extension/pull/16078

<img width="547" alt="Screen Shot 2022-11-09 at 7 33 04 PM" src="https://user-images.githubusercontent.com/8112138/200979200-95e94f84-f20c-4f08-a6ca-9f1033870b86.png">

2022-11-10 03:44 UTC, NidhiKJha approved these changes, later dismissed

2022-11-10 18:21 UTC, NidhiKJha approved these changes

2022-11-10 19:12 UTC, theweb3dev approved these changes

2022-11-10 19:13 UTC, garrettbear approved these changes

2022-11-10 19:13 UTC, merged