Added reject transactions modal to be present in the footer of the approve screen
MetaMask/metamask-extension pull request #16832
Opened 2022-12-07 11:06 UTC by VSaric

## Explanation

Added reject transactions modal to be present in the footer of the approve screen. Batch reject button is present now in the token allowance screen.

* Fixes #16769 

## Screenshots/Screencaps

### Before

### After

#### test-dapp

https://user-images.githubusercontent.com/92527393/206162292-1ac910eb-090d-48b5-a3b8-25ab5e535b35.mov

#### etherscan

https://user-images.githubusercontent.com/92527393/206162516-0803a2fa-1800-4b11-a2c4-a265adecc166.mov

## Manual Testing Steps

### test-dapp

1. Navigate to the [test dapp](https://metamask.github.io/test-dapp)
2. Connect your wallet
3. Deploy the `ERC20` token
4. Click `Approve Token` multiple times
5. Navigate back to the wallet

### etherscan

1. Go to https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f#writeContract
2. Connect your wallet
3. Under `approve` input any address and a number
4. Click on `write` multiple times
5. Navigate back to the wallet

2022-12-07 13:33 UTC, mirjanaKukic commented
Verified by QA

2022-12-07 20:22 UTC, darkwing requested changes

2022-12-07 20:22 UTC, darkwing commented on ui/pages/token-allowance/token-allowance.js
> +          <a onClick={() => handleCancelAll()}>
To make this accessible, this element needs a `href` attribute. So maybe something like:

```
<a href="" onClick={(e) => { e.preventDefault(); handleCancelAll() }}>
```

Better yet would be to use a `<Button>` component.

2022-12-08 17:51 UTC, darkwing approved these changes
Nicely done @VSaric !

2022-12-09 06:39 UTC, jpuri commented
Great work 👍 

Will be nice to have some test also added.

2022-12-09 07:52 UTC, VSaric commented
Hey @jpuri, I agree on adding some test for this, but we don't have any tests for `token-allowance.js`. Is it okay for you that we create new PR for adding tests for `token-allowance.js` and move forward with this PR and ship it? 

cc: @bschorchit

2022-12-12 12:49 UTC, danjm commented
> Is it okay for you that we create new ticket for adding tests for token-allowance.js and move forward with this PR and ship it?

I think this would be okay in this case. This just fixes a part of the component and is sort of a blocker for next release. But we should prioritize the tests very soon.

2022-12-12 12:57 UTC, bschorchit commented
I've created the new ticket for adding tests to token allowance here https://github.com/MetaMask/metamask-extension/issues/16910 and added to PS team's board.

2022-12-12 19:27 UTC, danjm approved these changes

2022-12-13 12:33 UTC, merged