User should be able to search setting to batch account balance request
MetaMask/metamask-extension pull request #16887
Opened 2022-12-09 10:07 UTC by jpuri

Fixes: #16829

User should be able to search setting to batch account balance request

2022-12-09 14:58 UTC, pedronfigueiredo submitted a review, later dismissed

2022-12-09 15:57 UTC, NiranjanaBinoy requested changes
Changes look good to me;
We also need to update the index of `this.settingsRefs[]` as well to scroll the view to the `Batch account balance requests`

2022-12-12 14:15 UTC, darkwing approved these changes

2022-12-12 14:26 UTC, digiwand approved these changes

2022-12-12 14:53 UTC, NiranjanaBinoy approved these changes

2022-12-12 15:05 UTC, merged