[e2e]Add e2e test for deleting custom network
MetaMask/metamask-extension pull request #17254
Opened 2023-01-17 13:43 UTC by dzfjz

## Explanation

Added new custom network and deleted the same one.

* Fixes #17023 
* See: #67890
-->

## Screenshots/Screencaps

### Before

### After

## Manual Testing Steps

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-01-18 11:30 UTC, pedronfigueiredo approved these changes, later dismissed

2023-01-24 13:29 UTC, PeterYinusa requested changes

2023-01-27 15:25 UTC, dzfjz commented on test/e2e/tests/add-custom-network.spec.js
> +        addNetwork.click();
Done

2023-01-27 15:48 UTC, PeterYinusa commented on test/e2e/tests/add-custom-network.spec.js
> +  it('Add a custom network and then delete that same network', async function () {
Nit: I would update the title as we are no longer `Add` a custom network

2023-01-27 15:48 UTC, PeterYinusa approved these changes

2023-01-27 15:56 UTC, seaona approved these changes
LGTM

2023-01-27 16:50 UTC, merged