Copy update on Transaction breakdown for ApproveToken
MetaMask/metamask-extension pull request #17296
Opened 2023-01-19 15:17 UTC by NiranjanaBinoy

Part of #17228 
## Explanation
Updating the copy changes suggested in the ticket:

> Update title to Approve token spending cap instead of Approve Token spend limit.
Update the copy to Spending cap instead of Spend limit amount.
so it matches the copy in the token allowance request itself.

## Screenshots/Screencaps

### Before
<img width="331" alt="Screenshot 2023-01-19 at 10 15 58 AM" src="https://user-images.githubusercontent.com/43930900/213480166-9392e4f1-f3a1-4fb3-9f32-7abf3dab7ec1.png">

### After
<img width="329" alt="Screenshot 2023-01-19 at 10 11 31 AM" src="https://user-images.githubusercontent.com/43930900/213479076-a69a54f3-01ef-488d-ac97-ad01b5fdaf22.png">

## Manual Testing Steps

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-01-19 18:18 UTC, jpuri requested changes
PR does not fix issue completely.

2023-01-20 15:39 UTC, bschorchit commented
Could we lower case the `token` in the tittle so it shows as `token` instead of `Token`? It's the content design standard

2023-01-20 18:03 UTC, NiranjanaBinoy commented
@jpuri This PR is intended to cover only the copy change mentioned in the comments in the ticket, the rest of the issue will be addressed in a follow up PR.

2023-01-23 15:20 UTC, jpuri submitted a review, later dismissed

2023-01-24 16:43 UTC, digiwand submitted a review, later dismissed

2023-01-24 19:21 UTC, digiwand approved these changes

2023-01-25 15:07 UTC, jpuri approved these changes

2023-01-25 15:15 UTC, merged