Feat/15086/add banner severities component
MetaMask/metamask-extension pull request #17307
Opened 2023-01-20 00:07 UTC by garrettbear

## Explanation

*Fixes: #15086 

## Screenshots/Screencaps

### Before
<img width="1024" alt="Screenshot 2023-01-19 at 4 04 52 PM" src="https://user-images.githubusercontent.com/26469696/213589162-5a2543dd-8093-401c-b445-ba8e44902757.png">

### After
Fixed `BannerBase` to be full width/block
<img width="926" alt="Screenshot 2023-01-19 at 4 04 25 PM" src="https://user-images.githubusercontent.com/26469696/213589169-34f23f56-a025-4b52-b5be-d41c733bff7b.png">

<img width="923" alt="Screenshot 2023-01-19 at 4 05 39 PM" src="https://user-images.githubusercontent.com/26469696/213589264-3d7805e8-9658-46e2-9357-525ac0fb8bcb.png">

## Manual Testing Steps

`yarn jest ui/components/component-library/banner/banner.test.js`

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [x] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [x] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-01-24 01:13 UTC, georgewrmarshall reviewed
Looking great! Some minor suggestions

2023-01-24 01:13 UTC, georgewrmarshall commented on ui/components/component-library/banner/banner.js
> +  };
Could you save some lines of code here by returning an object and spreading it to the Icon component? Something like:

```jsx
  const severityIcon = () => {
    switch (severity) {
      case SEVERITIES.DANGER:
        return {
          name: ICON_NAMES.DANGER_FILLED,
          color: COLORS.ERROR_DEFAULT,
        };
      case SEVERITIES.WARNING:
        return {
          name: ICON_NAMES.WARNING_FILLED,
          color: COLORS.WARNING_DEFAULT,
        };
      case SEVERITIES.SUCCESS:
        return {
          name: ICON_NAMES.CHECK_CIRCLE_ON_FILLED,
          color: COLORS.SUCCESS_DEFAULT,
        };
      // Defaults to SEVERITIES.INFO
      default:
        return {
          name: ICON_NAMES.INFO_FILLED,
          color: COLORS.PRIMARY_DEFAULT,
        };
    }
  };

return (
    <BannerBase
      startAccessory={<Icon size={SIZES.LG} {...severityIcon()} />}
      backgroundColor={severityBackground()}
```

```

2023-01-24 01:13 UTC, georgewrmarshall commented on ui/components/component-library/banner/banner.js
> +   * TODO WRITE HERE
Update to do
```suggestion
   * Use the `severity` prop and the `SEVERITIES` object from `./ui/helpers/constants/design-system.js` to change the context of `Banner`.
   * Possible options: `SEVERITIES.INFO`(Default), `SEVERITIES.WARNING`, `SEVERITIES.DANGER`, `SEVERITIES.SUCCESS`
```

2023-01-24 05:58 UTC, NidhiKJha requested changes, later dismissed
Looks really good. Just a couple of URL update in Readme

2023-01-24 05:58 UTC, NidhiKJha commented on ui/components/component-library/banner/README.mdx
> +The `Banner` accepts all props below as well as all [Box](/docs/ui-components-ui-box-box-stories-js--default-story#props) component props
Need to update the box url 
```suggestion
The `Banner` accepts all props below as well as all [Box](/docs/components-ui-box--default-story#props) component props
```

2023-01-24 05:58 UTC, NidhiKJha commented on ui/components/component-library/banner/README.mdx
> +Use the `actionButtonLabel` prop to pass text, `actionButtonOnClick` prop to pass an onClick handler, and `actionButtonProps` prop to pass an object of [ButtonLink props](/docs/ui-components-componen
```suggestion
Use the `actionButtonLabel` prop to pass text, `actionButtonOnClick` prop to pass an onClick handler, and `actionButtonProps` prop to pass an object of [ButtonLink props](/docs/components-componentlibrary-buttonlink--default-story) for the action
```

2023-01-25 15:15 UTC, darkwing approved these changes

2023-01-25 17:50 UTC, georgewrmarshall approved these changes
LGTM!

We have one accessibility violation but I think it's because the background color isn't using our `background-default` `#FFFFF`

<img width="1440" alt="Screenshot 2023-01-25 at 9 47 23 AM" src="https://user-images.githubusercontent.com/8112138/214642576-95f7240f-c9bc-4a7a-94b9-a388a59f849d.png">

Please also connect with @Akatori-Design because we have some inconsistencies with our code component and Figma component.

2023-01-25 18:39 UTC, merged