Move confirm-transaction/conf-tx.js to confirm-signature-request
MetaMask/metamask-extension pull request #17408
Opened 2023-01-25 05:23 UTC by jpuri

Fixes: #17240

Move confirm-transaction/conf-tx.js to confirm-signature-request

2023-01-26 12:54 UTC, pedronfigueiredo submitted a review, later dismissed

2023-02-01 15:08 UTC, brad-decker requested changes
It appears that conf-tx.js is no longer used except in its test file, should it be deleted?

2023-02-01 15:40 UTC, jpuri commented
Thanks @brad-decker : conf-tx it seems came back to branch during some rebase / merge. I removed it again 🙏

2023-02-01 17:07 UTC, brad-decker approved these changes

2023-02-02 14:02 UTC, blackdevelopa reviewed
LGTM

2023-02-02 14:10 UTC, pedronfigueiredo approved these changes

2023-02-02 14:52 UTC, merged