UX: Icons: Remove IconCheck and fa-check
MetaMask/metamask-extension pull request #17787
Opened 2023-02-16 23:31 UTC by darkwing

## Explanation

Removes the usage of both the `<IconCheck />` component as well as `fa-check`.

## Screenshots/Screencaps

Coming soon...

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-02-17 02:36 UTC, georgewrmarshall requested changes, later dismissed
Need to update `CLOSE` to `CHECK`

2023-02-17 02:36 UTC, georgewrmarshall commented on ui/components/app/account-menu/account-menu.component.js
> +              <Icon color={Color.successDefault} name={ICON_NAMES.CLOSE} />
```suggestion
              <Icon color={Color.successDefault} name={ICON_NAMES.CHECK} />
```

2023-02-17 02:36 UTC, georgewrmarshall commented on ui/components/app/modals/metametrics-opt-in-modal/metametrics-opt-in-modal.component.js
> +                  <Icon name={ICON_NAMES.CLOSE} />
```suggestion
                  <Icon name={ICON_NAMES.CHECK} />
```

2023-02-17 02:36 UTC, georgewrmarshall commented on ui/components/app/modals/metametrics-opt-in-modal/metametrics-opt-in-modal.component.js
> +                  <Icon name={ICON_NAMES.CLOSE} />
```suggestion
                  <Icon name={ICON_NAMES.CHECK} />
```

2023-02-17 02:36 UTC, georgewrmarshall commented on ui/components/app/modals/transaction-confirmed/transaction-confirmed.component.js
> +            name={ICON_NAMES.CLOSE}
```suggestion
            name={ICON_NAMES.CHECK}
```

2023-02-17 02:36 UTC, georgewrmarshall commented on ui/components/ui/editable-label/editable-label.js
> +          <Icon name={ICON_NAMES.CLOSE} className="editable-label__icon" />
```suggestion
          <Icon name={ICON_NAMES.CHECK} className="editable-label__icon" />
```

2023-02-17 02:36 UTC, georgewrmarshall commented on ui/components/ui/form-field/form-field.stories.js
> +    checkmark: <Icon name={ICON_NAMES.CLOSE} />,
```suggestion
    checkmark: <Icon name={ICON_NAMES.CHECK} />,
```

2023-02-17 02:36 UTC, georgewrmarshall commented on ui/pages/onboarding-flow/create-password/create-password.js
> +                  <Icon name={ICON_NAMES.CLOSE} />
```suggestion
                  <Icon name={ICON_NAMES.CHECK} />
```

2023-02-17 02:36 UTC, georgewrmarshall commented on ui/pages/onboarding-flow/metametrics/metametrics.js
> +          <Icon name={ICON_NAMES.CLOSE} color={Color.successDefault} />
```suggestion
          <Icon name={ICON_NAMES.CHECK} color={Color.successDefault} />
```

2023-02-17 02:36 UTC, georgewrmarshall commented on ui/pages/onboarding-flow/metametrics/metametrics.js
> +          <Icon name={ICON_NAMES.CLOSE} color={Color.successDefault} />
```suggestion
          <Icon name={ICON_NAMES.CHECK} color={Color.successDefault} />
```

2023-02-17 02:36 UTC, georgewrmarshall commented on ui/pages/permissions-connect/redirect/permissions-redirect.component.js
> +              name={ICON_NAMES.CLOSE}
```suggestion
              name={ICON_NAMES.CHECK}
```

2023-02-17 02:36 UTC, georgewrmarshall commented on ui/pages/send/send-content/add-recipient/domain-input.component.js
> +              name={ICON_NAMES.CLOSE}
```suggestion
              name={ICON_NAMES.CHECK}
```

2023-02-17 02:36 UTC, georgewrmarshall commented on ui/pages/settings/networks-tab/networks-list-item/networks-list-item.js
> +        <Icon name={ICON_NAMES.CLOSE} color={Color.successDefault} />
```suggestion
        <Icon name={ICON_NAMES.CHECK} color={Color.successDefault} />
```

2023-02-17 02:36 UTC, georgewrmarshall commented on ui/pages/settings/networks-tab/networks-list-item/networks-list-item.js
> +        <Icon name={ICON_NAMES.CLOSE} color={Color.transparent} />
```suggestion
        <Icon name={ICON_NAMES.CHECK} color={Color.transparent} />
```

2023-02-17 15:46 UTC, darkwing commented
*Sigh* I keep jumping between all these Icon PRs, I must've lost my mind.  Thank you @georgewrmarshall !

2023-02-17 18:18 UTC, darkwing commented on ui/components/app/account-menu/account-menu.component.js
>              ) : null}
<img width="326" alt="CheckAccountMenu" src="https://user-images.githubusercontent.com/46655/219747404-b37d68ba-adab-4269-8837-ca7f3941f510.png">

2023-02-20 22:31 UTC, DDDDDanica commented on ui/components/app/account-menu/account-menu.component.js
> +                color={Color.successDefault}
Can you use `IconColor` enum here?

2023-02-20 22:31 UTC, DDDDDanica commented on ui/components/app/dropdowns/network-dropdown.js
> +            <Icon name={ICON_NAMES.CHECK} color={Color.successDefault} />
Can you use `IconColor` enum here?

2023-02-20 22:31 UTC, DDDDDanica commented on ui/components/app/dropdowns/network-dropdown.js
> +          <Icon name={ICON_NAMES.CHECK} color={Color.successDefault} />
Can you use `IconColor` enum here?

2023-02-20 22:31 UTC, DDDDDanica commented on ui/components/app/modals/transaction-confirmed/transaction-confirmed.component.js
> +            color={Color.successDefault}
Can you use `IconColor` enum here?

2023-02-20 22:31 UTC, DDDDDanica commented on ui/pages/onboarding-flow/metametrics/metametrics.js
> +            color={Color.successDefault}
Can you use `IconColor` enum here?

2023-02-20 22:31 UTC, DDDDDanica commented on ui/pages/settings/networks-tab/networks-list-item/networks-list-item.js
> +        <Icon name={ICON_NAMES.CHECK} color={Color.successDefault} />
Can you use `IconColor` enum here?

2023-02-20 22:31 UTC, DDDDDanica commented on ui/pages/settings/networks-tab/networks-list-item/networks-list-item.js
> +        <Icon name={ICON_NAMES.CHECK} color={Color.transparent} />
Can you use `IconColor` enum here?

2023-02-20 22:34 UTC, DDDDDanica commented
Hey @darkwing just wanna let you know typescript enum changes made in [this MR](https://github.com/MetaMask/metamask-extension/pull/17518) will give us better enums to use, for Icons specifically we can use `IconColor` which was exposed before, and now will define a better scope for colors available for Icon~

2023-02-22 05:16 UTC, georgewrmarshall approved these changes
LGTM!

2023-02-22 05:16 UTC, georgewrmarshall commented on ui/components/ui/editable-label/editable-label.js
> +          iconName={ICON_NAMES.CHECK}
This will need an `ariaLabel` prop to pass accessibility

2023-02-22 05:16 UTC, georgewrmarshall requested changes
Sorry, forgot I left a suggestion above ☝️

2023-02-22 12:34 UTC, DDDDDanica commented on ui/components/app/modals/transaction-confirmed/transaction-confirmed.component.js
> +            color={Color.successDefault}
```suggestion
            color={IconColor.successDefault}
```

2023-02-22 12:34 UTC, DDDDDanica commented on ui/pages/send/send-content/add-recipient/domain-input.component.js
> +              color={Color.successDefault}
```suggestion
              color={IconColor.successDefault}
```

2023-02-22 21:44 UTC, DDDDDanica approved these changes, later dismissed

2023-02-23 00:08 UTC, georgewrmarshall submitted a review, later dismissed

2023-02-23 00:39 UTC, georgewrmarshall approved these changes, later dismissed

2023-02-23 00:57 UTC, georgewrmarshall approved these changes

2023-02-23 06:15 UTC, DDDDDanica approved these changes

2023-02-23 13:19 UTC, merged