[MMI] Conditional change title in home if buildType is MMI
MetaMask/metamask-extension pull request #17898
Opened 2023-02-24 14:44 UTC by albertolive

## Explanation

Conditional change title in home if buildType is MMI

https://consensyssoftware.atlassian.net/browse/MMI-2483

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved

## Pre-merge reviewer checklist

- [X] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [X] PR is linked to the appropriate GitHub issue

2023-02-27 05:38 UTC, DigitalsupportTeam commented
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

2023-03-01 16:00 UTC, zone-live requested changes

2023-03-01 16:00 UTC, zone-live commented on app/home.html
> +    {{@if(it.isMMI)}}
we will also need to check if it's not MMI, for the remaining cases. Because if not we will end up with 2 <title> when isMMI is true.

2023-03-02 15:06 UTC, zone-live approved these changes

2023-03-02 16:18 UTC, brad-decker approved these changes

2023-03-02 16:18 UTC, merged