link component
MetaMask/metamask-extension pull request #17897
Opened 2023-02-24 14:19 UTC by witmicko

## Explanation

Introducing a new Link component.  This is built as a wrapper around an anchor tag, but it defaults to safe settings, including target="_blank" and rel="noreferrer noopener", also allowing for overwrites.

Intent here is to eventually replace all bare `<a` tags with `<Link>` 

## Screenshots/Screencaps

### Before

### After

Storybook:
![image](https://user-images.githubusercontent.com/3279642/221200759-fd497703-4df0-4d77-999a-825160bb9949.png)

## Manual Testing Steps

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-02-24 14:25 UTC, brad-decker commented
@georgewrmarshall you'll probably want to see if there is reason to think about the design system as part of this. @witmicko isn't "_blank" going to open in a new window? That shouldn't be the default for *all* links because we do use a tags for internal routing which should happen in the same window. Could we have a variant of Link called ExternalLink that default to _blank and just inherits everything from Link but sets the default to _blank? It would probably be a good way to indicate to the engineers too when reviewing code links that are external versus internal.

2023-02-24 21:34 UTC, georgewrmarshall commented
Thanks for the tag @brad-decker and great work on this @witmicko. We are intending to use [ButtonLink component](https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-buttonlink--default-story) component for links. Could we possibly combine this work with the `ButtonLink` component? @garrettbear

2023-02-27 05:38 UTC, DigitalsupportTeam commented
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

2023-03-07 15:46 UTC, brad-decker commented
@witmicko I believe the direction is to not have the two new link components but rather reflect your work in the ButtonLink component, which I think you have started doing but the old Link and Externallink components still exist outside of the design system which I don't think we want. @garrettbear @georgewrmarshall am I correct in understanding the direction you were heading with this?

2023-03-08 17:11 UTC, georgewrmarshall requested changes
This is looking great! I have a few suggestions. Could we also add this story to both `button-base.stories.js` and `button-link.stories.js`

```
export const ExternalLink = (args) => (
  <ButtonBase {...args}>Anchor element with external link</ButtonBase>
);

ExternalLink.args = {
  href: '/metamask',
  externalLink: true,
};
```

And duplicate the documentation you wrote to ButtonLink readme as well?

2023-03-08 17:11 UTC, georgewrmarshall commented on ui/components/component-library/button-link/README.mdx
> +When an `externalLink` prop is passed it will change the element to an anchor(`a`) tag and add the `target="_blank"` and `rel="noopener noreferrer"` attributes.
From what I can see the logic that exists is that if `externalLink` prop is passed it will add the `target="_blank"` and `rel="noopener noreferrer"` it will not change the element to an anchor tag. Only passing an `href` will change the base element? Maybe we can update this and also add some insight into why?

```suggestion
When an `externalLink` prop is passed it adds the `target="_blank"` and `rel="noopener noreferrer"` attributes. 

`rel="noreferrer noopener"` is used in links to prevent security vulnerabilities that can be exploited by malicious websites. It disables the window.opener property and prevents the new page from sending the referrer information, providing an additional layer of security.
```

2023-03-08 17:11 UTC, georgewrmarshall commented on ui/components/ui/external-link/external-link.js
> +export default ExternalLink;
Do we still need this component?

2023-03-09 20:29 UTC, georgewrmarshall reviewed
Little suggestion!

2023-03-09 20:29 UTC, georgewrmarshall commented on ui/components/component-library/button-base/README.mdx
> +</Canvas>
Apologies I think I made a mistake with the component id that renders the story in the Docs tab

```suggestion
  <Story id="components-componentlibrary-buttonbase--external-link" />
```

Will fix this

<img width="1440" alt="Screenshot 2023-03-09 at 12 23 21 PM" src="https://user-images.githubusercontent.com/8112138/224147336-39df00f9-6367-4123-a2f2-bcd637b9e2e2.png">

2023-03-09 20:29 UTC, georgewrmarshall commented on ui/components/component-library/button-base/README.mdx
> +</ButtonLink>;
Update code example

```suggestion
import { ButtonBase } from '../../component-library';

<ButtonBase href="https://metamask.io" externalLink>
  Anchor element with external link
</ButtonBase>;
```

2023-03-09 20:29 UTC, georgewrmarshall commented on ui/components/component-library/button-link/README.mdx
> +  <Story id="components-componentlibrary-buttonlink--href" />
Once ExternalLink story has been added you can update this to
```suggestion
  <Story id="components-componentlibrary-buttonlink--external-link" />
```

2023-03-09 20:29 UTC, georgewrmarshall commented on ui/components/component-library/button-link/README.mdx
> +</ButtonLink>;
Just check this code example reflects the story but I think it does so not updates here

2023-03-09 20:29 UTC, georgewrmarshall commented on ui/components/component-library/button-link/button-link.stories.js
>        options: Object.values(ICON_NAMES),
I know we are duplicating some code here but I think it's worth adding the ExternalLink story to ButtonLink as well

```
export const ExternalLink = (args) => (
  <ButtonLink {...args}>Anchor element with external link</ButtonLink>
);

ExternalLink.args = {
  href: 'https://metamask.io',
  externalLink: true,
};
```

2023-03-10 15:33 UTC, georgewrmarshall reviewed
Lgtm just wondering if that storybook package is still needed?

2023-03-10 15:33 UTC, georgewrmarshall commented on yarn.lock
>    languageName: node
Is this package still needed?

2023-03-10 16:15 UTC, georgewrmarshall approved these changes, later dismissed
Great work! One nit but not blocking 
Would be great if the code example matched what was happening in the story

<img width="564" alt="Screenshot 2023-03-10 at 8 14 02 AM" src="https://user-images.githubusercontent.com/8112138/224367085-d6bb8bd9-dc9b-417a-aeaa-ce992faf14ad.png">

2023-03-10 17:44 UTC, georgewrmarshall commented on ui/components/component-library/button-link/button-link.stories.js
>        options: Object.values(ICON_NAMES),
yup!

2023-03-10 17:45 UTC, georgewrmarshall approved these changes
Excellente! 💯 🚀

2023-03-10 17:46 UTC, garrettbear approved these changes

2023-03-10 17:47 UTC, merged