[MMI] Applied code fencing in trabsactions and pending tx tracker controllers
MetaMask/metamask-extension pull request #17909
Opened 2023-02-27 11:02 UTC by albertolive

## Explanation

Applied code fencing in trabsactions and pending tx tracker controllers

https://consensyssoftware.atlassian.net/browse/MMI-2495

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved

## Pre-merge reviewer checklist

- [X] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [X] PR is linked to the appropriate GitHub issue

2023-03-01 15:55 UTC, zone-live requested changes

2023-03-01 15:55 UTC, zone-live commented on app/scripts/controllers/transactions/pending-tx-tracker.js
> +    // Don't emit noTxHashErr for custodian transactions https://consensys.slack.com/archives/C02612BF2LW/p1664360358834839?thread_ts=1663693387.576109&cid=C02612BF2LW
@albertolive delete this url from the comment, it creates too much noise

2023-03-02 15:39 UTC, zone-live submitted a review, later dismissed

2023-03-08 15:47 UTC, shane-t submitted a review, later dismissed

2023-04-26 08:52 UTC, albertolive commented
@darkwing could you approve it? I already added more tests

2023-04-26 09:00 UTC, albertolive commented on app/scripts/controllers/transactions/index.js
> +    ///: BEGIN:ONLY_INCLUDE_IN(mmi)
MMI does not broadcast transactions, as that is the responsibility of the custodian

2023-04-26 09:48 UTC, zone-live submitted a review, later dismissed

2023-05-03 15:14 UTC, albertolive commented
@zone-live @brad-decker could you review this one?

2023-05-05 13:48 UTC, pedronfigueiredo approved these changes

2023-05-05 13:56 UTC, zone-live approved these changes

2023-05-05 13:58 UTC, merged