UX: Icon: Update README with new variable names
MetaMask/metamask-extension pull request #17920
Opened 2023-02-28 00:25 UTC by darkwing

## Explanation

Our variable names have changed so the docs must be updated.

2023-02-28 07:25 UTC, NidhiKJha requested changes
Looks good. Just a small nit

2023-02-28 07:25 UTC, NidhiKJha commented on ui/components/component-library/text-field/README.mdx
> +        color={Color.successDefault}
```suggestion
        color={IconColor.successDefault}
```

2023-03-06 10:17 UTC, NidhiKJha approved these changes

2023-03-06 19:30 UTC, garrettbear approved these changes

2023-03-06 19:30 UTC, merged