Fix #17948 - Allow editing of NFT sends
MetaMask/metamask-extension pull request #17970
Opened 2023-03-02 20:57 UTC by darkwing

## Explanation

* Fixes #17948

The `Edit` link isn't displaying because `confirm-transaction-base.component.js` isn't being provided an `onEdit` prop.  The problem ultimately is happening because `ui/pages/confirm-transaction/confirm-token-transaction-switch.js` renders a `ConfirmTokenTransactionBase` by route `CONFIRM_TRANSFER_FROM_PATH` without the onEdit.

## Screenshots/Screencaps

https://user-images.githubusercontent.com/46655/222549071-8737c676-8a72-420c-86d8-69c3ed567390.mp4

## Manual Testing Steps

1.  Enable the NFT feature with `NFTS_V1 yarn start`
2. Start the NFT send flow
3. On the confirmation screen, click "Edit"
4. See the same NFT still selected
5. Choose a different NFT
6. On the confirmation screen, click "edit"

The proper NFT should display on the edit and confirmation screens.

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-03-06 15:09 UTC, albertolive submitted a review, later dismissed

2023-03-09 17:35 UTC, danjm requested changes
I don't think we want to allow editing of these transactions if they are coming from a dapp. I'll run this code and test it to see if I can make any suggestions in that regard

2023-03-09 19:41 UTC, danjm commented
> I don't think we want to allow editing of these transactions if they are coming from a dapp. I'll run this code and test it to see if I can make any suggestions in that regard

Actually, after some testing, I think this is safe

2023-03-09 19:41 UTC, danjm approved these changes

2023-03-09 20:59 UTC, vthomas13 approved these changes

2023-03-09 21:02 UTC, merged