Show new header on SIWE screen
MetaMask/metamask-extension pull request #17994
Opened 2023-03-06 09:51 UTC by filipsekulic

## Explanation
* Fixes #17812

## Screenshots/Screencaps

https://user-images.githubusercontent.com/92310504/223075665-dce85014-f143-4979-9ef9-e666a4c14a61.mov

## Manual Testing Steps

1. Go to https://metamask.github.io/test-dapp/
2. Under Sign In With Ethereum, click on Sign In With Ethereum

2023-03-07 12:22 UTC, dzfjz commented
Verified by QA

2023-03-07 14:43 UTC, darkwing requested changes

2023-03-07 14:43 UTC, darkwing commented on ui/components/app/signature-request-siwe/signature-request-siwe.js
> +  const getNetworkName = () => {
I see this function exists elsewhere in the codebase a few times.  Would it be possible to move it to a helper file so we aren't repeating as much?  You'd pass the helper function `provider` and `t`

2023-04-17 13:48 UTC, digiwand commented on ui/components/app/dropdowns/network-dropdown.js
> -
nice cleanup find

2023-04-17 13:48 UTC, digiwand commented on ui/components/app/signature-request-siwe/signature-request-siwe.js
> +  const provider = useSelector(getProvider);
[out-of-scope] interesting...  wonder how much of this logic could be moved into `NetworkAccountBalanceHeader` itself

2023-04-17 13:48 UTC, digiwand commented on ui/components/app/signature-request-siwe/signature-request-siwe.js
> +      />
what do you think about moving the logic into the Header component from './signature-request-siwe-header' to maintain separations of concerns?

2023-06-07 15:36 UTC, closed without merging