Part of 17670: Replace Typography with Text confirm-approve-content.component.js and home.component.js
MetaMask/metamask-extension pull request #18049
Opened 2023-03-08 12:24 UTC by spiritanand

## Explanation
Replace Typography with Text `confirm-approve-content.component.js` and `home.component.js`

Part of: #17670
## Screenshots/Screencaps
### Before
<img width="1220" alt="Before approve-content" src="https://user-images.githubusercontent.com/53999998/223711902-a5d61f72-739b-4810-af80-7400530d2657.png">

### After
<img width="1224" alt="After approve-content" src="https://user-images.githubusercontent.com/53999998/223711923-b8bc50ec-9f04-4f37-a927-d1491a874488.png">

## Manual Testing Steps

- Go to the latest build of storybook on this PR
- Follow path `Pages/ConfirmApprove/ConfirmApproveContent` in the side panel
- Check `ConfirmApproveContent` story against develop storybook

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-03-08 20:01 UTC, georgewrmarshall requested changes
Good start! Left some suggestions. Change all as="h7" to as="h6"

2023-03-08 20:01 UTC, georgewrmarshall commented on ui/pages/home/home.component.js
> +                          as="h7"
There is no html element `h7` check mapping. Anything that is over `h6` should be `h6`
```suggestion
                          as="h6"
```

2023-03-09 05:25 UTC, spiritanand commented on ui/pages/home/home.component.js
> +import { SECOND } from '../../../shared/constants/time';
Sure.

2023-03-09 05:47 UTC, spiritanand commented on ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
>          <div
what is the review for this line @georgewrmarshall

2023-03-09 20:21 UTC, georgewrmarshall commented on ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
>          <div
I add screenshots of the before and after changes as a comment on the file so it's easy to see what file relates to which screenshot. Helps with review if you could do the same for the rest of the files that would be greatly appreciated!

2023-03-10 04:22 UTC, spiritanand commented on ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
>          <div
ok sure. i will keep that in mind.

2023-03-10 04:27 UTC, spiritanand commented
@georgewrmarshall are there any other changes that I ought to do? I am currently failing in one test, i.e. the e2e chrome build test.

2023-03-10 16:27 UTC, georgewrmarshall submitted a review, later dismissed
LGTM 💯 Thanks for your contribution @spiritanand!
I believe the code coverage is not effected with these changes so happy to merge without any updates to the test coverage.

2023-03-10 18:11 UTC, georgewrmarshall commented on ui/pages/confirm-approve/confirm-approve-content/confirm-approve-content.component.js
> +              marginLeft={1}
Hey @spiritanand, I just added a little alignment fix here so we can get this through! cc @garrettbear 

<img width="603" alt="Screenshot 2023-03-10 at 10 10 24 AM" src="https://user-images.githubusercontent.com/8112138/224391904-645bfae3-a4c7-4428-bbd6-02bbda9dfca7.png">
<img width="617" alt="Screenshot 2023-03-10 at 10 09 51 AM" src="https://user-images.githubusercontent.com/8112138/224391927-8a74fb5e-2e86-43ec-9c4b-c1062269c34b.png">

2023-03-10 18:11 UTC, georgewrmarshall approved these changes

2023-03-10 18:16 UTC, garrettbear approved these changes

2023-03-13 19:27 UTC, merged