MMI adds the Jwt dropdown component
MetaMask/metamask-extension pull request #18117
Opened 2023-03-13 09:39 UTC by zone-live

## Explanation

This PR adds the MMI `JwtDropdown` component under the `ui/components/institutional/` folder
Ref ticket: https://consensyssoftware.atlassian.net/browse/MMI-2651

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved

## Pre-merge reviewer checklist

- [X] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [X] PR is linked to the appropriate GitHub issue

2023-03-13 10:00 UTC, albertolive approved these changes

2023-03-13 10:50 UTC, albertolive submitted a review, later dismissed

2023-03-13 15:42 UTC, darkwing commented on ui/components/institutional/jwt-dropdown/jwt-dropdown.scss
> +    color: var(--scorpion);
We no longer use this color in the extension; could it be `var(--color-error-default)`?

2023-03-13 15:43 UTC, darkwing commented on ui/components/institutional/jwt-dropdown/jwt-dropdown.js
> +      <span className="custody-search-jwt__select-title">{t('selectJWT')}</span>
For this we should use the new `<Text>` design system component with `padding={3}` and `color={Color.___}` values.

2023-03-13 15:44 UTC, darkwing commented on ui/components/institutional/jwt-dropdown/jwt-dropdown.js
> +    <div>
Instead of `<div>`, we can use `<Box>`

2023-03-13 15:47 UTC, darkwing requested changes
Adding a storybook component will help to ensure design integrity and help with review.

2023-03-15 19:32 UTC, darkwing approved these changes

2023-03-16 05:33 UTC, NidhiKJha approved these changes

2023-03-16 11:03 UTC, merged