Fix layer 2 fee alignment
MetaMask/metamask-extension pull request #18164
Opened 2023-03-15 08:46 UTC by amerkadicE

## Explanation

This PR fixes alignment for layer 2 gas fee value.
It also sets layer 2 gas fee decimals to be 12 instead of 6.

Fixes #17426 
## Screenshots/Screencaps

### Before
![image](https://user-images.githubusercontent.com/97883527/225254875-b70bbaa6-acab-40bc-9201-ccc120dfaa33.png)

### After
<img width="358" alt="image" src="https://user-images.githubusercontent.com/97883527/225255005-bfe5e68c-b6f5-4c35-ab29-89de27233693.png">

## Manual Testing Steps

1. Change to Optimism network
2. Go to Etherscan to interact with an ERC20 token https://optimistic.etherscan.io/token/0x94b008aa00579c1307b0ef2c499ad98a8ce58e58#writeContract
3. Click Connect MM
4. Accept MM
5. Click Approve and Add spender and amount
6. Click Write
7. Add any amount on MM
8. Click Next
9. See alignment for fees

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-03-16 11:01 UTC, dzfjz commented
Verified by QA

2023-03-22 14:37 UTC, brad-decker requested changes

2023-03-22 14:37 UTC, brad-decker commented on test/e2e/tests/custom-token-add-approve.spec.js
> -          text: '0.0006 ETH',
Doesn't appear to be a test related to the change

2023-03-28 07:52 UTC, amerkadicE commented on ui/components/app/approve-content-card/approve-content-card.js
> +                      <Box>{`${ethTransactionTotal} ${nativeCurrency}`}</Box>
It needed to wrap the second paragraph in a span.

2023-03-28 07:53 UTC, amerkadicE commented on ui/helpers/utils/confirm-tx.util.ts
> +      return numericAcc.add(new Numeric(ethAmount, 10)).round(12);
Fixed, now we pass an optional parameter to set number of decimals

2023-03-28 07:54 UTC, amerkadicE commented on test/e2e/tests/custom-token-add-approve.spec.js
> -          text: '0.0006 ETH',
We decided to change the number of decimals to 12 on the whole token allowance screen.

cc @danjm

2023-08-03 10:04 UTC, closed without merging