[FLASK] Update UI related to MetaMask Snaps Platform trademark
MetaMask/metamask-extension pull request #18172
Opened 2023-03-15 16:23 UTC by david0xd

Fixes: https://github.com/MetaMask/MetaMask-planning/issues/358

## Explanation

## Screenshots/Screencaps

### Before

### After

## Manual Testing Steps

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-03-16 16:05 UTC, david0xd commented on ui/pages/settings/flask/snaps-list-tab/snap-list-tab.js
> +                  {t('noSnapsLearnMoreLinkText')}
Yes, updated.

2023-03-16 18:26 UTC, rekmarks requested changes
We should use "MetaMask Snaps" to refer to the platform. We should try to avoid using those words to refer to snaps collectively.

2023-03-21 00:23 UTC, rekmarks commented on app/_locales/en/messages.json
> +  },
```suggestion
  "exploreWithSnaps": {
    "message": "Explore web3 with MetaMask Snaps"
  },
```

2023-03-21 00:24 UTC, rekmarks commented on ui/pages/settings/flask/snaps-list-tab/snap-list-tab.js
> +              title={t('learnAboutSnaps')}
```suggestion
              title={t('exploreWithSnaps')}
```

2023-03-21 03:09 UTC, rekmarks approved these changes, later dismissed
LGTM!

2023-03-21 12:38 UTC, FrederikBolding approved these changes

2023-03-21 15:48 UTC, rekmarks approved these changes

2023-03-21 15:52 UTC, merged