Mascara toggle
MetaMask/metamask-extension pull request #1825
Opened 2017-07-25 23:07 UTC by frankiebee

this will allow developers to switch between the mascara provider and the extension provider 
so that you dont have to disable the extension
simply type `web3.currentProvider.mascara = true` and the providers will switch and use the mascara provider

2017-07-26 00:09 UTC, kumavis requested changes
better to use `mascara` or `metamask` global var for detecting instead of looking for the script

2017-07-26 00:09 UTC, kumavis commented on app/scripts/lib/mascara-detection-usage.js
> +    if (src === 'MASCARA_PROXY_ORIGIN') {
lets make this a CONSTANT_VARIABLE and then set it at the top or somewhere

we could also prolly do this via process.env.ENV_VAR

2017-07-26 00:09 UTC, kumavis commented on app/scripts/lib/mascara-detection-usage.js
> +    if (src === 'MASCARA_PROXY_ORIGIN') {
or add attribute to the src tag like `metamascara=true`

2017-07-26 00:09 UTC, kumavis commented on app/scripts/lib/mascara-detection-usage.js
> +    if (src === 'MASCARA_PROXY_ORIGIN') {
or maybe better to check `window.mascara` or something

2017-07-26 00:09 UTC, kumavis commented on gulpfile.js
> +      .pipe(replace('\'MASCARA_PROXY_ORIGIN\'', MASCARA_PROXY_ORIGIN))
should be able to inject via envify or something (this feels a bit hacky, tho i know theres precedent the line above)

2017-08-01 20:05 UTC, kumavis requested changes

2017-08-01 20:05 UTC, kumavis commented on app/scripts/lib/mascara-detection-usage.js
> +      if (!global.web3.currentProvider.mascara) return
please rename to `isMascaraActive`

2017-08-01 20:05 UTC, kumavis commented on app/scripts/inpage.js
> +  if (!inpageProvider.mascara) web3.eth.defaultAccount = state.selectedAddress
please rename to `isMascaraActive`

2017-08-01 20:05 UTC, kumavis commented on mascara/src/mascara.js
> +provider.isMascara = true
remove

2017-08-01 20:05 UTC, kumavis commented on gulpfile.js
> +    json["content_scripts"][1]["exclude_matches"] = [`${MASCARA_ORIGIN}*`]
we should skip injection on prod mascara even when we're in dev mode

2017-08-01 22:26 UTC, frankiebee commented on gulpfile.js
> +    json["content_scripts"][1]["exclude_matches"] = [`${MASCARA_ORIGIN}*`]
content_scripts is an array with an object already in it. The object already in it is the one we want to write too

2017-08-04 22:15 UTC, kumavis approved these changes

2017-08-04 22:16 UTC, kumavis commented on app/scripts/lib/mascara-proxy-provider.js
> +  if (global.mascaraProvider) {
we should just abort if `global.mascaraProvide` is falsy, yes?

2017-08-04 22:22 UTC, frankiebee commented on app/scripts/lib/mascara-proxy-provider.js
> +  if (global.mascaraProvider) {
sure i will change it but... food for thought: what if the race condition shows up it wont be obvious till you send a tx that mascara isnt global. Left this way it throws an error if you expected it to be their and it's not.

2017-08-04 23:02 UTC, tmashuang commented
- [ ] clicking multiple times opens multiple transactions pop-ups
- [ ] Metamask pop up shows account screen after rejecting the transaction.
       STR: click Async Tx -> reject -> click anywhere on ZeroClient

2017-08-22 22:23 UTC, closed without merging

2017-08-22 22:29 UTC, Zanibas commented
Why are we closing this?