Sign in with Ethereum: domain and origin should compare without port
MetaMask/metamask-extension pull request #18296
Opened 2023-03-23 02:45 UTC by yonigoldberg

## Explanation
- Fixes: https://github.com/MetaMask/metamask-extension/issues/18188

The parsed SIWE domain doesn't have a port (e.g loclhost) therefore when it is compared with the origin, the host from the origin should be without a port as well. That is achieved by using `hostname` instead of `host`.

## Screenshots/Screencaps
### Before

<img width="355" alt="image" src="https://user-images.githubusercontent.com/239781/227086590-440ddfab-b35c-4a0b-aeb7-e5dadc6df92e.png">
### After

<img width="346" alt="image" src="https://user-images.githubusercontent.com/239781/227086914-c9dc7e21-cad7-46f2-8899-878db9ffcb12.png">
## Manual Testing Steps
- Run any local server and try to login with SIWE

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-03-23 02:49 UTC, yonigoldberg commented
I have read the CLA Document and I hereby sign the CLA

2023-03-23 05:35 UTC, skgbafa commented
Amazing, came to the repo to make this exact change. The hostname will always map to the domain and drop the port, preventing the domain binding bug from happening on localhost. This change looks great to me.

2023-03-26 02:45 UTC, digiwand submitted a review, later dismissed
Lgtm! Thanks for adding the fix and test for this @yonigoldberg!

I think it'd be a good idea to add another test to check the case where [domain contains the port number](https://eips.ethereum.org/EIPS/eip-4361) as well. I don't think this is a blocker for this PR, though I think we should add it here or in a follow-up PR

2023-03-27 18:59 UTC, digiwand approved these changes

2023-03-28 14:08 UTC, naugtur commented on ui/components/app/signature-request-siwe/signature-request-siwe.js
> +        parsedMessage.domain === hostname || parsedMessage.domain === host;
This loosening of origin matching doesn't seem to be limited to localhost in any way. As a result, any two origins (in the browser's sameorigin policy sense) that share the domain but not port&protocol will be considered a match. 

Are we not worried about changing that? 
Shared hosting services exist, where two different apps/customers get the same IP or domain but different port. I know it's a weird example, but it's a practical example of origin including a port.

If we consider it an extension of sameorigin policy, we should not fix localhost issues this way. 

(also, sorry this is coming in so late, but I was only made aware of this PR a few minutes ago and I don't even have all the context - I might be 100% wrong)

2023-03-28 14:32 UTC, digiwand requested changes
re: @naugtur [comment above](https://github.com/MetaMask/metamask-extension/pull/18296/files#r1150684088)

I think that's a good idea to limit the scope to localhost. Blocking this PR now to apply the change and continue the discussion above.

2023-03-28 14:50 UTC, naugtur commented on ui/components/app/signature-request-siwe/signature-request-siwe.js
> +        parsedMessage.domain === hostname || parsedMessage.domain === host;
Would this work too? There's no security concerns I see if done that way:  
```suggestion
        (hostname === 'localhost' && parsedMessage.domain === hostname) || parsedMessage.domain === host;
```

2023-03-29 13:28 UTC, digiwand approved these changes, later dismissed

2023-03-30 12:56 UTC, jpuri submitted a review, later dismissed

2023-03-30 12:56 UTC, jpuri commented
Hey @yonigoldberg : can you plz fix lint issue.

2023-03-31 16:58 UTC, digiwand commented on ui/components/app/signature-request-siwe/signature-request-siwe.js
> +        (hostname === 'localhost' && parsedMessage.domain === hostname) || parsedMessage.domain === host;
```suggestion
        (hostname === 'localhost' && parsedMessage.domain === hostname) || 
        parsedMessage.domain === host;
```
fixes lint

2023-04-01 06:13 UTC, digiwand reviewed
having an interesting conversation with @legobeat. 
 
@yonigoldberg, we will need to hold off on merging this right now while we figure this out. Thank you for your patience with this. I am curious to know if you have found a workaround the match the port numbers in the meantime. Hoping you have 

---

For clarification, I'm realizing the issue ticket that is currently related to this PR is only concerned with the http/https protocol rather than the port. maybe we can unrelate the tickets or combine the issues

**Other related tickets:**
- Support domain mismatch on SIWE on development mode #18191
- [Bug]: Weird behavior for SIWE requests on localhost #18188
- addressing subdomains (e.g. `www`) - (#18332)

2023-04-06 23:07 UTC, yonigoldberg commented
Per the conversation in  https://github.com/MetaMask/metamask-extension/issues/18188 I think we can close this PR.

2023-04-06 23:07 UTC, closed without merging

2023-04-07 04:07 UTC, digiwand commented
> Thank you for opening this PR, your input, and keeping the conversation moving @yonigoldberg

+1

2023-04-07 04:09 UTC, digiwand commented
+1

2023-04-07 04:09 UTC, digiwand commented
^ +1