fix alarms.getAll() console errors
MetaMask/metamask-extension pull request #18306
Opened 2023-03-23 18:40 UTC by pedronfigueiredo

## Explanation

Fixes this error in the console for mv3 builds

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getAll')
  at new MetaMetricsController (metametrics.js:179:21)
  at new MetamaskController (metamask-controller.js:396:34)
  at setupController (background.js:399:16)
  at initialize (background.js:251:5)
```

2023-03-24 21:23 UTC, danjm approved these changes

2023-03-24 22:43 UTC, adonesky1 approved these changes, later dismissed

2023-03-24 22:46 UTC, danjm requested changes
I need to investigate whether the root cause of the bug here is a lavamoat / snow issue

2023-03-27 13:27 UTC, pedronfigueiredo commented
I believe a regression might have been introduced here https://github.com/MetaMask/metamask-extension/pull/18218/files#diff-722208d23dde0a9af3f90b062acbcc12d9341482d73c8b55f52a57cf2a8e0e70, so I've selectively reverted those changes

2023-03-30 09:50 UTC, pedronfigueiredo commented
Closing since this has now been addressed here https://github.com/MetaMask/metamask-extension/pull/18336

2023-03-30 09:50 UTC, closed without merging