convert text component to TS
MetaMask/metamask-extension pull request #18329
Opened 2023-03-24 23:41 UTC by garrettbear

## Explanation
* Fixes: #18325 

Update `Text` component to TS

## Screenshots/Screencaps

### Before

### After

## Manual Testing Steps
`yarn jest ui/components/component-library`

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved
  - [X] How reviewers can test my changes
- [X] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [X] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [X] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-03-28 20:48 UTC, georgewrmarshall requested changes
Good start. Left some suggestions

2023-03-28 20:48 UTC, georgewrmarshall commented on ui/components/component-library/text/text.stories.tsx
> +    // },
Should these be uncommented or removed?

2023-03-28 20:48 UTC, georgewrmarshall commented on ui/components/component-library/text/text.stories.tsx
> +    // },
Should this be uncommented or removed?

2023-03-28 20:48 UTC, georgewrmarshall commented on ui/components/component-library/text/text.tsx
> +      return 'span';
Should these return the ValidTag enum?

2023-03-28 20:48 UTC, georgewrmarshall commented on ui/components/component-library/text/text.tsx
> +  ref: Ref<HTMLDivElement>,
Should this be any HTML element? `h1-h6` `p`, `li` etc
```suggestion
  ref: Ref<HTMLElement>,
```

2023-03-28 20:48 UTC, georgewrmarshall commented on ui/components/component-library/text/text.types.ts
> +  fontWeight?: typeof FONT_WEIGHT;
Should we use keyof here? We don't want the whole object just the key value.
```suggestion
  fontWeight?: keyof typeof FONT_WEIGHT;
```

2023-03-28 20:48 UTC, georgewrmarshall commented on ui/components/component-library/text/text.types.ts
> +import { BoxProps } from '../../ui/box';
I think you want
```suggestion
import type { BoxProps } from '../../ui/box/box.d';
```

2023-03-31 20:17 UTC, Jah2233 reviewed
Слава Україні!

2023-03-31 20:18 UTC, Jah2233 commented
Дякую

2023-03-31 23:17 UTC, georgewrmarshall reviewed
Do you need to create the deprecated folder if you aren't updating the types to enums?

2023-04-03 15:48 UTC, georgewrmarshall reviewed
Left one suggestion. I pulled the branch and it seems to work?

2023-04-03 17:32 UTC, georgewrmarshall approved these changes

2023-04-03 17:37 UTC, NidhiKJha approved these changes

2023-04-03 17:42 UTC, merged