Part of 17670: Replace Typography with Text in detected-token-address.js
MetaMask/metamask-extension pull request #18435
Opened 2023-04-03 22:47 UTC by Ananyamadhu08

## Explanation

Updating Typography to Text `detected-token-address.js`

Part of: #17670

## Screenshots/Screencaps

### Before

![Screenshot 2023-04-04 at 4 10 25 AM](https://user-images.githubusercontent.com/78725970/229643095-7401d84b-28a6-471b-8db0-e65e06a31205.png)

### After

![Screenshot 2023-04-04 at 4 09 02 AM](https://user-images.githubusercontent.com/78725970/229643116-eb7147af-20a7-434a-a88a-232bf2da7e18.png)

## Manual Testing Steps

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [x] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [x] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-04-03 22:50 UTC, Ananyamadhu08 commented
I have read the CLA Document and I hereby sign the CLA

2023-04-04 15:34 UTC, georgewrmarshall requested changes
Thanks for your contribution! Excellent PR description and screenshots 💯 There was a mistake in the issue that incorrectly mapped the `Text` component to an `h7` tag. Heading tags in html go from `h1` - `h6`. I've update the issue and made a couple of suggestions for the tags. Apologies! If you can make those 2 changes I can approve 👍

2023-04-04 15:34 UTC, georgewrmarshall commented on ui/components/app/detected-token/detected-token-address/detected-token-address.js
> +      <Text variant={TextVariant.bodySm} as="h7" color={TextColor.textDefault}>
Update to `h6` tag
```suggestion
      <Text variant={TextVariant.bodySm} as="h6" color={TextColor.textDefault}>
```

2023-04-04 15:34 UTC, georgewrmarshall commented on ui/components/app/detected-token/detected-token-address/detected-token-address.js
> +        as="h7"
Update to `h6` tag
```suggestion
        as="h6"
```

2023-04-07 16:59 UTC, Ananyamadhu08 commented
@georgewrmarshall I have made the requested changes, please review.

2023-04-11 11:25 UTC, georgewrmarshall approved these changes
LGTM 💯 Thanks for your contribution!
- checked storybook on local

2023-04-24 09:19 UTC, NidhiKJha approved these changes
LGTM

2023-04-24 09:19 UTC, merged