Transaction controller refractor part 1: promises for everyone and more tests!
MetaMask/metamask-extension pull request #1848
Opened 2017-08-02 15:48 UTC by frankiebee

fixes #957

2017-08-02 15:54 UTC, frankiebee commented
@tmashuang can you QA this

2017-08-02 16:34 UTC, frankiebee commented
`#getChainID` should parse with base 16

2017-08-02 16:40 UTC, kumavis requested changes
- [ ] consider using `async` keyword in tests - make sure mocha/whatever supports returning promises

2017-08-02 16:40 UTC, kumavis commented on app/scripts/controllers/transactions.js
> +  get unapprovedTxCount () {
maybe just use a function
i think its clearer that its doing some calc and could have side effects when its a fn
by making a getter we're sort of pretending its a property

2017-08-02 16:40 UTC, kumavis commented on app/scripts/controllers/transactions.js
>    // PRIVATE METHODS
make it bigger like

```
<newline>
//
// PRIVATE METHODS
//
<newline>
```

2017-08-02 16:40 UTC, kumavis commented on app/scripts/metamask-controller.js
> +    this.sendUpdate()
remove `this.sendUpdate()`
we get this anyways

2017-08-02 16:40 UTC, kumavis commented on app/scripts/metamask-controller.js
> +    this.opts.showUnapprovedTx(txMeta)
instead of calling it here, we should listen for the `metamaskController.txController.on('newTx')` or w/e the event is

2017-08-02 16:40 UTC, kumavis commented on app/scripts/metamask-controller.js
> +  async newUnapprovedTransaction (txParams) {
move this fn into tx controller

2017-08-02 16:40 UTC, kumavis commented on test/unit/tx-controller-test.js
> +        done()
missing `catch`

2017-08-02 16:40 UTC, kumavis commented on test/unit/tx-utils-test.js
> +const sinon = require('sinon')
seems like we're not using this?

2017-08-02 16:40 UTC, kumavis commented on app/scripts/lib/tx-utils.js
> +  validateTxParams (txParams) {
prefer `async` keyword instead of manually returning a promise
`reject(err)` -> `throw err`
`resolve(val)` -> `return val`

2017-08-02 16:40 UTC, kumavis commented on app/scripts/controllers/transactions.js
> +      this.setTxStatusFailed(noTxHash)
missing txId `this.setTxStatusFailed(txId, noTxHash)`

2017-08-02 16:40 UTC, kumavis commented on app/scripts/controllers/transactions.js
> +      const noTxHash = new Error('We had an error while submitting this transaction, please try again.')
rename to `noTxHashErr`

2017-08-02 16:40 UTC, kumavis commented on app/scripts/controllers/transactions.js
> +    return Promise.resolve()
prefer async instead of manually returning promise

2017-08-02 16:40 UTC, kumavis commented on app/scripts/controllers/transactions.js
> +    const getChainId = parseInt(networkState)
parse explicitly as hex `parseInt(networkState, 16)`

2017-08-02 16:40 UTC, kumavis commented on app/scripts/controllers/transactions.js
>    async signTransaction (txId) {
dont mix `await` and `then`

2017-08-02 16:40 UTC, kumavis commented on app/scripts/controllers/transactions.js
>      })
dont mix `await` and `then`

2017-08-02 16:40 UTC, kumavis commented on app/scripts/controllers/transactions.js
> +      let index = fullTxList.findIndex((metaTx) => ((metaTx.status === 'confirmed' || metaTx.status === 'rejected') && network === txMeta.metamaskNetworkId))
prefer const

2017-08-02 16:40 UTC, kumavis commented on app/scripts/lib/tx-utils.js
> +    return this.query.sendRawTransaction(rawTx)
this is correct but lets use the `async` keyword to make it clear we're returning a promise
```js
async publishTransaction (rawTx) {
  return await this.query.sendRawTransaction(rawTx)
}
```

2017-08-02 16:40 UTC, kumavis commented on test/unit/tx-controller-test.js
> +      const addTxDefaultsStub = sinon.stub(txController, 'addTxDefaults').callsFake(() => Promise.resolve)
maybe you meant `Promise.resolve()`?

2017-08-02 18:47 UTC, frankiebee commented on app/scripts/controllers/transactions.js
> +    const getChainId = parseInt(networkState)
https://github.com/ethereum/wiki/wiki/JSON-RPC#net_version
return value is not a hex

2017-08-03 02:55 UTC, kumavis approved these changes

2017-08-03 02:57 UTC, merged