Feat/18308/ds popover header component
MetaMask/metamask-extension pull request #18489
Opened 2023-04-06 17:54 UTC by garrettbear

## Explanation

Using `HeaderBase` build a `PopoverHeader` component that defaults with a back button in startAccessory position and close button in the endAccessory position. 

*Fixes #18308 

## Screenshots/Screencaps

### Before

### After

<img width="1116" alt="Screenshot 2023-04-12 at 3 55 48 PM" src="https://user-images.githubusercontent.com/26469696/231603907-7a52e4aa-8047-4cef-8518-6c93f04959df.png">

## Manual Testing Steps
`yarn jest ui/components/component-library`

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved
  - [X] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [X] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [X] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-04-18 09:08 UTC, georgewrmarshall reviewed
Looking good! Left a small suggestion

2023-04-18 09:08 UTC, georgewrmarshall commented on ui/components/component-library/popover-header/popover-header.stories.tsx
> +      onClose={() => console.log('close')}
Can these be actions?

2023-04-18 09:49 UTC, georgewrmarshall reviewed
These should be resolved. They will fail the build if used in a .tsx file. The only reason it's not failing is because storybook files are currently being ignored but we will want to change that eventually

<img width="628" alt="Screenshot 2023-04-18 at 7 18 08 PM" src="https://user-images.githubusercontent.com/8112138/232739949-40c92280-cf0d-4143-9e9c-34882609c6f4.png">
<img width="659" alt="Screenshot 2023-04-18 at 7 18 15 PM" src="https://user-images.githubusercontent.com/8112138/232739973-9a69d398-165f-4352-bc59-cc55b89d37db.png">

2023-04-18 09:56 UTC, georgewrmarshall commented
> @georgewrmarshall do you remember what fix you had to do when running into the props not loading on README? <img alt="Screenshot 2023-04-17 at 3 13 03 PM" width="1074" src="https://user-images.githubusercontent.com/26469696/232622119-effa3a0d-d60e-43b1-b8f4-eabb51e1241c.png">

Hmm I do not. Will check it out tomorrow

2023-04-18 23:30 UTC, georgewrmarshall approved these changes
LGTM! 🚀

2023-04-19 04:56 UTC, georgewrmarshall requested changes, later dismissed
Had another review looks like we should still keep argTypes to prevent the stories from breaking. Controls don't really add any value if they don't work as expected. We may have to do some house keeping on the other TS components


https://user-images.githubusercontent.com/8112138/232970644-0723026f-a531-4d03-8cfe-ee1048810bcd.mov

2023-04-19 04:56 UTC, georgewrmarshall commented on ui/components/component-library/popover-header/popover-header.test.tsx
> +describe('Popover', () => {
nit: Change to PopoverHeader
```suggestion
describe('PopoverHeader', () => {
```

2023-04-19 04:56 UTC, georgewrmarshall commented on ui/components/component-library/popover-header/popover-header.test.tsx
> +  it('should render popover element correctly', () => {
nit
```suggestion
  it('should render popover header correctly', () => {
```

2023-04-19 16:48 UTC, NidhiKJha submitted a review, later dismissed

2023-04-19 17:08 UTC, vthomas13 approved these changes

2023-04-19 17:09 UTC, NidhiKJha approved these changes

2023-04-19 17:36 UTC, merged