Migrates avatar base to TypeScript
MetaMask/metamask-extension pull request #18494
Opened 2023-04-06 20:16 UTC by spiritanand

## Explanation

Currently, the AvatarBase component is built in JavaScript. This PR deprecates the JS component and creates a new TypeScript version.

Migrated all `.js` to `.tsx` or `.ts` files

- Converted objects to enum
- Updated storybook documentation as well as how to add a new icon
- Resolves #18063

## Screenshots/Screencaps

### Before

https://user-images.githubusercontent.com/53999998/230484021-3b3eae39-4f8a-46b6-bc15-0580094a6a7a.mp4

### After

## Manual Testing Steps

- Go to the storybook build on this PR
- Search AvatarBase and go to the AvatarBase story in component-library
- Check stories
- Check docs align with enums

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be required.

2023-04-10 18:32 UTC, spiritanand commented on ui/components/component-library/avatar-base/avatar-base.tsx
> +      textTransform="UPPERCASE"
I was unable to pass `TEXT_TRANSFORM.UPPERCASE` as the type of `textTransform` in `Text` component is:-
<img width="565" alt="image" src="https://user-images.githubusercontent.com/53999998/230968019-85c52306-88e6-46e8-8ec1-8de4a68fc9cf.png">
`text.tsx`
This is translating to `ts` only accepting `"UPPERCASE" | "LOWERCASE" | "CAPITALIZE" | undefined`

What do you suggest I do?

<img width="530" alt="image" src="https://user-images.githubusercontent.com/53999998/230967983-920c0f8f-8242-404e-a448-e81e70dda072.png">
`text.types.ts`

2023-04-11 08:58 UTC, DDDDDanica commented on ui/components/component-library/avatar-base/avatar-base.types.ts
> +  XL = 'xl',
Can you change to Xs  to be consistent with what have been done in Icon?
https://github.com/MetaMask/metamask-extension/blob/develop/ui/components/component-library/icon/icon.types.ts#L4
Thank you !

```suggestion
  Xs = 'xs',
  Sm = 'sm',
  Md = 'md',
  Lg = 'lg',
  Xl = 'xl',
```

2023-04-11 12:04 UTC, georgewrmarshall reviewed
Not sure if Text being in TS is a dependency of this PR?

2023-04-11 12:04 UTC, georgewrmarshall commented on ui/components/component-library/avatar-base/avatar-base.types.ts
> +}
Please add the type descriptions from the PropTypes here with appropriate adjustments for typescript

2023-04-11 12:05 UTC, georgewrmarshall commented on ui/components/component-library/avatar-base/avatar-base.types.ts
> +export enum AvatarBaseSizes {
Should be singular
```suggestion
export enum AvatarBaseSize {
```

2023-04-11 15:52 UTC, spiritanand commented on ui/components/component-library/avatar-base/avatar-base.tsx
> +      textTransform={TEXT_TRANSFORM.UPPERCASE}
Well, this solves the issue. But feel more of a hack to me. Shouldn't we be accepting the values of the enum rather than their keys?

2023-04-11 15:55 UTC, spiritanand commented on ui/components/component-library/avatar-base/avatar-base.tsx
> +      textTransform="UPPERCASE"
@georgewrmarshall please have a look at this thread. We are dependent on the types `Text` accepts.

2023-04-12 14:41 UTC, DDDDDanica submitted a review, later dismissed

2023-04-18 08:14 UTC, georgewrmarshall reviewed
Looking good! Made one suggestion that I missed in last review. Also need to update snapshots 
```
yarn jest ui/components/component-library/avatar-base --updateSnapshot
```

2023-04-18 16:22 UTC, spiritanand commented
Updated :)

2023-04-19 06:55 UTC, legobeat requested changes
edb650f88c5e975278588cb850ecf4706f00b44b removes the yarn release - I assume this is unintentional.

2023-04-19 07:15 UTC, georgewrmarshall reviewed
Hey @spiritanand, could you please remove `.yarn/releases/yarn-3.2.4.cjs` file changes?

2023-04-19 09:33 UTC, spiritanand commented
Removed yarn file from git.

2023-04-19 09:41 UTC, DDDDDanica approved these changes, later dismissed

2023-04-20 02:29 UTC, georgewrmarshall reviewed
Looks like there are still linting issues you can use `yarn lint` to debug. thanks!

2023-04-20 06:08 UTC, georgewrmarshall reviewed
Looks like you have some conflicts that need to be resolved

2023-04-20 10:51 UTC, georgewrmarshall reviewed
Getting there made some more suggestions!

2023-04-20 10:51 UTC, georgewrmarshall commented on ui/components/component-library/avatar-base/avatar-base.types.ts
> +export interface AvatarBaseProps {
I believe this interface should extend the `TextProps` interface

2023-04-20 10:51 UTC, georgewrmarshall commented on ui/components/component-library/avatar-base/avatar-base.types.ts
> +   */
This comment can be removed
```suggestion
```

2023-04-20 11:31 UTC, spiritanand commented
@georgewrmarshall everything is working now, except the chrome test. How can we fix that?

2023-04-21 19:23 UTC, spiritanand commented
@georgewrmarshall I am getting the error
`AvatarBase not found via ../avatar-base/index.ts -> ../avatar-base/avatar-base.js  import/named`

2023-04-26 19:27 UTC, spiritanand commented
@georgewrmarshall what is the update on my questions?

2023-04-26 23:16 UTC, georgewrmarshall commented
Hi @spiritanand, I'm not sure what your issue is from a quick glance. I'll try do some digging this week. It also looks like you have a failing unit test.

<img width="1127" alt="Screenshot 2023-04-27 at 8 45 08 AM" src="https://user-images.githubusercontent.com/8112138/234722330-00bc9c6a-9996-4a0d-af8c-d03fba13515f.png">

2023-04-27 05:24 UTC, spiritanand commented
Thanks for the catch @legobeat, that was something I missed as well. The linting errors that I am getting are,
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/53999998/234766799-885eb3a0-5cc0-48a8-be11-2876c4c49e3b.png">


I have fixed the issue you have pointed out above, though. Added `forwardRef` in `AvatarBase`

2023-04-27 05:51 UTC, spiritanand commented
It is working perfectly. Thank you, @legobeat and @georgewrmarshall 

You guys have been tremendously patient and helpful :)

2023-04-28 07:02 UTC, georgewrmarshall requested changes
Looking great! Left 2 small suggestions

2023-04-28 07:02 UTC, georgewrmarshall commented on ui/components/component-library/avatar-base/README.mdx
> +<AvatarBase size={AvatarBaseSizes.XL} />
Should use the singular
```suggestion
import { AvatarBaseSize } from '../ui/component-library/avatar-base/avatar-base.types';
import { AvatarBase } from '../../component-library/avatar-base';
<AvatarBase size={AvatarBaseSize.XS} />
<AvatarBase size={AvatarBaseSize.SM} />
<AvatarBase size={AvatarBaseSize.MD} />
<AvatarBase size={AvatarBaseSize.LG} />
<AvatarBase size={AvatarBaseSize.XL} />
```

2023-04-29 05:27 UTC, spiritanand commented
Done :)

2023-05-01 15:26 UTC, brad-decker approved these changes

2023-05-02 00:44 UTC, georgewrmarshall approved these changes
LGTM! 💯 Thank you for you contribution @spiritanand

2023-05-04 00:27 UTC, legobeat approved these changes
LGTM

2023-05-04 00:30 UTC, merged