UX Multichain: updated ethereum logo icon
MetaMask/metamask-extension pull request #18528
Opened 2023-04-11 11:55 UTC by NidhiKJha

As per the new UI, we are updating the Ethereum logo 

## Screenshot

### Before

![Screenshot 2023-04-11 at 5 24 45 PM](https://user-images.githubusercontent.com/39872794/231155150-a1f0e171-4d7b-4506-88cc-0d81e8e49799.jpg)

### After
![Screenshot 2023-04-11 at 5 23 26 PM](https://user-images.githubusercontent.com/39872794/231154852-d987a07a-f5d5-42c0-9164-6e60c8db5025.jpg)

2023-04-11 22:27 UTC, georgewrmarshall requested changes, later dismissed
I think we may want to add a PNG and update the image paths. The svg added here is just an image wrapped in an svg I also think we should add a square image. I'll attach an appropriate image shortly

2023-04-18 02:19 UTC, georgewrmarshall reviewed
Draft PR here with some suggested changes https://github.com/MetaMask/metamask-extension/pull/18631

2023-04-19 13:20 UTC, darkwing approved these changes

2023-04-19 15:22 UTC, DDDDDanica approved these changes

2023-04-19 15:25 UTC, merged