Initial changes to support adding multiple nfts in one user interaction
MetaMask/metamask-extension pull request #18556
Opened 2023-04-13 01:33 UTC by dswilson4

## Explanation

Currently you can only add a single NFT of a single contract to your MM wallet in one user interaction.  The user currently needs to repeat this flow for as many NFTs as they have from a given contract.

This change proposes a user flow to add multiple NFTs from the same contract to your MM wallet in one user interaction as opposed to N interactions for N NFTs.

On an implementation level, I created two new actions that handle multiple token Ids at once in batch.  One action checks for ownership and the second action checks for the token details of the NFTs the user intends to add.  These are both very similar to the actions that exist that handle single NFT additions, these could potentially be merged such that one function handles both cases.

On the frontend, a new checkbox has been added that signifies whether the use is attempting to add one NFT or multiple NFTs in one user interaction.  I'm looking for suggestions and improvements for this UX, I'm not certain if there's a better component to use (ie. a dropdown, radio group, etc) or if the input schema should change.  Currently, the form accepts a string of comma separated NFT Ids.

## Screenshots/Screencaps

### Before

### After

![addMultipleNFTs](https://user-images.githubusercontent.com/33137497/231622431-600ede7e-a12c-46b5-9e5e-e5324b4adfa5.gif)

## Manual Testing Steps

1. Navigate to the NFT tab
2. Click the checkbox under the `Add multiple NFT` title
3. Enter NFT contract address
4. Enter a comma-separated list of NFT ids into the form ie. `1, 2`
5. Submit and see multiple NFTs added in one interaction

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved
  - [X] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-04-13 01:39 UTC, dswilson4 commented
@pedronfigueiredo @georgewrmarshall @NidhiKJha @garrettbear

2023-04-13 02:10 UTC, dswilson4 commented
I have read the CLA Document and I hereby sign the CLA

2023-04-18 19:10 UTC, digiwand requested changes
Cool seeing this working! 

left comments above. I wonder if design can weight in on this. 

Some thoughts:
- what if we don't need a checkbox and can leave an instruction to the user that they can add multiple NFTs by using a comma?  
- placeholder text should support new input 
- rather than sending a request for each entry, can the API handle receiving multiple values?

2023-04-18 19:10 UTC, digiwand commented on ui/store/actions.ts
> +      }
what if we had one action that supported adding one or more NFTs?

2023-04-18 19:10 UTC, digiwand commented on ui/pages/add-nft/add-nft.js
> +            <Text variant={TextVariant.bodySm}>Add multiple NFT</Text>
![Screen Shot 2023-04-18 at 2 43 33 PM](https://user-images.githubusercontent.com/20778143/232879887-229e0ef2-b36d-47ae-ad72-9aafbe91be38.png)

padding and alignment should be updated

2023-08-03 10:04 UTC, closed without merging