update icons to ts enum version
MetaMask/metamask-extension pull request #18698
Opened 2023-04-20 17:51 UTC by garrettbear

## Explanation

`Pages` folder Icon imports updated to TS version

Update imports from `'../../component-library/component-name/deprecated';` to `'../../component-library'`
Update component instances from using JS consts to enums

* Part of #18492 

## Screenshots/Screencaps

See comments

## Manual Testing Steps
regex search `ICON_NAMES` in the `ui/pages` folder

<img width="488" alt="Screenshot 2023-04-18 at 11 44 48 AM" src="https://user-images.githubusercontent.com/26469696/232873701-c979d70e-6dc8-4b7d-acca-149b20923813.png">

`yarn lint`
`yarn jest ui/pages`

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved
  - [X] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [X] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [X] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-04-20 18:37 UTC, brad-decker submitted a review, later dismissed

2023-04-20 18:39 UTC, NidhiKJha requested changes
LGTM! Just some small nits

2023-04-20 18:39 UTC, NidhiKJha commented on ui/pages/add-nft/add-nft.js
> +  IconSize,
```suggestion
  ButtonIconSize,
```

2023-04-20 18:39 UTC, NidhiKJha commented on ui/pages/send/send-content/add-recipient/domain-input.component.js
> +                size={IconSize.Sm}
```suggestion
                size={ButtonIconSize.Sm}
```

2023-04-20 18:39 UTC, NidhiKJha commented on ui/pages/send/send-content/add-recipient/domain-input.component.js
> +  IconSize,
```suggestion
  ButtonIconSize,
```

2023-04-20 18:40 UTC, NidhiKJha commented on ui/pages/add-nft/add-nft.js
> +                      size={IconSize.Sm}
```suggestion
                      size={ButtonIconSize.Sm}
```

2023-04-21 04:13 UTC, georgewrmarshall reviewed
Looking good couple small suggestions

2023-04-21 04:13 UTC, georgewrmarshall commented on ui/pages/settings/contact-list-tab/contact-list-tab.component.js
>              color={Color.iconMuted}
```suggestion
            color={IconColor.iconMuted}
```

2023-04-21 04:13 UTC, georgewrmarshall commented on ui/pages/settings/flask/snaps-list-tab/snap-list-tab.js
>                color={Color.iconMuted}
```suggestion
              color={IconColor.iconMuted}
```

2023-04-21 23:16 UTC, georgewrmarshall approved these changes
LGTM!

2023-04-24 09:14 UTC, NidhiKJha approved these changes

2023-04-24 14:19 UTC, merged