Part of #17670 Replace Typography with Text component for files: 'review-recovery-phrase' & 'metametrics'
MetaMask/metamask-extension pull request #18808
Opened 2023-04-25 18:08 UTC by PrgrmrHarshShukla

## Explanation
In this PR I have worked on the issue #17670 Replace Typography with Text component and issue #18714 Replace deprecated design system typography consts with enums for the files:

## Screenshots/Screencaps

### Before

### After

## Manual Testing Steps

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-05-05 01:30 UTC, georgewrmarshall reviewed
Code looks good. Could you please add screenshots to the PR description

2023-05-05 01:31 UTC, georgewrmarshall commented
Looks like you might need to update snapshots as well

2023-05-05 11:10 UTC, DDDDDanica commented on ui/pages/onboarding-flow/metametrics/metametrics.js
> +        marginTop={2}
Just curious about where is this style coming from? Previously we did not have margin-top appended

2023-05-05 11:11 UTC, DDDDDanica commented on ui/pages/onboarding-flow/metametrics/metametrics.js
> +                display={DISPLAY.INLINE_BLOCK}
```suggestion
                as="span"
```

2023-05-05 11:11 UTC, DDDDDanica commented on ui/pages/onboarding-flow/metametrics/metametrics.js
>                  marginTop={0}
You can remove this one now :)

2023-05-05 11:12 UTC, DDDDDanica commented on ui/pages/onboarding-flow/metametrics/metametrics.js
> +                display={DISPLAY.INLINE_BLOCK}
```suggestion
                       as="span"
```

2023-05-05 11:12 UTC, DDDDDanica commented on ui/pages/onboarding-flow/metametrics/metametrics.js
> +                display={DISPLAY.INLINE_BLOCK}
```suggestion
         as="span"
```

2023-05-09 05:14 UTC, georgewrmarshall reviewed
Hey @PrgrmrHarshShukla, just need to update snapshots and we can get this merged. Thanks!

2023-05-09 22:08 UTC, georgewrmarshall requested changes
Hey @PrgrmrHarshShukla, I think there is an incorrect prop being used. `align` should be `textAlign` could you please update

2023-05-09 22:08 UTC, georgewrmarshall commented on ui/pages/onboarding-flow/metametrics/__snapshots__/metametrics.test.js.snap
> +      align="center"
Seems like a prop has been incorrectly used and is being passed down to the html element

2023-05-09 22:08 UTC, georgewrmarshall commented on ui/pages/onboarding-flow/metametrics/metametrics.js
> +        align={TextAlign.Center}
I believe you want `textAlign` here this is what is being passed down to the html element. docs: https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-text--text-align-story#text-align
```suggestion
        textAlign={TextAlign.Center}
```

2023-05-10 22:05 UTC, georgewrmarshall reviewed
You still have some instances of `align={` in the `Text` components. Please update

2023-05-18 00:11 UTC, georgewrmarshall commented
Hey @PrgrmrHarshShukla, just wanted to check in. It looks like this PR is almost there. Did you still want to work on it? If so, that's great! Let us know if you need any assistance or if there are any blockers. If you're unable to continue working on it or haven't had a chance to address it, no worries! I can take it from here and carry it forward. Cheers!

2023-06-01 21:23 UTC, georgewrmarshall commented
Hey @PrgrmrHarshShukla, thanks for all your effort with this PR I am going to close it as it has become stale. Please feel free to open another PR in future. Thanks for your contributions thus far!

2023-06-01 21:23 UTC, closed without merging