Part of #17670 Replace Typography with Text component for 5 files.
MetaMask/metamask-extension pull request #18831
Opened 2023-04-26 13:11 UTC by PrgrmrHarshShukla

## Explanation
In this PR I have worked on the issue #17670 Replace Typography with Text component and issue #18714 Replace deprecated design system typography consts with enums for the files:

## Screenshots/Screencaps

### Before

### After

## Manual Testing Steps

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-05-05 01:33 UTC, georgewrmarshall requested changes
hey @PrgrmrHarshShukla, Left some suggestions could you please add screenshots to the PR description

2023-05-05 01:33 UTC, georgewrmarshall commented on ui/components/app/snaps/copyable/copyable.js
> +        variant={TextVariant.H6}
incorrect TextVariant

2023-05-05 01:33 UTC, georgewrmarshall commented on ui/pages/keychains/restore-vault.js
> +            <Text color={TextColor.textDefault} margin={0} marginBottom={4}>
```suggestion
            <Text color={TextColor.textDefault} marginBottom={4}>
```

2023-05-06 02:20 UTC, PrgrmrHarshShukla commented
Hello @georgewrmarshall ,

I added the screenshots of the component I was able to find in the UI.
Kindly help for the other components.

2023-05-09 05:16 UTC, georgewrmarshall commented
Hey @PrgrmrHarshShukla, the best way is to follow @brad-decker's comment here https://github.com/MetaMask/metamask-extension/pull/18741#issuecomment-1538837547

2023-05-10 00:47 UTC, georgewrmarshall commented
The other option you have for gathering before / after screenshots is to create a story for the component. Docs are here https://metamask.github.io/metamask-storybook/?path=/story/getting-started-documentation-guidelines--page#creating-a-story

```jsx
import React from 'react';
import MyComponent from '.';

export default {
  title: 'Components/UI/MyComponent', // title should follow the folder structure location of the component. Don't use spaces.

};

export const DefaultStory = () => <MyComponent />;

DefaultStory.storyName = 'Default';
```

2023-05-18 00:12 UTC, georgewrmarshall commented
Hey @PrgrmrHarshShukla, just wanted to check in. It looks like this PR is almost there. Did you still want to work on it? If so, that's great! Let us know if you need any assistance or if there are any blockers. If you're unable to continue working on it or haven't had a chance to address it, no worries! I can take it from here and carry it forward. Cheers!

2023-06-01 21:24 UTC, georgewrmarshall commented
Hey @PrgrmrHarshShukla, thanks for all your effort with this PR I am going to close it as it has become stale. Please feel free to open another PR in future. Thanks for your contributions thus far!

2023-06-02 09:47 UTC, PrgrmrHarshShukla commented
Hey @georgewrmarshall ,
Closing this one myself.
Equipped with all the experiences I gained from these PRs, I will be back soon with more organized and better PRs.

Regards,
Harsh

2023-06-02 09:47 UTC, closed without merging

2023-06-02 13:01 UTC, georgewrmarshall commented
Hey @PrgrmrHarshShukla, thanks again for all your contributions, best of luck and look forward to collaborating with you in future