feat(accounts): import account without password
MetaMask/metamask-extension pull request #19132
Opened 2023-05-15 09:02 UTC by montelaidev

## Explanation

Makes password optional when importing an account from a JSON file.

* Fixes #18180

## Screenshots/Screencaps

### Before
<img width="348" alt="Screenshot 2023-05-15 at 4 49 03 PM" src="https://github.com/MetaMask/metamask-extension/assets/96463427/86699439-8fba-4157-93fa-46b498c22595">

### After

<img width="370" alt="Screenshot 2023-05-17 at 10 06 25 AM" src="https://github.com/MetaMask/metamask-extension/assets/96463427/5436aba9-76cb-4a8d-a3af-37a8da15ce7b">

## Manual Testing Steps

1. Click on account icon
2. Click on `Import Account`
3. Select Json for type
4. Click on Password less toggle
5. Upload Json file
6. Click on Import.

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-05-15 09:39 UTC, Ezeone38 submitted a review, later dismissed

2023-05-15 15:00 UTC, darkwing requested changes, later dismissed

2023-05-15 15:13 UTC, darkwing commented
This area looks really really busy and overwhelming:

<img width="366" alt="SCR-20230515-jfsa" src="https://github.com/MetaMask/metamask-extension/assets/46655/4fd4f328-4617-46d9-a6e3-7d554866653c">

Maybe we can add some spacing?

2023-05-15 16:04 UTC, montelaidev commented on ui/pages/create-account/import-account/json.js
> +  }
yes, let me change that.

2023-05-16 04:55 UTC, HowardBraham commented
Did this work before if you just left the password field blank?  I'm mostly guessing that because I don't see any changes to the actual functionality, just changes to how the UI behaves.

2023-05-16 15:59 UTC, plasmacorral commented
Could we please have a screenshot of the update made wrt spacing and in response to this [comment]?(https://github.com/MetaMask/metamask-extension/pull/19132#issuecomment-1548057171)

2023-05-17 00:50 UTC, montelaidev commented
> Did this work before if you just left the password field blank? I'm mostly guessing that because I don't see any changes to the actual functionality, just changes to how the UI behaves.

Yea, users were able to pass an empty password before.

2023-05-17 17:44 UTC, HowardBraham approved these changes

2023-05-23 08:39 UTC, danroc commented
@montelaidev, do you have test files (with and without a password)?

2023-05-23 12:04 UTC, danroc approved these changes

2023-05-23 19:49 UTC, HowardBraham approved these changes

2023-05-23 22:40 UTC, danjm approved these changes

2023-05-23 22:54 UTC, merged