design systems constants DISPLAY FLEX_DIRECTION FLEX_WRAP BLOCKSIZES …
MetaMask/metamask-extension pull request #19133
Opened 2023-05-15 09:21 UTC by nazrul7711

…changed to enum

## Explanation

## Screenshots/Screencaps

### Before

### After

## Manual Testing Steps

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-05-15 21:04 UTC, georgewrmarshall requested changes
Hey @nazrul7711, thanks for your contribution. This is looking really great! Left a few small suggestions.

I wasn't sure if we would have to update the `box.d.ts` file with a union type of the `Display` enum as well as the `DISPLAY` const? There doesn't seem to be any errors in the TypeScript files I was looking at which I found interesting I suppose because it is just looking for the string or an array of strings.

2023-05-16 02:25 UTC, nazrul7711 commented on yarn.lock
ok

2023-05-16 02:26 UTC, nazrul7711 commented on ui/helpers/constants/design-system.ts
> +/**
added

2023-05-16 02:27 UTC, nazrul7711 commented on ui/helpers/constants/design-system.ts
>    SCREEN: 'screen',
depracated

2023-05-16 02:29 UTC, nazrul7711 commented on ui/components/ui/box/box.js
> +    flexDirection = FlexDirection.ROW,
rectified

2023-05-16 02:31 UTC, nazrul7711 commented on yarn.lock
removed

2023-05-16 02:43 UTC, nazrul7711 commented
hi @georgewrmarshall I have made the modifications , kindly review it.

2023-05-17 08:19 UTC, georgewrmarshall commented on yarn.lock
Sorry if I was unclear, I didn't mean to remove the yarn.lock file just revert the changes so it doesn't appear in your PR

2023-05-17 08:42 UTC, nazrul7711 commented on yarn.lock
so u mean i should have yarn.lock in my repo but remove it from the PR.rest is fine?

2023-05-17 08:50 UTC, georgewrmarshall requested changes
Hey @nazrul7711, I've updated the PR title and description so the PR is a little more clear. Some of it was still commented out. I've also realized that I missed `SEVERITIES` in the issue(now updated). Could you also create an enum for `SEVERITIES`. I don't think we need one for `RESIZE` as it's used for a single component that will likely be migrated to TypeScript and have it's own types.

2023-05-17 10:50 UTC, nazrul7711 commented on ui/components/component-library/tag-url/tag-url.js
>        <AvatarFavicon src={src} name={label} {...avatarFaviconProps} />
modified

2023-05-17 21:10 UTC, georgewrmarshall approved these changes
Hey @nazrul7711, I rebased this PR to remove the `yarn.lock` changes and made sure that the deprecated constants still work by keeping the unit tests for them. This was kind of blocking some other TS migration work so I really appreciate your timing on this and hope you don't mind my updates. LGMT 🔥

2023-05-17 22:44 UTC, brad-decker approved these changes

2023-05-17 22:44 UTC, merged