covers issue #19124 Migrate components to TS: PickerNetwork
MetaMask/metamask-extension pull request #19148
Opened 2023-05-15 17:52 UTC by doesnots

## Explanation
* Changed the files in ui/components/component-library to typescript
* Re-wrote everything in Typescript and also added proper extensions along with documentation.
*  Fixes #19124 

## Pre-merge author checklist

- I've clearly explained:
  - [ ✅] What problem this PR is solving
  - [ ✅] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-05-15 17:53 UTC, doesnots commented
> **CLA Signature Action:**
> 
> Thank you for your submission, we really appreciate it. We ask that you read and sign our [Contributor License Agreement](https://metamask.io/cla.html) before we can accept your contribution. You can sign the CLA by just by adding a comment to this pull request with this exact sentence:
> 
> > _**I have read the CLA Document and I hereby sign the CLA**_
> 
> By commenting with the above message you are agreeing to the terms of the CLA. Your account will be recorded as agreeing to our CLA so you don't need to sign it again for future contributions to this repository.
> 
> **0** out of **1** committers have signed the CLA. ❌ @doesnots

I have read the CLA Document and I hereby sign the CLA

2023-05-15 22:44 UTC, georgewrmarshall requested changes
Hey @doesnots, thanks for your contribution. The issue this PR is intended to solve is to replace the picker-network component this PR is creating a new folder see screenshot. You are also missing some files outlined in the template in the issue. e.g. `picker-network.types.js`

<img width="273" alt="Screenshot 2023-05-16 at 10 43 04 AM" src="https://github.com/MetaMask/metamask-extension/assets/8112138/f1cdd140-79cd-40d2-ad49-9d4667896f0e">

2023-05-16 05:01 UTC, doesnots commented
My apologies, I'll correct all of that by today.
Thanks for pointing out.

2023-05-17 08:31 UTC, georgewrmarshall requested changes
Hey @doesnots, I've made a few suggestions but this PR has a fair way to go to meet the acceptance criteria.
- The component should be a named export
- The propType comments should be moved to the types in the `.types` file
- The storybook file is missing storybook types


It is also failing a lot of unit tests. I'm afraid I am going to have to close it. I appreciate your contribution and encourage you to contribute in future. These issues may be more suitable to work on.

- https://github.com/MetaMask/metamask-extension/issues/18896
- https://github.com/MetaMask/metamask-extension/issues/18714
- https://github.com/MetaMask/metamask-extension/issues/17670

2023-05-17 08:31 UTC, georgewrmarshall commented on ui/components/component-library/picker-network/README.tsx
> +import { Story, Canvas, ArgsTable } from '@storybook/addon-docs';
This should remain a `.mdx` file

2023-05-17 08:31 UTC, georgewrmarshall commented on ui/components/component-library/picker-network/picker-network.tsx
> +export default PickerNetwork;
Should be a named export

2023-05-17 08:33 UTC, closed without merging