Update v10.31.0 changelog
MetaMask/metamask-extension pull request #19147
Opened 2023-05-15 17:40 UTC by tmashuang

For #19032.

Should I have included all the MMI changes/additions?

2023-05-16 19:30 UTC, danjm commented on CHANGELOG.md
> +- Fix popover hiding ([#18843](https://github.com/MetaMask/metamask-extension/pull/18843))
```suggestion
- Fix terms of use popover scroll button hiding when scollbar is at the bottom. ([#18843](https://github.com/MetaMask/metamask-extension/pull/18843))
```

2023-05-16 19:38 UTC, danjm requested changes
Only a couple suggested changes

2023-05-16 22:32 UTC, tmashuang commented on CHANGELOG.md
> +- Fix popover hiding ([#18843](https://github.com/MetaMask/metamask-extension/pull/18843))
Done on https://github.com/MetaMask/metamask-extension/pull/19147/commits/8aa975ef9d3a67fd2c46570bccc9a79a322352d3#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR31

2023-05-17 08:22 UTC, FrederikBolding commented on CHANGELOG.md
>  - [FLASK] Update permissions to use IconName and IconSize design system enum ([#18786](https://github.com/MetaMask/metamask-extension/pull/18786))
```suggestion
```
Probably fine to omit.

2023-05-17 08:22 UTC, FrederikBolding commented on CHANGELOG.md
> +- [FLASK] Expand Snap authorship component ([#18775](https://github.com/MetaMask/metamask-extension/pull/18775))
```suggestion
```
Remove to be combined with another entry

2023-05-17 08:22 UTC, FrederikBolding commented on CHANGELOG.md
>  - [FLASK] Add updated version of the Snaps settings UI ([#18438](https://github.com/MetaMask/metamask-extension/pull/18438))
```suggestion
- [FLASK] Add updated version of the Snaps settings UI ([#18438](https://github.com/MetaMask/metamask-extension/pull/18438), ([#18775](https://github.com/MetaMask/metamask-extension/pull/18775)))
```
Combine with another PR

2023-05-17 17:06 UTC, merged