feature: Migrated input components to TS -> #19122
MetaMask/metamask-extension pull request #19166
Opened 2023-05-16 09:44 UTC by git-init-priyanshu

### Fixes #19122
**JavaScript to TypeScript Migration Completed Successfully**
I have successfully migrated all the JavaScript files to TypeScript files, following the provided instructions. By making this transition, we can now benefit from enhanced code maintainability, reliability, and scalability.

**Before**

**After**
![image](https://github.com/MetaMask/metamask-extension/assets/110045644/b6be03b3-948c-4620-a935-0e0810dcbce0)

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-05-16 09:49 UTC, git-init-priyanshu commented
I have read the CLA Document and I hereby sign the CLA

2023-05-17 08:25 UTC, georgewrmarshall requested changes
Hey @git-init-priyanshu, thanks for your contribution. You have instances of the incorrect casing for the enum which should be causing errors e.g. `InputType.text` should be `InputType.Text`. There are also a few other conventions you are missing. I would suggest having a look at the `BadgeWrapper` component

2023-05-17 12:25 UTC, git-init-priyanshu commented
Hey @georgewrmarshall  thanks for reviewing my PR. 
I apologize for the errors and oversights in my recent contribution. I will make the necessary changes and review the BadgeWrapper component thoroughly to address any conventions I might have missed.

2023-05-18 00:39 UTC, georgewrmarshall reviewed
Still a bit to go :)

2023-05-18 00:39 UTC, georgewrmarshall commented on ui/components/component-library/input/index.ts
> +export { InputType } from './input.types';
Need a line break here
```suggestion
export { InputType } from './input.types';

```

2023-05-18 00:39 UTC, georgewrmarshall commented on ui/components/component-library/input/input.types.ts
> +}
Need a line break here. As well as the `InputProps`
```suggestion
}
```

2023-05-18 00:39 UTC, georgewrmarshall commented on ui/components/component-library/input/input.tsx
>     */
You need to migrate the PropTypes to an interface in the `.types.ts` file

2023-05-18 06:10 UTC, git-init-priyanshu commented
Thanks @georgewrmarshall for being so kind and patient, and for reviewing my PR. I will make sure to implement all these suggestions.

2023-05-19 06:11 UTC, git-init-priyanshu commented
Made some tweaks but not sure if they are correct or not.

2023-05-19 06:58 UTC, git-init-priyanshu commented
I have read the CLA Document and I hereby sign the CLA

2023-05-20 13:20 UTC, git-init-priyanshu commented
Hey @georgewrmarshall, could you please review my PR.
Thanks.

2023-05-31 22:21 UTC, georgewrmarshall commented
Hey @git-init-priyanshu , Thanks for your time and effort in creating this pull request. As you're probably aware we have identified an issue related to the typing of the `Box` component, specifically with the polymorphic `as` prop. To address this issue, we have an open ticket at https://github.com/MetaMask/metamask-extension/issues/19239 and a draft pull request at https://github.com/MetaMask/metamask-extension/pull/19363 that needs to be merged before we can proceed with your PR. Thanks for your patience

2023-06-01 05:07 UTC, git-init-priyanshu commented
Hey @georgewrmarshall, thanks for your reply
I'll wait for the necessary changes to be addressed and merged so that we can proceed smoothly. Once those changes are merged, I'll be ready to rebase and update my pull request accordingly.

2023-06-27 02:37 UTC, georgewrmarshall commented
Blocked by https://github.com/MetaMask/metamask-extension/pull/19572

2023-07-24 22:42 UTC, georgewrmarshall commented
Hey @git-init-priyanshu, thank you very much for your contribution. Another PR was opened that solves this task and it has one approval so I am going to close this one.

2023-07-24 22:42 UTC, closed without merging