Part of #19125: Migrate component to TS: Tag
MetaMask/metamask-extension pull request #19186
Opened 2023-05-17 15:36 UTC by dhruvv173

## Explanation

- This PR is a part of  #19125 
Migrated the components from JS to TS for `Tag`
Filepath: `ui\components\component-library\tag`
It extends the `BoxProps` so the controls have increased

## Screenshots/Screencaps

### Before

![image](https://github.com/MetaMask/metamask-extension/assets/79097544/8336e5ec-3821-487f-b879-672e1144a7c7)
![image](https://github.com/MetaMask/metamask-extension/assets/79097544/783fd876-8656-43db-a62b-a45a62172187)

### After

![image](https://github.com/MetaMask/metamask-extension/assets/79097544/491e380e-fcac-49dd-9cc5-c9637f3d4f84)
![image](https://github.com/MetaMask/metamask-extension/assets/79097544/ef5a3363-6dfe-4c2e-8f79-c31b294d735c)

## Manual Testing Steps

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-05-18 00:47 UTC, georgewrmarshall approved these changes
Hey @dhruvv173, thanks for your contribution, you hit it out of the park! LGTM 🚀

2023-05-18 01:02 UTC, georgewrmarshall requested changes
Ah sorry I missed the error. One small update!

2023-05-18 01:02 UTC, georgewrmarshall commented on ui/components/component-library/tag/tag.types.ts
> +import { BoxProps } from 'ui/components/ui/box/box';
Ah this will fix the error you are getting
```suggestion
import type { BoxProps } from '../../ui/box/box.d';
```

2023-05-18 02:35 UTC, dhruvv173 commented
> Hey @dhruvv173, thanks for your contribution, you hit it out of the park! LGTM 🚀 

Sorry I didn't leave a message for review as a dependency test was failing. However, you've gone out of your way to help me out with it. Thanks a lot!

I'll make the changes and submit the PR. Thanks once again!

2023-05-18 08:48 UTC, dhruvv173 commented
Hey @georgewrmarshall I have made the changes as suggested, could you please review them?
Thanks!

2023-05-18 19:56 UTC, georgewrmarshall commented
Hey @dhruvv173, yes updating the deprecated consts for enums would be great! Thanks

2023-05-19 15:02 UTC, dhruvv173 commented
> Hey @dhruvv173, yes updating the deprecated consts for enums in the Tag component would be great! Thanks

Hey @georgewrmarshall, sorry for the delayed response but by the time I started working on updating `consts -> enums` the open PR related to it was already merged. So I just had to make changes in the `Tag` component file. 
Could you please review it?
Thanks

2023-05-19 23:55 UTC, georgewrmarshall requested changes
Hey @dhruvv173, in my final checks I found some things that could be updated
- deprecated storybook `ComponentMeta` tags
- PropType issue in storybook

<img width="662" alt="Screenshot 2023-05-20 at 11 54 13 AM" src="https://github.com/MetaMask/metamask-extension/assets/8112138/1f3ab3a2-3172-459b-8d02-f2b8375897ce">
<img width="1440" alt="Screenshot 2023-05-20 at 11 54 20 AM" src="https://github.com/MetaMask/metamask-extension/assets/8112138/e2ce1d07-6767-4f4b-95cb-28e045eb3134">

2023-05-20 08:27 UTC, dhruvv173 commented
> Hey @dhruvv173, in my final checks I found some things that could be updated
> 
> * deprecated storybook `ComponentMeta` tags
> * PropType issue in storybook


hey @georgewrmarshall, the deprecated component issue was due to change in the storybook version to `v7` for which my branch wasn't updated. However, its fixed now. 
![image](https://github.com/MetaMask/metamask-extension/assets/79097544/9efd6c9e-e9ec-4321-ab5a-6bcb5685f4be)


- I looked into the PropType issue and found out that the control should be passed in as an array and not an object and thats when the changes are reflected correctly. Does that need to be changed? If yes, I'd like to do it if you could guide me.
Thanks
![image](https://github.com/MetaMask/metamask-extension/assets/79097544/c3fe6aef-9330-4c79-a0e7-12afb6df87dd)
![image](https://github.com/MetaMask/metamask-extension/assets/79097544/58fb5a82-3b5f-4c1d-b1b3-64559024fbf9)

2023-05-21 13:32 UTC, dhruvv173 commented
hey @georgewrmarshall, just an update on this issue.
I was going through the already migrated components and faced the same PropType issue for the extended `Box` props.
The props defined in the `.types.ts` file work fine but its the extended ones which cause this issue.
![image](https://github.com/MetaMask/metamask-extension/assets/79097544/33d393af-b13e-40ee-b474-4282aa5f3fd6)

Works fine when passed as an array
![image](https://github.com/MetaMask/metamask-extension/assets/79097544/27ea367d-9a8a-4d91-afb7-e67093999a1b)

2023-05-31 22:22 UTC, georgewrmarshall commented
Hey @dhruvv173, Thanks for your time and effort in creating this pull request. We have identified an issue related to the typing of the `Box` component, specifically with the polymorphic `as` prop. To address this issue, we have an open ticket at https://github.com/MetaMask/metamask-extension/issues/19239 and a draft pull request at https://github.com/MetaMask/metamask-extension/pull/19363 that needs to be merged before we can proceed with your PR. Thanks for your patience

2023-06-11 16:23 UTC, dhruvv173 commented
> Hey @dhruvv173, Thanks for your time and effort in creating this pull request. We have identified an issue related to the typing of the `Box` component, specifically with the polymorphic `as` prop. To address this issue, we have an open ticket at #19239 and a draft pull request at #19363 that needs to be merged before we can proceed with your PR. Thanks for your patience

hey, can this be worked on now?

2023-06-12 20:38 UTC, georgewrmarshall commented
Hey @dhruvv173, one more blocker that I'm working on now https://github.com/MetaMask/metamask-extension/pull/19572

2023-06-12 20:47 UTC, dhruvv173 commented
> Hey @dhruvv173, one more blocker that I'm working on now https://github.com/MetaMask/metamask-extension/pull/19572

Apologies for missing that part out:/
I'll keep an eye on that PR and start working once it's merged, thankyou for bringing it to my attention!

2023-06-27 02:38 UTC, georgewrmarshall commented
Blocked by https://github.com/MetaMask/metamask-extension/pull/19572

2023-07-19 08:51 UTC, dhruvv173 commented
hello @georgewrmarshall , made changes with a clean commit history and resolved conflicts [here](https://github.com/MetaMask/metamask-extension/pull/20086)

2023-07-20 14:27 UTC, closed without merging