Component-Library storybook introduction fix
MetaMask/metamask-extension pull request #19359
Opened 2023-05-31 19:18 UTC by dhruvv173

## Explanation

- This PR closes #19329 
The Component-library introduction story is fixed and it maintains consistency with other introduction stories.

## Screenshots/Screencaps

### Before

![image](https://github.com/MetaMask/metamask-extension/assets/79097544/916fd80d-a7c1-4684-9817-4d000bcbb489)

### After

![image](https://github.com/MetaMask/metamask-extension/assets/79097544/e634b219-e561-4aa2-8cf1-a356f2ca8c21)

## Manual Testing Steps
Pull this branch
run `yarn storybook`
check `Introduction` in `ComponentLibrary`

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-05-31 19:49 UTC, dhruvv173 commented
hey @georgewrmarshall, could you please review this PR?
Thanks!

2023-05-31 20:31 UTC, georgewrmarshall requested changes
Hey @dhruvv173, this looks great. Can you please update the name `COMPONENT-LIBRARY.stories.mdx` to `README.stories.mdx` we still want a readme and I'm hoping it will still show up on GitHub ok so there is still readable documentation about the component-library without having to run storybook

2023-05-31 20:51 UTC, dhruvv173 commented
> Hey @dhruvv173, this looks great. Can you please update the name `COMPONENT-LIBRARY.stories.mdx` to `README.stories.mdx` we still want a readme and I'm hoping it will still show up on GitHub ok so there is still readable documentation about the component-library without having to run storybook

I renamed the file but it does not show up on GitHub as a `README`, should I make a `README.md` and paste the content there aswell?

2023-05-31 21:36 UTC, dhruvv173 commented
hey @georgewrmarshall, I did some research and found the fix to this. Now, it can be read on GitHub with `README.md` and on Storybook with `COMPONENT-LIBRARY.stories.mdx`. Attaching screenshots below from latest commit for reference.
I renamed the stories file as well, could you please check this once?

![image](https://github.com/MetaMask/metamask-extension/assets/79097544/3d182466-ff19-4dfc-ba23-c193f327e5d6)
![image](https://github.com/MetaMask/metamask-extension/assets/79097544/ffcd4daa-7c8c-4e24-aea5-c1cd2f03694a)

2023-05-31 22:40 UTC, georgewrmarshall approved these changes, later dismissed
Hey @dhruvv173, checked out the branch looks good made a couple small updated wile I was there. Thanks for your contribution!

2023-05-31 22:40 UTC, georgewrmarshall commented on ui/components/component-library/README.md
> +[DS components figma file](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=16%3A6) (internal)
Oh we made our Figma UI Kit publicly viewable so we can remove "(internal)"
```suggestion
[DS components figma file](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=16%3A6)
```

2023-05-31 22:47 UTC, georgewrmarshall approved these changes
Ah missed the rename of the file. Nice work

2023-06-01 21:41 UTC, garrettbear approved these changes

2023-06-05 15:53 UTC, merged