Multichain activity screen
MetaMask/metamask-extension pull request #19497
Opened 2023-06-07 16:51 UTC by vthomas13

## Explanation

## Screenshots/Screencaps

### Before

### After

## Manual Testing Steps

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-06-07 18:33 UTC, NidhiKJha requested changes
Really good start. Left some comments :)

2023-06-07 18:33 UTC, NidhiKJha commented on ui/components/app/transaction-icon/transaction-icon.scss
>      background: var(--color-background-alternative);
Let's use [AvatarIcon](https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-avataricon--docs) here. We won't have to write extra css then

2023-06-07 18:33 UTC, NidhiKJha commented on ui/components/app/transaction-icon/transaction-icon.js
> +    return <Box className="transaction-icon__grey-circle" />;
Can we use AvatarIcon here as well?

2023-06-07 18:33 UTC, NidhiKJha commented on ui/components/ui/list-item/index.scss
> +  }
Let's use Text for this

2023-06-07 18:33 UTC, NidhiKJha commented on ui/helpers/utils/util.js
> +  fallback = "MMM d, y 'at' h:mm a",
I think we can create another function for this format in that case we would not have to deal with test failure and updating the hook. wdyt?

2023-06-07 18:33 UTC, NidhiKJha commented on ui/components/ui/list-item/index.scss
> +    'top  top      top      top      top      top      top      top      top   top   top   top'
Following our conversation, I think you can get rid of grid and do it with Flex. We can follow the same pattern as what we have for multichainTokenList

2023-06-07 18:33 UTC, NidhiKJha commented on ui/components/ui/list-item/list-item.component.js
> +        <div className="list-item__top-content">{topContent}</div>
I think we can use Text for topContent here?
![Screenshot 2023-06-08 at 12 02 17 AM](https://github.com/MetaMask/metamask-extension/assets/39872794/0c03d820-2dfc-4b6e-9ece-339bb94bdbee)

2023-07-13 14:14 UTC, closed without merging

2023-07-13 14:15 UTC, vthomas13 commented
dupe branch