Fix unknown processing time not showing in warning color
MetaMask/metamask-extension pull request #19527
Opened 2023-06-08 19:20 UTC by segun

## Explanation
Problem: whenever we are sending a transaction with an Unknown processing time we see the text displayed green instead of in the Warning color.

Fixes: #19305 

## Screenshots/Screencaps

### Before

![](https://user-images.githubusercontent.com/54408225/241233731-933744ab-ad90-4c60-9e19-a6894c2d7b87.png)

### After

<img width="414" alt="Screenshot 2023-06-08 at 22 15 36" src="https://github.com/MetaMask/metamask-extension/assets/44811/d4ba32c2-25a1-412f-bdb2-809baf27cf20">

## Manual Testing Steps

1. Start a transaction
2. Click to edit the gas fees
3. Click on advanced
4. Set Priority Fee to 0
5. Click Save
6. Unknown processing time should be shown in warning colour.

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-06-09 14:08 UTC, brad-decker requested changes

2023-06-09 14:08 UTC, brad-decker commented on ui/components/app/gas-timing/gas-timing.component.js
> +  console.log('estimateUsed', estimateUsed);
Console.logs need removed

2023-06-13 14:33 UTC, jpuri approved these changes
LGTM 👍

2023-06-13 14:35 UTC, jpuri commented
Will be nice to have test coverage if possible.

2023-06-15 11:39 UTC, danjm approved these changes

2023-06-15 14:51 UTC, brad-decker approved these changes

2023-06-15 15:52 UTC, merged