creating story for `cancel button`
MetaMask/metamask-extension pull request #19566
Opened 2023-06-12 08:20 UTC by rohiiittttt

## Explanation

- This PR is a part of #18896 
- created story for cancel button and replaced deprecated button component

## Screenshots/Screencaps

![image](https://github.com/MetaMask/metamask-extension/assets/129620973/a9531514-01c7-408d-8a62-7d80a76322e6)
![image](https://github.com/MetaMask/metamask-extension/assets/129620973/cc917e96-1a3f-42c2-b0b7-22816aacd548)

## Manual Testing Steps

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-06-15 20:40 UTC, garrettbear requested changes
Thanks for helping out @rohiiittttt 

Our old Button is not a 1 to 1 transition to the new Button. I've made a few comments on changes to closely align. 

But upon looking at this and with the recommended changes, there still might be some concerns about the font size of our new button when next to an old button. 

Before
<img width="693" alt="Screenshot 2023-06-15 at 1 11 48 PM" src="https://github.com/MetaMask/metamask-extension/assets/26469696/6dea55f0-a9ce-4da5-95a0-75175728748d">

After
<img width="833" alt="Screenshot 2023-06-15 at 1 22 16 PM" src="https://github.com/MetaMask/metamask-extension/assets/26469696/daf7accf-b89f-44d0-bf52-221835fb9fcc">

This will begin to make this PR a bit larger since now the Primary buttons paired next to the CancelButton also need to be updated to the latest version. 

With that being all said, you are still welcome to add the `cancel-button.stories.js` file and undo any changes to `cancel-button.js`

2023-06-16 06:24 UTC, rohiiittttt commented on ui/components/app/cancel-button/cancel-button.js
> +import { Button } from '../../component-library';
@garrettbear i have made the changes please check..

2023-06-19 20:15 UTC, georgewrmarshall approved these changes
Hey @rohiiittttt, thanks for your contribution but in this case updating the component here effects other UI so I'm reverting those changes and keeping the story. I think updating this components deprecated components should update the transaction details as well.

<img width="1440" alt="Screenshot 2023-06-19 at 1 09 21 PM" src="https://github.com/MetaMask/metamask-extension/assets/8112138/44c2ca4b-8cc7-4cd5-bb8b-db2e01586028">

2023-06-20 20:44 UTC, garrettbear approved these changes

2023-06-20 20:44 UTC, merged