Part of #18714: Replacing deprecated constants in `confirm-subtitle` folder
MetaMask/metamask-extension pull request #19699
Opened 2023-06-21 04:54 UTC by rohiiittttt

## Explanation

- This PR is a part of #18714 

Replaced deprecated design system and storybook constants in the confirm-subtitle
ui/components/app/confirm-subtitle

## Screenshots/Screencaps

### Before
![image](https://github.com/MetaMask/metamask-extension/assets/129620973/6cb04412-40b8-4cdc-bcd9-e346ad80c843)
![image](https://github.com/MetaMask/metamask-extension/assets/129620973/d3490c06-31e1-4b07-a976-d27eddbe3450)

### After
![image](https://github.com/MetaMask/metamask-extension/assets/129620973/890d9494-118a-45d1-ba1f-d22ab8217eb3)
![image](https://github.com/MetaMask/metamask-extension/assets/129620973/0cab43a4-1a87-4203-9185-ea56df2b5ae6)

## Manual Testing Steps

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-06-21 18:29 UTC, georgewrmarshall requested changes
Hey @rohiiittttt, I think we can remove fontWeight altogether here

2023-06-21 18:29 UTC, georgewrmarshall commented on ui/components/app/confirm-subtitle/confirm-subtitle.js
> +  FontWeight,
We could actually remove this because the font-weight for bodyMd is already normal

2023-06-21 18:29 UTC, georgewrmarshall commented on ui/components/app/confirm-subtitle/confirm-subtitle.js
> +      fontWeight={FontWeight.Normal}
Remove as unneeded
```suggestion
```

2023-06-22 16:19 UTC, rohiiittttt commented
@georgewrmarshall i have done the changes please check

2023-06-23 21:39 UTC, georgewrmarshall approved these changes, later dismissed

2023-06-23 21:40 UTC, georgewrmarshall approved these changes

2023-06-27 01:16 UTC, darkwing approved these changes

2023-06-27 02:35 UTC, merged