Fix misaligned icons in 'Connected sites' modal
MetaMask/metamask-extension pull request #19944
Opened 2023-07-10 19:22 UTC by jase-b

Fixes #19901: Connected sites modal misaligned icons

Replaced `<SiteIcon>` with `<AvatarFavicon>` in `<ConnectedSitesList>`

### Before

![19901 before](https://github.com/MetaMask/metamask-extension/assets/4392888/7885e77c-8954-4824-8331-22306d7ec35c)

### After

![19901 after](https://github.com/MetaMask/metamask-extension/assets/4392888/9a01eb62-fabb-417a-bfed-f5b7b0039eaf)

## Manual Testing Steps

- Log in to MetaMask.
- Connect the wallet to at least one site (if not already).
- Open the 'Connected sites' modal.
- Observe all listed site icons are centered within their circular container element.

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [x] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [x] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

2023-07-10 19:23 UTC, jase-b commented
I have read the CLA Document and I hereby sign the CLA

2023-07-11 16:23 UTC, jase-b commented on builds.yml
> +      - MMI_CONFIGURATION_SERVICE_URL: ''
Default value added based on suggestion from failing CircleCI test:

![mmi ppolicy test fail](https://github.com/MetaMask/metamask-extension/assets/4392888/35624925-e207-4456-be09-0565e706326d)

2023-07-12 07:31 UTC, NidhiKJha requested changes
The changes look really great. I have suggested some changes to use border color and size from design-system constants. Thanks for your contribution @jase-b

2023-07-12 07:31 UTC, NidhiKJha commented on ui/components/app/connected-sites-list/connected-sites-list.component.js
> +                src={subject.iconUrl}
```suggestion
              <AvatarFavicon
                borderColor={BorderColor.borderMuted}
                className="connected-sites-list__subject-icon"
                name={subject.name}
                size={Size.MD}
                src={subject.iconUrl}
```

2023-07-12 14:44 UTC, NidhiKJha approved these changes
LGTM! Thanks for your contribution

2023-07-12 17:41 UTC, vthomas13 approved these changes

2023-07-12 17:47 UTC, merged

2023-07-12 21:29 UTC, vthomas13 commented
Congrats @jase-b! Really appreciate the contribution 😁