Reset price ack if price diff in % changed, insufficient gas event, log a page load event once
MetaMask/metamask-extension pull request #19961
Opened 2023-07-11 11:58 UTC by dan437

## Explanation
This PR has the following things:
- Reset price acknowledgement if price diff in % changed
- Insufficient gas event (it will help us to understand how often users don't have enough for gas on different networks and if they continue with swapping afterwards)
- Log a page load event only once

### Testing
**Reset price ack if price diff in % changed**
- Select tokens for a swap that will trigger the price acknowledgement notification
- Confirm it
- When the price diff in % changes, you have to confirm it again

**Insufficient gas event**
- Select token from (ETH) and token to in Swaps
- If you have for example a 0.1 ETH balance, choose 0.099 ETH in the amount field
- You will see a blue notification about insufficient gas
- In the background dev tools in the Network tab you can see a new "Swap Error" event

**Log a page load event only once**
- Go to Swaps and see the "Prepare Swap Page Loaded" event in the background dev tools in the Network tab
- Click on the gear icon for Transaction Settings and opt-in / opt-out from Smart Swap, click on the Update button
- Verify that there is not another "Prepare Swap Page Loaded" event after clicking on the Update button

2023-07-24 14:09 UTC, brad-decker requested changes

2023-07-24 14:09 UTC, brad-decker commented on ui/pages/swaps/prepare-swap-page/review-quote.js
> +      ((isSmartTransaction && prevEthBalanceNeededStx) ||
prevEthBalanceNeededStx doesn't appear in this hook's dependencies.

2023-07-24 14:09 UTC, brad-decker commented on ui/pages/swaps/prepare-swap-page/review-quote.js
> +        ...eventObjectBase,
eventObjectBase should be in the hook dependencies

2023-07-24 14:09 UTC, brad-decker commented on ui/pages/swaps/prepare-swap-page/review-quote.js
> +      quotesLastFetched !== prevQuotesLastFetched
multiple things here are not listed in the hooks dependencies

2023-07-25 14:57 UTC, brad-decker submitted a review, later dismissed

2023-07-27 11:55 UTC, pedronfigueiredo submitted a review, later dismissed

2023-07-27 12:31 UTC, DDDDDanica approved these changes, later dismissed

2023-08-01 13:58 UTC, brad-decker approved these changes

2023-08-01 14:01 UTC, DDDDDanica approved these changes

2023-08-01 16:18 UTC, merged