ButtonIcon background & ButtonBase disabled update
MetaMask/metamask-extension pull request #19976
Opened 2023-07-12 15:30 UTC by garrettbear

## Explanation

* Fixes #19590 

- Made a temporary disabled css variable, but we should consider adding to design tokens
- Update ButtonBase disabled opacity from 0.3 to 0.5 (this will update ButtonPrimary, ButtonSecondary, and ButtonLink)
- Update ButtonIcon hover and active state to have a background color and replace disabled opacity 
- Added ButtonIcon size Medium 😬

## Screenshots/Screencaps

See comments below for screenshots

## Manual Testing Steps
`yarn jest ui/components/component-library`

## Pre-merge author checklist

- [X] I've clearly explained:
  - [X] What problem this PR is solving
  - [X] How this problem was solved
  - [X] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [X] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [X] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-07-12 16:01 UTC, georgewrmarshall commented on ui/components/component-library/component-library-components.scss
> +
Ooh, interesting. Should we set aside some time to compare Sass vars vs CSS vars? Another option is to create a stylesheet for opacity similar to z-index.css.

2023-07-12 17:54 UTC, georgewrmarshall commented on ui/components/component-library/component-library-components.scss
> +
That makes sense. I'll create a ticket to add opacity tokens

2023-07-12 22:31 UTC, georgewrmarshall requested changes
All these updates look great! Because there are still conversations happening with ButtonLink does it make sense to move those to a separate PR and get the rest in? Left one suggestion on a typo

2023-07-12 22:31 UTC, georgewrmarshall commented on ui/components/component-library/button-link/button-link.scss
>    }
Wondering if we move the underline update to another PR then we can get the rest of these updates in?

2023-07-12 22:31 UTC, georgewrmarshall commented on ui/components/component-library/button-link/button-link.stories.js
> +        Auto (default)g
```suggestion
        Auto (default)
```

2023-07-13 13:21 UTC, georgewrmarshall approved these changes

2023-07-13 20:03 UTC, brad-decker approved these changes

2023-07-13 20:22 UTC, merged