UX: Show Checksum Addresses in Account Menu
MetaMask/metamask-extension pull request #20135
Opened 2023-07-22 00:00 UTC by darkwing

## Explanation

@kumavis pointed out that the account menu wasn't using a checksum'd address, so the casing was different than the copy button on the home screen.  This PR fixes that issue.

## Screenshots/Screencaps

<img width="424" alt="SCR-20230721-qoou" src="https://github.com/MetaMask/metamask-extension/assets/46655/4b8b045e-f2d8-48be-b739-17c6233a2b8e">

## Manual Testing Steps

1.  On the home screen, in the CopyAddressButton, see some capital letters
2. Click the Accounts menu
3. See the same letters capitalized

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-07-24 08:18 UTC, NidhiKJha requested changes
Looks good to me. Since we are updating the checksum address in the AccountDetails Modal, I think we should update it here as well, since the Import Private key is in the same modal. 

![Screenshot 2023-07-24 at 1 46 53 PM](https://github.com/MetaMask/metamask-extension/assets/39872794/42e7d2fc-9af4-4a31-92b3-9dd81f76bd78)

2023-07-25 10:28 UTC, DDDDDanica approved these changes, later dismissed

2023-07-26 15:09 UTC, vthomas13 approved these changes

2023-07-26 15:18 UTC, NidhiKJha approved these changes

2023-07-26 19:37 UTC, merged