Replaced ActionableMessage Instances in edit-gas
MetaMask/metamask-extension pull request #20196
Opened 2023-07-26 07:53 UTC by pritam1813

## Explanation

- This PR is part of #19528 
- This PR replaces instances of `ActionableMessage` with `BannerAlert` in `ui/components/app/edit-gas-display/edit-gas-display.component.js`

## Screenshots/Screencaps

### Before

![Before](https://github.com/MetaMask/metamask-extension/assets/46365255/3cb955f5-5735-4956-bac3-81d5cd4f1953)
![Before2](https://github.com/MetaMask/metamask-extension/assets/46365255/17ce45cf-4507-4b52-9519-d3305db51e00)

### After
![After](https://github.com/MetaMask/metamask-extension/assets/46365255/28956c46-1393-4275-a248-bda61fe499a8)
![After2](https://github.com/MetaMask/metamask-extension/assets/46365255/8d35b851-511a-4577-b44b-939613e748d5)

## Manual Testing Steps

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-07-26 08:38 UTC, pritam1813 commented
Hi @georgewrmarshall , please review this.

2023-07-26 17:43 UTC, georgewrmarshall requested changes
Hey @pritam1813, this is looking good but I believe the after screenshots in the before/after section is not a good representation of the changes. It looks like the same screenshots. Could you please update the After section with the correct screenshots and also add some manual testing steps. Thanks

2023-07-27 07:07 UTC, pritam1813 commented
Hi @georgewrmarshall , Sorry , I thought that there isn't much visual difference in `BannerAlert` with `Severity` warning and `ActionableMessage` with type `Danger`, but,  actually it was due to the `className="actionable-message--warning"` which was interfering with the `BannerAlert` styling. I have changed the `className` to `"banner-alert--warning"`, I hope that's OK. 

 I have also changed the `ErrorMessage` element to `BannerAlert` `Severity='danger'`, which was displaying the insufficient balance error message.

2023-07-28 23:06 UTC, georgewrmarshall commented on ui/components/app/edit-gas-display/edit-gas-display.component.js
> -  }
Moved to line `70`

2023-07-28 23:07 UTC, georgewrmarshall commented on ui/components/app/edit-gas-display/edit-gas-display.component.js
> -          <div className="edit-gas-display__warning">
Can reduce nesting and utilize style utility props for margin styles

2023-07-28 23:07 UTC, georgewrmarshall commented on ui/components/app/edit-gas-display/index.scss
> -  }
No longer using the components that use these class names

2023-07-28 23:08 UTC, georgewrmarshall commented on ui/components/app/edit-gas-display/index.scss
> -  }
No longer using this classname
![Screenshot 2023-07-28 at 4 08 41 PM](https://github.com/MetaMask/metamask-extension/assets/8112138/bfd2f375-3bb2-4d91-858d-7ac93ffe7902)

2023-07-28 23:09 UTC, georgewrmarshall commented on ui/components/app/edit-gas-display/index.scss
> -  &__advanced-button {
No classname exists for these styles
![Screenshot 2023-07-28 at 3 54 46 PM](https://github.com/MetaMask/metamask-extension/assets/8112138/86eeb862-d216-4590-91cc-61c709d1aabe)

2023-07-28 23:09 UTC, georgewrmarshall commented on ui/components/app/edit-gas-display/index.scss
> -  &__education {
No className exists for these styles
![Screenshot 2023-07-28 at 3 54 21 PM](https://github.com/MetaMask/metamask-extension/assets/8112138/fe9cfd8e-5748-4e31-beae-23b60b69f4c8)

2023-07-28 23:10 UTC, georgewrmarshall commented on ui/components/app/edit-gas-display/index.scss
> -  &__warning {
Can be replaced with style utility props

2023-07-28 23:11 UTC, georgewrmarshall approved these changes
LGTM! While I was in your branch I removed some of the unused styles. I've updated the PR description with up to date screenshots. Thanks for you contribution @pritam1813

2023-08-01 21:21 UTC, garrettbear approved these changes

2023-08-01 21:21 UTC, merged