updated to newer Checkbox
MetaMask/metamask-extension pull request #20242
Opened 2023-07-27 19:31 UTC by akp111

## Explanation

As per the comments on this PR https://github.com/MetaMask/metamask-extension/pull/20198, addressing the issue https://github.com/MetaMask/metamask-extension/issues/20164, I have broken down the changes into smaller PR. This one addresses replacing the checkbox in `ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.js`
## Screenshots/Screencaps

### Before

### After

## Manual Testing Steps

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-07-27 23:34 UTC, georgewrmarshall requested changes
Thanks for your contribution @akp111, could you please add some before and after screencasts of the UI to show no visual regressions?

2023-08-01 13:21 UTC, akp111 commented
Hey @georgewrmarshall , I have added that. Also I have raised other PRs to replace the checkbox

2023-08-01 21:18 UTC, georgewrmarshall commented on ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-defaults/advanced-gas-fee-defaults.stories.js
> +DefaultStory.storyName = 'Default';
<img width="961" alt="Screenshot 2023-08-01 at 2 17 44 PM" src="https://github.com/MetaMask/metamask-extension/assets/8112138/2817228b-32e0-4bf6-9120-ceaecab0575f">

2023-08-01 21:25 UTC, georgewrmarshall submitted a review, later dismissed
LGTM! Thanks for your contribution @akp111. I push some small updates and a story for `AdvancedGasFeeDefaults` so we can easily update it in future


https://github.com/MetaMask/metamask-extension/assets/8112138/dfee4e11-fffd-427a-9364-bece15e069d5

2023-08-02 15:31 UTC, georgewrmarshall approved these changes

2023-08-02 18:02 UTC, garrettbear approved these changes

2023-08-03 19:22 UTC, merged