UX: Remove the 'Source' and 'Link' URLs from NFT detail
MetaMask/metamask-extension pull request #20248
Opened 2023-07-27 23:10 UTC by darkwing

## Explanation

Removes the `Source` and `Link` fields from NFT details.

## Screenshots/Screencaps

### After

<img width="751" alt="SCR-20230727-pwyi" src="https://github.com/MetaMask/metamask-extension/assets/46655/90ca3418-98fe-41ca-a29b-f59689f0ad1b">

## Manual Testing Steps

1.  Click into any NFT to get to the detail screen
2. See no "Link" or "Source" information

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-07-31 08:18 UTC, NidhiKJha requested changes
I think we should update the story file as well since `imageThumbnail` is used as a prop there

2023-08-03 17:33 UTC, NidhiKJha submitted a review, later dismissed

2023-08-04 10:28 UTC, NidhiKJha approved these changes

2023-08-04 16:39 UTC, pedronfigueiredo approved these changes

2023-08-04 18:28 UTC, merged