updated the checkbox to the newer version
MetaMask/metamask-extension pull request #20271
Opened 2023-07-28 19:36 UTC by akp111

## Explanation

As per the comments on this PR https://github.com/MetaMask/metamask-extension/pull/20198, addressing the issue https://github.com/MetaMask/metamask-extension/issues/20164, I have broken down the changes into smaller PR. This one implements the new checkbox in `ui/components/app/connected-accounts-permissions/connected-accounts-permissions.js`. 

* Fixes: https://github.com/MetaMask/metamask-extension/issues/20164

## Screenshots/Screencaps

### Before

### After

![image](https://github.com/MetaMask/metamask-extension/assets/38760485/6b58abbe-78be-4240-9f78-2cd6a4a597b1)

## Manual Testing Steps

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-07-28 19:38 UTC, akp111 commented
Also @georgewrmarshall , shall I create individual issues for each file that needs to be changed to the newer checkbox component?

2023-08-01 21:36 UTC, georgewrmarshall requested changes
Hey @akp111, this is looking close I've left a suggestion. Thanks for your contribution

2023-08-01 21:36 UTC, georgewrmarshall commented on ui/components/app/connected-accounts-permissions/connected-accounts-permissions.js
> +                isDisabled
Can you use the `label` prop on the Checkbox here? and remove the label? Also double check to see if you can remove the styles associated with `connected-accounts-permissions__checkbox` class

2023-08-04 17:22 UTC, georgewrmarshall commented
Hey @akp111, we would like to reduce the PR queue. Because this PR is missing some of the acceptance criteria I am going to close it for now. Please feel free to reopen it once you have addressed the comments. Thanks for your contribution!

2023-08-04 17:22 UTC, closed without merging