blockaid: add request failed UI
MetaMask/metamask-extension pull request #20362
Opened 2023-08-02 12:03 UTC by digiwand

## Explanation

Fixes: https://github.com/MetaMask/MetaMask-planning/issues/1056

Before these changes, we displayed the title and description based on the reason value.  

After, the title and description value may be determined by the result type being failed or the reason value. 

This is in draft mode because I'm advocating the the reason value to support a fixed failed value to remove the above mentioned complication in the logic and provide a consistent reason value format. See https://github.com/MetaMask/metamask-extension/pull/20125#discussion_r1281028676 

## Screenshots/Screencaps

### Before

Before, no alert was shown

### After

<img width="1054" alt="Screenshot 2023-08-02 at 1 58 35 PM" src="https://github.com/MetaMask/metamask-extension/assets/20778143/0e58d37d-b5ca-4761-88cf-8bf074c13da9">

## Manual Testing Steps

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-08-03 15:24 UTC, jpuri submitted a review, later dismissed

2023-08-03 16:05 UTC, segun requested changes
The screenshot doesn't quite align with what's in the figma.

2023-08-03 16:51 UTC, digiwand commented
@segun @jpuri updated https://github.com/MetaMask/metamask-extension/pull/20362/commits/814d4fb101571db79b4a76af946b07cfbc751bb7

2023-08-14 14:34 UTC, jpuri approved these changes

2023-08-14 15:47 UTC, segun approved these changes

2023-08-14 16:38 UTC, merged