Fixing Broken TokenAllowance Story
MetaMask/metamask-extension pull request #20422
Opened 2023-08-08 07:25 UTC by Jainex17

## Explanation

The `TokenAllowance` story was not being displayed in the Storybook. This PR resolves the issue and now it is shown in the Storybook.

### chnages made
- Renamed `token-allowance.stories-to-do.js` to `token-allowance.stories.js`.
- Fixed issues in `token-allowance.stories.js`.

* Fixes #17343 

## Screenshots/Screencaps
### Before
I don't have it because the story was not available due to it being broken
### After

https://github.com/MetaMask/metamask-extension/assets/81921291/b2e58c25-b61d-489a-9be7-f8b2b4c92b43

## Manual Testing Steps

- Pull this branch
- Run storybook
- Search `TokenAllowance`

## Pre-merge author checklist

- [x] I've clearly explained:
  - [x] What problem this PR is solving
  - [x] How this problem was solved
  - [x] How reviewers can test my changes
- [x] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

2023-08-15 13:11 UTC, Jainex17 commented
@NidhiKJha Could you please review this pr?

2023-08-17 11:39 UTC, NidhiKJha submitted a review, later dismissed
LGTM! Thanks for your contribution

2023-08-17 14:21 UTC, Jainex17 commented
@georgewrmarshall Could you please review this pr?

2023-08-18 23:05 UTC, georgewrmarshall submitted a review, later dismissed
LGTM! Thanks for your contribution @Jainex17

2023-08-28 23:14 UTC, georgewrmarshall commented
Still a few more selector updates that need to be made to get this to pass. Let me know if you need some assistance @Jainex17

2023-08-29 13:18 UTC, Jainex17 commented
> Still a few more selector updates that need to be made to get this to pass. Let me know if you need some assistance @Jainex17


Thanks, I'm still making an effort, but having some steps from you to resolve this build issue would be incredibly helpful.

2023-10-16 08:27 UTC, georgewrmarshall approved these changes, later dismissed
LGTM! Hey @Jainex17, to get this PR in I reverted the changes to the token allowance files and we can open another PR to swap out the deprecated components. Thanks for your contribution

2023-10-16 10:23 UTC, NidhiKJha submitted a review, later dismissed
LGTM

2023-10-16 12:19 UTC, georgewrmarshall commented on ui/pages/token-allowance/token-allowance.stories.js
> +  },
Hey @matthewwalsh0, do you have any ideas on how one could show the insufficient funds for gas error? I seem to be struggling with that

<img width="362" alt="Screenshot 2023-10-16 at 3 07 43 PM" src="https://github.com/MetaMask/metamask-extension/assets/8112138/782210f1-1893-4a90-8ad8-0dab58dd805c">

2023-10-16 19:10 UTC, kumavis commented
thank you for this!
the After video shows a bug suggesting some type error: "Spending cap request for your [Object object]"

2023-10-17 03:09 UTC, kumavis requested changes
thank you for this!
the After video shows a bug suggesting some type error: "Spending cap request for your [Object object]"

2023-10-18 12:39 UTC, georgewrmarshall commented
> I created a follow-up ticket for us to address here: #21405
Thanks @digiwand  🙏

2023-10-19 17:02 UTC, kumavis submitted a review, later dismissed

2023-10-26 19:49 UTC, georgewrmarshall approved these changes

2023-11-08 04:12 UTC, legobeat approved these changes

2023-11-14 13:34 UTC, Jainex17 commented
@georgewrmarshall Sorry for being inactive is there anything i can do in this PR Thanks

2024-01-23 23:10 UTC, merged