Feature - Reject all unapproved transactions button (MM Submission: feat. @davidp94)
MetaMask/metamask-extension pull request #2045
Opened 2017-09-07 22:24 UTC by Zanibas

Thanks to @davidp94 for submitting this PR! Made a small modification that uses a button to reject instead of an icon.

Needed to use another PR because the CI won't run on outside PRs.

![screenshot from 2017-09-07 15-23-21](https://user-images.githubusercontent.com/1840057/30187877-88cdf04c-93e0-11e7-9229-25aa212b9724.png)

2017-09-07 22:32 UTC, danfinlay requested changes
Two small change ideas, what do you think?

2017-09-07 22:32 UTC, flyswatter commented on ui/app/components/pending-tx.js
> +            margin: '14px 25px',
Maybe only show if there is more than one tx?

2017-09-07 22:32 UTC, flyswatter commented on CHANGELOG.md
> +- Added button to reject all transactions (thanks [davidp94](https://github.com/davidp94)!)
I prefer no markdown in changelogs, since it's used to generate text that we post on various mediums, that don't all support markdown.

2017-09-11 21:15 UTC, Zanibas commented
Addressed--anything else?

2017-09-11 21:31 UTC, danfinlay approved these changes

2017-09-11 21:32 UTC, merged

2017-09-11 21:32 UTC, flyswatter commented
Nope, good work!