Part of #20163 for file ui\components\app\terms-of-use-popup\terms-of-use-popup.js
MetaMask/metamask-extension pull request #20618
Opened 2023-08-26 16:41 UTC by PrgrmrHarshShukla

## Explanation
This PR is a part of the issue #20163 Replace deprecated CheckBox component with Checkbox from the component-library for file
`ui\components\app\terms-of-use-popup\terms-of-use-popup.js`

Also fixed a small typo in 
`ui\components\app\snaps\install-error\install-error.stories.js`

## Screenshots/Screencaps

### Before
![Screenshot 2023-08-25 075322](https://github.com/MetaMask/metamask-extension/assets/125105825/28a12454-86b1-492c-bd88-7f9634eeeee9)

### After

![Screenshot 2023-08-25 075410](https://github.com/MetaMask/metamask-extension/assets/125105825/91b583b6-1f1a-44cf-b71c-028061e667b4)

## Manual Testing Steps

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-08-26 16:59 UTC, PrgrmrHarshShukla commented
Hey @garrettbear and @georgewrmarshall ,

Kindly look at the positioning of the checkbox and label text.
There is some change in their positioning in the before and after UI.
I thought it would be better to ask if it should be made to follow the earlier positioning.

Also,
the label text was bold earlier.
I could not make out how to do so, please help me with some idea on how to do that, in case it is needed.

2023-08-26 17:02 UTC, PrgrmrHarshShukla commented
Also,
please let me know if I should move the typo problem to a new PR to keep things separate.
I thought it is a relatively small problem, so it might be okay to keep it here.

Regards,
Harsh

2023-08-28 22:41 UTC, georgewrmarshall reviewed
Hey @PrgrmrHarshShukla, these changes look good! Great call out on the visual regressions! This is an issue with the Checkbox component that can be addressed separately. There are some failing e2e tests that will need to be resolved for the PR to get merged. If you can kindly see to those that would be great!

2023-08-30 00:59 UTC, PrgrmrHarshShukla commented
Hey @georgewrmarshall ,
Both the e2e tests are failing because of the same reason.
The reason being `TimeoutError` while waiting for an element ( probably  `Checkbox` element, we can get a hint here `[data-testid=&#x22;terms-of-use-checkbox&#x22;]` below ) to be located by the CSS selector.

![Screenshot 2023-08-29 072550](https://github.com/MetaMask/metamask-extension/assets/125105825/b0066913-1d82-4530-92fc-6f79cccb54f2)

![Screenshot 2023-08-29 072622](https://github.com/MetaMask/metamask-extension/assets/125105825/fb219db5-3d0e-460e-8eb1-bf0ee7821e96)



## Also
while updating the snapshots for another PR #20535 , I encountered this,


![Screenshot 2023-08-29 072650](https://github.com/MetaMask/metamask-extension/assets/125105825/2f58efa2-fcf5-4ff9-bb83-27c26f6f88f1)


Probably, these are connected in some way.


## Possible Solution

Probably we can let the CSS selector grab the just higher level component of the `Checkbox`, 
that is, the **div** with `className="create-new-vault__terms"`.
![image](https://github.com/MetaMask/metamask-extension/assets/125105825/99eb74aa-7a0c-47af-8641-4febb5d96c52)

Also,
here the `Checkbox` is rendered conditionally and the condition `includeTerms` is initially false, this might be making it unavailable for the CSS selector to grab.


🙏🏼
@georgewrmarshall , please share your insights on this.

Regards,
Harsh

2023-09-26 13:42 UTC, georgewrmarshall requested changes
Left some suggestions

2023-09-26 13:42 UTC, georgewrmarshall commented on ui/components/app/terms-of-use-popup/terms-of-use-popup.js
>                dataTestId="terms-of-use-checkbox"
Update to
```suggestion
              data-testid="terms-of-use-checkbox"
```

2023-09-26 13:42 UTC, georgewrmarshall commented on ui/components/app/terms-of-use-popup/terms-of-use-popup.js
>                onClick={() => {
Update to
```suggestion
              onChange={() => {
```

2023-10-12 08:54 UTC, georgewrmarshall approved these changes
LGTM! Not sure why the e2e tests are failing here will try updating from develop

2023-11-15 10:32 UTC, PrgrmrHarshShukla commented
Hey @garrettbear ,
Your help is probably needed here.

2024-01-24 04:13 UTC, garrettbear approved these changes

2024-01-24 04:53 UTC, georgewrmarshall approved these changes

2024-01-24 05:01 UTC, georgewrmarshall approved these changes
LGTM ✅ 
- checked storybook

2024-01-24 09:08 UTC, FrederikBolding approved these changes

2024-01-24 14:04 UTC, merged