feat: CircleCI is now storing test builds and test-flask builds
MetaMask/metamask-extension pull request #20749
Opened 2023-09-06 05:16 UTC by HowardBraham

2023-09-06 21:21 UTC, plasmacorral commented
- [x] builds (test):[firefox](https://output.circle-artifacts.com/output/job/5ba094cc-d56d-4aac-a629-93b9a3e24bc7/artifacts/0/builds-test/metamask-firefox-11.0.0.zip)

Able to run individual e2e locally on Firefox v117 on Mac Ventura 13.5.1

Chrome is producing a version error:
```
Current browser version is 116.0.5845.140 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 114
```

Both links for `builds (test-flask):` do not initiate a download and instead render a page with `{"message":"not found"}`

2023-09-07 21:26 UTC, plasmacorral commented
Still getting this: 

Both links for builds (test-flask): do not initiate a download and instead render a page with {"message":"not found"} when trying to download test flask builds from https://github.com/MetaMask/metamask-extension/pull/20749#issuecomment-1709219126

2023-09-13 22:45 UTC, plasmacorral commented
Looks good, the missing builds are now present in the latest https://github.com/MetaMask/metamask-extension/pull/20749#issuecomment-1716966424

2023-09-19 15:36 UTC, brad-decker commented
@HowardBraham I think i'm not understanding the benefit/reason for storing the test builds? is it just to make them available for pulling for testing locally when the PR passes? Sorry if I'm being dense here.

2023-09-19 19:23 UTC, HowardBraham commented
> @HowardBraham I think i'm not understanding the benefit/reason for storing the test builds? is it just to make them available for pulling for testing locally when the PR passes? Sorry if I'm being dense here.

@brad-decker The benefit is to save a little time for QA and developers, when they have to write, modify, or debug local E2E tests.  The `builds-test` and the `builds-test-flask` can be downloaded from the PR instead of locally generated.  It also ensures that your local E2E is running the same code as the CircleCI E2E.

However, I think that extra fanciness I did with `save_cache` may no longer be necessary?  Because now `all-tests-pass` requires `test-e2e-chrome-snaps-flask` and `test-e2e-firefox-snaps-flask`

2023-09-25 18:57 UTC, brad-decker approved these changes

2023-09-25 20:38 UTC, plasmacorral requested changes
Lets update the PR description details to reflect the updated approach now that save_cache is no longer included.

2023-09-26 16:49 UTC, plasmacorral approved these changes

2023-09-26 17:42 UTC, merged