Feat/add mm e2e mmi build
MetaMask/metamask-extension pull request #20931
Opened 2023-09-18 13:53 UTC by racitores

## Explanation

This PR adds Metamask e2e tests run in the circle ci pipeline for a MMI build generated extension. There are a set failing tests marked as `@no-mmi` so that when running the tests with 

## Screenshots/Screencaps

### Before

### After

## Manual Testing Steps

## Pre-merge author checklist

- [ ] I've clearly explained:
  - [ ] What problem this PR is solving
  - [ ] How this problem was solved
  - [ ] How reviewers can test my changes
- [ ] Sufficient automated test coverage has been added

## Pre-merge reviewer checklist

- [ ] Manual testing (e.g. pull and build branch, run in browser, test code being changed)
- [ ] PR is linked to the appropriate GitHub issue
- [ ] **IF** this PR fixes a bug in the release milestone, add this PR to the release milestone

If further QA is required (e.g. new feature, complex testing steps, large refactor), add the `Extension QA Board` label.

In this case, a QA Engineer approval will be be required.

2023-09-19 11:42 UTC, zone-live submitted a review, later dismissed
💪🏼

2023-09-20 15:07 UTC, brad-decker requested changes
@PeterYinusa you should probably review this and see if we should include some way of documenting the `@no-mmi` flag in our E2E documents. Blocking for review but overall the code looks good for me.

2023-09-20 15:08 UTC, brad-decker commented on test/e2e/run-e2e-test.js
> +
Could you add inline documentation here for what these flags do (grep/invert) and explain the @no-mmi tag on some of the tests

2023-09-21 16:26 UTC, PeterYinusa commented
> @PeterYinusa you should probably review this and see if we should include some way of documenting the `@no-mmi` flag in our E2E documents. Blocking for review but overall the code looks good for me.

Thanks for the heads up @brad-decker, this seems in line with the approach discussed with @racitores.
It looks good to me, but I agree we should add some documentation around the usage of the tags to ensure contributors understand when to use them.

2023-09-21 16:27 UTC, PeterYinusa submitted a review, later dismissed
Looks great, please add documentation for contributors

2023-09-22 09:06 UTC, zone-live approved these changes

2023-09-22 09:39 UTC, PeterYinusa approved these changes
🚀

2023-09-22 14:30 UTC, brad-decker approved these changes

2023-09-22 15:01 UTC, merged