documenting network scenarios
MetaMask/metamask-extension pull request #21120
Opened 2023-09-29 14:05 UTC by benjisclowder

## **Description**
_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions:_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

Adding test scenarios for manual QA of the network flows.

## **Manual testing steps**

_1. Step1:_
_2. Step2:_
_3. ..._

## **Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change._

### **Before**

_[screenshot]_

### **After**

_[screenshot]_

## **Related issues**

_Fixes #???_

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained:
  - [ ] What problem this PR is solving.
  - [ ] How this problem was solved.
  - [ ] How reviewers can test my changes.
- [ ] I’ve indicated what issue this PR is linked to: Fixes #???
- [ ] I’ve included tests if applicable.
- [ ] I’ve documented any added code.
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-10-02 09:59 UTC, PeterYinusa submitted a review, later dismissed

2023-10-02 15:12 UTC, chloeYue requested changes

2023-10-02 15:12 UTC, chloeYue commented on test/scenarios/7. network/delete networks in Settings.csv
> +5,Select the network to delete.,e.g. Avalanche Mainnet.,"The network name, RPC URL, chain ID, currency symbol and block explorer URL are shown. The Delete button is shown. ",The Delete button is show
Please add a pre-condition to inform that a custom network should be added first, e.g. Avalanche Mainnet

2023-10-02 15:12 UTC, chloeYue commented on test/scenarios/7. network/update networks.csv
> +7,Save changes. ,,The request and status are shown in the Networks tab in the browser Developer Tools. ,
Please add a pre-condition to inform that a custom network should be added first, e.g. Arbitrum One  becase default network cannot be updated.

2023-10-02 16:39 UTC, benjisclowder commented on test/scenarios/7. network/add custom network manually.csv
> +6,Fill in the network details. ,e.g. Network name: Test; RPC URL: http://localhost:8545; Chain ID: 1337; Currency symbol: ETH,,
Changes committed.

2023-10-02 16:55 UTC, chloeYue approved these changes

2023-10-03 16:32 UTC, PeterYinusa approved these changes

2023-10-04 10:21 UTC, merged