require metamascara
MetaMask/metamask-extension pull request #2124
Opened 2017-09-19 02:09 UTC by frankiebee

WOOF! require mascara module

2017-09-21 17:46 UTC, kumavis requested changes

2017-09-21 17:46 UTC, kumavis commented on app/scripts/background.js
> +platform.context = 'extension'
lets put this in the platform class

2017-09-21 17:46 UTC, kumavis commented on app/scripts/background.js
> +platform.context = 'extension'
how about `isExtension: true` in the `ExtensionPlatform` class definition

2017-09-26 16:42 UTC, kumavis commented on app/scripts/metamask-controller.js
> -      originHttpHeaderKey: 'X-Metamask-Origin',
lets re-enable setting this flag

2017-09-26 16:43 UTC, frankiebee commented on app/scripts/metamask-controller.js
> -      originHttpHeaderKey: 'X-Metamask-Origin',
👍

2017-09-26 16:43 UTC, kumavis approved these changes
good to go after the `x-metamask-origin` is re-enabled

2017-09-27 23:27 UTC, merged