Migrated components to TS: FormTextField
MetaMask/metamask-extension pull request #21315
Opened 2023-10-11 05:43 UTC by subhajit20

## **Description**
Migrated components to TS: FormTextField
issue - #21311 

Screenshots
![Components _ ComponentLibrary _ FormTextField - Default ⋅ Storybook - Google Chrome 11-10-2023 11_10_07](https://github.com/MetaMask/metamask-extension/assets/99127578/d3d67d09-e37d-4919-b24f-54dc76108512)

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions:_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

## **Manual testing steps**

_1. Step1:_
_2. Step2:_
_3. ..._

## **Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change._

### **Before**

_[screenshot]_

### **After**

_[screenshot]_

## **Related issues**

_Fixes #???_

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained:
  - [ ] What problem this PR is solving.
  - [ ] How this problem was solved.
  - [ ] How reviewers can test my changes.
- [ ] I’ve indicated what issue this PR is linked to: Fixes #???
- [ ] I’ve included tests if applicable.
- [ ] I’ve documented any added code.
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-10-12 12:28 UTC, georgewrmarshall reviewed
Hey @subhajit20, this is a great start but I believe there is a dependency https://github.com/MetaMask/metamask-extension/issues/19127 there is a PR open for this issue and it's close but I don't think we can start this task until that one is complete

2023-10-13 14:38 UTC, brad-decker requested changes

2023-10-13 14:38 UTC, brad-decker commented on ui/components/component-library/form-text-field/form-text-field.tsx
> -import Box from '../../ui/box/box';
More should be being done in these files to convert to typescript, namely adding types for props and removing propTypes which are not necessary when the types are specified for the props

2023-10-25 19:52 UTC, georgewrmarshall commented
Hey @subhajit20, I'm going to close this until https://github.com/MetaMask/metamask-extension/issues/19127 has been merged. Feel free to open another PR once it has been

2023-10-25 19:52 UTC, closed without merging