Enable blockaid in main build
MetaMask/metamask-extension pull request #21352
Opened 2023-10-12 15:00 UTC by jpuri

## **Description**
_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions:_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

## **Manual testing steps**

_1. Step1:_
_2. Step2:_
_3. ..._

## **Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change._

### **Before**

_[screenshot]_

### **After**

_[screenshot]_

## **Related issues**

_Fixes #???_

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained:
  - [ ] What problem this PR is solving.
  - [ ] How this problem was solved.
  - [ ] How reviewers can test my changes.
- [ ] I’ve indicated what issue this PR is linked to: Fixes #???
- [ ] I’ve included tests if applicable.
- [ ] I’ve documented any added code.
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-10-12 15:18 UTC, jpuri commented
@metamaskbot update-policies

2023-10-16 16:02 UTC, segun approved these changes, later dismissed

2023-10-17 13:11 UTC, blackdevelopa approved these changes, later dismissed

2023-10-17 14:27 UTC, cryptotavares commented on package.json
> +    "test:e2e:single": "UPDATE_SNAPSHOTS=true node test/e2e/run-e2e-test.js",
Remove `UPDATE_SNAPSHOTS`. I don't think that we want to have it as a default when running an e2e test.

2023-10-17 14:43 UTC, brad-decker requested changes
Other then removing the update snapshot as default, this looks good from the privacy impact

2023-10-17 15:27 UTC, danjm approved these changes

2023-10-17 15:28 UTC, brad-decker approved these changes

2023-10-17 17:08 UTC, merged