fix/#20498
MetaMask/metamask-extension pull request #21383
Opened 2023-10-15 22:07 UTC by CodeWithUmair

## **Description**
This PR is fixes#20498 . Which is to Replace the old Menu Component with new Popover Component.

_1. What is the reason for the change?_
Ans: @deprecated The `<Menu />` component has been deprecated in favor of the new `<Popover>` component from the component-library.

_2. What is the improvement/solution?_
Ans: In this PR, I've changed just `GlobalMenu` component.

## **Manual testing steps**

_1. Step1:_
👉 Open `metamask` extension, Enter your Password to login

_2. Step2:_
👉 Click on `Three Dots` on the `Top Right` side of the header. to see the changes

## **Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change._

### **Before with `Menu Component`**

![Menu_Component](https://github.com/MetaMask/metamask-extension/assets/91899494/020f709f-b7c9-4e2c-94b0-4f80a79edfbd)

### **After with `Popover Component`**

![Popover_Component](https://github.com/MetaMask/metamask-extension/assets/91899494/80eb7c86-35c6-4c9f-b9e9-dd7275f3c544)

## **Related issues**

One Issue that I want to tell you is that, You have to close `Popover Component` to click on three dots again.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained:
  - [ ] What problem this PR is solving.
  - [ ] How this problem was solved.
  - [ ] How reviewers can test my changes.
- [ ] I’ve indicated what issue this PR is linked to: Fixes #???
- [ ] I’ve included tests if applicable.
- [ ] I’ve documented any added code.
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-10-15 22:14 UTC, CodeWithUmair commented
I have read the CLA Document and I hereby sign the CLA

2023-10-16 07:29 UTC, georgewrmarshall requested changes
Hey @CodeWithUmair, this is a good start. I've left some suggestions. We shouldn't change anything in `ui/components/component-library/popover` unless there is a limitation to the component. To change the styling we should do it at the implementation stage using the props available or as a last resort adding a custom class name.

2023-10-16 07:29 UTC, georgewrmarshall commented on ui/components/component-library/popover/popover.tsx
> +      isPortal = true,
Shouldn't make any updates to the defaults if you need to change this prop do it at the implementation stage in `ui/components/multichain/global-menu/global-menu.js`

2023-10-16 07:29 UTC, georgewrmarshall commented on ui/components/component-library/popover/popover.tsx
>          {hasArrow && (
Let's not make any changes to the component file. We should be able to make the necessary overrides in `ui/components/multichain/global-menu/global-menu.js`

2023-10-16 07:29 UTC, georgewrmarshall commented on ui/components/multichain/global-menu/global-menu.js
> +    <Popover referenceElement={anchorElement} isOpen={closeMenu}>
`isOpen` is a boolean type while `closeMenu` is a function type I think the equivalent prop is `onBlur` for the Popover component

```suggestion
    <Popover referenceElement={anchorElement} onBlur={closeMenu}>
```

2023-10-16 07:29 UTC, georgewrmarshall commented on ui/components/multichain/global-menu/global-menu.js
> +  anchorElement: PropTypes.instanceOf(window.Element),
Are there any changes here? It seems they are being changed around? Let's revert these changes if it's just changing the ordering as it makes it difficult to see if there have been any updates.

2023-10-16 07:30 UTC, georgewrmarshall commented
It also looks like you have some failing tests that will need to be resolved

2023-10-17 15:15 UTC, CodeWithUmair commented
@georgewrmarshall Sir Please review this.

And One thing is that:

![image](https://github.com/MetaMask/metamask-extension/assets/91899494/0e430547-dbeb-4aed-a349-aefcc9cac16c)

I have to use this `important` because any of other changes is not applying CSS in `Popover.tsx` Component

2023-10-18 12:49 UTC, georgewrmarshall requested changes
Looks like you might have had a bad merge here. There are many files that are being changed that shouldn't.  Would you be able to revert those changes?

2023-10-18 12:54 UTC, Ashok1927 commented
I don't like as a type of this "co-agent" mail??😢

I like only official email with  "official logo"😢😢

AshokDubey.

Thanks.
please do the needful.

On Wed, 18 Oct, 2023, 6:20 pm George Marshall, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Looks like you might have had a bad merge here. There are many files that
> are being changed that shouldn't. Would you be able to revert those changes?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MetaMask/metamask-extension/pull/21383#pullrequestreview-1684990700>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6EVGZPPVMI2HIAMIAMONBDX77GCXAVCNFSM6AAAAAA6BJJRLKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMOBUHE4TANZQGA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-10-19 03:58 UTC, closed without merging