UX Multichain: Show associate token symbols with account balances
MetaMask/metamask-extension pull request #21404
Opened 2023-10-17 12:11 UTC by NidhiKJha

## **Description**
This PR is to  display an account's token symbols up to four symbols, sorted from lowest to highest value, left to right.

## **Manual testing steps**

1. On AccountListItem, if user has only one token, it should show AvatarToken and Balance
2. When user has more than one token, Sort it by lowest to highest value, left to right up to 4 symbols.
3. User user has more than 4 tokens, Sort it by lowest to highest value, left to right up to 4 symbols and then indicate rest by "+[n]" with _n_ representing the token symbols number not displayed

## **Screenshots/Recordings**

### **Before**
![Screenshot 2023-10-17 at 5 40 24 PM](https://github.com/MetaMask/metamask-extension/assets/39872794/85371f8b-ee9f-4386-aea3-c1847889637c)

### **After**
![Screenshot 2023-10-17 at 5 39 51 PM](https://github.com/MetaMask/metamask-extension/assets/39872794/27e8d36b-e15d-4303-a11b-af7d9bed1ff9)

## **Related issues**

_Fixes [#1425](https://github.com/MetaMask/MetaMask-planning/issues/1425)

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained:
  - [x] What problem this PR is solving.
  - [x] How this problem was solved.
  - [x] How reviewers can test my changes.
- [x] I’ve indicated what issue this PR is linked to: Fixes #???
- [x] I’ve included tests if applicable.
- [x] I’ve documented any added code.
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-10-18 14:17 UTC, darkwing requested changes
I also wonder if we should put the sorting in a different hook, since it probably adds a perf hit.  For example, this hook is used on the home wallet screen, where we don't care about the tokens, so all of that sorting and image "work" would be excessive.

2023-10-18 14:17 UTC, darkwing commented
BTW, this feature is 🔥🔥🔥🔥🔥🔥

2023-10-23 08:15 UTC, NidhiKJha commented on ui/hooks/useAccountTotalFiatBalance.js
> +      if (matchingToken) {
I don't think so, since it's used to get the detectedTokens and we are using `getTokenList` to match with it.

2023-10-23 08:17 UTC, NidhiKJha commented on ui/hooks/useAccountTotalFiatBalance.js
> +  const sortedTokenList = allTokensWithFiatValues.sort(
Updated it to `orderedTokenList` https://github.com/MetaMask/metamask-extension/pull/21404/commits/b24951ca46d18c4ee98b317d66d8fd7a0c09b19f

2023-10-23 08:18 UTC, NidhiKJha commented on ui/hooks/useAccountTotalFiatBalance.js
> +    sortedTokenList,
Yup, it's updated in this test` ui/hooks/useAccountTotalFiatBalance.test.js`

2023-10-24 19:33 UTC, darkwing approved these changes

2023-10-25 13:53 UTC, DDDDDanica commented on ui/hooks/useAccountTotalFiatBalance.js
> +  const findMatchingTokens = (array1, array2) => {
Totally Optional: you can refactor for readability: 
```
const findMatchingTokens = (array1, array2) => {
  return array2
    .filter(token2 => array1.some(token1 => token1.symbol === token2.symbol))
    .map(token2 => {
      const matchingToken = array1.find(token1 => token1.symbol === token2.symbol);
      return {
        ...matchingToken,
        balance: token2.balance,
        string: token2.string,
        balanceError: token2.balanceError,
      };
    });
};
```

2023-10-25 14:02 UTC, vthomas13 approved these changes

2023-10-25 14:08 UTC, merged