e2e: with the newest version of Selenium, manually updating Geckodriver and Chromedriver is no longer necessary
MetaMask/metamask-extension pull request #21481
Opened 2023-10-21 10:22 UTC by HowardBraham

## **Description**

Yay!  We don't have to manually update Geckodriver and Chromedriver anymore, so they shouldn't get out of sync!
https://www.selenium.dev/blog/2023/whats-new-in-selenium-manager-with-selenium-4.11.0/

## **Manual testing steps**

`yarn`

then
```
yarn test:e2e:single <pick_a_testfile> --browser=firefox --debug
yarn test:e2e:single <pick_a_testfile> --browser=chrome --debug
```

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained:
  - [x] What problem this PR is solving.
  - [x] How this problem was solved.
  - [x] How reviewers can test my changes.
- [ ] I’ve indicated what issue this PR is linked to: Fixes #???
- [x] I’ve included tests if applicable.
- [x] I’ve documented any added code.
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-10-23 10:10 UTC, PeterYinusa approved these changes, later dismissed

2023-10-23 12:30 UTC, DDDDDanica submitted a review, later dismissed

2023-10-24 17:00 UTC, brad-decker requested changes
Curious if this has any security implications assuming selenium is downloading a version of chrome that coincides with our driver version?

2023-10-24 17:14 UTC, HowardBraham commented on package.json
> +    "start:test": "BLOCKAID_FILE_CDN=static.metafi-dev.codefi.network/api/v1/confirmations/ppom SEGMENT_HOST='https://api.segment.io' SEGMENT_WRITE_KEY='FAKE' SENTRY_DSN_DEV=https://fake@sentry.io/00
I was having trouble running local tests on this build without this, so I made it match the other `start` commands.  But do you think there's a problem?

2023-10-24 17:57 UTC, brad-decker commented on package.json
> +    "start:test": "BLOCKAID_FILE_CDN=static.metafi-dev.codefi.network/api/v1/confirmations/ppom SEGMENT_HOST='https://api.segment.io' SEGMENT_WRITE_KEY='FAKE' SENTRY_DSN_DEV=https://fake@sentry.io/00
usually those issues revolve around lavamoat policy not being updated, etc... I'm hesitant on removing here without confirmation from @PeterYinusa who i think uses this to get as close to our test build as possible which does include lavamoat.

2023-10-24 18:13 UTC, HowardBraham commented
Trying @metamaskbot update-policies

2023-10-24 18:14 UTC, HowardBraham commented
@metamaskbot update-policies

2023-10-24 23:04 UTC, HowardBraham commented
> Curious if this has any security implications assuming selenium is downloading a version of chrome that coincides with our driver version?

With this PR, Selenium is now downloading Chrome and Chromedriver, or Firefox and Geckodriver, on whatever version is considered "stable."

2023-10-25 09:58 UTC, PeterYinusa commented on package.json
> +    "start:test": "BLOCKAID_FILE_CDN=static.metafi-dev.codefi.network/api/v1/confirmations/ppom SEGMENT_HOST='https://api.segment.io' SEGMENT_WRITE_KEY='FAKE' SENTRY_DSN_DEV=https://fake@sentry.io/00
IMO it's OK for the `start:test` script to be similar to `start` as it is only used for local test development and execution. We're using `build:test` in the pipeline so it won't effect the runs there.

2023-10-26 11:42 UTC, pedronfigueiredo approved these changes, later dismissed

2023-10-26 18:10 UTC, brad-decker commented
@MetaMask/supply-chain could I get a review of security implications with having an automated download in our CI chain?

2023-10-27 04:19 UTC, HowardBraham commented
Had to solve the merge conflict after #21543, and it reset approvals

2023-11-01 22:42 UTC, brad-decker commented
A member of the team vouched for the maintainer of the tool that installs so i vote we move forward.

2023-11-01 22:42 UTC, brad-decker approved these changes

2023-11-02 20:51 UTC, danjm approved these changes

2023-11-02 20:53 UTC, merged