[Snaps] E2E test improvements
MetaMask/metamask-extension pull request #21706
Opened 2023-11-07 00:59 UTC by bowensanders

## **Description**

This makes some small changes to align all tests with new helper functions from a previous PR.

## **Related issues**

Fixes: #

## **Manual testing steps**

1. CI will pass if the tests work correctly.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-11-16 09:09 UTC, Mrtenz requested changes

2023-11-16 09:09 UTC, Mrtenz commented on test/e2e/snaps/test-snap-dialog.spec.js
> +        // assert.equal(await result.getText(), 'false');
```suggestion
```

2023-11-16 09:09 UTC, Mrtenz commented on test/e2e/snaps/test-snap-dialog.spec.js
> +        // await driver.delay(500);
```suggestion
```

2023-11-16 09:09 UTC, Mrtenz commented on test/e2e/snaps/test-snap-dialog.spec.js
> +        // assert.equal(await result.getText(), 'true');
```suggestion
```

2023-11-16 09:09 UTC, Mrtenz commented on test/e2e/snaps/test-snap-dialog.spec.js
> +        // assert.equal(await result.getText(), 'null');
```suggestion
```

2023-11-16 09:09 UTC, Mrtenz commented on test/e2e/snaps/test-snap-dialog.spec.js
> +        // assert.equal(await result.getText(), '"2323"');
```suggestion
```

2023-11-16 09:09 UTC, Mrtenz commented on test/e2e/snaps/test-snap-lifecycle.spec.js
> +        // );
```suggestion
```

2023-11-16 09:09 UTC, Mrtenz commented on test/e2e/snaps/test-snap-management.spec.js
> +        // assert.equal(await notificationResult.getText(), '1');
```suggestion
```

2023-11-16 09:09 UTC, Mrtenz commented on test/e2e/snaps/test-snap-management.spec.js
> +// const { strict: assert } = require('assert');
```suggestion
```

2023-11-17 11:09 UTC, FrederikBolding approved these changes

2023-11-17 11:50 UTC, Mrtenz approved these changes

2023-11-20 20:00 UTC, merged