Confirm header
MetaMask/metamask-extension pull request #22081
Opened 2023-11-29 12:45 UTC by jpuri

## **Description**

## **Related issues**

Fixes: #

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-12-06 09:27 UTC, segun submitted a review, later dismissed
Changes look good. Fix CI Failures.

2023-12-13 15:01 UTC, segun submitted a review, later dismissed

2023-12-15 02:00 UTC, digiwand requested changes
added suggestions to update styles, classnames, and tests. I also included an open-ended thought related to storybook controls

2023-12-15 14:28 UTC, jpuri commented on ui/components/app/confirm/header/header.scss
> +    margin-left: -12px;
Hey this is the small network icon on top of account icon, I think RTL will not effect this.

2023-12-15 14:30 UTC, jpuri commented on ui/components/app/confirm/header/header.tsx
> +      className="confirm_header-wrapper"
Updated.

2023-12-15 14:30 UTC, jpuri commented on ui/components/app/confirm/header/header.tsx
> +          className="confirm_header-avatar_network"
Updated.

2023-12-15 15:07 UTC, jpuri commented on ui/hooks/confirm/useConfirmationNetworkInfo.test.ts
> +});
👍 I added test cases

2023-12-15 15:34 UTC, jpuri commented on ui/hooks/confirm/syncConfirmPath.ts
> +        // url for all signature requests
This `if` condition is actually needed by TS also.

2023-12-15 22:53 UTC, digiwand submitted a review, later dismissed
updates look good 

[outstanding discussion](https://github.com/MetaMask/metamask-extension/pull/22081/files#r1427471966) is a non-blocker

2023-12-15 22:53 UTC, digiwand commented on ui/hooks/confirm/useConfirmationNetworkInfo.test.ts
> +  it('returns network display name when confirmation chainId is present', () => {
```suggestion
  it('returns display name and image when confirmation chainId is present', () => {
```

2023-12-15 22:53 UTC, digiwand commented on ui/hooks/confirm/useConfirmationNetworkInfo.test.ts
> +  it('returns network display name of provider chainId when confirmation chainId is not present', () => {
```suggestion
  it('returns display name and image of provider chainId when confirmation chainId is not present', () => {
```

2023-12-16 00:17 UTC, digiwand commented on ui/components/app/confirm/header/header.scss
> +}
```suggestion
}

```

<img width="1471" alt="Screenshot 2023-12-15 at 4 16 22 PM" src="https://github.com/MetaMask/metamask-extension/assets/20778143/dff7ab27-d595-4b56-b841-de4b5d77bf4b">

there's a lint error here. maybe this suggestion would fix it

2023-12-18 15:28 UTC, digiwand approved these changes

2023-12-19 09:28 UTC, segun approved these changes
PR looks good. Left a small nit.

2023-12-19 09:28 UTC, segun commented on ui/components/app/confirm/header/header.test.tsx
> +  it('should match snapshot', async () => {
```suggestion
  it('should match snapshot', () => {
```

2023-12-19 12:34 UTC, merged