Fix/password not present after tapping back
MetaMask/metamask-extension pull request #22867
Opened 2024-02-08 03:45 UTC by dawnseeker8

## **Description**

This PR fix the issue #20598 , 
The fix will make sure password authentication will popup every time user click "Show private key" in account detail screen in Metamask Extension. this behaviour will be same as Metamask mobile behaviour.

## **Related issues**

Fixes: #20598

## **Manual testing steps**

1. Setup a wallet and be at wallet view
2. Select accounts drop-down
3. Select kebab menu next to an HD account
4. Select "Account details"
5. Select "Show private key"
6. Provide correct password and select "confirm"
7. Click and hold to reveal private key
8. Select the back arrow and note that you are returned to "Account details"
9. Select "Show private key"
10. Password authentication popup should shown again to ask user input their password.
11. Provide correct password and select "confirm"
12. Click and hold to reveal private key

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-02-08 04:02 UTC, dawnseeker8 commented
I have read the CLA Document and I hereby sign the CLA

2024-02-08 04:09 UTC, dawnseeker8 commented on ui/components/app/modals/hold-to-reveal-modal/hold-to-reveal-modal.tsx
> -import { ModalContent } from '../../../component-library/modal-content/deprecated';
Remove two deprecated component and replace with new `ModalContent` and `ModalHeader`

2024-02-08 05:16 UTC, HowardBraham requested changes
The margins are not correct on the dialog that says "Keep your private key safe. Your Private Key provides full access to your wallet and funds."

Please look at the layout before this change and match it.

2024-02-08 16:37 UTC, dawnseeker8 commented on ui/components/app/modals/hold-to-reveal-modal/hold-to-reveal-modal.tsx
> -import { ModalContent } from '../../../component-library/modal-content/deprecated';
Due to styling issue, revert the code back to use `deprecated` component.

2024-02-08 16:57 UTC, dawnseeker8 commented
hi, @HowardBraham i have revert the code in `hold-to-reveal-modal.tsx`, and now styling is correct again. please review again when you have time, thank you very much!

2024-02-08 23:32 UTC, HowardBraham approved these changes
I re-implemented the new Design System components and fixed the margins

2024-02-15 18:41 UTC, owencraston approved these changes

2024-02-15 18:42 UTC, merged