Fix #7073 - Provide a QR to export private key
MetaMask/metamask-extension pull request #22885
Opened 2024-02-09 02:42 UTC by darkwing

## **Description**

It's been requested by many to provide a QR code to export private key in the "Show Private Key" flow.  This PR puts a QR code on the private key modal after the user has authenticated password and pressed-to-hold.

## **Related issues**

Fixes: #7073

## **Manual testing steps**

1. Click the three-dot global menu
2.  Click "Account Details"
3. Click "Show Private Key"
4. Enter correct password
5. Hold the button to reveal key
6. See the QR code above the text private key
7. Use a QR reader to read the value
8. Ensure the output matches the private key

## **Screenshots/Recordings**

### **Before**

N/A

### **After**

Not putting in the PR to not expose any data

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-02-09 02:43 UTC, darkwing commented
This PR could likely use security review and advisement

2024-02-15 15:16 UTC, vthomas13 approved these changes

2024-02-16 08:54 UTC, NidhiKJha approved these changes

2024-02-22 18:44 UTC, HowardBraham requested changes
It's not great that this adds a scrollbar and puts the Warning below the fold.

Can we maybe make this a button that shows the QR code?

2024-03-13 18:14 UTC, closed without merging