PPOM version update to fetch files only when transaction is received
MetaMask/metamask-extension pull request #23001
Opened 2024-02-16 14:20 UTC by jpuri

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-02-16 15:54 UTC, jpuri commented
@SocketSecurity ignore npm/@metamask/ppom-validator@0.25.0

2024-02-19 09:02 UTC, naugtur requested changes
blocking update to ppom-validator v0.25.0 
Feel free to override after we've had a conversation or if we've ran out of time.

2024-02-19 14:56 UTC, naugtur submitted a review, later dismissed

2024-02-19 14:58 UTC, naugtur commented
I'm gonna unblock this PR before I go offline (the only way to do it myself was to approve, sorry) but I would like to handle the privacy impact at least by surfacing to the user that something is being sent.

2024-02-21 10:17 UTC, seaona commented
hi there :wave: from QA I see the following behaviour, which I think it is expected:
- switching to a new network does not trigger any CDN request
- starting a transaction/signature triggers a `HEAD` request
  - if it's the 1st transaction/signature in that network (there is no data in the ppom-db for that net), the subsequent cdn requests are made to get the config, stale and stale_diff data
  - if it's not the 1st transaction in that network, and there are no updates, no subsequent cdn requests are made

https://github.com/MetaMask/metamask-extension/assets/54408225/da6380de-b887-4bb7-8fd2-5c9365ff6c31

https://github.com/MetaMask/metamask-extension/assets/54408225/b11d370f-c866-4182-98d6-657156e21575


@jpuri let me know if this sounds good too :pray:

2024-02-21 13:14 UTC, seaona commented
sounds good @jpuri I can do that and report back :+1:

2024-02-22 05:44 UTC, digiwand approved these changes, later dismissed

2024-02-22 08:38 UTC, blackdevelopa submitted a review, later dismissed

2024-02-22 09:58 UTC, jpuri commented
@metamaskbot update-policies

2024-02-22 09:59 UTC, jpuri commented
@SocketSecurity ignore npm/@metamask/ppom-validator@0.26.0

2024-02-22 10:17 UTC, jpuri commented
@metamaskbot update-policies

2024-02-22 10:41 UTC, segun commented on ui/pages/confirmations/components/confirm/info/info copy.tsx
Is this change supposed to be part of this PR?

2024-02-22 11:16 UTC, segun approved these changes, later dismissed

2024-02-22 11:24 UTC, blackdevelopa approved these changes, later dismissed

2024-02-22 13:05 UTC, segun approved these changes

2024-02-22 13:41 UTC, blackdevelopa approved these changes

2024-02-22 13:41 UTC, merged