[MMI] Hide buy / sell / nft buttons for mmi
MetaMask/metamask-extension pull request #23199
Opened 2024-02-27 12:24 UTC by albertolive

## **Description**

Context
We have in the extension for EOAs and Custodial accounts the Buy / Receive / NFT that should all be hidden

TODO
-Hide buy / receive / nft buttons

## **Related issues**

Fixes: https://consensyssoftware.atlassian.net/browse/MMI-4671

## **Manual testing steps**

1. Go to this page home screen
2. No Buy / Sell / NFT Tab is displayed

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've clearly explained what problem this PR is solving and how it is solved.
- [X] I've linked related issues
- [X] I've included manual testing steps
- [X] I've included screenshots/recordings if applicable
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [X] I’ve properly set the pull request status:
  - [X] In case it's not yet "ready for review", I've set it to "draft".
  - [X] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [X] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [X] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-02-27 12:27 UTC, DDDDDanica approved these changes, later dismissed

2024-02-27 16:00 UTC, zone-live requested changes
I don't think we want to remove the NFTs tab from MMI build. Just the "learn more" button inside it 🤔

2024-02-28 10:50 UTC, zone-live approved these changes, later dismissed

2024-02-28 11:55 UTC, zone-live submitted a review, later dismissed

2024-02-28 12:49 UTC, DDDDDanica submitted a review, later dismissed

2024-02-29 11:16 UTC, zone-live approved these changes

2024-02-29 12:46 UTC, NidhiKJha approved these changes

2024-02-29 12:55 UTC, merged