feat: Add ConnectedAccountsMenu Component
MetaMask/metamask-extension pull request #23228
Opened 2024-02-28 17:25 UTC by jonybur

## **Description**

Adds ConnectedAccountsMenu Component

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/23228?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/23197

## **Manual testing steps**

- Add the component somewhere in the DOM
- Check if it renders, as it has no functionality yet

## **Screenshots/Recordings**

<img width="480" alt="Screenshot 2024-02-28 at 01 37 36" src="https://github.com/MetaMask/metamask-extension/assets/11148144/b1d22120-c18e-4657-a2f4-37b88a709949">

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [X] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [X] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [X] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [X] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [X] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-02-28 17:42 UTC, darkwing submitted a review, later dismissed
Great work!  First one in, @jonybur ! :)

2024-02-28 17:45 UTC, vthomas13 approved these changes

2024-02-28 17:47 UTC, vthomas13 requested changes
Looks great, but we may need to run `yarn tsc` and see what's going on with the lint step

2024-02-29 09:38 UTC, NidhiKJha approved these changes
LGTM! Nice work @jonybur 🥳

2024-02-29 14:25 UTC, darkwing approved these changes

2024-02-29 15:02 UTC, vthomas13 approved these changes

2024-02-29 15:03 UTC, merged