feat: Implement ConnectedAccountsMenu buttons
MetaMask/metamask-extension pull request #23258
Opened 2024-03-01 04:00 UTC by jonybur

## **Description**

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

https://github.com/MetaMask/metamask-extension/assets/11148144/f6080ea3-df7f-42fc-9ac2-0638034ccf0b

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-03-04 13:52 UTC, NidhiKJha requested changes
Great work @jonybur Left some suggestions but overall looks great!
Can we add a condition to not show switch to this account option when there is only one account connected?
![Screenshot 2024-03-04 at 7 21 17 PM](https://github.com/MetaMask/metamask-extension/assets/39872794/d07240af-0d67-4c2e-bcdf-7ab827591523)

2024-03-04 13:52 UTC, NidhiKJha commented on ui/components/multichain/connected-accounts-menu/index.scss
> +@use "design-system";
Do we need this file?

2024-03-04 13:52 UTC, NidhiKJha commented on ui/components/multichain/connected-accounts-menu/connected-accounts-menu.tsx
> +interface Identity {
Let's keep types in a separate file

2024-03-04 13:52 UTC, NidhiKJha commented on ui/components/multichain/connected-accounts-menu/connected-accounts-menu.tsx
> +                  location: 'Main Menu',
So, metametrics are specific to component. I don't think we should use these here. We might create new one. Not a part of this ticket

2024-03-04 13:52 UTC, NidhiKJha commented on ui/components/multichain/connected-accounts-menu/connected-accounts-menu.tsx
> +              closeMenu();
Let's change it to this
```suggestion
              dispatch(setSelectedAccount(identity.address));
              onClose();
              closeMenu();
```

2024-03-04 14:08 UTC, jonybur commented on ui/components/multichain/connected-accounts-menu/connected-accounts-menu.tsx
> +interface Identity {
Done

2024-03-05 12:25 UTC, NidhiKJha requested changes
Almost there! Just some small nits

2024-03-05 12:25 UTC, NidhiKJha commented on ui/components/multichain/connected-accounts-menu/connected-accounts-menu.test.tsx
> +  it('renders switch to this account menu item if account switcher is enabled', async () => {
Really nice!

2024-03-05 12:25 UTC, NidhiKJha commented on ui/components/multichain/connected-accounts-menu/connected-accounts-menu.tsx
> +  disableAccountSwitcher,
By default this should be false?

2024-03-05 12:25 UTC, NidhiKJha commented on ui/components/multichain/account-list-item/account-list-item.js
> +          disableAccountSwitcher={accountsCount === 1}
Hmmm...Do you think we should create a separate variable for this?

2024-03-05 12:38 UTC, jonybur commented on ui/components/multichain/connected-accounts-menu/connected-accounts-menu.test.tsx
> +  it('renders switch to this account menu item if account switcher is enabled', async () => {
Thanks!

2024-03-05 13:59 UTC, NidhiKJha submitted a review, later dismissed
LGTM

2024-03-05 15:22 UTC, darkwing approved these changes, later dismissed

2024-03-07 00:26 UTC, darkwing approved these changes

2024-03-07 12:11 UTC, DDDDDanica approved these changes

2024-03-07 13:10 UTC, merged