test: add scenario for eth sign using hardware wallet
MetaMask/metamask-extension pull request #23313
Opened 2024-03-05 11:21 UTC by segun

## **Description**
In this PR we add the scenario for the flow: eth sign with hardware wallet.
This task belongs to the effort of documenting manual QA flows[ in this Epic](https://github.com/MetaMask/metamask-extension/issues/21962).

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes: #22026 

## **Manual testing steps**

1. Check the video below.

## **Screenshots/Recordings**
Performing the steps defined in the scenario

https://github.com/MetaMask/metamask-extension/assets/44811/a858aa5e-2bde-411c-bc4e-dd787efa778f

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-03-06 15:38 UTC, seaona requested changes
See comment

2024-03-12 14:58 UTC, blackdevelopa approved these changes, later dismissed
Looks good. The csv is formatted as expected

2024-03-13 14:37 UTC, jpuri approved these changes

2024-03-13 14:37 UTC, jpuri approved these changes, later dismissed

2024-03-14 15:07 UTC, seaona commented on test/scenarios/13. sign/eth sign with hardware wallet.csv
> +16,"Click Sign in the displayed modal Then the ""Your funds may be at risk"" modal is shown click Sign",,,The signature hash is displayed on the test dapp.,
I think here we don't expect yet that the 'Signature hash is displayed on the test dapp yet' but we do expect it in the next step 17

2024-03-14 15:08 UTC, seaona commented on test/scenarios/13. sign/eth sign with hardware wallet.csv
> +16,"Click Sign in the displayed modal Then the ""Your funds may be at risk"" modal is shown click Sign",,,The signature hash is displayed on the test dapp.,
the rest looks good to me!

2024-03-15 14:49 UTC, seaona approved these changes
LGTM

2024-03-16 05:01 UTC, sleepytanya approved these changes

2024-03-18 15:01 UTC, merged