test: add scenario for personal sign using hardware wallet
MetaMask/metamask-extension pull request #23314
Opened 2024-03-05 12:33 UTC by segun

## **Description**
In this PR we add the scenario for the flow: eth sign with hardware wallet.
This task belongs to the effort of documenting manual QA flows[ in this Epic](https://github.com/MetaMask/metamask-extension/issues/21962).

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes: #22027 

## **Manual testing steps**

1. Check the video below.

## **Screenshots/Recordings**
Performing the steps defined in the scenario

https://github.com/MetaMask/metamask-extension/assets/44811/ed18a2d7-7862-481f-aa7c-bb3d011fc440

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-03-06 15:38 UTC, seaona requested changes
See comment

2024-03-06 15:39 UTC, seaona commented
hey @segun the flow description looks good. I've seen that there is some csv formatting problem, since if I check the file, I don't see the table rendered.
See [here](https://github.com/MetaMask/metamask-extension/blob/d2770a63566f0f8bc9d783bcb6fec0658d13e86c/test/scenarios/13.%20sign/personal%20sign%20with%20hardware%20wallet.csv).


![Screenshot from 2024-03-06 16-38-03](https://github.com/MetaMask/metamask-extension/assets/54408225/a0f65ef0-0950-4de6-91e8-2797dc399564)

If you check another file, you will see the table rendered. Ie.

![Screenshot from 2024-03-06 16-35-02](https://github.com/MetaMask/metamask-extension/assets/54408225/6dc7c03a-8ee7-4c7e-8633-1e5cb0e1614d)

This is likely caused by some comma missing or extra

2024-03-12 16:46 UTC, blackdevelopa approved these changes

2024-03-14 15:36 UTC, seaona approved these changes
lgtm

2024-03-14 16:35 UTC, merged