wip: connections dapp badges
MetaMask/metamask-extension pull request #23397
Opened 2024-03-08 15:08 UTC by vthomas13

## **Description**

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-03-13 16:20 UTC, darkwing approved these changes, later dismissed

2024-03-14 16:35 UTC, NidhiKJha submitted a review, later dismissed

2024-03-18 16:04 UTC, darkwing approved these changes, later dismissed
This is awesome!

2024-03-19 17:41 UTC, NidhiKJha requested changes
Looks amazing. But can we add a test for this selector?

2024-03-19 17:41 UTC, NidhiKJha commented on ui/selectors/selectors.js
> +export const getConnectedSitesListWithNetworkInfo = createDeepEqualSelector(
Can we add a test for this selector?

2024-03-21 14:24 UTC, NidhiKJha approved these changes

2024-03-21 20:40 UTC, darkwing approved these changes
Well done!

2024-03-21 20:42 UTC, merged