chore: add words to Code Spell Checker
MetaMask/metamask-extension pull request #23405
Opened 2024-03-08 22:17 UTC by HowardBraham

## **Description**

Add a bunch of words to the Code Spell Checker dictionary, and also fix a few typos.

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Followup to: #23210 

## **Manual testing steps**
## **Screenshots/Recordings**
## **Pre-merge author checklist**
## **Pre-merge reviewer checklist**

2024-03-08 23:00 UTC, davidmurdoch requested changes

2024-03-13 21:53 UTC, davidmurdoch submitted a review, later dismissed

2024-03-17 17:31 UTC, hjetpoluru reviewed
Could you include the below words:-

**ignoreWords**
eamodio
azuretools
rvest
Brainstem
autofetch


**Words**
Predicition
devcontainers
Codespace
tsconfigs
tsbuildinfo
typecheck 
MULTICHAIN
MULTIPROVIDER

2024-03-18 13:01 UTC, davidmurdoch approved these changes, later dismissed

2024-03-18 14:59 UTC, hjetpoluru approved these changes, later dismissed

2024-03-26 21:14 UTC, brad-decker approved these changes

2024-03-26 21:14 UTC, brad-decker commented on shared/modules/Numeric.ts
> +   * @returns A fixed point decimal string representation of the Numeric
Ouch. lol. Might as well call this PR "Fix Brad's typos"

2024-03-26 23:46 UTC, hjetpoluru approved these changes

2024-03-26 23:47 UTC, merged