feat: Disable services with a Basic configuration toggle
MetaMask/metamask-extension pull request #23456
Opened 2024-03-13 12:39 UTC by jonybur

## **Description**

This PR adds a Basic configuration toggle that disables the following services:
- Token API: Automatic token detection (also on new netowork info component)
- Price API: Currency rate check
- Phishing List: Phish detect

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes: https://app.zenhub.com/workspaces/metamask-wallet-ux-63529dce65cbb100265a3842/issues/gh/metamask/metamask-planning/2077

## **Manual testing steps**

1. Go to Settings
2. Go to Security & privacy
3. Enable Basic Configuration
4. Check that 'Autodetect tokens', 'Show balance and token price checker', 'Use phishing detection' are all turned off
5. Check that when rendering new-network-info.js the component does not make any requests to `https://token-api.metaswap.codefi.network/tokens/`

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-03-21 05:18 UTC, MajorLift commented
Some caveats about `useTokenDetection`:
- Setting it to false doesn't stop polling. 
- Setting it to false does stop `detectTokens` from executing.
  - Exception: if mainnet is active, "ERC20 token auto detection will be triggered for each contract address in the legacy token list from the @metamask/contract-metadata repo."

Calling `tokenDetectionController.disable()` instead will both stop polling and completely prevent `detectTokens` from executing (including the behavior on mainnet).

To re-enable token detection, simply call `tokenDetectionController.enable()` or `tokenDetectionController.start()` (this will also initiate polling).

2024-03-22 16:52 UTC, darkwing requested changes
A few thoughts:

1.  Can we get more detail in this message?  Can we tell them what won't work?

<img width="957" alt="SCR-20240322-kmba" src="https://github.com/MetaMask/metamask-extension/assets/46655/4c33ecec-9cfe-4382-b89e-5fea2d98f04d">

2.  Can this be a `<label>`?  


<img width="445" alt="SCR-20240322-kmjl" src="https://github.com/MetaMask/metamask-extension/assets/46655/58bdb873-9364-4b2e-a677-b24dd6d7f0ed">

2024-03-28 16:42 UTC, mmragkandala commented
spotted a few issues with the test build:

**1. Wrong modal for Onboarding -> Advanced Config**
When a user toggles off basic functionality the The `turn on modal` is displayed when it should be the `turn off modal`
_Incorrect_
<img width="377" alt="Screenshot 2024-03-27 at 4 25 40 PM" src="https://github.com/MetaMask/metamask-extension/assets/152526076/001341e1-4ff9-4e27-a176-fc87d1986c20">

_Correct_
<img width="340" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/152526076/b9c0d679-fdc1-4e6b-916f-1aa6f94c9968">

**2. Button style for turn-off modal**
The `turn-off button` in the `turn-off modal` should use a primary-destructive (filled-red) rather than a secondary-destructive (outline-red) button style

_Incorrect_
<img width="382" alt="Screenshot 2024-03-27 at 4 27 58 PM" src="https://github.com/MetaMask/metamask-extension/assets/152526076/f90fe37f-94d6-499e-ac5b-6bcee781e7dc">

_Correct_
<img width="338" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/152526076/6a9967c9-272f-4fb7-8452-aa99cdfe0d70">


**3. Button style for turn-on modal**
The `turn-on button` in the `turn-on modal` should use a primary (filled-blue) rather than a secondary-destructive (outline-red) button style

_Incorrect_
<img width="403" alt="Screenshot 2024-03-27 at 4 27 28 PM" src="https://github.com/MetaMask/metamask-extension/assets/152526076/598bc59c-ce92-49b7-8aca-b3a82ce4da62">

_Correct_
<img width="340" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/152526076/f438a220-401f-4439-9877-3a4574dac92a">

**4. Button sizes for both modals**
It seems the test builds are using MD buttons (40px) whereas in the designs we are using a LG button (48px)

2024-03-29 01:46 UTC, darkwing requested changes
Looks awesome.  Holding for for a big UX win of making this a `<label>`; the user should never need to click on a checkbox:

<img width="490" alt="SCR-20240328-rzam" src="https://github.com/MetaMask/metamask-extension/assets/46655/8609eba8-066a-44ad-a45d-7a4f5e17aa40">
lly be label:

<img width="490" alt="SCR-20240328-rzam" src="https://github.com/MetaMask/metamask-extension/assets/46655/8609eba8-066a-44ad-a45d-7a4f5e17aa40">

2024-03-29 13:14 UTC, Gudahtt commented on app/scripts/controllers/preferences.js
> +      disableExternalServices: false,
Nit: Maybe better to call this something like `useExternalServices` or `enableExternalServices, to avoid the double-negative.

2024-04-08 19:04 UTC, darkwing commented
Can we make this a `<label>` for usability?

<img width="489" alt="SCR-20240408-mlut" src="https://github.com/MetaMask/metamask-extension/assets/46655/75a1db9b-e08d-4911-a4cb-f908fb02f58a">

If I turn of this setting during onboarding, should I still see these values?
<img width="967" alt="SCR-20240408-mmhy" src="https://github.com/MetaMask/metamask-extension/assets/46655/e0a49f7b-5e00-42d4-9e59-64daf429271e">

2024-04-09 22:01 UTC, vthomas13 commented on ui/pages/settings/advanced-tab/advanced-tab.container.js
> +    setDisableExternalServices: (value) => {
Hey, are the changes in this file needed? @jonybur

2024-04-11 15:52 UTC, hesterbruikman commented
Not blocked, but planned to merge after [#4094](https://github.com/MetaMask/core/pull/4094. This ensures gas estimation requests are made to the RPC provider rather than a gas estimation APIs.

2024-04-25 15:26 UTC, darkwing submitted a review, later dismissed
Approving with the caveat that we there should be a very fast follow up PR with an E2E

2024-04-26 11:48 UTC, DDDDDanica commented on ui/components/app/basic-configuration-modal/basic-configuration-modal.tsx
> +      isOpen={true}
Nit: can be refactored as 
```suggestion
      isOpen
```

2024-04-26 11:49 UTC, DDDDDanica commented on ui/components/app/basic-configuration-modal/basic-configuration-modal.tsx
> +              }}
```suggestion
              onClick={closeModal}
```

2024-04-26 11:49 UTC, DDDDDanica commented on ui/components/app/basic-configuration-modal/basic-configuration-modal.tsx
> +                }}
```suggestion
                onClick={setHasAgreed((prevValue) => !prevValue}
```

2024-04-26 11:50 UTC, DDDDDanica commented on ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
>      // toggle to false
💯 for the comments here, much clear !

2024-04-26 11:50 UTC, DDDDDanica commented on ui/pages/onboarding-flow/privacy-settings/privacy-settings.test.js
> +    fireEvent.click(toggles[0]); // toggleExternalServicesStub
💯 for the comments here, much clear !

2024-04-26 11:51 UTC, DDDDDanica commented on ui/pages/settings/security-tab/security-tab.component.js
> +              if (useExternalServices === true) {
```suggestion
              if (useExternalServices) {
```

2024-04-26 11:54 UTC, DDDDDanica commented
Hey @jonybur can you add e2e test for this functionality? thank you !

2024-04-26 11:54 UTC, DDDDDanica commented
Hey @jonybur thanks for the work, i noticed that this PR has been around for a while, feel free go merge it. 
You can leave the comments to next PR :)

2024-05-03 13:24 UTC, darkwing approved these changes

2024-05-03 13:45 UTC, DDDDDanica commented on ui/components/app/basic-configuration-modal/basic-configuration-modal.tsx
> +  const onboardingFlow = pathname === ONBOARDING_PRIVACY_SETTINGS_ROUTE;
You can use `useMemo` to cache the value
```suggestion
  const onboardingFlow = useMemo(
    () => return pathname === ONBOARDING_PRIVACY_SETTINGS_ROUTE,
    [pathname]
  );;
  
```

Documentation [here](https://react.dev/reference/react/useMemo)

2024-05-03 13:45 UTC, DDDDDanica commented on ui/components/app/basic-configuration-modal/basic-configuration-modal.tsx
> +                    : dispatch(toggleExternalServices(true));
```suggestion
dispatch(toggleExternalServices(!isExternalServicesEnabled))
```

2024-05-03 13:46 UTC, DDDDDanica commented on ui/store/actions.ts
> +export function toggleExternalServices(
Can you add a simple unit test here?

2024-05-03 13:53 UTC, DDDDDanica approved these changes

2024-05-03 19:32 UTC, merged