feat: disconnect all modal flow
MetaMask/metamask-extension pull request #23488
Opened 2024-03-14 13:49 UTC by NidhiKJha

This PR is to integrate disconnect all modal flow
## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-03-15 13:49 UTC, darkwing reviewed
Can we add a test here to ensure that:

1.  `removePermissionsFor` is called an appropriate amount of times
2. The list goes to empty and the empty content is shown

2024-03-18 16:21 UTC, darkwing requested changes
Manual testing worked great!  Just could use a few Jest tests.

2024-03-19 17:35 UTC, darkwing approved these changes
Nice!

2024-03-19 17:43 UTC, vthomas13 approved these changes

2024-03-20 06:05 UTC, merged