refactor(preferences-controller): remove redundant syncIdentities calls
MetaMask/metamask-extension pull request #23620
Opened 2024-03-21 08:37 UTC by mikesposito

## **Description**

This PR removes unnecessary calls to `PreferencesController.syncIdentitites`, as syncing identities is now a PreferencesController internal responsibility.

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-03-21 11:53 UTC, mikesposito commented
@metamaskbot update-policies

2024-03-26 11:56 UTC, mikesposito commented
@metamaskbot update-policies

2024-03-26 17:55 UTC, Gudahtt commented on app/scripts/metamask-controller.js
So the main risk of regression here is probably from keyring interactions that change state without the `KeyringController` being informed. In those cases, we need to tell the `KeyringController` that state has changed (probably easiest to do this by manually calling `keyringController.persistAllKeyrings`).

I've audited the places where I can see keyrings being called directly, but I couldn't find any keyring writes that are unaccompanied by a `KeyringController` call that would trigger a state change. Hopefully we are good here.

2024-03-26 17:55 UTC, Gudahtt approved these changes, later dismissed
LGTM!

2024-03-26 18:03 UTC, mikesposito commented on app/scripts/metamask-controller.js
I think that the PreferencesController was always manually updated with accounts coming from KeyringController
e.g.
```typescript
const newAccounts = await this.keyringController.getAccounts();
this.preferencesController.setAddresses(newAccounts);
```

So as the accounts always came from the KeyringController state, we should assume that it was already changed - thus the PreferencesController should capture the event anyway

2024-03-26 18:08 UTC, Stam098c commented
@refactor/remove-preferences-controller-calls

2024-03-26 18:15 UTC, mikesposito commented on app/scripts/metamask-controller.js
I am still not 100% sure about the account selection though. 
Some direct calls to set the selected account on PreferencesController and AccountsController have been removed, and based on e2e and manual tests it looks like the behavior didn't change - but I feel less confident here

2024-03-26 18:42 UTC, mikesposito commented on app/scripts/metamask-controller.js
Uhm, actually `KeyringController.getAccounts` directly calls each keyring's `getAccounts`, so a direct interaction with a keyring would result in a new account event without calling `persistAllKeyrings`, so as you said there's a risk of regression especially for hardware keyrings, that are the use case for `persistAllKeyrings` and are not covered by e2e

2024-03-28 00:22 UTC, Gudahtt commented on app/scripts/metamask-controller.js
Hmm, `getAccounts` would still never result in accounts being added or removed though. I could only find examples of read-only methods being called.

2024-03-28 08:50 UTC, mikesposito commented on app/scripts/metamask-controller.js
Yes, `getAccounts` itself is a read-only operation, but what I wanted to say is that given a scenario like this:
1. Create a new account _directly on a keyring_, like with `KeyringController.getKeyringByType` and then `Keyring.addAccounts`
2. I forget to call `persistAllKeyrings`

In this scenario, if I inspect the KeyringController state I would not find the new account (since persistAllKeyrings was not called), but instead calling `KeyringController.getAccounts` would return the new account created above, since this function calls the single Keyrings directly to list their account instead of taking them from the state.

So from the perspective of the PreferencesController, being updated from the KeyringController state and being updated from `KeyringController.getAccounts` is not the same thing

2024-03-28 15:15 UTC, Gudahtt commented on app/scripts/metamask-controller.js
We just talked about this in our sync meeting; I had been on the same page about the details here but had misunderstood the main point being made, which is that this change would prevent the `PreferencesController` from being synchronized in cases where the `KeyringController` state was stale/invalid.

IMO this is a benefit, because if the `KeyringController` state is invalid/stale, then things are already broken because some parts of the application refer to that state directly. And this would call more attention to that bug.

2024-04-08 15:02 UTC, mikesposito commented
@metamaskbot update-policies

2024-04-09 11:14 UTC, kanthesha requested changes

2024-04-15 10:49 UTC, mikesposito commented
✅ Manually tested these steps with **Trezor One**, **Ledger Nano X**, **Keystone 3 Pro**:
* Connect account
* Sign typed data v4
* Remove account

2024-04-15 11:18 UTC, mikesposito commented on app/scripts/controllers/preferences.js
> +    }
That's a good point! applied in [8a5fac9](https://github.com/MetaMask/metamask-extension/pull/23620/commits/8a5fac9c79fc222f7dfe7eeab9fffb5c35d745bc)

2024-04-23 22:42 UTC, mcmire commented
@kanthesha It looks like your suggestion was made, do you want to release your request for changes and/or approve this PR if it all looks good to you?

2024-04-23 22:45 UTC, mcmire submitted a review, later dismissed
One nit, but looks good to me regardless.

2024-04-23 22:45 UTC, mcmire commented on app/scripts/metamask-controller.js
>      // Ensure preferences + identities controller know about all addresses
Nit: Do we need to update this comment? Or even better, nix it (because the code describes what we are doing already)

``` suggestion
```

2024-04-25 12:36 UTC, Gudahtt submitted a review, later dismissed
LGTM!

2024-05-01 22:31 UTC, Gudahtt commented
Looks like there is a new conflict to resolve

2024-05-07 08:15 UTC, mikesposito commented
@metamaskbot update-policies

2024-05-07 11:13 UTC, kanthesha approved these changes
LGTM.

2024-05-07 11:34 UTC, legobeat approved these changes

2024-05-07 11:37 UTC, merged