feat: add IoTeX logo and update config
MetaMask/metamask-extension pull request #23744
Opened 2024-03-26 19:55 UTC by nicky-ru

## **Description**

This pull request introduces the addition of the IoTeX mainnet logo to the MetaMask extension and updates the necessary configuration files to support this change.

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. **Open and connect:** Begin by navigating to the Chainlist website. Use the following link to directly access the search results for IoTeX: https://chainlist.org/?search=iotex. Upon arrival, connect your MetaMask extension to the site.
2. **Add network:** In the search results, locate 'IoTeX Mainnet'. Next to it, you'll find a button to 'Add to Metamask'. Click this button to initiate the process of adding the IoTeX Mainnet network to your MetaMask.
3. **Verify Logo Presence:** After successfully adding the network, open your MetaMask extension and switch to the IoTeX Mainnet. You should now observe the IoTeX logo accompanying the network's name, indicating successful integration.

## **Screenshots/Recordings**

### **Before**

<img width="346" alt="Screenshot 2024-03-26 at 10 49 03 PM" src="https://github.com/MetaMask/metamask-extension/assets/64008830/540bead8-26b2-4502-a4d2-8585607dc354">

### **After**

<img width="362" alt="Screenshot 2024-03-26 at 10 32 16 PM" src="https://github.com/MetaMask/metamask-extension/assets/64008830/7abb5ef6-9f04-4d48-9e0b-42abfc1318d7">

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-03-26 19:58 UTC, nicky-ru commented
I have read the CLA Document and I hereby sign the CLA

2024-08-20 01:20 UTC, gambinish approved these changes, later dismissed

2024-08-21 22:16 UTC, vinnyhoward approved these changes, later dismissed

2024-08-21 22:17 UTC, vinnyhoward commented
I've approved but just a heads up the token image is still missing but the network image is fine
![Screenshot 2024-08-21 at 4 17 38 PM](https://github.com/user-attachments/assets/1f1f253d-6579-44da-8d6d-13e415a15ba6)

2024-08-22 18:44 UTC, nicky-ru commented
@gambinish @vinnyhoward thanks for the catch! just pushed an update with the token img:

<img width="350" alt="Screenshot 2024-08-23 at 2 38 58 AM" src="https://github.com/user-attachments/assets/a81cf6c0-15e4-46fc-931b-63a6456984fc">

2024-08-22 22:36 UTC, gambinish submitted a review, later dismissed

2024-08-22 22:41 UTC, vinnyhoward approved these changes

2024-08-22 22:42 UTC, vinnyhoward commented
LGTM😄

2024-08-22 22:48 UTC, vinnyhoward requested changes

2024-08-22 22:48 UTC, vinnyhoward commented on app/images/iotex.svg
Can we actually get an icon with a background? Upon closer inspection of your screenshot the network icon without the background looks a little funky

2024-08-22 22:55 UTC, gambinish commented on app/images/iotex.svg
Agreed. @nicky-ru it might make sense to use the same image (black background) for both the token and network images. Unless the images are significantly different, the same image is fine.

2024-08-22 22:55 UTC, gambinish commented on app/images/iotex.svg
Will make it look more clear on light mode as well.

2024-08-22 23:21 UTC, gambinish commented on app/images/iotex.svg
Once you make this change I will get this merged in 👍

2024-08-23 19:31 UTC, nicky-ru commented on app/images/iotex.svg
Thanks for feedback! Indeed, the light version was not looking too great.

We left the token image as it is, but since the token image has bigger padding, the logo looks too small if applied as a network image. We've decided to keep both images but added dark bg to the network image, think it should work now:

<img width="358" alt="Screenshot 2024-08-23 at 10 18 04 PM" src="https://github.com/user-attachments/assets/0ba3254c-51f7-4937-8a07-19373caa267b">
<img width="358" alt="Screenshot 2024-08-23 at 10 17 59 PM" src="https://github.com/user-attachments/assets/cc1487d1-8fab-4599-bdca-a2c4a71ec123">
<img width="358" alt="Screenshot 2024-08-23 at 10 17 34 PM" src="https://github.com/user-attachments/assets/cba47488-35fb-4db7-a2e3-e317f10af19f">
<img width="358" alt="Screenshot 2024-08-23 at 10 17 30 PM" src="https://github.com/user-attachments/assets/45ed42f6-3871-4123-8f49-557b1e3d04a4">

2024-08-23 22:04 UTC, gambinish approved these changes

2024-08-23 22:05 UTC, vinnyhoward approved these changes

2024-08-23 22:06 UTC, vinnyhoward commented on app/images/iotex.svg
LGTM! Thank you for the screenshots for light and dark as well

2024-08-28 15:39 UTC, gambinish commented
Not sure why SonarCloud is failing. Going to open a PR separately with these same changes. I expect it has something to do with the timing of this PR.

Here is the other one: https://github.com/MetaMask/metamask-extension/pull/26723

2024-08-28 15:39 UTC, closed without merging