ci: update amannn/action-semantic-pull-request to v5.4.0
MetaMask/metamask-extension pull request #23819
Opened 2024-04-01 18:31 UTC by davidmurdoch

## **Description**

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-02 12:33 UTC, Mrtenz requested changes
This workflow is not on the allowlist: https://github.com/MetaMask/metamask-extension/actions/runs/8512078157

2024-04-02 15:16 UTC, brad-decker approved these changes

2024-04-03 20:38 UTC, davidmurdoch commented
> This workflow is not on the allowlist: https://github.com/MetaMask/metamask-extension/actions/runs/8512078157

Where does this allow list live?

2024-04-16 21:05 UTC, Mrtenz approved these changes

2024-04-16 21:11 UTC, merged