Updated the script to generate commits in the release
MetaMask/metamask-extension pull request #23914
Opened 2024-04-09 15:56 UTC by hjetpoluru

## **Description**

This PR is to updated the existing script to generate commits in the release. I enhanced author attribution list, tagged labels with release version, and filtered out specific commit message like 'Changelog' or 'Merge pull request' or 'master-sync' .

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

Provide your github token in the development/generate-rc-commits.js
Provide the below command in the terminal and the cvs file is generated
node development/generate-rc-commits.js origin/v11.14.0 origin/v11.13.0

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-10 09:03 UTC, pedronfigueiredo commented on development/generate-rc-commits.js
> +    'Pedro Figueiredo',
Confirmations UX

2024-04-12 09:43 UTC, pedronfigueiredo approved these changes, later dismissed

2024-04-18 16:07 UTC, benjisclowder approved these changes
Tested locally and got this csv file: 
![image](https://github.com/MetaMask/metamask-extension/assets/120041701/f862a620-cad9-47f4-9e5e-facaac49f50b)


Git command line in manual steps should be: node development/generate-rc-commits.js origin/Version-v11.15.0 origin/Version-v11.14.0.

2024-04-18 16:08 UTC, benjisclowder requested changes
Tested locally and got this csv file: 
![image](https://github.com/MetaMask/metamask-extension/assets/120041701/f862a620-cad9-47f4-9e5e-facaac49f50b)


Git command line in manual steps should be: node development/generate-rc-commits.js origin/Version-v11.15.0 origin/Version-v11.14.0

2024-04-18 18:08 UTC, benjisclowder approved these changes
LGTM.

2024-04-19 12:56 UTC, chloeYue approved these changes
LGTM !

2024-04-19 15:11 UTC, merged