Add migration for stuck transactions
MetaMask/metamask-extension pull request #24027
Opened 2024-04-15 11:45 UTC by OGPoyraz

## **Description**

This PR aims to add a migration which sets transaction to `failed` status if they are created before 8 December 2023 (release date of `TransactionController` migration) and they are still `approved` or `signed` status. 

The reason of this migration added is that some users had these transactions in their MM state and [after recent changes](https://github.com/MetaMask/metamask-extension/pull/22676) in the confirmation page, the transactions are blocking users to approve subsequent transactions. 

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/23361

## **Manual testing steps**

N/A

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-17 19:54 UTC, dbrans requested changes

2024-04-17 19:54 UTC, dbrans commented on app/scripts/migrations/115.ts
> + * This migration updates the status of transactions that were approved or signed before December 8, 2023 to failed.
I think your PR description says it better. Something like:
```suggestion
 * This migration sets the `status` to `failed` for all transactions created before December 8, 2023 that are still `approved` or `signed`.
```

2024-04-17 19:54 UTC, dbrans commented on app/scripts/migrations/115.ts
> +  );
Using the Object.fromEntries/Object.entries pattern could make this more succinct. Also, note that you don't need to clone the transactions as the cloning is handled in `migrate` above. 

```typescript
const STUCK_STATES = [TransactionStatus.approved, TransactionStatus.signed];
```

```suggestion
  const newTxs = Object.fromEntries(
    Object.entries(transactions).map(([id, tx]) => {
      if (
        tx.time < TARGET_DATE &&
        STUCK_STATES.includes(tx.status)
      ) {
        tx.status = TransactionStatus.failed;
      }
      return [id, tx];
    })
  );
```

2024-04-17 20:10 UTC, dbrans requested changes

2024-04-18 07:48 UTC, matthewwalsh0 commented on app/scripts/migrations/115.ts
> +const STUCK_STATES = [TransactionStatus.approved, TransactionStatus.signed];
Minor, but should we define this at the top so all the constants are together?

2024-04-18 07:48 UTC, matthewwalsh0 commented on app/scripts/migrations/115.ts
> +  const transactions = state?.TransactionController?.transactions ?? {};
Should the fallback be `[]` since `transactions` is now an array following the migration?

2024-04-18 07:48 UTC, matthewwalsh0 commented on app/scripts/migrations/115.ts
> +  for (const tx of Object.values(transactions)) {
No need for `Object.values` since `transactions` should be an array.

2024-04-18 07:48 UTC, matthewwalsh0 commented on app/scripts/migrations/115.ts
> +      tx.status = TransactionStatus.failed;
Should we also set `error` to a suitable `TransactionError` object for the sake of clarity and future debug?

2024-04-18 07:48 UTC, matthewwalsh0 commented on app/scripts/migrations/115.ts
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
Why is this needed if the below is a standard array of statuses?

2024-04-18 07:48 UTC, matthewwalsh0 commented on app/scripts/migrations/115.test.ts
> +const TRANSACTIONS_MOCK = {
Will need to be an array also.

2024-04-23 07:52 UTC, matthewwalsh0 approved these changes

2024-04-23 11:29 UTC, dbrans approved these changes
Nice work!

2024-04-23 11:31 UTC, merged