feat: Removed product tour from home page
MetaMask/metamask-extension pull request #24051
Opened 2024-04-16 12:24 UTC by NidhiKJha

This PR is to remove product tour from home page

## **Related issues**

Fixes: 

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-16 16:02 UTC, darkwing commented
Doesn't this require some cleanup within global state?

2024-04-16 16:05 UTC, jonybur approved these changes

2024-04-16 16:06 UTC, jonybur commented
Getting: `Too long with no output (exceeded 10m0s): context deadline exceeded` on the CI, other than that all good

2024-04-16 16:08 UTC, jonybur requested changes

2024-04-16 16:08 UTC, jonybur commented on ui/components/multichain/app-header/app-header.js
> -  getShowProductTour,
Please remove from global store as it is not used anymore

2024-04-16 16:17 UTC, NidhiKJha commented
@darkwing @jonybur I am thinking to do the global state update in a separate PR since it will need a migration as well. With this one merged, we could remove the product tour from the new Multichain build. Or should I do the migration in this PR?

2024-04-17 01:18 UTC, jonybur commented
@NidhiKJha What sort of migration would be necessary?

2024-04-18 10:41 UTC, jonybur approved these changes

2024-04-18 11:34 UTC, sahar-fehri approved these changes

2024-04-18 11:44 UTC, merged