fix: Fix tooltip distance
MetaMask/metamask-extension pull request #24098
Opened 2024-04-18 02:21 UTC by jonybur

## **Description**

The permissions tooltip is not displaying correctly within the connect accounts modal. Additionally there should be a 4px spacing between the tooltip info icon and the permissions text label.

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/23859

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

<img width="355" alt="Screenshot 2024-04-18 at 03 21 07" src="https://github.com/MetaMask/metamask-extension/assets/11148144/11f93d28-074c-4885-ab36-e4347dd0c892">

### **After**

<img width="374" alt="Screenshot 2024-04-18 at 03 13 02" src="https://github.com/MetaMask/metamask-extension/assets/11148144/9007d51d-a39d-4b31-9133-9b14d648993b">

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-18 09:29 UTC, NidhiKJha requested changes
Good start! Position prop fix the tooltip positioning issue and we don't need the distance prop. 
![Screenshot 2024-04-18 at 2 58 12 PM](https://github.com/MetaMask/metamask-extension/assets/39872794/69eca98d-6ab1-4dad-9f15-0672bbeed799)

2024-04-18 09:29 UTC, NidhiKJha commented on ui/components/multichain/connect-accounts-modal/connect-accounts-modal-list.tsx
> +                distance={75}
Why do we need this property?

2024-04-18 18:20 UTC, jonybur commented
@NidhiKJha 

With the marginInlineEnd attribute:

<img width="361" alt="Screenshot 2024-04-18 at 19 01 48" src="https://github.com/MetaMask/metamask-extension/assets/11148144/95dc168c-0bad-4ac7-9475-14c8a83e837e">

With the distance attribute:

<img width="351" alt="Screenshot 2024-04-18 at 19 17 16" src="https://github.com/MetaMask/metamask-extension/assets/11148144/9a9c96fd-352d-4642-a681-15fd0664d8c4">

The distance attribute, according to React Tippy, is `how far in pixels the tippy element is from the reference element.`

2024-04-19 08:02 UTC, NidhiKJha commented
> Fix distance, marginInlineEnd

@jonybur Marginline is fine. But I still don't think we need distance here.` position="top"` prop is handling the position of tooltip

2024-04-19 10:46 UTC, jonybur commented
@NidhiKJha It is handling the position but not the distance to the icon. The bug shows a desired positioning where the tooltip is further away from the icon than what we currently render.

This is the desired design:

<img width="356" alt="Screenshot 2024-04-19 at 11 45 42" src="https://github.com/MetaMask/metamask-extension/assets/11148144/863aeaae-2efe-44a9-8f5e-c942ef0b9799">

Without the `distance` attribute, the tooltip renders too close to the (i) icon

2024-04-19 12:38 UTC, NidhiKJha approved these changes

2024-04-19 14:30 UTC, EtherWizard33 commented
not sure about the positioning on the left of the tooltip in the 'After' picture above, https://github.com/MetaMask/metamask-extension/pull/24098#:~:text=Before-,After,-Pre%2Dmerge%20author

seems like its hugging the left side, not sure if thats intended already talked about it with Jony

2024-04-20 00:28 UTC, darkwing approved these changes

2024-04-22 10:35 UTC, merged