feat: set useRequestQueue on by default
MetaMask/metamask-extension pull request #24274
Opened 2024-04-29 07:15 UTC by NidhiKJha

This PR is to ensure that `useRequestQueue` is set to `true` by default. After setting it to true, it turn the setting on for all users while keeping the toggle, since this is a state update. This PR also includes a migration.

## **Related issues**

Fixes: #23985 

## **Manual testing steps**

1. Go to settings > Experimental
2. Check `Select networks for each site` toggle is on
3. Toggle should work properly

## **Screenshots/Recordings**

### **Before**

![Screenshot 2024-04-29 at 12 43 31 PM](https://github.com/MetaMask/metamask-extension/assets/39872794/6bdc6f49-6f20-44f1-a063-f9edd1dba09b)

### **After**

![Screenshot 2024-04-29 at 12 43 03 PM](https://github.com/MetaMask/metamask-extension/assets/39872794/19fce2fa-d0cb-43b8-8731-7b64c6d33975)

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-29 12:54 UTC, jonybur requested changes

2024-05-01 17:28 UTC, adonesky1 commented
`MetaMask provider should inform dapp when switching networks` is failing because the expected behavior its testing has actually changed: we should no longer expect for the network of the dapp not to change when you change the network in network switcher in full screen

2024-05-03 17:27 UTC, adonesky1 commented
[This PR](https://github.com/MetaMask/metamask-extension/pull/24371) should resolve at least one of the test failures on this PR: `Test Snap RPC can use the cross-snap RPC endowment and produce a public key`

2024-05-06 19:24 UTC, salimtb submitted a review, later dismissed

2024-05-07 20:09 UTC, darkwing approved these changes

2024-05-07 20:16 UTC, jonybur approved these changes

2024-05-07 21:10 UTC, adonesky1 commented on test/e2e/tests/dapp-interactions/provider-api.spec.js
> -  it('provider should inform dapp when switching networks', async function () {
I suppose we could add this back with the step to toggle off the setting, like we did with the `wallet_switchEthereumChain` e2e test

2024-05-07 21:10 UTC, adonesky1 commented on test/e2e/json-rpc/switchEthereumChain.spec.js
>        async ({ driver }) => {
we should possibly add either a comment or some note in the description about how this toggles off the per dapp selected network setting

2024-05-08 04:27 UTC, merged