test: [Snaps E2E Test] Create test for snaps UI images
MetaMask/metamask-extension pull request #24298
Opened 2024-04-29 21:11 UTC by bowensanders

## **Description**
This test covers images in the snaps UI.

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Manually execute the E2E test or check CI for completion

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-29 21:12 UTC, bowensanders commented
Note: This test avoids changing the privacy snapshot by omitting the "Show Cat" test as it's not an approved data source.

2024-04-30 07:52 UTC, Mrtenz requested changes

2024-04-30 07:52 UTC, Mrtenz commented on test/e2e/snaps/test-snap-ui-imgs.spec.js
> +  it('can pop up bip-44 snap and get private key result', async function () {
This needs to be updated.

2024-04-30 17:01 UTC, bowensanders commented on test/e2e/snaps/test-snap-ui-imgs.spec.js
> +  it('can pop up bip-44 snap and get private key result', async function () {
fixed in latest commit

2024-04-30 21:37 UTC, Mrtenz approved these changes

2024-05-01 08:56 UTC, FrederikBolding approved these changes

2024-05-01 09:25 UTC, merged