Fix 1
MetaMask/metamask-extension pull request #24319
Opened 2024-04-30 20:51 UTC by darkwing

## **Description**

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-30 21:05 UTC, Gudahtt approved these changes, later dismissed
LGTM!

2024-04-30 21:05 UTC, Gudahtt commented on ui/pages/confirmations/components/confirm-page-container/confirm-page-container.component.js
> +                ? showEdit
We should follow up in a later PR to simplify this logic a bit (I think we can inline the remaining useful parts of `showEdit` here). There might be more dead code to remove as well.

2024-04-30 21:05 UTC, Gudahtt commented on ui/pages/confirmations/components/confirm-page-container/confirm-page-container.component.js
> +                ? showEdit
We should also follow up with e2e test coverage for any impacted types of transactions we can think of

2024-04-30 21:16 UTC, Gudahtt commented on ui/pages/confirmations/components/confirm-page-container/confirm-page-container.component.js
> +              currentTransaction.type === TransactionType.simpleSend
If we wanted to continue allowing token transfer edits:
```suggestion
              [TransactionType.simpleSend, TransactionType.tokenMethodTransfer].includes(currentTransaction.type)
```

2024-04-30 21:57 UTC, cryptotavares submitted a review, later dismissed

2024-05-01 01:38 UTC, danjm approved these changes

2024-05-01 12:29 UTC, Gudahtt approved these changes

2024-05-01 12:31 UTC, Gudahtt requested changes

2024-05-01 12:31 UTC, Gudahtt commented on ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js
> -            onEdit={async ({ txData }) => {
Actually wait, it looks like this component assumes that `onEdit` is always passed in

2024-05-01 12:34 UTC, Gudahtt commented on ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js
> -            onEdit={async ({ txData }) => {
Following the trail here: this is a non-required prop, passed into `confirm-token-transaction-base`. That component passes it to `confirm-transaction-base` (passed through the container untouched, to the component module).

It's called here: https://github.com/MetaMask/metamask-extension/blob/4b543cd1fc843547e10096a3591f28036aa303b9/ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js#L617

We try to call this in `handleEdit` without checking that it's defined.

2024-05-01 12:34 UTC, Gudahtt commented on ui/pages/confirmations/confirm-transaction/confirm-token-transaction-switch.js
> -            onEdit={async ({ txData }) => {
Oh but wait, we also set `showEdit` to `false` when `onEdit` is false, here: https://github.com/MetaMask/metamask-extension/blob/4b543cd1fc843547e10096a3591f28036aa303b9/ui/pages/confirmations/confirm-transaction-base/confirm-transaction-base.component.js#L1099

Super confusing how this is setup, but never mind, this should work as-is.

2024-05-01 12:34 UTC, Gudahtt approved these changes

2024-05-01 13:15 UTC, jpuri approved these changes

2024-05-01 13:22 UTC, merged