Bump metamask/gas-fee-controller to v15.1.1
MetaMask/metamask-extension pull request #24333
Opened 2024-05-01 18:08 UTC by danjm

## **Description**

This PR bumps the gas-fee-controller to the latest version.

The changes between the previous version and the latest are:

### [15.1.1]

*Changed**

- Bump `@metamask/polling-controller` to `^6.0.2` ([#4234](https://github.com/MetaMask/core/pull/4234))

**Removed**

- Remove fee history fallback in favour of `eth_gasPrice` call ([#4210](https://github.com/MetaMask/core/pull/4210))

### [15.1.0]

**Added**

- Add nonRPCGasFeeApisDisabled property to the gas fee controller, allowing the user to specify that they want to prevent network request to gas estimate services, and only want gas estimates to be based on rpc requests (eth_feeHistory and eth_gasPrice) to the provider. ([#4094](https://github.com/MetaMask/core.git/pull/4094))

**Fixed**

- Fix GasFeeController incorrectly setting globally selected state, so that state is only updated if the gasFeeEstimate fetched is for the currently selected network ([#4214](https://github.com/MetaMask/core.git/pull/4214))

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Part of: https://github.com/MetaMask/MetaMask-planning/issues/2070

## **Manual testing steps**

This is mostly not testable right now. I will add testing steps after some functionality has been added to another PR. Same goes for automated tests. Some things that can be tested:
- Gas related functionality should continue to work unchanged
- Go to the confirmation screen for any transaction on any EIP-1559 network. If developer tools in the background are opened to the network tab, and calls to the [/suggestedGasFees](https://gas.api.cx.metamask.io/networks/1/suggestedGasFees) api are disabled, then you should see requests to a json rpc api with the method `eth_gasPrice`

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-05-01 18:11 UTC, jiexi approved these changes, later dismissed

2024-05-01 18:24 UTC, legobeat commented
@metamaskbot update-policies

2024-05-01 18:24 UTC, vthomas13 approved these changes, later dismissed

2024-05-01 18:29 UTC, legobeat commented on yarn.lock
> +"@metamask/polling-controller@npm:^6.0.2":
Also, this needs `yarn deduplicate` to dedupe with existing `@metamask/polling-controller@6.0.1`.

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/78538/workflows/68a63caf-d89e-4bf1-b1c0-ef1ad9665cc9/jobs/2738624

2024-05-02 00:47 UTC, legobeat requested changes
Needs a `yarn deduplicate`.

https://github.com/MetaMask/metamask-extension/pull/24333/files#r1586616380

2024-05-03 06:50 UTC, legobeat commented
I guess this is waiting for https://github.com/MetaMask/core/pull/4245 and a release of v15.1.2?

2024-05-21 08:20 UTC, danjm commented
this was replaced by https://github.com/MetaMask/metamask-extension/pull/24520

2024-05-21 08:20 UTC, closed without merging