feat(1753): update trezor logo
MetaMask/metamask-extension pull request #24343
Opened 2024-05-02 10:58 UTC by Akaryatrh

## **Description**

Update Trezor logo to its latest version.

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Partly Fixes: https://github.com/MetaMask/mobile-planning/issues/1753

## **Manual testing steps**

1. Open account dropdown and click on "add account or hardware wallet" button.
2.  Click on add hardware wallet button
3. Check that Trezor logo is updated on hardware wallet selection page

## **Screenshots/Recordings**
### **Before**
<img width="617" alt="Capture d’écran 2024-05-02 à 12 39 50" src="https://github.com/MetaMask/metamask-extension/assets/574787/68fa2226-dbd8-4700-a81e-404dcf58536c">

### **After**
<img width="676" alt="Capture d’écran 2024-05-02 à 12 38 17" src="https://github.com/MetaMask/metamask-extension/assets/574787/8e82e89c-8597-438f-bdeb-d46bdc9afbe6">

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-05-02 11:12 UTC, legobeat requested changes
Needs update of unit test.

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/78625/workflows/5ee7663a-2229-4b75-96d4-cf0e84450bd6/jobs/2743117

2024-05-06 10:25 UTC, legobeat approved these changes

2024-05-06 10:27 UTC, legobeat commented
Somehow GitHub wouldn't dismiss my request for changes (which is resolved) without approving. I haven't actually tested with the logo.

2024-05-28 08:12 UTC, salimtb approved these changes

2024-05-28 11:21 UTC, merged