feat: replace deprecated chip component with tag in recovery-phrase-c…
MetaMask/metamask-extension pull request #24594
Opened 2024-05-18 04:19 UTC by nickpismenkov

…hips component

## **Description**

Replaced deprecated chip component with tag in recovery-phrase-chips component

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes: #20487

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-05-22 00:04 UTC, georgewrmarshall commented
Hey @nickpismenkov, could you please make sure the PR description is complete and includes the manual testing steps for the reviewers? Thanks!

2024-05-22 02:30 UTC, nickpismenkov commented
@georgewrmarshall Hi. I completed description. Could you please help with e2e failed tests?

2024-05-24 22:02 UTC, georgewrmarshall commented on ui/pages/onboarding-flow/recovery-phrase/recovery-phrase-chips.js
> -import Typography from '../../../components/ui/typography';
Deprecated components

2024-05-24 22:03 UTC, georgewrmarshall commented on ui/pages/onboarding-flow/recovery-phrase/recovery-phrase-chips.js
> +  Display,
Replacing deprecated helpers

2024-05-24 22:04 UTC, georgewrmarshall commented on ui/pages/onboarding-flow/recovery-phrase/recovery-phrase-chips.stories.js
> +export const PhraseRevealed = Template.bind({});
Adding a Storybook story for easier isolated development

https://github.com/MetaMask/metamask-extension/assets/8112138/6aad55ed-02bf-4ab9-b829-804429fec421

2024-05-25 21:05 UTC, georgewrmarshall commented on ui/pages/onboarding-flow/recovery-phrase/index.scss
> -
Removing unused styles and moving some to https://github.com/MetaMask/metamask-extension/pull/24594/files#diff-58ef2d79c613500bbe5a15545874fbeb5a4d07a22d3796a9e9a1d9463a592347

2024-05-25 21:05 UTC, georgewrmarshall commented on ui/pages/onboarding-flow/recovery-phrase/recovery-phrase-chips.test.js
> +      'recovery-phrase-chips__chips--hidden',
Updating classnames to reflect whats in javascript

2024-05-25 21:08 UTC, georgewrmarshall requested changes
Hey @nickpismenkov,

I did some more digging, and I think this task is a bit more complex than I initially thought. I've refactored it to align with our design system standards. 

I've created a couple of other PRs that will need to be merged before this one:
- https://github.com/MetaMask/metamask-extension/pull/24781
- https://github.com/MetaMask/metamask-extension/pull/24780

Once the above PRs are merged, we can rebase and re-test. Thanks for your contribution and patience.

Blocking until above PRs have been merged

2024-08-07 22:04 UTC, closed without merging