Add custom network modal form
MetaMask/metamask-extension pull request #25213
Opened 2024-06-11 11:59 UTC by salimtb

## **Description**
 the custom add network form flow is now available on the modal

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Run `yarn && ENABLE_NETWORK_UI_REDESIGN=1 yarn start`
2. Go to Settings -> Developer Options
3. Tun on the network new toggle
4. Go to the wallet page
5. Click on the network button ( see the video below )
6. you should see the list of popular network
7.click on add network ( you should see the network form )

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-06-11 16:26 UTC, bergeron approved these changes, later dismissed
worked locally, was able to add a new network from the modal

2024-06-11 22:13 UTC, darkwing commented on ui/components/app/modals/modal.js
> +    contents: <AddNetworkModal isNewNetworkFlow={false} />,
Awesome, awesome catch!  I hadn't thought of this flow!

Could we provide a better prop name than `isNewNetworkFlow`?  At first glance I don't understand what it represents.

2024-06-14 00:23 UTC, darkwing commented on ui/pages/onboarding-flow/add-network-modal/index.js
> +export default function AddNetworkModal({ isNewNetworkFlow = false }) {
The `defaultProps` at the bottom sets this value to `true`.  Which should it be?

2024-06-14 15:22 UTC, bergeron approved these changes, later dismissed

2024-06-18 12:57 UTC, darkwing requested changes
One nit and one question!  Almost perfect!

2024-06-18 13:49 UTC, salimtb commented on ui/components/app/modals/modal.js
> +    contents: <AddNetworkModal newNetworkMenuDesignActive={false} />,
we don't need to use it here , nice found i just fixed it

2024-06-18 15:15 UTC, bergeron submitted a review, later dismissed

2024-06-18 17:35 UTC, darkwing approved these changes, later dismissed

2024-06-18 17:49 UTC, bergeron submitted a review, later dismissed

2024-06-18 18:00 UTC, bergeron submitted a review, later dismissed

2024-06-18 18:00 UTC, darkwing submitted a review, later dismissed

2024-06-18 20:00 UTC, bergeron approved these changes

2024-06-18 21:09 UTC, darkwing approved these changes

2024-06-18 21:09 UTC, merged