ci: Adding node-linux-medium executor
MetaMask/metamask-extension pull request #25476
Opened 2024-06-21 18:16 UTC by vthomas13

## **Description**
This PR implements a suggestion from @davidmurdoch to use linux machine image to reduce CI costs on the build steps in our pipeline. Starting with the build steps, we want to optimize for cost for any tests that can support a linux executor.

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/25476?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/25229

## **Manual testing steps**

1. Check CI

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-06-21 21:38 UTC, davidmurdoch submitted a review, later dismissed
🚀  We'll need to follow up on this PR in a week or so to measure credit usage to be sure we are saving $$$$$s

2024-06-21 22:21 UTC, DDDDDanica approved these changes, later dismissed

2024-06-21 22:37 UTC, hjetpoluru submitted a review, later dismissed
LGTM

2024-06-21 23:48 UTC, HowardBraham requested changes
This **_should_** reduce credits per workflow, since Linux VM medium costs 10 credits per minute, and Docker Medium+ costs 15 credits per minute.  As long as we don't somehow expand our minutes by 50%.
https://circleci.com/product/features/resource-classes/

There are a few more jobs that I noticed can use `node-linux-medium`:
- prep-build
- prep-build-mv2
- prep-build-mmi
- prep-build-flask
- prep-build-flask-mv2
- prep-build-test-mmi-playwright

2024-06-21 23:48 UTC, HowardBraham commented on .circleci/config.yml
> +      image: ubuntu-2204:2024.04.4
We're in an Ubuntu LTS transition period.  I think we might as well go with the next version, which is
`ubuntu-2404:2024.05.1`

2024-06-24 14:51 UTC, HowardBraham approved these changes

2024-06-24 16:03 UTC, davidmurdoch approved these changes

2024-06-24 16:21 UTC, Gudahtt commented on .circleci/config.yml
> +      NODE_OPTIONS: --max_old_space_size=6144
Curious that we're allowing for a larger heap here than on `medium+`. I guess there should be adequate room though, as long as we're not running multiple Node.js processes in one job.

2024-06-24 16:22 UTC, Gudahtt approved these changes
LGTM!

2024-06-24 17:14 UTC, merged