fix: add ellipsis for permit fiat values
MetaMask/metamask-extension pull request #26001
Opened 2024-07-22 12:36 UTC by OGPoyraz

## **Description**

This PR goal is to add ellipsis to the fiat value if it's more than 15 character in permit simulations.

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/MetaMask-planning/issues/2842

## **Manual testing steps**

1. Go to cowswap
2. Swap a token with gas-free approve for another token
3. Notice the permit signature screen

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-07-22 13:34 UTC, vinistevam submitted a review, later dismissed

2024-07-22 13:37 UTC, vinistevam commented
Great PR @OGPoyraz ! Just a small lint error (jsdocs) failing the pipeline.

2024-07-22 14:18 UTC, jpuri approved these changes, later dismissed

2024-07-22 22:03 UTC, matthewwalsh0 requested changes

2024-07-22 22:03 UTC, matthewwalsh0 commented on ui/hooks/useFiatFormatter.ts
> +export const useFiatFormatter = (shortenFiatValue?: boolean): FiatFormatter => {
Could this instead go on the returned function itself so the same hook can be re-used in either format?

2024-07-22 22:03 UTC, matthewwalsh0 commented on ui/hooks/useFiatFormatter.ts
> +export const useFiatFormatter = (shortenFiatValue?: boolean): FiatFormatter => {
Since this is a boolean, should we use an object argument to make it more readable?

2024-07-22 22:03 UTC, matthewwalsh0 commented on ui/hooks/useFiatFormatter.ts
> +export const useFiatFormatter = (shortenFiatValue?: boolean): FiatFormatter => {
Minor, but could we just call this `shorten` since fiat value is implied?

2024-07-22 22:04 UTC, matthewwalsh0 approved these changes, later dismissed

2024-07-23 10:21 UTC, jpuri approved these changes

2024-07-25 09:48 UTC, matthewwalsh0 approved these changes

2024-07-25 09:48 UTC, merged

2024-08-20 02:11 UTC, digiwand commented
Follow-up PR adds tooltip when ellipsis is shown and updates calculation with decimals
https://github.com/MetaMask/metamask-extension/pull/26523

2024-08-20 02:14 UTC, digiwand commented
Cherry-pick PR into 12.1.0 https://github.com/MetaMask/metamask-extension/pull/26515