fix(26353): fix flaky test Request-queue UI changes should show network specific to domain @no-mmi
MetaMask/metamask-extension pull request #26354
Opened 2024-08-08 17:58 UTC by DDDDDanica

## **Description**
After investigation, it is not very clear that the reject transaction is finished before we switch to the second dapp to perform send transaction action. Hence we put an await for transaction to be finished. 

This test is ran locally 20 times with no failure, and the report is attached here: 
[command_output.txt](https://github.com/user-attachments/files/16551755/command_output.txt)

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/26353

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-08-08 17:59 UTC, DDDDDanica commented on test/e2e/tests/request-queuing/ui.spec.js
> -        // Navigate to extension home screen
We are on extension home page after unlock so this step is unnecessary.

2024-08-08 17:59 UTC, DDDDDanica commented on test/e2e/tests/request-queuing/ui.spec.js
> +        await switchToDappAndSendTransaction(driver, DAPP_ONE_URL);
rename to illustrate the function better

2024-08-08 18:40 UTC, desi approved these changes
LGTM

2024-08-12 14:39 UTC, hjetpoluru approved these changes
LGTM

2024-08-12 19:49 UTC, Gudahtt requested changes
The `should autoswitch networks to the last used network for domain` test in this file is consistently failing since the last update with `develop`, caused by a timeout. The test stalls and times out after 20 minutes.

2024-08-13 01:03 UTC, DDDDDanica commented
Hey @Gudahtt Can you show me the pipeline where that test is failing? I checked the ci and the flakiness are from other tests , running this test locally didn't not result in a failure

2024-08-13 01:14 UTC, sunobun commented
Support

On Tue, 13 Aug 2024 at 02:05, Danica Shen ***@***.***> wrote:

> Hey @Gudahtt <https://github.com/Gudahtt> Can you show me the pipeline
> where that test is failing? I checked the ci and the flakiness are from
> other tests , running this test locally didn't not result in a failure
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MetaMask/metamask-extension/pull/26354#issuecomment-2285153557>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BHUP2VMSBWDFZJ3UMSY2WSLZRFLT3AVCNFSM6AAAAABMG7KEVGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOBVGE2TGNJVG4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-08-13 11:03 UTC, Gudahtt commented
Check out the logs for the `test-e2e-chrome-webpack` job. You can see that it runs for a very long time, and the last output is for the test run "Request-queue UI changes should signal from UI to dapp the network change @no-mmi". And it exits with a code of 124, indicating a timeout. The most recent three failing runs failed this exact same way.

It seems that due to the timeout, the test was not registered as a failing test, so it was skipped when "rerun failed tests" was run 🤔 . That's concerning, I didn't realize that "rerun failed tests" could skip tests from being run at all.

2024-08-19 15:59 UTC, DDDDDanica commented
close due to the fix from https://github.com/MetaMask/metamask-extension/pull/26449

2024-08-19 15:59 UTC, closed without merging