[NewUI-flat] New deposit ether modal UI.
MetaMask/metamask-extension pull request #2642
Opened 2017-12-02 06:52 UTC by danjm

This PR implements the new design for the deposit ether modal. It is missing a working shapeshift link (waiting for reply on slack).

<img width="252" alt="screen shot 2017-12-02 at 3 04 05 am" src="https://user-images.githubusercontent.com/7499938/33512726-ef4befbe-d70f-11e7-873b-56676d41a13d.png">
--
<img width="335" alt="screen shot 2017-12-02 at 3 04 24 am" src="https://user-images.githubusercontent.com/7499938/33512727-ef5ec3dc-d70f-11e7-8f8c-47af38685fbf.png">
--
<img width="867" alt="screen shot 2017-12-02 at 3 04 50 am" src="https://user-images.githubusercontent.com/7499938/33512728-ef71e6d8-d70f-11e7-9490-7c7eb26fd710.png">
--
![buymodal](https://user-images.githubusercontent.com/7499938/33512735-0e1b7a0e-d710-11e7-8ee2-2495b5833edc.gif)

2017-12-07 05:33 UTC, chikeichan commented
Let's make mobile modal fullscreen

2017-12-07 16:56 UTC, danjm commented
022b209d New deposit modal full screen on mobile, and other style fixes.

![revisedmobiledepositmodal](https://user-images.githubusercontent.com/7499938/33727282-1a55340e-db52-11e7-9ea1-446b41d4af28.gif)

Full screen stays consistent:

<img width="831" alt="screen shot 2017-12-07 at 1 22 33 pm" src="https://user-images.githubusercontent.com/7499938/33727303-2b18b770-db52-11e7-9ab5-9776b4a2776b.png">

2018-01-09 18:53 UTC, danjm commented
I have made changes to include the shapeshift modal. The UI changes are captured below:

![buywithshapeshift-actualbuy](https://user-images.githubusercontent.com/7499938/34737188-fc36e6f8-f54f-11e7-9837-c9bf4c006d2a.gif)
-
![buywithshapeshift-mobile](https://user-images.githubusercontent.com/7499938/34737189-fc4ba46c-f54f-11e7-9580-c8b73ccea96c.gif)
-
![buywithshapeshift-browser](https://user-images.githubusercontent.com/7499938/34737190-fc643d74-f54f-11e7-8ea4-8d023ac49ae7.gif)

@cjeria Could you review the above screen shots and let me know if you'd like any changes made. I have ported the design from the Mascara first time flow, but had to make some design/UX decisions when integrating with the buy modal and I'm happy to make changes.

2018-01-10 18:46 UTC, danjm commented
@alextsg d4565eac

<img width="908" alt="screen shot 2018-01-10 at 3 15 57 pm" src="https://user-images.githubusercontent.com/7499938/34789542-3d295352-f619-11e7-99da-c9cee2ff0d41.png">

2018-01-10 20:00 UTC, cjeria commented
@danjm this looks good from what I can see from the gifs. What happens after I go through the entire flow of trading a crypto for eth? Are there other screens we should look at in the flow like a success screen?

2018-01-11 16:43 UTC, danjm commented
> @danjm this looks good from what I can see from the gifs. What happens after I go through the entire flow of trading a crypto for eth? Are there other screens we should look at in the flow like a success screen?

@cjeria No, there is no success screen for a shapeshift trade. See the first of the three gifs I posted. A shapeshift transaction will appear in the transaction list. Once the user actually sends bitcoin to the address, then the status of that transaction will update.

2018-01-12 02:07 UTC, alextsg requested changes

2018-01-12 02:07 UTC, alextsg commented on ui/app/components/shapeshift-form.js
> +      'Deposit your BTC to the address bellow:',
typo: "bellow"

2018-01-12 02:07 UTC, alextsg commented on ui/app/components/modals/deposit-ether-modal.js
> +    // h('div.deposit-ether-modal__buy-rows-container', [
Delete unless it's a placeholder for possible future changes.

2018-01-12 02:07 UTC, alextsg commented on ui/app/css/itcss/components/modal.scss
> +  // &__buy-rows-container {
Delete unneeded styles

2018-01-12 18:03 UTC, danjm commented
@alextsg fixed issues you identified here: 29389936

Also removed some code intended to allow us to identify which accounts created a shape shift transaction. Something like this is needed to ensure that a shapeshift tx created in one account doesn't show up in another. But my impementation here creates other problems. We'll have to discuss a better solution and implement in a future PR.

2018-01-12 19:48 UTC, alextsg approved these changes

2018-01-12 19:48 UTC, merged