feat: converted PreferencesController to typescript
MetaMask/metamask-extension pull request #26710
Opened 2024-08-28 13:50 UTC by kanthesha

## **Description**
As a prerequisite for migrating PreferencesController to BaseController v2, and to support the TypeScript migration effort for the extension, we want to convert PreferencesController to TypeScript.

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/26710?quickstart=1)

## **Related issues**

Fixes: #25923 

## **Manual testing steps**

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## @cryptodev-2s **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

## @MajorLift  **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-04 12:05 UTC, cryptodev-2s commented on app/scripts/controllers/preferences-controller.ts
> +  async setAccountLabel(address: string, label: string): Promise<string> {
I believe this function shouldn't be async in first place, once removed the return type would be string

2024-09-04 12:07 UTC, cryptodev-2s commented on app/scripts/controllers/preferences-controller.ts
> +  async setPreference(
I believe this function shouldn't be async in first place, once removed the return type would be Preferences

2024-09-04 12:08 UTC, cryptodev-2s commented on app/scripts/controllers/preferences-controller.ts
> +  async setIpfsGateway(domain: string): Promise<string> {
I believe this function shouldn't be async in first place, once removed the return type would be string

2024-09-04 12:08 UTC, cryptodev-2s commented on app/scripts/controllers/preferences-controller.ts
> +  async setIsIpfsGatewayEnabled(enabled: boolean): Promise<void> {
I believe this function shouldn't be async in first place, once removed the return type would be void

2024-09-04 12:09 UTC, cryptodev-2s commented on app/scripts/controllers/preferences-controller.ts
> +  async setDismissSeedBackUpReminder(
I believe this function shouldn't be async in first place, once removed the return type would be void
also this.store.updateState is not a promise no need to await

2024-09-04 12:28 UTC, cryptodev-2s commented on app/scripts/controllers/preferences-controller.ts
>     * @property {object} store The stored object containing a users preferences, stored in local storage
Minor suggestion:
How about renaming this store property to match the actual property name, `initState`?
Additionally, I believe we can remove the `{object}` type annotation now that we have a defined options type.

2024-09-04 12:34 UTC, cryptodev-2s commented on app/scripts/controllers/preferences-controller.ts
> +  network?: any;
I believe the `network` property can just be removed I don't see it used anywhere.

2024-09-04 12:35 UTC, cryptodev-2s commented on app/scripts/controllers/preferences-controller.ts
> +  private network: any;
Same as the below comment if we remove the network property from the constructor options. we can remove this private variable

2024-09-04 13:47 UTC, cryptodev-2s commented on app/scripts/controllers/preferences-controller.ts
> +};
```suggestion

const controllerName = 'PreferencesController';

/**
 * Returns the state of the {@link PreferencesController}.
 */
export type PreferencesControllerGetStateAction = {
  type: 'PreferencesController:getState';
  handler: () => PreferencesControllerState;
};

/**
 * Actions exposed by the {@link PreferencesController}.
 */
export type PreferencesControllerActions = PreferencesControllerGetStateAction;

/**
 * Event emitted when the state of the {@link PreferencesController} changes.
 */
export type PreferencesControllerStateChangeEvent = {
  type: 'PreferencesController:stateChange';
  payload: [PreferencesControllerState, []];
};

/**
 * Events emitted by {@link PreferencesController}.
 */
export type PreferencesControllerEvents = PreferencesControllerStateChangeEvent;

/**
 * Actions that this controller is allowed to call.
 */
export type AllowedActions =
  | AccountsControllerGetAccountByAddressAction
  | AccountsControllerSetAccountNameAction
  | AccountsControllerGetSelectedAccountAction
  | AccountsControllerSetSelectedAccountAction;

/**
 * Events that this controller is allowed to subscribe.
 */
export type AllowedEvents = AccountsControllerChangeEvent;

export type PreferencesControllerMessenger = RestrictedControllerMessenger<
  typeof controllerName,
  PreferencesControllerActions | AllowedActions,
  PreferencesControllerEvents | AllowedEvents,
  AllowedActions['type'],
  AllowedEvents['type']
>;

type PreferencesControllerOptions = {
  networkConfigurations?: Record<string, { chainId: Hex }>;
  initState?: Partial<PreferencesControllerState>;
  initLangCode?: string;
  messenger: PreferencesControllerMessenger;
};
```

I believe the network property can just be removed I don't see it used anywhere.

2024-09-04 13:48 UTC, cryptodev-2s commented on app/scripts/controllers/preferences-controller.ts
> +};
I believe the`network` property can just be removed I don't see it used anywhere.

2024-09-04 13:50 UTC, cryptodev-2s commented on app/scripts/controllers/preferences-controller.ts
> +  private messagingSystem: any;
```suggestion
private messagingSystem: PreferencesControllerMessenger;
```

2024-09-04 13:53 UTC, cryptodev-2s commented on app/scripts/controllers/preferences-controller.ts
>      );
```suggestion
    this.messagingSystem = opts.messenger;
    this.messagingSystem.registerActionHandler(
      `PreferencesController:getState`,
      () => this.store.getState(),
    );
    this.messagingSystem.registerInitialEventPayload({
      eventType: `PreferencesController:stateChange`,
      getPayload: () => [this.store.getState(), []],
    });

    this.messagingSystem.subscribe(
      'AccountsController:stateChange',
      this.#handleAccountsControllerSync.bind(this),
    );
````

2024-09-04 13:57 UTC, cryptodev-2s commented on app/scripts/controllers/preferences-controller.ts
> +  async setAccountLabel(address: string, label: string): Promise<string> {
Nit:
We could also consider updating the function by switching the order to check the address first. Additionally, it should throw an error if the account is not found to ensure that `account.id` passes TypeScript validation, as `account` could be undefined.
````
 setAccountLabel(address: string, label: string): string {
    if (!address) {
      throw new Error(
        `setAccountLabel requires a valid address, got ${String(address)}`,
      );
    }

    const account = this.messagingSystem.call(
      'AccountsController:getAccountByAddress',
      address,
    );

    if (!account) {
      throw new Error(`Account for '${address} not found`);
    }

    this.messagingSystem.call(
      'AccountsController:setAccountName',
      account.id,
      label,
    );

    return label;
  }
```

2024-09-04 13:58 UTC, cryptodev-2s commented on app/scripts/controllers/preferences-controller.test.ts
> +  let controllerMessenger: any;
```suggestion
 let controllerMessenger: ControllerMessenger<
    | PreferencesControllerActions
    | AllowedActions
    | KeyringControllerGetAccountsAction
    | KeyringControllerGetKeyringsByTypeAction
    | KeyringControllerGetKeyringForAccountAction,
    | PreferencesControllerEvents
    | KeyringControllerStateChangeEvent
    | KeyringControllerAccountRemovedEvent
    | SnapControllerStateChangeEvent
    | AllowedEvents
  >;
```

2024-09-04 14:00 UTC, cryptodev-2s commented on app/scripts/controllers/preferences-controller.test.ts
>        const preferencesControllerExistingUser = new PreferencesController({
```suggestion
    it('should keep initial value of useTokenDetection for existing users', function () {
      // TODO: Remove unregisterActionHandler and clearEventSubscriptions once the PreferencesController has been refactored to use the withController pattern.
      controllerMessenger.unregisterActionHandler(
        'PreferencesController:getState',
      );
      controllerMessenger.clearEventSubscriptions(
        'PreferencesController:stateChange',
      );
      const preferencesControllerExistingUser = new PreferencesController({
        messenger: controllerMessenger.getRestricted({
          name: 'PreferencesController',
          allowedActions: [],
          allowedEvents: ['AccountsController:stateChange'],
        }),
        initLangCode: 'en_US',
        initState: {
          useTokenDetection: false,
        },
        networkConfigurations: NETWORK_CONFIGURATION_DATA,
      });
      const state = preferencesControllerExistingUser.store.getState();
      expect(state.useTokenDetection).toStrictEqual(false);
    });
  });

2024-09-04 14:11 UTC, cryptodev-2s commented
Nit:
We can also update the Controller initialisation in metamask-controller.js to
```
   const preferencesMessenger = this.controllerMessenger.getRestricted({
      name: 'PreferencesController',
      allowedActions: [
        'AccountsController:setSelectedAccount',
        'AccountsController:getAccountByAddress',
        'AccountsController:setAccountName',
        'AccountsController:setSelectedAccount',
      ],
      allowedEvents: ['AccountsController:stateChange'],
    });

    this.preferencesController = new PreferencesController({
      initState: initState.PreferencesController,
      initLangCode: opts.initLangCode,
      messenger: preferencesMessenger,
      networkConfigurations: this.networkController.state.networkConfigurations,
    });

2024-09-04 20:01 UTC, cryptodev-2s approved these changes, later dismissed

2024-09-06 13:05 UTC, MajorLift reviewed
nits

2024-09-06 13:05 UTC, MajorLift commented on app/scripts/controllers/preferences-controller.ts
> +export type AllowedEvents = AccountsControllerChangeEvent;
```suggestion
export type AllowedEvents = AccountsControllerChangeEvent;

```

2024-09-06 13:05 UTC, MajorLift commented on app/scripts/controllers/preferences-controller.ts
> +      opts.networkConfigurations || {},
```suggestion
      opts.networkConfigurations ?? {},
```

2024-09-06 13:05 UTC, MajorLift commented on app/scripts/controllers/preferences-controller.ts
> +      currentLocale: opts.initLangCode || '',
```suggestion
      currentLocale: opts.initLangCode ?? '',
```

2024-09-06 13:11 UTC, MajorLift requested changes, later dismissed
Narrow references to properties of the `Preferences` type: from `string` to `keyof Preferences`

2024-09-06 13:11 UTC, MajorLift commented on app/scripts/controllers/preferences-controller.ts
> +type Preferences = {
```suggestion
export type Preferences = {
```

2024-09-06 13:11 UTC, MajorLift commented on app/scripts/controllers/preferences-controller.ts
> +    globalThis.setPreference = (key: string, value: boolean) => {
```suggestion
    globalThis.setPreference = (key: keyof Preferences, value: boolean) => {
```

2024-09-06 13:11 UTC, MajorLift commented on app/scripts/controllers/preferences-controller.ts
> +  setPreference(preference: string, value: boolean | object): Preferences {
```suggestion
  setPreference(
    preference: keyof Preferences,
    value: Preferences[typeof preference],
  ): Preferences {
```

2024-09-06 13:11 UTC, MajorLift commented on types/global.d.ts
> +  function setPreference(key: string, value: boolean);
```suggestion
  function setPreference(key: keyof Preferences, value: boolean);
```

```diff
diff --git a/types/global.d.ts b/types/global.d.ts
index 33e5c52fd0..5b963f1ec5 100644
--- a/types/global.d.ts
+++ b/types/global.d.ts
@@ -21,6 +21,7 @@ import {
   OffscreenCommunicationTarget,
   TrezorAction,
 } from 'shared/constants/offscreen-communication';
+import type { Preferences } from '../app/scripts/controllers/preferences-controller';
```

2024-09-06 13:20 UTC, MajorLift commented on app/scripts/controllers/preferences-controller.ts
>  export default class PreferencesController {
nit: What do you think about aligning this export statement with the core controller here? The extra diffs for going back and forth between default vs. named import seem unnecessary.

```suggestion
export class PreferencesController {
```

```diff
diff --git a/app/scripts/controllers/mmi-controller.ts b/app/scripts/controllers/mmi-controller.ts
index 7cc024d0cd..4b1e534907 100644
--- a/app/scripts/controllers/mmi-controller.ts
+++ b/app/scripts/controllers/mmi-controller.ts
@@ -41,7 +41,7 @@ import AccountTracker from '../lib/account-tracker';
 import { getCurrentChainId } from '../../../ui/selectors';
 import MetaMetricsController from './metametrics';
 import { getPermissionBackgroundApiMethods } from './permissions';
-import PreferencesController from './preferences-controller';
+import { PreferencesController } from './preferences-controller';
 import { AppStateController } from './app-state';
 
 type UpdateCustodianTransactionsParameters = {
diff --git a/app/scripts/controllers/preferences-controller.test.ts b/app/scripts/controllers/preferences-controller.test.ts
index 56885232be..1822071e22 100644
--- a/app/scripts/controllers/preferences-controller.test.ts
+++ b/app/scripts/controllers/preferences-controller.test.ts
@@ -14,12 +14,13 @@ import { SnapControllerStateChangeEvent } from '@metamask/snaps-controllers';
 import { CHAIN_IDS } from '../../../shared/constants/network';
 import { mockNetworkState } from '../../../test/stub/networks';
 import { ThemeType } from '../../../shared/constants/preferences';
-import PreferencesController, {
+import type {
   AllowedActions,
   AllowedEvents,
   PreferencesControllerActions,
   PreferencesControllerEvents,
 } from './preferences-controller';
+import { PreferencesController } from './preferences-controller';
 
 const NETWORK_CONFIGURATION_DATA = mockNetworkState(
   {
diff --git a/app/scripts/lib/ppom/ppom-middleware.ts b/app/scripts/lib/ppom/ppom-middleware.ts
index d623d4868a..d3cbea90f3 100644
--- a/app/scripts/lib/ppom/ppom-middleware.ts
+++ b/app/scripts/lib/ppom/ppom-middleware.ts
@@ -11,7 +11,7 @@ import { detectSIWE } from '@metamask/controller-utils';
 
 import { MESSAGE_TYPE } from '../../../../shared/constants/app';
 import { SIGNING_METHODS } from '../../../../shared/constants/transaction';
-import PreferencesController from '../../controllers/preferences-controller';
+import { PreferencesController } from '../../controllers/preferences-controller';
 import { AppStateController } from '../../controllers/app-state';
 import { LOADING_SECURITY_ALERT_RESPONSE } from '../../../../shared/constants/security-provider';
 import { getProviderConfig } from '../../../../ui/ducks/metamask/metamask';
diff --git a/app/scripts/metamask-controller.js b/app/scripts/metamask-controller.js
index b7214ad198..478e0cc750 100644
--- a/app/scripts/metamask-controller.js
+++ b/app/scripts/metamask-controller.js
@@ -283,7 +283,7 @@ import { NetworkOrderController } from './controllers/network-order';
 import { AccountOrderController } from './controllers/account-order';
 import createOnboardingMiddleware from './lib/createOnboardingMiddleware';
 import { isStreamWritable, setupMultiplex } from './lib/stream-utils';
-import PreferencesController from './controllers/preferences-controller';
+import { PreferencesController } from './controllers/preferences-controller';
 import AppStateController from './controllers/app-state';
 import AlertController from './controllers/alert';
 import OnboardingController from './controllers/onboarding';
diff --git a/shared/constants/mmi-controller.ts b/shared/constants/mmi-controller.ts
index 67123b83d5..0efcceeb08 100644
--- a/shared/constants/mmi-controller.ts
+++ b/shared/constants/mmi-controller.ts
@@ -4,7 +4,7 @@ import { TransactionUpdateController } from '@metamask-institutional/transaction
 import { CustodyController } from '@metamask-institutional/custody-controller';
 import { SignatureController } from '@metamask/signature-controller';
 import { NetworkController } from '@metamask/network-controller';
-import PreferencesController from '../../app/scripts/controllers/preferences-controller';
+import { PreferencesController } from '../../app/scripts/controllers/preferences-controller';
 import { AppStateController } from '../../app/scripts/controllers/app-state';
 import AccountTracker from '../../app/scripts/lib/account-tracker';
 import MetaMetricsController from '../../app/scripts/controllers/metametrics';
```

2024-09-09 13:47 UTC, cryptodev-2s approved these changes

2024-09-09 14:42 UTC, MajorLift approved these changes
LGTM

2024-09-09 15:41 UTC, desi reviewed
@kanthesha can you please check the pre merge checklist and make sure you have checked against all of those. @MajorLift and @cryptodev-2s did either of you do testing? If so can you indicate such in the reviewer checklist?

2024-09-13 15:21 UTC, desi approved these changes
Based on previous reviewers indicating testing and complete review I am approving in order to allow merging (code owners)

2024-09-13 15:32 UTC, merged