fix: rename migration 126 to 121.1 (#26742)
MetaMask/metamask-extension pull request #26778
Opened 2024-08-29 21:07 UTC by owencraston

This PR renames migration 126 to 121.1. The reason for this renaming is that commit 759b92e is being cherry-picked into version 12.1.1.

Between version 12.1.1 and the develop branch, there are missing migrations. To avoid skipping these migrations in subsequent releases, we need to rename migration 126 to 121.1.

## **Description**

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-08-29 21:12 UTC, Gudahtt commented on app/scripts/migrations/126.ts
We should exclude this migration; it was included in the rename only because it needed to be re-numbered. It's not something we want to back port.

2024-08-29 21:13 UTC, Gudahtt requested changes
Mostly looks good, but one extra migration was added that we should remove

2024-08-29 21:18 UTC, owencraston commented on app/scripts/migrations/126.ts
Removed in this [commit](https://github.com/MetaMask/metamask-extension/pull/26778/commits/11b2115b4d7b2f09ce215d59d8ea30cd7f3a72d2)

2024-08-29 21:18 UTC, Gudahtt approved these changes

2024-08-30 09:28 UTC, chloeYue approved these changes

2024-08-30 09:48 UTC, merged