refactor: use `withKeyring` method (#25435)
MetaMask/metamask-extension pull request #27025
Opened 2024-09-10 12:56 UTC by mikesposito

## **Description**

This PR cherry-picks def6b15 into `develop`, after being reverted at 821c3bd. The reason the original commit was reverted is explained in #26840.

_From the original PR (#25435):_

With `@metamask/keyring-controller` v16 a new method is available which simplify safe direct keyring interactions which are not available through KeyringController.

Through `withKeyring` it's possible to lock KeyringController's main mutex and select a specific keyring to interact with while KeyringController will be unusable concurrently. `withKeyring` also takes care of persisting keyrings and updating the controller state at the end of the operation, which makes it possible to use it in substitution of `getKeyringsByType` and `persistAllKeyrings`.

Currently, most of the direct keyring interactions in the extension are made for hardware devices and snaps.

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/27025?quickstart=1)

## **Related issues**

Fixes: #26840 
Fixes: #24276

## **Manual testing steps**
_As for the original PR (#25435):_

Affected workflows may include:

- Lock
- Unlock
- Add account
- Remove account
- Connect hardware wallet
- All hardware wallet interactions

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-16 10:27 UTC, cryptodev-2s submitted a review, later dismissed

2024-09-30 12:12 UTC, mikesposito commented
This is currently blocked by https://github.com/MetaMask/accounts-planning/issues/615

2025-01-09 14:54 UTC, mikesposito commented on app/scripts/metamask-controller.js
> +      return deviceName;
This comparison is inverted so that the function can return without potentially adding a new keyring

2025-01-09 14:57 UTC, mikesposito commented on app/scripts/metamask-controller.js
> -    }
`KeyringController` automatically removes empty keyrings when removing accounts

2025-01-09 14:59 UTC, mikesposito commented on app/scripts/metamask-controller.js
> +  async withKeyringForDevice(options, callback) {
This is probably the main change of this PR: `getKeyringForDevice` is now `withKeyringForDevice`.

Instead of being a getter for a Keyring instance related to a device, it is now a safe callback executor for hardware devices

2025-01-09 15:46 UTC, cryptodev-2s commented on app/scripts/metamask-controller.js
> +  async withKeyringForDevice(options, callback) {
Nit: can we make this private I see it's being used only on this file (can we have a workaround for the test file without mocking a private function)?

2025-01-09 15:46 UTC, cryptodev-2s commented on app/scripts/metamask-controller.js
> +  async _onAccountRemoved(address) {
Nit: this seems to me it can be just a void can we remove the async keyword ? and await when calling the function

2025-01-16 11:54 UTC, mikesposito commented on app/scripts/metamask-controller.js
> +  async _onAccountRemoved(address) {
good point! done in https://github.com/MetaMask/metamask-extension/pull/27025/commits/d84e1671c72d5d09d90d82e4147396ddd4c681ab

2025-01-16 13:47 UTC, mikesposito commented on app/scripts/metamask-controller.js
> +  async withKeyringForDevice(options, callback) {
There's no other component relying on this method besides MetamaskController itself so I believe that it can be indeed made private (#withKeyringForDevice), though as you are suggesting there are a couple of test cases where it's being mocked. We could try to mock `KeyringController.withKeyring` instead, since it's the function that withKeyringForDevice relies upon

2025-01-16 14:03 UTC, mikesposito commented on app/scripts/metamask-controller.js
> +  async withKeyringForDevice(options, callback) {
Done in https://github.com/MetaMask/metamask-extension/pull/27025/commits/bfda15f6caffa7648eb2ff32a735c8df8fc4f500

2025-01-16 14:20 UTC, mikesposito commented on app/scripts/metamask-controller.js
> +  async withKeyringForDevice(options, callback) {
Note that this has been then renamed to `#withKeyringForDevice` in this commit: https://github.com/MetaMask/metamask-extension/commit/bfda15f6caffa7648eb2ff32a735c8df8fc4f500

2025-01-17 09:15 UTC, Akaryatrh requested changes

2025-01-17 09:15 UTC, Akaryatrh commented on app/scripts/metamask-controller.js
> +        this._onAccountRemoved(address);
It will not call `await this.keyringController.removeAccount(address)` while previously it did through `this.removeAccount(address)`, is it expected?

2025-01-17 09:15 UTC, Akaryatrh commented on app/scripts/metamask-controller.js
> +  async #withKeyringForDevice(options, callback) {
This is a pure architecture question: I have hard time understanding why we allow keyring resolution by `address` or by `keyringType` directly inside `withKeyring` from `KeyringController`, but we don't allow resolution by `deviceName`?
I know it would imply to add some types and more logic to `keyringController`, but I don't see any reason why this resolution would happen in extension directly instead of being handled by controller?

2025-01-17 09:35 UTC, mikesposito commented on app/scripts/metamask-controller.js
> +        this._onAccountRemoved(address);
Our keyrings remove all their accounts on a `forgetDevice` call: https://github.com/MetaMask/accounts/blob/5fcd8d275472a0be5b3c11a847e132eb5bbc832a/packages/keyring-eth-ledger-bridge/src/ledger-keyring.ts#L551

On the other hand, KeyringController automatically removes empty keyrings and refreshes its state with the current available accounts. So a `forgetDevice` call on a keyring makes these things happen:
- Removes accounts from Keyring
- Forgets the device
- Removes the keyring from KeyringController
- Removes accounts from KeyringController

So the call to await this.keyringController.removeAccount(address)` was redundant

2025-01-17 09:39 UTC, mikesposito commented on app/scripts/metamask-controller.js
> +  async #withKeyringForDevice(options, callback) {
Good question, the reason is mainly that not all keyrings are devices (e.g. HDKeyring, SimpleKeyring) and KeyringController should be as much keyring-agnostic as possible, so it provides selectors that make sense for all available keyrings and that require the less knowledge possible about the actual device that the keyring is managing - so `keyringType` and `address` is something that work for all selectable keyrings

2025-01-17 09:50 UTC, Akaryatrh commented on app/scripts/metamask-controller.js
> +        this._onAccountRemoved(address);
Makes sense!

2025-01-17 09:51 UTC, Akaryatrh commented on app/scripts/metamask-controller.js
> +  async #withKeyringForDevice(options, callback) {
Understood, thanks for response!

2025-01-17 09:51 UTC, Akaryatrh approved these changes

2025-01-17 09:53 UTC, cryptodev-2s approved these changes
LGTM!

2025-01-17 13:06 UTC, merged