fix: remove repeated account option
MetaMask/metamask-extension pull request #27116
Opened 2024-09-12 21:54 UTC by gantunesr

## **Description**

This PR fixes an issue about the account option `Add a new Bitcoin account (testnet)` being repeated.

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes: None

## **Manual testing steps**

1. Enable bitcoin testnet account in the experimental setting
2. Go to the "Add account" menu

## **Screenshots/Recordings**

### **Before**

<img src="https://github.com/user-attachments/assets/35322739-3c82-4773-9649-6acbce70d799" width=250 />

### **After**

<img src="https://github.com/user-attachments/assets/393bb4d1-daf3-42fb-abf9-de537ee64a3c" width=250 />

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-13 11:31 UTC, ccharly requested changes

2024-09-16 05:15 UTC, gantunesr commented on ui/components/multichain/account-list-menu/account-list-menu.tsx
>                ///: BEGIN:ONLY_INCLUDE_IF(build-flask)
corrected in [dc527a5](https://github.com/MetaMask/metamask-extension/pull/27116/commits/dc527a5ff7563919d313d139b1789c24bbbe2549)

2024-09-16 05:15 UTC, gantunesr commented on ui/components/multichain/account-list-menu/account-list-menu.tsx
> -              ///: END:ONLY_INCLUDE_IF
corrected in [dc527a5](https://github.com/MetaMask/metamask-extension/pull/27116/commits/dc527a5ff7563919d313d139b1789c24bbbe2549)

2024-09-16 13:29 UTC, ccharly approved these changes

2024-09-16 15:27 UTC, digiwand approved these changes

2024-09-16 15:27 UTC, k-g-j approved these changes
LGTM - I only see one add testnet account option now 👍 

<img width="370" alt="Screenshot 2024-09-16 at 11 26 50 AM" src="https://github.com/user-attachments/assets/56c06e4b-5772-485b-80b6-551b6537c1c1">

2024-09-16 18:03 UTC, merged