fix: Limit amount of decimals on spending cap modal
MetaMask/metamask-extension pull request #27672
Opened 2024-10-07 16:35 UTC by pedronfigueiredo

## **Description**

If the user tries to add more decimals to the spending cap than what the token supports, the spending cap cannot be submitted and a notice is displayed.

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27618

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

<img width="472" alt="Screenshot 2024-10-07 at 16 57 24" src="https://github.com/user-attachments/assets/d8faa964-63c9-48c1-b8f5-59bf1591a16c">

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-07 20:27 UTC, matthewwalsh0 requested changes, later dismissed

2024-10-07 20:27 UTC, matthewwalsh0 commented on ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx
> +  const showDecimalError = useMemo(() => {
Minor, do we need a memo for this as some basic math will have negligible performance cost?

2024-10-07 20:27 UTC, matthewwalsh0 commented on ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx
> +      onClose={() => handleCancel()}
Minor, no need for the lambda since `handleCancel` is already a function reference with no arguments?

2024-10-09 14:12 UTC, jpuri submitted a review, later dismissed

2024-10-09 14:14 UTC, jpuri commented on ui/pages/confirmations/components/confirm/info/approve/edit-spending-cap-modal/edit-spending-cap-modal.tsx
> +}
`return numberString.split(".")[1].length || 0;`

2024-10-09 14:20 UTC, OGPoyraz approved these changes

2024-10-09 16:01 UTC, jpuri approved these changes

2024-10-09 16:52 UTC, merged