feat: Native asset send
MetaMask/metamask-extension pull request #27979
Opened 2024-10-21 09:34 UTC by pedronfigueiredo

## **Description**

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

![Screenshot 2024-10-21 at 10 31 24](https://github.com/user-attachments/assets/a5ba797a-be9a-42ca-908e-c77094f01901)

<img width="358" alt="Screenshot 2024-10-21 at 10 32 05" src="https://github.com/user-attachments/assets/a8149e22-0f5a-49e5-b051-cc3969db9d1a">

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-25 11:56 UTC, jpuri approved these changes, later dismissed

2024-10-29 08:43 UTC, digiwand commented on ui/pages/confirmations/components/confirm/info/info.tsx
> +      [TransactionType.simpleSend]: () => NativeTransferInfo,
[nit] relocate to under `TransactionType.deployContract` to aim for alphabetizing. We should alphabetize the other items in this list as it is growing

2024-10-29 09:13 UTC, digiwand requested changes
there is a precision issue here. We are able to add lengthy values in the Send screen e.g. `0.000123456789012345678901234567890123456789` (paste twice in initial input). Because JavaScript coerces numbers outside of the MAX_SAFE_INTEGER range into scientific notation, it loses precision. 

From the Send screen, we can observe that the From value can have our desired number. Then we can see the To value loses decimal values. In the Review screen the value is also seen to have lost decimals from the original input. 

I'm unsure what the expected behavior here is, but if we did want to allow the users to enter in more digits, we could support this by preserving the string value and passing this string value to the BigNumber constructor.

once that is done, we'd need to be careful to avoid coercing it back into a JS number because it would lose precision again. We could use toFixed or toString to display the values, and avoid toNumber here

example BigNumber handling:
```
  const transferValue = new BigNumber(
    '0.000123456789012345678901234567890123456789',
  );

  console.log('transferValue', transferValue);
  console.log('transferValue toNumber', transferValue?.toNumber());
  console.log('transferValue toFixed', transferValue?.toFixed());
  console.log('transferValue toString', transferValue?.toString());
```
![CleanShot 2024-10-29 at 16 00 36@2x](https://github.com/user-attachments/assets/fbbe28a3-60b8-45be-9694-2eb052d370a0)

observe large value displayed input:
<img width="320" src="https://github.com/user-attachments/assets/d3ccafb2-d8f1-4df0-a2c9-0176511c3cc6">

observe value has been coerced in To value
<img width="320" src="https://github.com/user-attachments/assets/9ab9f6ed-90e3-4876-8348-205a701db928">

observe value has been coerced in Review screen
<img width="320" src="https://github.com/user-attachments/assets/cbfbcde8-3f7f-4af4-b956-76683a725923">

2024-10-29 11:28 UTC, pedronfigueiredo commented
@digiwand In practice, I don't think there is any issue.

The reason you're seeing a truncated value is that the transfer value is saved as a WEI value.

You can see that on `nativeSendHeading`, `nativeAssetTransferValue` converts that value back to ETH.

I think it's reasonable not to expect resolutions below WEI units. In other words, the user is limited by the number of decimals the token has. What I don't know for sure is wether or not the number of decimals for native tokens can be determined dynamically or not with existing utils in the wallet, but I haven't found that. So at the moment that number is hardcoded to 18.

2024-10-29 12:57 UTC, jpuri submitted a review, later dismissed

2024-10-29 16:14 UTC, digiwand approved these changes, later dismissed

2024-10-30 09:57 UTC, jpuri submitted a review, later dismissed

2024-10-30 10:10 UTC, digiwand commented on ui/pages/confirmations/components/confirm/info/info.tsx
> +      [TransactionType.tokenMethodSafeTransferFrom]: () => NFTTokenTransferInfo,
❤️

2024-10-30 10:16 UTC, digiwand submitted a review, later dismissed

2024-10-30 11:54 UTC, jpuri approved these changes

2024-10-30 13:15 UTC, vinistevam approved these changes

2024-10-30 15:12 UTC, merged