fix: resolve secp256k1 to latest version
MetaMask/metamask-extension pull request #28000
Opened 2024-10-21 21:04 UTC by NEllusion

## **Description**
This pull request resolves the secp256k1 library to the latest version. Currently we use a variety of versions under 4.0.x, this would unify them under 4.0.4.

This is the state of the library before this resolution - as you can see, only patch changes will apply. 

<img width="521" alt="" src="https://github.com/user-attachments/assets/21a8133f-84d0-41c2-993d-9a4822766e30">

 

## **Manual testing steps**

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-21 21:41 UTC, legobeat approved these changes, later dismissed

2024-10-21 21:41 UTC, legobeat commented
@metamaskbot update-policies

2024-10-21 21:53 UTC, legobeat approved these changes

2024-10-21 21:54 UTC, legobeat commented
@NicholasEllul related:
- https://github.com/MetaMask/metamask-extension/pull/27973

2024-10-21 22:03 UTC, legobeat requested changes

2024-10-21 22:03 UTC, legobeat commented on package.json
> +    "secp256k1": "4.0.4"
Hm, this also tries to pin the 3.x versions, which should go to `3.8.1`?

2024-10-22 00:18 UTC, danjm approved these changes
LGTM (unless the answer to the question from Nic to lego changes my understanding of what exactly needs to be pinned here)

2024-10-22 00:51 UTC, legobeat commented
@danjm Maybe we can consider superseding this by #11932?

2024-10-22 08:22 UTC, FrederikBolding approved these changes

2024-10-22 09:32 UTC, OGPoyraz approved these changes

2024-10-22 12:33 UTC, closed without merging