fix: Updates to the simulations component
MetaMask/metamask-extension pull request #28107
Opened 2024-10-25 14:01 UTC by pedronfigueiredo

## **Description**

Updates the copy, layout and text color for 3 scenarios: No changes, Generic Error and Fiat value not available as per design review.

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/27072

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

<img width="359" alt="Screenshot 2024-10-25 at 14 52 54" src="https://github.com/user-attachments/assets/df189f0b-01c0-4f47-a59c-2e323fe6c8b3">
<img width="364" alt="Screenshot 2024-10-25 at 14 15 36" src="https://github.com/user-attachments/assets/a4775ee5-d39e-4d11-8baa-03b504912efe">
<img width="361" alt="Screenshot 2024-10-25 at 14 14 19" src="https://github.com/user-attachments/assets/367e9351-3e81-4b42-8ec6-3f53a2e73f08">

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-25 14:19 UTC, jpuri submitted a review, later dismissed

2024-10-29 08:40 UTC, digiwand requested changes
In the GH description screenshots, "No Changes" is a lighter gray. Should we update the description and/or the UI? the [Figma](https://www.figma.com/design/8DrinrQI4hs76Grm2F34xK/Simulations-MVP?node-id=1495-9747&node-type=canvas&m=dev) displays the copy with a darker gray

2024-11-01 21:03 UTC, matthewwalsh0 approved these changes, later dismissed

2024-11-01 21:03 UTC, matthewwalsh0 commented on ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.tsx
> +              <Box
Minor, since we have three nested boxes, would the readability benefit from some local components?

2024-11-01 21:03 UTC, matthewwalsh0 commented on ui/pages/confirmations/components/confirm/info/personal-sign/personal-sign.tsx
> +          <Box
I assume the necessary formatting isn't feasible to encapsulate within the `ConfirmInfoRow` component?

2024-11-06 11:37 UTC, digiwand approved these changes

2024-11-07 12:21 UTC, OGPoyraz approved these changes

2024-11-07 12:45 UTC, merged