feat: display native values returned from decoding api
MetaMask/metamask-extension pull request #28374
Opened 2024-11-08 05:13 UTC by jpuri

## **Description**

display native values returned from decoding api

## **Related issues**

Fixes: https://github.com/MetaMask/MetaMask-planning/issues/3617

## **Manual testing steps**

1. Enable signature decoding api
2. On test dapp submit permit request
3. Check simulation section

## **Screenshots/Recordings**
<img width="333" alt="Screenshot 2024-11-08 at 10 21 09 AM" src="https://github.com/user-attachments/assets/10fcf954-7e10-4783-a82a-e32cff8481e9">

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-11-20 15:00 UTC, digiwand requested changes
minor suggestion to remove the snapshot test. I think the snapshot tests have diminishing returns. With a minor change, there is a lot of change in this PR. I suggest we avoid snapshot tests for smaller, reusable components as they will be tested together in parent snapshots

2024-11-21 10:51 UTC, digiwand approved these changes

2024-11-21 11:01 UTC, pedronfigueiredo approved these changes

2024-11-21 12:08 UTC, Joj501 approved these changes

2024-11-21 12:09 UTC, Joj501 approved these changes

2024-11-22 00:50 UTC, merged