fix: redesigned_confirmation should be excluded on non-redesigned confirmation metrics
MetaMask/metamask-extension pull request #28385
Opened 2024-11-08 17:12 UTC by digiwand

## **Description**

the metrics were included when ENABLE_CONFIRMATION_REDESIGN was turned on regardless of the setting. The fix is to include the metrics when both the ENABLE_CONFIRMATION_REDESIGN is enabled and the setting is enabled. The  ENABLE_CONFIRMATION_REDESIGN should control the option for redesigned confirmations to be shown.

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/28322 (old native send)
Fixes: https://github.com/MetaMask/metamask-extension/issues/28339 (old contract deployment)

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-11-08 17:14 UTC, digiwand commented on app/scripts/lib/transaction/metrics.test.ts
> +  getIsRedesignedConfirmationsDeveloperEnabled: jest.fn().mockReturnValue(true),
Previously, the tests were not testing this flag

2024-11-13 06:50 UTC, digiwand commented
Fix and tests need to be updated

2024-11-13 15:24 UTC, cryptotavares requested changes

2024-11-13 15:24 UTC, cryptotavares commented on app/scripts/lib/transaction/metrics.ts
> +    Boolean(process.env.ENABLE_CONFIRMATION_REDESIGN) &&
We cannot do this... `ENABLE_CONFIRMATION_REDESIGN` is just intended for local dev. (we should get rid of it as soon as possible to avoid confusion)

2025-02-13 10:03 UTC, closed without merging