feat: Better handle very long names in the name component
MetaMask/metamask-extension pull request #28560
Opened 2024-11-20 11:24 UTC by pedronfigueiredo

## **Description**

Truncates long names (>15 characters).

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/MetaMask-planning/issues/3630

## **Manual testing steps**

1. Trigger a new confirmation
2. Add a long petname, by clicking an address and writing it in the input field
3. The name should be truncated with an ellipsis.

## **Screenshots/Recordings**

### **Before**

### **After**

<img width="360" alt="Screenshot 2024-11-20 at 11 24 21" src="https://github.com/user-attachments/assets/68055ea8-10f4-455c-afa2-ce34c10fbb7c">

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-11-20 11:32 UTC, matthewwalsh0 requested changes

2024-11-20 11:32 UTC, matthewwalsh0 commented on ui/components/app/name/name.tsx
> +export function formatName(name: string): string {
`shortenString` from `ui/helpers/utils/util.js`?

2024-11-20 13:15 UTC, jpuri approved these changes, later dismissed

2024-11-20 13:16 UTC, jpuri commented on ui/components/app/name/name.tsx
>              <Text className="name__value" variant={TextVariant.bodyMd}>
Will be nice to have some unit test coverage also

2024-11-20 22:07 UTC, matthewwalsh0 approved these changes

2024-11-21 11:38 UTC, jpuri approved these changes

2024-11-21 12:37 UTC, merged