fix: has_marketing_consent flag on metametrics
MetaMask/metamask-extension pull request #28795
Opened 2024-11-28 17:01 UTC by jonybur

## **Description**

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-11-28 17:16 UTC, NidhiKJha requested changes
Data collection for marketing works fine. But when I click on Participate in MetaMetrics toggle, it doesn't work
https://github.com/user-attachments/assets/9f41e1e0-35f2-460b-8f4b-0b2e11fe57b9

2024-11-28 18:08 UTC, NidhiKJha approved these changes

2024-11-28 18:17 UTC, Gudahtt approved these changes
LGTM!

2024-11-28 18:23 UTC, salimtb approved these changes

2024-11-29 00:47 UTC, merged

2024-11-29 11:44 UTC, vpintorico commented
Hi @jonybur, these changes should have been included on 12.9.0. Please confirm.

2024-11-29 14:18 UTC, hesterbruikman commented
@vpintorico these changes should go in 12.9.0. If they didn't make release cut it's ok to include in 12.10.0

cc @jonybur @NidhiKJha