SOL-46 Adds the multichain transactions controller
MetaMask/metamask-extension pull request #29129
Opened 2024-12-12 10:36 UTC by zone-live

## **Description**

This is the Part 1 of the work to have SOL/BTC transactions history showing in the activity tab, this PR adds the `MultichainTransactionsController` that will be responsible for retrieving Txs from the snap. On the snap side, the followup logic is under development as well.
It also adds already some of the necessary UI to display the Txs in the activity list.

## **Related issues**

Fixes:

## **Manual testing steps**

As of right now, It's not possible to display anything since there's still work being done in the snaps.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-12-12 10:56 UTC, zone-live commented
@metamaskbot update-policies

2024-12-13 04:45 UTC, Mariozisa1 commented
Fusión

2025-01-08 11:09 UTC, ccharly commented on app/scripts/lib/transaction/MultichainTransactionsController.ts
> +      data: Transaction[];
What about renaming this to `transactions` instead? `data` feels a bit too more generic for a state, WDYT?

2025-01-08 11:13 UTC, Mrtenz requested changes, later dismissed
Can you move the controller/tracker to `MetaMask/core`, so it can be reused for mobile as well? I think generally we shouldn't add new controllers to the extension repo directly.

2025-01-08 11:27 UTC, zone-live commented
> Can you move the controller/tracker to `MetaMask/core`, so it can be reused for mobile as well? I think generally we shouldn't add new controllers to the extension repo directly.

@Mrtenz this will happen for sure, it will all be moved to Core repo as follow-up work, it's currently in the extension to speed up our development and make iteration faster.

2025-01-08 11:48 UTC, zone-live commented on app/scripts/lib/transaction/MultichainTransactionsController.ts
> +      );
For Solana we are returning the devnet Txs as well, since one account can have Txs on both sides (mainnet & devnet), and in order for us to test things it's useful. We can add the BTC testnet there as well.
@aganglada any other reason I'm forgetting? I think thats it no?

2025-01-08 14:18 UTC, aganglada commented on app/scripts/lib/transaction/MultichainTransactionsController.ts
> +      );
yes, `getAccountTransactions` is network agnostic (mainnet/devnet)

2025-01-08 14:19 UTC, zone-live commented on ui/components/app/transaction-list/transaction-list.component.js
> +  };
Makes sense, I'll refactor this based on your approach 💪🏼

2025-01-08 14:47 UTC, zone-live commented on shared/types/multichain/transactions.ts
> +};
Yap, also per last talk it will move there, and this PR will be closed. Ref [slack thread](https://consensys.slack.com/archives/C07M5L4U51U/p1736346069505929?thread_ts=1736337000.372069&cid=C07M5L4U51U)

2025-01-08 14:49 UTC, zone-live commented on app/scripts/lib/transaction/MultichainTransactionsController.ts
> +      data: Transaction[];
Can be, yes. 👍🏼

2025-01-08 14:50 UTC, zone-live commented on shared/types/multichain/transactions.ts
> +    };
We will get rid of this now since this controller will be moved to Core and this PR closed.

2025-01-08 14:52 UTC, zone-live commented on ui/components/app/transaction-list/transaction-list.component.js
> +        <Box className="transaction-list__transactions">
Will do

2025-01-08 14:53 UTC, zone-live commented on ui/components/app/transaction-list/transaction-list.component.js
> +                              />
Silly me, forgot to edit those, i've added the values from the `MULTICHAIN_PROVIDER_CONFIGS`, we already had them and I didn't noticed.

2025-01-08 14:54 UTC, zone-live commented on app/scripts/lib/transaction/MultichainTransactionsController.ts
> +    };
Yes!

2025-01-09 10:24 UTC, GuillaumeRx commented on app/scripts/lib/transaction/MultichainTransactionsTracker.ts
This should probably be based on one of the polling controllers available here: https://github.com/MetaMask/core/tree/main/packages/polling-controller/src

2025-01-09 11:22 UTC, zone-live commented on app/scripts/lib/transaction/MultichainTransactionsTracker.ts
Will be doing that now that it's being moved to Core 👍🏼

2025-01-22 14:44 UTC, zone-live commented
@metamaskbot update-policies

2025-01-23 09:57 UTC, aganglada submitted a review, later dismissed

2025-01-23 10:15 UTC, zone-live commented
@metamaskbot update-policies

2025-01-23 10:33 UTC, aganglada approved these changes

2025-01-23 11:28 UTC, FrederikBolding approved these changes
Policy changes LGTM

2025-01-23 14:44 UTC, merged