fix: Temp `BaseController` migration for `Decrypt/Encrypt` message manager
MetaMask/metamask-extension pull request #29237
Opened 2024-12-16 15:19 UTC by OGPoyraz

## **Description**

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2025-01-07 10:47 UTC, jpuri submitted a review, later dismissed

2025-01-07 12:04 UTC, OGPoyraz commented on app/scripts/controllers/decrypt-message.ts
> -      this.hub.emit('updateBadge');
`XMessageManager`s will be emitting the `X:updateBadge` via messaging system hence these are not needed anymore, we directly listen manager event on `background.js`

2025-01-08 21:01 UTC, matthewwalsh0 requested changes

2025-01-08 21:01 UTC, matthewwalsh0 commented on app/scripts/metamask-controller.js
> +      managerMessenger: this.controllerMessenger.getRestricted({
Since the message manager instance is created inside the controller, does it make sense for it to have its own top level messenger? Or should it just rely on the same allowed actions and events from the decrypt controller messenger?

2025-01-09 09:09 UTC, OGPoyraz commented on app/scripts/metamask-controller.js
> +      managerMessenger: this.controllerMessenger.getRestricted({
I think we cannot handle both with one top level messenger because once messenger scoped with `messenger.getRestricted` using passed `name` property, it requires that messenger can only emit events with template of `Name:EventName`.

We could've done that if we extend controller with `DecryptMessageManager` instead of having instance but that actually requires more work than I thought and it's actually the should be the last step of the refactor if we want to pursue that way.

2025-01-09 09:21 UTC, matthewwalsh0 approved these changes, later dismissed

2025-01-17 14:06 UTC, jpuri approved these changes, later dismissed

2025-01-24 07:13 UTC, OGPoyraz commented
@metamaskbot update-policies

2025-01-27 09:49 UTC, matthewwalsh0 approved these changes

2025-01-27 10:04 UTC, jpuri approved these changes

2025-01-27 10:38 UTC, merged