chore: remove mmi e2e tests from ci
MetaMask/metamask-extension pull request #29233
Opened 2024-12-16 14:03 UTC by racitores

## **Description**

MMI e2e tests are not longer maintained so they need to be removed from ci

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-12-16 14:26 UTC, chloeYue approved these changes, later dismissed
LGTM

2024-12-16 14:35 UTC, cmd-ob submitted a review, later dismissed

2025-01-15 01:01 UTC, danjm requested changes
The "Publish MMI release to Sentry" step of the `job-publish-release` job also needs to be removed

2025-01-15 12:22 UTC, dbrans approved these changes
LGTM

2025-01-15 13:31 UTC, Gudahtt approved these changes
LGTM!

2025-01-15 14:01 UTC, danjm approved these changes

2025-01-15 15:59 UTC, merged