chore: add the new policy.json review process documentation and config
MetaMask/metamask-extension pull request #29383
Opened 2024-12-20 10:56 UTC by naugtur

## **Description**

Introducing the document outlining policy review process.

The current change to CODEOWNERS doesn't remove the all devs group - this makes it a soft-launch of the process where a specific approving review is not yet mandatory.

We'll be releasing a training video early January

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/PR?quickstart=1)

## **Related issues**

Fixes:  lack of attention to policy updates

## **Manual testing steps**

1. Follow the process and experience joy

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2025-01-07 12:26 UTC, naugtur commented
Hey, @MetaMask/policy-reviewers would you mind approving the PR that establishes the use of the group? :smile:

2025-01-08 09:08 UTC, Mrtenz approved these changes, later dismissed

2025-01-08 10:15 UTC, Prithpal-Sooriya approved these changes, later dismissed

2025-01-08 13:43 UTC, Gudahtt commented on docs/lavamoat-policy-review-process.md
> +   1. Notice the `validate-lavamoat-policy-*` circleci job fail because dependency updates or changes need a policy update.
We recently migrated this check to GitHub Actions, and the name changed slightly:
```suggestion
   1. Notice the `Validate lavamoat policy*` PR status check fail because dependency updates or changes need a policy update.
```

2025-01-08 13:44 UTC, Gudahtt commented on docs/lavamoat-policy-review-process.md
> +      *Remember the Security Reviewer comes with more security expertise but less intimate knowledge of the codebase and the change you’ve built, so you are the most qualified to know whether the dep
Nit: Accidental extra spaces?
```suggestion
      *Remember the Security Reviewer comes with more security expertise but less intimate knowledge of the codebase and the change you’ve built, so you are the most qualified to know whether the dependency needs the powers detected by LavaMoat or not.*
```

2025-01-08 13:45 UTC, Gudahtt requested changes
Looks great! Just one minor correction

2025-01-08 13:48 UTC, Gudahtt approved these changes

2025-01-08 13:50 UTC, Mrtenz approved these changes

2025-01-08 19:20 UTC, merged