query network version when metamask is back on line
MetaMask/metamask-extension pull request #3004
Opened 2018-01-17 01:34 UTC by frankiebee

partial fix for issue #2636 however their maybe some other things in that issue that i am not considering.

the issue this fixes is that if a provider was created when offline the network spinner goes for ever and a request never goes through for net_version, this should fix that. 

their are subsequent issues that have been discovered in the pursuit of fixing this one:
https://github.com/MetaMask/eth-block-tracker/issues/27
https://github.com/MetaMask/metamask-extension/issues/3003

2018-01-18 02:12 UTC, kumavis submitted a review, later dismissed
nice find, implementation needs some improvements

2018-01-18 02:12 UTC, kumavis commented on app/scripts/controllers/network.js
> +      cb(err, network)
if `err` is truthy, this part will not be reached

2018-01-18 02:12 UTC, kumavis commented on app/scripts/controllers/network.js
> +        return
`cb` not called

2018-01-18 02:12 UTC, kumavis commented on app/scripts/controllers/network.js
> +  lookupNetwork (cb = () => {}) {
define `noop` up by the require statements

2018-01-18 02:12 UTC, kumavis commented on app/scripts/platforms/extension.js
> +  onLine (cb) {
not clearly named

2018-01-18 02:12 UTC, kumavis commented on app/scripts/metamask-controller.js
> +          this.provider.stop()
this is referring to the blockTracker actually, correct?

2018-01-18 02:12 UTC, kumavis commented on app/scripts/metamask-controller.js
> +        })
this is not the correct way to emit updates for MetamaskController

2018-01-25 21:07 UTC, danfinlay commented
Related to #2548

2018-02-01 19:36 UTC, danfinlay requested changes
Also should have a changelog.

Frankie isn't doing well, so I'm going to make my requested changes.

2018-02-01 19:36 UTC, danfinlay commented on app/scripts/controllers/network.js
> +        console.error(err)
Should be `log.error` to use our `loglevel` utility.

2018-02-01 19:36 UTC, danfinlay commented on app/scripts/metamask-controller.js
> +    if (this.platform.addOnLineListener) {
"online" is one word, I'd rather we didn't camel case it into two. Non blocking.

2018-02-01 19:36 UTC, danfinlay commented on app/scripts/platforms/extension.js
> +    window.addEventListener('online', cb)
Yeah camel cased correctly here. Incorrect capitalization kinda driving me nuts, going to change it myself.

2018-02-01 19:46 UTC, danfinlay commented
I can readily reproduce an instance of #2636 on this branch with these steps:

1. Select main network
2. Ensure Ganache/local network is not running
3. Switch to the local network which is not running
4. Turn on the local network/ganache

Results: The network spinner stays on.

The block tracker's `start` method returns a promise that does not seem to get any retries, so only if the disconnect is 

## Regression:

If a test network is successfully connected, and then disconnected, the network indicator is never shown. This seems to me like it breaks the basic functionality of the network connection spinner, and is arguably worse than the current behavior.

I wouldn't want to merge this until the spinner accurately reflects network status.

2018-03-13 23:53 UTC, kumavis commented on app/scripts/platforms/extension.js
> +    return navigator.onLine
sadly, this is the webapi's camelization

2018-03-28 02:44 UTC, kumavis commented
@frankiebee said we can retire this one

2018-03-28 02:44 UTC, closed without merging