Improve transaction retry method
MetaMask/metamask-extension pull request #3051
Opened 2018-01-20 00:44 UTC by danfinlay

Fixes #3011

When the "Retry with higher gas" button is clicked, we now create a
duplicate transaction of that one, so users can more clearly see which
transaction is successful, and if they cancel the retry, it does not
appear to cancel the original transaction.

`Pending-tx-tracker` is now responsible for marking same-nonced txs as
failed when a tx is confirmed as mined.

Unified the tx submission under `pendingTxTracker.submitTx`, to avoid
duplicating its very specific error handling. Renamed `resubmitPendingTx`
to `submitTx` to reflect this more generic purpose.

Moved the tx submission error handling into that method, so it can be
called from outside without duplicating its unique error handling.

### Unrelated:

We now record the time of the first successful tx submission, and use
that to show the retry button, to avoid too-soon "waiting?" buttons.

2018-01-20 00:51 UTC, danfinlay commented
There's still one test failing, probably needs rewriting.

2018-01-22 18:55 UTC, kumavis requested changes

2018-01-22 18:55 UTC, kumavis commented on app/scripts/controllers/transactions.js
> +      publishTransaction: (rawTx) => { return this.query.sendRawTransaction(rawTx) },
this is equivalent

2018-01-22 18:55 UTC, kumavis commented on app/scripts/controllers/transactions.js
> +  async addUnapprovedTransaction (txParams, lastGasPrice = false) {
lets make this 2nd arg an options obj, for the future

2018-01-22 18:55 UTC, kumavis commented on app/scripts/controllers/transactions.js
> +          txMeta.submitTime = Date.now()
there might be a better place to do this, not certain

2018-01-22 18:55 UTC, kumavis commented on app/scripts/lib/pending-tx-tracker.js
> +    const pending = this.getPendingTransactions() || []
this.getPendingTransactions() should return an empty array

2018-01-22 18:55 UTC, kumavis commented on app/scripts/lib/pending-tx-tracker.js
> +        if (txBlockDistance <= Math.pow(2, retryCount) - 1) return
this line could use a comment

2018-01-22 18:55 UTC, kumavis commented on app/scripts/lib/pending-tx-tracker.js
> +      this.emit('tx:failed', txMeta, err)
why are we failing on resubmit?

2018-01-22 18:55 UTC, kumavis commented on app/scripts/lib/tx-state-manager.js
> +    this.updateTx(tx)
i dont think we need updateTx since we are setting status below

2018-01-22 18:55 UTC, kumavis commented on app/scripts/lib/tx-state-manager.js
> +    this.getTxList()
there is a utility for filtering the tx list

2018-01-22 18:55 UTC, kumavis commented on test/unit/pending-tx-test.js
> +      pendingTxTracker.submitTx = async (tx) => {
`submit` vs `resubmit` seems like a semantic change

2018-01-22 18:55 UTC, kumavis commented on ui/app/components/transaction-list-item.js
> +  return status === 'submitted' && ((Date.now() - earliest) > 30000)
thanks for clearer order of operations 👍

2018-01-22 19:10 UTC, kumavis commented on app/scripts/lib/pending-tx-tracker.js
> +      this.emit('tx:failed', txMeta, err)
dont manually set state via `emit`

2018-01-22 19:12 UTC, kumavis commented
> Pending-tx-tracker is now responsible for marking same-nonced txs as
failed when a tx is confirmed as mined.

i thought we already had a mechanism for this, but idk

2018-01-22 19:14 UTC, kumavis commented
we agreed theres some todos here, but had to pick up higher priority items
- dont fail on resubmit
- potentially fail on first submit
- dont manually transition state (emit state event)
- wrap warning emits in a helper

2018-03-07 21:38 UTC, danfinlay commented
Closing in favor of @frankiebee's current work.

2018-03-07 21:38 UTC, closed without merging