Fixes #2562
MetaMask/metamask-extension pull request #3309
Opened 2018-02-22 13:53 UTC by scsaba

As [Edge does not support PBKDF2 algorithm](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9259365/) at the moment, I had to use the [asmcrypto](https://github.com/asmcrypto/asmcrypto.js) package. It is used in case of Edge browser only.

2018-02-23 10:08 UTC, scsaba commented
added tests

2018-02-23 10:12 UTC, scsaba commented
Fixes #2562

2018-02-23 12:28 UTC, scsaba commented
I finished working on this issue, please review my pull request.

2018-02-26 22:19 UTC, Zanibas commented
We are currently in-process of putting it through our pipeline

2018-02-28 17:19 UTC, danfinlay approved these changes
This looks like a good, safe change. I just need to verify that it fixes the Edge compat issue before approving the bounty...

2018-02-28 17:25 UTC, danfinlay commented on app/scripts/edge-encryptor.js
> +const Unibabel = require('browserify-unibabel')
Needs to be added to dependencies.

2018-02-28 18:22 UTC, tmashuang commented
First run through looks really good. The only issue is downloading files such as the JSON state logs and the initial account creation seed phrase text file.  Which are features helps users backup their accounts and the other is for users sending support logs.

2018-02-28 21:12 UTC, danfinlay requested changes
Thomas tried this out and said that address copying still wasn't working, I'd like a verification that this works before approving.

2018-03-01 07:01 UTC, scsaba commented
I"m looking into the file export issue.

2018-03-01 15:15 UTC, scsaba commented
Well, I spent most of my day trying to find a solution to be able to export a file in Edge extension, but it seems it is not feasible at the moment. I tried several approach ([this is the preferred way](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8178877/) in other browsers), but all of them failed with exception (either "script16386: no such interface supported" or "SEC7134: Resource not allowed to load."). So it seems saving a file (/blob) is not possible in an Edge extension. The solutions I tried, work under normal conditions (part of a homepage opened in Edge), so I'm not sure if it is intentional.

One option if you would like to support Edge is removing the possibility of downloading files (seed words, private key, state logs if I'm not mistaken) in Edge. It is far from ideal, but might be tolerable, as these are mostly convenience features.

The address copying is working, please let me know what issue you see with that (steps to reproduce).

2018-03-02 01:49 UTC, danfinlay commented
Cool, once we confirm copying working, I think we can award this. Thanks a lot!

2018-03-02 06:45 UTC, scsaba commented
Hi @tmashuang,

Please let me know what issue you had/have with address copying. I can copy the address using the context menu:

![copyaddress](https://user-images.githubusercontent.com/3006955/36886631-a0d6f23c-1ded-11e8-9259-b0f4d43a0818.PNG)

Thanks!

2018-03-03 21:38 UTC, scsaba commented
@tmashuang meanwhile I checked it using the beta interface, and it also works there.
CC @danfinlay

2018-03-05 18:05 UTC, tmashuang commented
The issue is not with the copy address functionality but with the seed phrase downloading and the state logs.
I will paste the screens.
The extension API that edge doesn't support is `runtime.getPlatformInfo()` which was the issue on my first initial run.
![settingscreen](https://user-images.githubusercontent.com/13376180/36990749-7fc18660-205a-11e8-9114-4c840109fccb.png)
![saveseedscreen](https://user-images.githubusercontent.com/13376180/36990754-81bd6ab0-205a-11e8-9ccc-d00c1253e896.png)

2018-03-05 19:18 UTC, scsaba commented
@tmashuang Yes, runtime.getPlatformInfo() is not supported either, but as I noticed that does not break anything and does not prevent the user from doing anything. Unfortunately saving a file from an edge extension [is not possible currently](https://github.com/MetaMask/metamask-extension/pull/3309#issuecomment-369623726).

@danfinlay it seems there was some confusion [here](https://github.com/MetaMask/metamask-extension/pull/3309#pullrequestreview-100230628), and Thomas [confirmed](https://github.com/MetaMask/metamask-extension/pull/3309#issuecomment-369793433) that address copying is working.

Please let me know if anything more is needed from my side.

2018-03-06 01:20 UTC, danfinlay commented
Looking great @scsaba.

If you could just add `browserify-unibabel` to the `package.json` dependencies, I think we can wrap this up and call it complete. I've contacted our friend at Microsoft about file downloading, so we'll deal with that on our end.

2018-03-06 08:25 UTC, scsaba commented
@danfinlay Now it is added. Sorry I missed this. It was added indirectly by browser-passworder, so the build passed.

2018-03-06 17:39 UTC, danfinlay approved these changes
Looks good, thanks a lot!

2018-03-06 17:39 UTC, merged