Add French translation 🇫🇷
MetaMask/metamask-extension pull request #3545
Opened 2018-03-13 21:09 UTC by vincentlg

resolve #3541

2018-03-13 21:12 UTC, kumavis commented
Awesome, just looking for an approval from a native french speaker

2018-03-14 13:40 UTC, Senshii requested changes
Overall good but there are some changes to do.

2018-03-14 13:40 UTC, Senshii commented on app/_locales/fr/messages.json
> +    "message": "Ethereum navigateur extension",
"Extension Ethereum pour navigateur" should be better

2018-03-14 13:40 UTC, Senshii commented on app/_locales/fr/messages.json
> +    "message": "doit être supérieur ou égal à 1 $ et inférieur ou égal à 2 $",
"$1" instead of "1 $" , same for "$1" instead of "2 $"

2018-03-14 13:40 UTC, Senshii commented on app/_locales/fr/messages.json
> +    "message": "Déposez votre BTC à l'adresse ci-dessous:"
"Déposez vos BTC à l'adresse ci-dessous:" seems better.

2018-03-14 13:40 UTC, Senshii commented on app/_locales/fr/messages.json
> +    "description": "Indique à l'utilisateur quelle pièce ils ont choisi de déposer avec shapeshift"
"Indique à l'utilisateur quelle pièce ils ont choisi de déposer avec shapeshift" -> "Indique à l'utilisateur quelle monnaie ils a choisi de déposer avec shapeshift"

2018-03-14 13:40 UTC, Senshii commented on app/_locales/fr/messages.json
> +    "message": "Dépôt avec Fiat"
"Dépôt avec Fiat" -> "Dépôt de monnaie-fiat"

2018-03-14 13:40 UTC, Senshii commented on app/_locales/fr/messages.json
> +    "message": "Si vous possédez d'autres crypto-monnaies, vous pouvez échanger et déposer Ether directement dans votre portefeuille MetaMask. Aucun compte requis."
"Si vous possédez d'autres crypto-monnaies, vous pouvez échanger et déposer Ether directement dans votre portefeuille MetaMask. Aucun compte requis." -> "Si vous possédez d'autres crypto-monnaies, vous pouvez échanger et déposer de l'Ether directement dans votre portefeuille MetaMask. Aucun compte n'est requis."

2018-03-14 13:40 UTC, Senshii commented on app/_locales/fr/messages.json
> +    "message": "Détails du message"
"Détails du message" -> "Détails"

2018-03-14 13:40 UTC, Senshii commented on app/_locales/fr/messages.json
> +    "message": "Si vous avez déjà de l'Ether, le moyen le plus rapide d'obtenir des Ether dans votre nouveau portefeuille par dépôt direct."
"Si vous avez déjà de l'Ether, le moyen le plus rapide d'obtenir des Ether dans votre nouveau portefeuille par dépôt direct." -> "Si vous avez déjà de l'Ether, le moyen le plus rapide d'obtenir des Ether dans votre nouveau portefeuille est par dépôt direct."

2018-03-14 13:40 UTC, Senshii commented on app/_locales/fr/messages.json
> +    "message": "message de"
"message de" -> "de" ?

2018-03-14 13:40 UTC, Senshii commented on app/_locales/fr/messages.json
> +    "message": "Collez votre seed phrase privée ici:",
"Collez votre seed phrase privée ici:" -> "Collez votre clé privée ici:", there is an error here, it's not the seed but the private key.

2018-03-14 13:40 UTC, Senshii commented on app/_locales/fr/messages.json
> +    "message": "Vous utilisez maintenant la nouvelle interface utilisateur Metamask Jetez un coup d'oeil, essayez de nouvelles fonctionnalités comme l'envoi de jetons, et faites-nous savoir si vous a
"Vous utilisez maintenant la nouvelle interface utilisateur Metamask. Jetez un coup d'oeil, essayez de nouvelles fonctionnalités comme l'envoi de jetons, et faites-nous savoir si vous avez des problèmes." -> "Vous utilisez maintenant la nouvelle interface utilisateur Metamask. Jetez un coup d'oeil, essayez de nouvelles fonctionnalités comme l'envoi de jetons, et faites-nous savoir si vous avez des problèmes."

2018-03-14 17:10 UTC, vincentlg commented
Thank you very much for this review @Senshii 👍 update available here =>  https://github.com/MetaMask/metamask-extension/pull/3545/commits/9963bf6429871e85719e06c096ad81bd5d9eda64

2018-03-14 18:47 UTC, kumavis approved these changes

2018-03-14 18:47 UTC, kumavis commented
Thanks @vincentlg and @Senshii !

2018-03-14 18:47 UTC, merged