Update kr translation to messages.json
MetaMask/metamask-extension pull request #3564
Opened 2018-03-14 17:25 UTC by nujabes403

Updated kr translation to messages.json

I will update more tomorrow 👍

2018-03-15 22:56 UTC, kumavis requested changes

2018-03-15 22:56 UTC, kumavis commented on app/_locales/ko/messages.json
> +    "message": "1 달러 이상 2 달러 이하여야 합니다.",
the 1 and 2 should be $1 and $2

2018-03-15 22:57 UTC, kumavis commented on app/_locales/ko/messages.json
> +    "message": "교환비율"
jee.choi suggested `환율`

2018-03-15 23:33 UTC, JeeChoi reviewed
I don't know if it's important, but every where it says 'ether', it's been translated to 'ethereum' in Korean. For the most part it looks good. There were just a couple words that were awkward or aren't really used.

2018-03-15 23:33 UTC, JeeChoi commented on app/_locales/ko/messages.json
> +  },
The korean word does mean amount but is also the same word for sheep and I don't really see this word being used all the often. I would change it to 금액. same with amountPlusGas

2018-03-15 23:33 UTC, JeeChoi commented on app/_locales/ko/messages.json
> +    "message": "유효"
I don't think this is the right word for available. It means 'valid' or 'of pertinence'

2018-03-15 23:33 UTC, JeeChoi commented on app/_locales/ko/messages.json
> +    "message": "생성"
maybe should be 'DEN 생성.  Though 생성 is also an awkward word

2018-03-15 23:33 UTC, JeeChoi commented on app/_locales/ko/messages.json
> +    "message": "가스 설정"
This says 'select Gas'

2018-03-15 23:33 UTC, JeeChoi commented on app/_locales/ko/messages.json
> +    "message": "교환비율"
change to 환율 works better

2018-03-15 23:33 UTC, JeeChoi commented on app/_locales/ko/messages.json
> +    "message": "최소"
this says 'cancel' in korean

2018-03-15 23:33 UTC, JeeChoi commented on app/_locales/ko/messages.json
> +    "message": "비밀키 스트링을 붙여넣어주세요.",
I would change to "비밀키 입력해주세요" should roughly translates to 'please input private key'

2018-03-15 23:33 UTC, JeeChoi commented on app/_locales/ko/messages.json
> +    "message": "코인베이스로 계속하기"
코인베이스로 계속하기 should be 코인베이스로 계속가기

2018-03-16 05:28 UTC, nujabes403 commented
Thank you for review. I changed some word according to your comment.
@kumavis @JeeChoi

2018-03-17 21:15 UTC, kumavis approved these changes

2018-03-17 21:16 UTC, merged

2018-03-18 04:02 UTC, nujabes403 commented
@kumavis Thank you! It's really nice to be a member of Metamask team :)