Italian translation
MetaMask/metamask-extension pull request #3579
Opened 2018-03-15 17:52 UTC by matteopey

Fixes #3548
I will ask to some italian people to review. :)

2018-03-15 21:31 UTC, fiblan requested changes
Just only one change

2018-03-15 21:31 UTC, fiblan commented on app/_locales/it/messages.json
> +    "message": "La tua firma sta venendo richiesta"
"E' richiesta la tua firma" or "La tua firma è richiesta"

2018-03-19 17:03 UTC, tmashuang commented
We have made added more to the `messages.json` file, please update and add.

2018-03-20 17:48 UTC, kumavis approved these changes

2018-03-20 17:48 UTC, merged

2018-03-20 18:24 UTC, kumavis commented
@fiblan Please accept the invitation to the MetaMask translator team https://github.com/MetaMask