updated ethereum, coinbase spellings. removed typo errors
MetaMask/metamask-extension pull request #3839
Opened 2018-04-03 09:22 UTC by vikaskyadav

2018-04-03 17:58 UTC, kumavis requested changes

2018-04-03 17:58 UTC, kumavis commented on app/_locales/index.json
> +  { "code": "tml", "name": "Tamil" },
we dont have a Tamil locale yet so we can't add it to the index

2018-04-03 20:18 UTC, kumavis commented
@vikaskyadav thanks for the improvements to Hindi!

 can you add a Tamil translation or remove the Tamil reference from the locales index.json

2018-04-04 02:46 UTC, ctrlaltvikas reviewed
removed the Tamil shortcode from index.json. will add that later on.

2018-04-10 09:11 UTC, kumavis approved these changes

2018-04-10 09:11 UTC, kumavis commented
@vikaskyadav wow thanks for adding Tamil!

2018-04-10 09:12 UTC, kumavis commented
note to merger: please squash and merge

2018-04-10 12:35 UTC, vikaskyadav commented
@kumavis . It was supposed to be a PR for gitcoin. We were already discussing in https://github.com/MetaMask/metamask-extension/issues/3549#issuecomment-3795027591
So, do I need to raise the PR since you already have merged?
Let me know I have to Submit the work on gitcoin too

2018-04-18 17:33 UTC, merged

2018-04-18 17:33 UTC, kumavis commented
@vikaskyadav sorry for the delay-- merged!