Documentation for various controllers and and lib utils
MetaMask/metamask-extension pull request #3987
Opened 2018-04-16 17:10 UTC by danjm

2018-04-16 22:40 UTC, whymarrh requested changes

2018-04-16 23:52 UTC, danjm commented on app/scripts/controllers/shapeshift.js
> +   * @constant {string} key - The 'shapeshift' key differentiates this from other types of txs in Metamask
Is it incorrect to use `@constant`? The issue is that this property will always be the string `'shapeshift'`, and I think that should be indicated in some way.

2018-04-16 23:54 UTC, danjm commented
@whymarrh I believe I address all your comments in 23acddf, cc7e714 and e9ca7199

2018-04-18 02:07 UTC, whymarrh commented on app/scripts/controllers/shapeshift.js
> +   * @constant {string} key - The 'shapeshift' key differentiates this from other types of txs in Metamask
From reading the docs, I think this should be `@property`. It also seems that's what tooling recognizes (TS and my IDE at least)

2018-04-18 02:50 UTC, whymarrh commented
@danjm outside of that last comment above this LGTM

2018-04-18 02:55 UTC, whymarrh commented
One other thing I might comment on is that some of the docblocks added have introduced mixed tabs and spaces (e.g. `currency.js`) so it might be worth updating those from now

2018-04-18 18:42 UTC, danjm commented on app/scripts/controllers/shapeshift.js
> +   * @constant {string} key - The 'shapeshift' key differentiates this from other types of txs in Metamask
Fixed in 6d96b1a2

2018-04-18 18:42 UTC, danjm commented
> One other thing I might comment on is that some of the docblocks added have introduced mixed tabs and spaces (e.g. currency.js) so it might be worth updating those from now

Fixed in e80bd230

2018-04-18 20:27 UTC, whymarrh approved these changes
LGTM

2018-04-18 20:39 UTC, merged