Documentation
MetaMask/metamask-extension pull request #4020
Opened 2018-04-18 21:05 UTC by bitpshr

This PR adds JSDoc where applicable to the following modules:

```
app/scripts/config.js
app/scripts/contentscript.js
app/scripts/edge-encryptor.js
app/scripts/first-time-state.js
app/scripts/inpage.js
app/scripts/popup-core.js
```

2018-04-18 23:19 UTC, danfinlay requested changes
A few spelling changes, a conceptual note, a few fun facts, and maybe we remove the jsdoc build output from git?

2018-04-18 23:38 UTC, bitpshr commented on app/scripts/popup-core.js
> + * @param {{ container: Element, connectionStream: any }} config Popup configuration object
JSDoc technically supports most DOM interfaces as actual types. `Element`, or even `HTMLElement` to be more specific, are valid JSDoc types. `any` is actually TypeScript, so good catch there. It should be an asterisk.

2018-04-18 23:39 UTC, bitpshr commented on app/scripts/popup-core.js
> + * @param {any} connectionStream PortStream instance establishing a background connection
Agreed. We could define one ourselves, but TypeScript...built in...soon 🙏

2018-04-18 23:41 UTC, bitpshr commented on docs/jsdocs/config.js.html
> +<!DOCTYPE html>
Cool. For PR clarity I removed them from version control as part of this PR and updated the `.gitignore`.

2018-04-19 00:32 UTC, danfinlay requested changes
Sorry, I only wanted `jsdocs` out of repo, other docs are good!

2018-04-19 00:32 UTC, danfinlay commented on .gitignore
> +docs
Only ignore `docs/jsdocs` please! Other docs are good, just trying to reduce things that can be rebuilt on each commit.

2018-04-19 01:48 UTC, bitpshr commented
@danfinlay good catch, thanks. PR updated.

2018-04-19 18:39 UTC, bitpshr commented
A few more files documented @danfinlay.

2018-04-19 19:06 UTC, bitpshr commented on app/scripts/contentscript.js
> + * @returns {boolean} True of Web3 should be injected
I didn't know this was actually valid for type in JSDoc. I thought this was only a shortcut to render `true` (or any other code fragment) in place of a parameter. I'm inclined to leave `boolean` to let parsers do their thing.

2018-04-19 19:10 UTC, whymarrh commented on app/scripts/contentscript.js
> + * @returns {boolean} True of Web3 should be injected
Sorry, yeah, I was referring to the description: `{@code true} of Web3 should be injected`

2018-04-19 19:10 UTC, whymarrh commented on app/scripts/contentscript.js
> + * @returns {boolean} True of Web3 should be injected
(Also just noticed "of" should be "if".)

2018-04-19 19:10 UTC, bitpshr commented on app/scripts/popup-core.js
> + * @param {*} connectionStream PortStream instance establishing a background connection
We should actually just be able to use `PortDuplexStream` as a type. Updated.

2018-04-19 19:12 UTC, bitpshr commented on app/scripts/contentscript.js
> + * @returns {boolean} True of Web3 should be injected
Ah, I see. Good call!

2018-04-19 19:14 UTC, bitpshr commented
@whymarrh thanks for the great feedback. This should be ready for another review when you have a chance.

2018-04-19 19:56 UTC, whymarrh approved these changes
LGTM!

2018-04-19 20:34 UTC, bitpshr commented
@danfinlay this should be ready for another review when you have a chance. Thanks!

2018-04-20 21:09 UTC, danfinlay approved these changes
Awesome, thank you!

2018-04-20 21:10 UTC, merged