Wraps calls to symbol() and decimals() in try catch (Fixes #4107)
MetaMask/metamask-extension pull request #4113
Opened 2018-04-27 23:17 UTC by danjm

Fixes #4107

![sendtokenswithoutsymboldecimals](https://user-images.githubusercontent.com/7499938/39388634-2063de58-4a5c-11e8-9431-36139af73e3d.gif)

2018-04-27 23:23 UTC, kumavis requested changes
handle case where decimals is 0

2018-04-27 23:23 UTC, kumavis requested changes

2018-04-27 23:28 UTC, whymarrh commented on ui/app/token-util.js
> +    return {
Could we return the `exisitingToken`?

2018-04-28 00:06 UTC, danjm commented on ui/app/components/pending-tx/index.js
> +    if (symbol && decimals) {
Handled in b71dbf52

Note that change assumes that the contract `decimal` method will return a `uint` (which ethjs-abi will return to as a BN).

2018-04-28 00:09 UTC, danjm commented on ui/app/token-util.js
> +    return {
Done in 9f9e8789

2018-04-28 00:15 UTC, kumavis approved these changes

2018-04-28 01:21 UTC, merged