Fixes #4534
MetaMask/metamask-extension pull request #4552
Opened 2018-06-12 13:45 UTC by flo-pereira

fix https://github.com/MetaMask/metamask-extension/issues/4534, that happen when blockGasLimit exceed 4503599627370496 and the problem is that metamask completly  freeze after that, forcing it to be reinstalled in extension panel.

2018-06-13 17:14 UTC, Zanibas commented
If I may ask, why is 9007199254740992 a significant number for the gasLimit to begin breaking the application?

2018-06-14 03:29 UTC, kumavis commented
can BN interpret a hex string correctly? this seems incorrect as it removes the parseInt call
ideally we have BN directly take the hex string and dont parseInt on it

2018-06-14 03:29 UTC, kumavis requested changes
can BN interpret a hex string correctly? this seems incorrect as it removes the parseInt call
ideally we have BN directly take the hex string and dont parseInt on it

2018-06-14 05:02 UTC, kumavis commented
related #4568

2018-06-15 08:01 UTC, flo-pereira commented
@kumavis done

2018-06-18 19:37 UTC, kumavis commented
BN does not accept hex-prefixed strings
```js
new BN('0x01', 16).toString(10)
//=> '2049'
```

2018-07-05 16:37 UTC, bdresser commented
@kumavis is this good to go, or do you still need changes from @flo-pereira? couple people asking

2018-07-10 08:02 UTC, flo-pereira commented
@kumavis fix

2018-07-18 12:33 UTC, whymarrh commented
@flo-pereira rebasing this on `develop` should get the build to pass (thanks for the PR btw!)

2018-09-12 19:02 UTC, bdresser commented
@flo-pereira bumping this - quick rebase could get this merged in! thanks

2018-09-13 07:16 UTC, flo-pereira commented
@bdresser @whymarrh .. rebase done but required test "test-integration-mascara-firefox" still failed

2018-09-13 17:46 UTC, whymarrh commented
@flo-pereira thanks! I think we can take care of the failures on our end.

@kumavis when you get a minute can you take a look at this? (Or dismiss your review if it's been addressed?)

2019-02-12 19:06 UTC, danjm commented
Thanks again for the contribution. This changes the old-ui which is no longer used. Closing.

2019-02-12 19:06 UTC, closed without merging