refactor gas-fee-display component
MetaMask/metamask-extension pull request #4627
Opened 2018-06-21 06:44 UTC by TrejGun

#4622

2018-06-21 10:47 UTC, TrejGun commented
I don't uderstad why it can't find button by text
there where no text before
https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/components/send/gas-fee-display-v2.js#L49

2018-06-21 17:10 UTC, danjm commented
Thanks @TrejGun! I will review and also provide some help on getting those tests passing within the next 24 hours.

2018-06-22 18:09 UTC, danjm commented
Code looks good @TrejGun ! And nice job on the unit tests. I'll investigate why e2e and integration tests are failing.

2018-06-22 18:09 UTC, danjm approved these changes

2018-06-22 18:14 UTC, danjm commented on ui/app/components/pending-tx/confirm-send-ether.js
> +const GasFeeDisplay = require('../send_/send-content/send-gas-row/gas-fee-display/gas-fee-display.component')
Needs to be `const GasFeeDisplay = require('../send_/send-content/send-gas-row/gas-fee-display/gas-fee-display.component').default`

Read here for explanation: https://stackoverflow.com/questions/33704714/cant-require-default-export-value-in-babel-6-x

2018-06-22 18:14 UTC, danjm commented on ui/app/components/pending-tx/confirm-send-token.js
> +const GasFeeDisplay = require('../send_/send-content/send-gas-row/gas-fee-display/gas-fee-display.component.js')
Needs to be `const GasFeeDisplay = require('../send_/send-content/send-gas-row/gas-fee-display/gas-fee-display.component').default`

Read here for explanation: https://stackoverflow.com/questions/33704714/cant-require-default-export-value-in-babel-6-x

2018-06-22 18:15 UTC, danjm requested changes
@TrejGun just made two comments on the code. I think if you fix that, the tests will pass.

2018-06-23 00:06 UTC, TrejGun commented
oh, my bad, fixed

2018-06-23 00:11 UTC, TrejGun commented
what do you think about making `contextTypes` a static prop same as `propTypes`?

2018-06-26 18:53 UTC, danjm approved these changes

2018-06-26 18:55 UTC, danjm commented
> what do you think about making contextTypes a static prop same as propTypes

I think that is a good idea. Do you want to do it in a separate PR?

2018-06-26 18:55 UTC, merged

2018-06-29 08:22 UTC, TrejGun commented
@danjm i do

2018-07-02 02:12 UTC, TrejGun commented
@danjm #4702