refactor and fix AccountDetailsModal
MetaMask/metamask-extension pull request #4722
Opened 2018-07-04 01:29 UTC by TrejGun

2018-07-04 19:46 UTC, danjm commented
@TrejGun What "fix" is included in this PR?

2018-07-05 02:10 UTC, TrejGun commented
@danjm path was wrong in lines
```
const NewAccountCreateForm = require('./create-form')
const NewAccountImportForm = require('../import')
```

2018-07-23 22:38 UTC, danjm requested changes

2018-07-23 22:38 UTC, danjm commented on ui/app/accounts/new-account/index.js
> +export { default } from './new-accout.container'
Can you correct the name `./new-accout.container` to `./new-account.container`

2018-09-27 01:54 UTC, closed without merging