Further new ui e2e test improvements
MetaMask/metamask-extension pull request #4868
Opened 2018-07-24 19:46 UTC by danjm

This PR attempts to improve new UI e2e beta tests in three places that continue to be unreliable:
- the setup process in metamask-beta-ui.spec.js is now also used in from-import-beta-ui.spec.js (7598c75)
- the seed word confirmation step now won't error if two or more of the seed words are the same (d5ef7ce)
- the waits for deployment of the test contract are now more explicit and reliable (db175ad)

2018-07-27 20:26 UTC, whymarrh requested changes
A few comments

2018-07-27 22:52 UTC, danjm commented on test/e2e/beta/from-import-beta-ui.spec.js
> +        await loadExtension(driver, extensionId)
> Is this intending to reload the extension as an error handling mechanism?

yes

2018-08-06 14:29 UTC, whymarrh reviewed
One small non-blocking nitpick

2018-08-06 14:29 UTC, whymarrh commented on test/e2e/beta/metamask-beta-ui.spec.js
> +      const word0 = await findElement(driver, By.xpath(xpath), 10000)
This can be `word` now that we only have the one

2018-08-06 14:29 UTC, whymarrh submitted a review, later dismissed
LGTM once the tests pass

2018-08-06 15:08 UTC, whymarrh approved these changes

2018-08-06 18:01 UTC, merged