tx-gas-utils -  catch all errors from gas estimation
MetaMask/metamask-extension pull request #4871
Opened 2018-07-24 21:26 UTC by jennypollack

estimateGas can fail for reasons other than the two previously captured in "simulationFailed"

This change propagates that there was an error with the transaction to the UI but still allows the user to submit the transaction if they wish.

Fixes https://github.com/MetaMask/metamask-extension/issues/3519, uses txMeta to calculate gas in old-ui/app/components/pending-tx.js

Additional improvements are to pass on the actual errors to the UI. #4870

2018-07-24 21:46 UTC, alextsg approved these changes

2018-07-26 01:26 UTC, frankiebee submitted a review, later dismissed
great

2018-07-26 01:30 UTC, frankiebee requested changes

2018-07-26 01:30 UTC, frankiebee commented on app/scripts/controllers/transactions/tx-gas-utils.js
> +      txMeta.simulationFails = {
i would consider keeping the same key name `simulationFailed` unless their is also the ui changes to go with this

2018-07-26 01:33 UTC, frankiebee approved these changes

2018-07-26 01:33 UTC, frankiebee commented on app/scripts/controllers/transactions/tx-gas-utils.js
> +      txMeta.simulationFails = {
oooh i see now

2018-07-26 01:33 UTC, merged