Another e2e beta test fix
MetaMask/metamask-extension pull request #5059
Opened 2018-08-14 03:11 UTC by danjm

Line 519 of https://github.com/MetaMask/metamask-extension/compare/e2e-tests-more-reliable?expand=1#diff-b00929238ad0453812af55a40336e889 was incorrectly matching the text on line 14 of test/e2e/beta/contract-test/index.html before the contract deploy was actually complete.

By updating the text on line 14 of test/e2e/beta/contract-test/index.html, these tests should now more consistently pass.

This PR also adds timeouts to a few places in the metamask-beta-ui specs.

2018-08-14 09:57 UTC, whymarrh requested changes

2018-08-14 09:57 UTC, whymarrh commented on test/e2e/beta/metamask-beta-ui.spec.js
> +      let contractStatus = await driver.findElement(By.css('#contractStatus'), 10000)
Can we use `await findElement(driver, By.css(...))` as that already has the longer timeout?

2018-08-14 09:57 UTC, whymarrh commented on test/e2e/beta/metamask-beta-ui.spec.js
> +      let contractStatus = await driver.findElement(By.css('#contractStatus'), 10000)
Similarly for all instances below

2018-08-14 13:45 UTC, whymarrh commented
> Line 519 of [...] was incorrectly matching the text on line 14 of [...] before the contract deploy was actually complete

How do we know this is the case? I don't _think_ that should happen given that the regex isn't flagged as case-insensitive (that is, it _is_ case-sensitive) and where it is `/Deployed/` and not `/deployed/` the regex shouldn't match the original text.

2018-08-14 15:18 UTC, danjm commented
> How do we know this is the case? I don't think that should happen given that the regex isn't flagged as case-insensitive (that is, it is case-sensitive) 

@whymarrh yeah, when I wrote that I was thinking that regex is case-sensitive by default. Sometimes I forget how regex works after midnight.

I have completely updated the PR description and commits.

2018-08-14 16:48 UTC, whymarrh commented
> I will leave this PR open until we get the firefox tests constistently passing.

I guess we still have a bit of digging to do—`test-e2e-beta-firefox` is failing with the new timeout

2018-08-14 16:52 UTC, whymarrh commented on test/e2e/beta/contract-test/contract.js
> +      } else if (typeof contract.address !== 'undefined') {
I don't think this `else` is needed since we're throwing in `if (e)`

2018-08-15 00:59 UTC, whymarrh approved these changes

2018-08-15 14:40 UTC, merged