Add sidebar component
MetaMask/metamask-extension pull request #5129
Opened 2018-08-23 03:08 UTC by danjm

- Extracts the code for the wallet-view sidebar (visible in the popup view) from app.js and into its own component.
- Adds code for a sidebar from the left side (for future use)
- refactors redux handling of sidebar state to allow for other types of sidebars with different types of content

All current functionality is maintained
![sidebarrightgif](https://user-images.githubusercontent.com/7499938/44502557-a9c8fb80-a66c-11e8-8516-3a9e93075e88.gif)

This will allow for the following sort of sidebar in the future (code for this sidebar is not in this PR):
![customizegassidebar](https://user-images.githubusercontent.com/7499938/44502589-c9602400-a66c-11e8-93a4-98894946869f.gif)

2018-08-23 11:16 UTC, whymarrh requested changes

2018-08-23 11:16 UTC, whymarrh commented on ui/app/components/tx-view.js
> + dispatch(actions.showSidebar({
Nit: this indentation needs adjusting

2018-08-23 11:16 UTC, whymarrh commented on ui/app/components/sidebars/index.scss
> +  // top: 41px;
If we don't need this can we remove this line?

2018-08-23 11:48 UTC, danjm commented
@whymarrh I made the requested changes

2018-08-27 22:02 UTC, alextsg commented on ui/app/components/sidebars/sidebars.component.js
> +      case 'wallet-view':
Would probably be good to turn these cases into constants at some point.

2018-08-27 22:04 UTC, alextsg commented on ui/app/components/sidebars/sidebars.component.js
> +    switch (type) {
nit: can we include a default case to return `null`?

2018-08-27 22:04 UTC, alextsg submitted a review, later dismissed

2018-09-04 14:34 UTC, whymarrh approved these changes

2018-09-04 18:49 UTC, merged