Connect the gas-button-group component to redux and a live api.
MetaMask/metamask-extension pull request #5214
Opened 2018-09-06 16:22 UTC by danjm

This PR connects the GasPriceButtonGroup to live data from the ethgasstation api.

Note two architectural choices:
(1) The data from state is already formatted and renderable when passed to the component. No operations are made on the data in the `*.component.js` files
(2) Only the `GasModalPageContainer` is connected to state. Data is directly passed to its children and its children's children.

![buttongroupconnected](https://user-images.githubusercontent.com/7499938/45171116-22d36180-b1dc-11e8-8af2-1fe7b55b95c8.gif)

2018-09-07 21:02 UTC, whymarrh submitted a review, later dismissed
Two defaults that might be worth adjusting

2018-09-07 21:02 UTC, whymarrh commented
On the two choices:

> The data from state is already formatted and renderable when passed to the component. No operations are made on the data in the `*.component.js` files

I'm cool with this, it seems fine in this PR for sure

> Only the `GasModalPageContainer` is connected to state. Data is directly passed to its children and its children's children

Again, in the context of this PR, it looks pretty good

2018-09-09 16:35 UTC, danjm commented on ui/app/components/gas-customization/gas-modal-page-container/basic-tab-content/basic-tab-content.component.js
> +          {...this.props.gasPriceButtonGroupProps}
addressed in https://github.com/MetaMask/metamask-extension/pull/5214/commits/5132fff633837026b8cf7c2decdc7fa8d7a85330

2018-09-09 16:35 UTC, danjm commented on ui/app/components/button-group/button-group.component.js
> +      : this.props.defaultActiveButtonIndex || 0,
addressed in https://github.com/MetaMask/metamask-extension/pull/5214/commits/5132fff633837026b8cf7c2decdc7fa8d7a85330

2018-09-15 05:34 UTC, whymarrh requested changes
Two quick nitpicks about `console.log`s that we should probably remove

2018-09-15 05:34 UTC, whymarrh commented on ui/app/components/gas-customization/gas-modal-page-container/basic-tab-content/basic-tab-content.component.js
> +          handleGasPriceSelection={(newPrice) => console.log('New Price:', newPrice)}
Nit: `console.log`

2018-09-15 05:34 UTC, whymarrh commented on ui/app/components/gas-customization/gas-modal-page-container/gas-modal-page-container.container.js
> +    handleGasPriceSelection: newPrice => console.log('NewPrice: ', newPrice),
Nit: `console.log`

2018-09-18 16:13 UTC, danjm commented
@whymarrh I forgot that console.logs are removed in a downstream PR. Merging

2018-09-18 16:13 UTC, merged