Fix rounding issue when sending max tokens
MetaMask/metamask-extension pull request #5695
Opened 2018-11-07 23:29 UTC by alextsg

Fixes #5682

2018-11-08 02:34 UTC, whymarrh requested changes
Two small comments but otherwise this looks good to me

2018-11-08 02:34 UTC, whymarrh commented on test/e2e/beta/metamask-beta-ui.spec.js
> +        assert.equal(await tokenBalanceAmount.getText(), '43\nTST')
We could use `\s` here in a regular expression, similar to how we have below:

```js
await driver.wait(until.elementTextMatches(balance, /0\s*BAT/))
```

2018-11-08 02:34 UTC, whymarrh commented on ui/app/components/currency-display/currency-display.container.js
> +    displayValue = propsDisplayValue || formatCurrency(convertedValue, toCurrency)
If we inline `convertedValue` could we write this as a single `cost displayValue` statement without the conditional?

2018-11-08 10:10 UTC, danjm commented on ui/app/components/send/send.component.js
> +window.BigNumber = BigNumber
why do we need to put `BigNumber` on `window`? I'm guess this was just for local development/testing purposes?

2018-11-09 14:27 UTC, whymarrh submitted a review, later dismissed

2018-11-11 22:58 UTC, danjm commented
I made a PR against this branch to fix a minor issue: https://github.com/alextsg/metamask-extension/pull/2

2018-11-11 23:17 UTC, danjm commented
QA'd. All looks good.

As a separate issue, we may want to deal with cases with a lot of significant digits on the confirm screen

![screenshot from 2018-11-11 19-45-45](https://user-images.githubusercontent.com/7499938/48319616-9766ba00-e5ea-11e8-8fd1-5762d289c6c2.png)

2018-11-12 17:37 UTC, alextsg commented
@danjm Merged your PR and noticed that tests were failing due to number inputs. Why was it necessary to remove the `Number()` part from `return Number(decimalValueString) || 0` in `token-input.component.js`? `getDecimalValue` is expected to return a number instead of a string so it's causing some input issues.

2018-11-13 21:44 UTC, danfinlay commented
Fixes #5180.

2018-11-20 00:04 UTC, danjm approved these changes

2018-11-20 00:06 UTC, merged