Add visual indicator when displaying a cached balance.
MetaMask/metamask-extension pull request #5854
Opened 2018-11-29 16:08 UTC by danjm

this branches off of https://github.com/MetaMask/metamask-extension/pull/5843

This adds an asterix next to balances to indicate to the user that the displayed balances may be cached.

![balance-outdated](https://user-images.githubusercontent.com/7499938/49234749-33f2cf80-f3d3-11e8-898b-5ae7f14093a6.jpeg)

----

![screenshot from 2018-11-29 12-35-21](https://user-images.githubusercontent.com/7499938/49234784-440aaf00-f3d3-11e8-951d-07e20d7895ee.png)

@cjeria Does this look okay to you? The scenario is that the user is being shown a balance that might be slightly outdated (i.e. a small number of blocks old). The user would be shown this balance because of connectivity issues. We are deciding here that it is better to show an outdated balance than nothing or a zero balance.

Also ccing @bahnju as I imagine we will also start consulting you on this sort of stuff soon

2019-01-24 22:41 UTC, whymarrh requested changes

2019-01-24 22:41 UTC, whymarrh commented on ui/app/components/index.scss
> +// @import './send/account-list-item/account-list-item/index';
Can we remove this?

2019-01-30 05:41 UTC, danjm commented on ui/app/components/index.scss
> +// @import './send/account-list-item/account-list-item/index';
removed

2019-01-30 12:15 UTC, whymarrh approved these changes

2019-01-30 12:16 UTC, merged