Group transactions by nonce
MetaMask/metamask-extension pull request #5886
Opened 2018-12-05 23:59 UTC by alextsg

Fixes #5544 
Fixes #5732 
Fixes #5809

![image](https://user-images.githubusercontent.com/8051479/49552061-c0efca00-f8a6-11e8-8303-c378db4accdd.png)
![image](https://user-images.githubusercontent.com/8051479/49552039-afa6bd80-f8a6-11e8-8692-a6d707d0b33e.png)
![image](https://user-images.githubusercontent.com/8051479/49551998-753d2080-f8a6-11e8-9e0b-3b1c155b3df5.png)

2018-12-06 01:10 UTC, alextsg commented
@bdresser np, that won't be a huge change if we decide to do that.

2018-12-06 20:00 UTC, bdresser commented
Notes from kyo sync:
* Current Etherscan button pops open the most recent tx – how do we link to Etherscan for the previous transactions? We can use the tiny little up arrow, could even link the whole line.
* Remove the transaction counter

2018-12-06 22:08 UTC, cjeria commented
@alextsg @bdresser Here's an option for repositioning the attempts counter outside of the pill and adding a bit more copy for context. Thoughts?

![image](https://user-images.githubusercontent.com/597770/49614793-2668b700-f98a-11e8-8881-f47684b6efe0.png)

2018-12-06 23:10 UTC, alextsg commented
@cjeria I'm not too sure about the "No attempts made" option because we'd have a clickable link within a clickable container, and if that can be a confusing interaction for users. Also, I kind of see Cancel being grouped together with Speed Up in terms of functionality. Would it make sense to keep them together as they were before?

2018-12-07 05:36 UTC, alextsg commented
![image](https://user-images.githubusercontent.com/8051479/49629471-81a4a480-f99e-11e8-9b0c-0fa84b269411.png)
Updated to remove the transaction counter and link each activity in the activity log to Etherscan.

2018-12-07 15:00 UTC, cjeria commented
@alextsg 

> I'm not too sure about the "No attempts made" option because we'd have a clickable link within a clickable container

I agree. This was an attempt at surfacing the `speed up` button to address some complaints we've  recently received from support tickets that some users don't see or know that they can speed up the transaction. Let's keep it as you have it for now and we'll iterate on this some more. Maybe @bahnju can take a pass at some other options for surfacing up the `speed up` label per tx?

Re: the clickable activity link to etherscan - is the blue highlighted activity in your screenshot a hover state? If so, I'd suggest we make the hover state solid black on hover and use a lighter grey (same color as activity icons #9B9B9B) for the default state of all activity lines and `cursor:pointer` to indicate it's also a link.

Also, when did the details container bg color is get so dark? I have it at #FAFBFC in the designs.

![image](https://user-images.githubusercontent.com/597770/49654612-19de7000-fa17-11e8-8e74-9c548a90822b.png)

Sorry for the nitpicks!

2018-12-07 18:12 UTC, alextsg commented
@cjeria Yeah the blue was a hover state, and sure I'll make those color changes. I welcome the nitpicks!

2018-12-08 01:14 UTC, whymarrh requested changes
A few small nitpicks. Some general feedback:

- It might be good to document the new functions added to `ui/app/selectors/transactions.js` from now while it's still fresh
- I skipped reading the CSS

2018-12-08 01:14 UTC, whymarrh commented on ui/app/components/transaction-activity-log/transaction-activity-log-icon/transaction-activity-log-icon.component.js
> +    eventKey: PropTypes.oneOf([
Can we use the keys from `imageHash` here to keep them in sync?

2018-12-08 01:14 UTC, whymarrh commented on ui/app/components/transaction-list-item/transaction-list-item.component.js
> +  handleRetry = id => {
If we're gonna a JSDoc here, we should document the `id` param too

2018-12-08 01:14 UTC, whymarrh commented on ui/app/selectors/transactions.js
> +    console.log('SELECTOR', transactions)
Do we need this log here?

2018-12-08 08:15 UTC, alextsg commented
Updated PR

2018-12-08 18:49 UTC, whymarrh approved these changes

2018-12-08 18:49 UTC, whymarrh commented
LGTM

2018-12-09 20:48 UTC, merged