Loading network screen
MetaMask/metamask-extension pull request #5893
Opened 2018-12-08 00:46 UTC by danjm

fixes https://github.com/MetaMask/metamask-extension/issues/3776

![peek 2018-12-07 21-14](https://user-images.githubusercontent.com/7499938/49679361-4ae59180-fa65-11e8-8193-5820041cfacf.gif)

2018-12-08 00:56 UTC, whymarrh requested changes
A couple of small nitpicky things. Also should we write `LoadingNetworkError` as a class for consistency sake?

2018-12-08 00:56 UTC, whymarrh commented on ui/app/components/loading-network-screen/loading-network-screen.component.js
> +    this.state = {
We can move this out of the ctor and onto the class as a property

2018-12-08 00:56 UTC, whymarrh commented on ui/app/components/loading-network-screen/loading-network-screen.component.js
> +class LoadingNetworkScreen extends Component {
Can we use `PureComponent` here?

2018-12-08 00:56 UTC, whymarrh commented on ui/app/components/loading-network-screen/loading-network-screen.component.js
> +LoadingNetworkScreen.propTypes = {
Can we can move this into the class a property?

2018-12-08 01:08 UTC, alextsg requested changes

2018-12-08 01:08 UTC, alextsg commented on ui/app/components/loading-network-screen/loading-network-screen.component.js
> +          { 'Switch Networks' }
Should this and "Try Again" below be translated strings?

2018-12-08 01:08 UTC, alextsg commented on ui/app/components/modals/loading-network-error/loading-network-error.component.js
> +        description={'Oops! Something went wrong.'}
Should this be translated text?

2018-12-08 01:08 UTC, alextsg commented on ui/app/components/transaction-list/transaction-list.component.js
> +    return id === transactionToRetry.id && Date.now() - submittedTime > 3000
Should this change be committed? Or was the time reduced to 3 seconds for testing purposes?

2018-12-08 01:08 UTC, alextsg commented on ui/app/selectors.js
> +
nit: remove newline

2018-12-10 17:32 UTC, danjm commented
@alextsg @whymarrh Addressed your comments in latest commit

2018-12-11 18:57 UTC, bdresser commented
seeing a little funky text display `[SWITCHNETWORKS]`, maybe due to the translations? 

<img width="334" alt="screen shot 2018-12-11 at 10 53 14 am" src="https://user-images.githubusercontent.com/1016190/49823015-8a490200-fd33-11e8-9a40-a1e0b7010283.png">

2018-12-12 17:33 UTC, whymarrh requested changes
One small issue (I think)

2018-12-12 17:33 UTC, whymarrh commented on app/_locales/en/messages.json
> +  "switchNetworks": {
This looks like a formatting error?

2018-12-12 17:33 UTC, whymarrh commented on app/_locales/en/messages.json
> +  "switchNetworks": {
I think there should be a closing brace on the line above

2018-12-13 15:56 UTC, whymarrh approved these changes

2018-12-13 16:33 UTC, alextsg approved these changes

2018-12-13 17:50 UTC, merged