Feature flag mobile sync
MetaMask/metamask-extension pull request #5955
Opened 2018-12-20 17:45 UTC by danfinlay

Replaces #5935.

Hides that feature (which doesn't make sense until we have mobile) behind a hidden feature flag.

Adds the ability to set feature flags from the background console using this method:

```javascript
/*
* @method
* Sets a feature flag to the `enabled` value.
* @param { String } featureName - The unique name for the feature.
* @param { Boolean } enabled - Whether the feature should be enabled.
*/
function setPreference (featureName, enabled) { /* implementation */ }
```

You can try it out by entering `setPreference('mobileSync', true)` in the background console, which will add a new button to the bottom of the settings view.

2019-01-30 18:51 UTC, brunobar79 submitted a review, later dismissed
Adding this comments so I can address before we decide to merge this in

2019-01-30 18:51 UTC, brunobar79 commented on ui/app/components/pages/mobile-sync/index.js
> +      publishKey: 'pub-c-d40e77d5-5cd3-4ca2-82eb-792a1f4573db',
We gotta rotate keys before merging this in, move the keys into CircleCI env variables and consume it here via process.env.PUBNUB_SUB_KEY and process.env.PUBNUB_PUB_KEY

2019-01-30 18:51 UTC, brunobar79 commented on app/scripts/metamask-controller.js
> +    const simpleKeyPairKeyring = await this.keyringController.getKeyringsByType('Simple Key Pair')[0]
remove

2019-02-21 18:13 UTC, danfinlay commented
There's an important item to note with this feature: Since it hangs a method on the `global` namespace, preferences managed are highly exposed to all dependencies, so we should make sure that none of the preferences have any potential for abuse by a malicious dependency.

2019-02-21 18:50 UTC, danfinlay commented
Ok I've pushed up some comments to help encourage correct future use of the feature flags hash. I'm ok with this being merged if someone approves it now.

2019-02-25 18:28 UTC, whymarrh requested changes
Two small things:

1. The noted regression (?) in the PreferencesController
2. The changes to the `package-lock.json` file should probably be dropped and re-added, I'm seeing this PR downgrade the version of json-rpc-engine we're pinned to from 3.8.0 to 3.7.3 which doesn't seem correct.

2019-02-25 18:28 UTC, whymarrh commented on app/scripts/controllers/preferences.js
> +      },
We should drop this addition before merging as this seems to be a regression

2019-02-25 19:10 UTC, whymarrh approved these changes
Looks fine to me

2019-02-25 19:10 UTC, merged

2019-05-22 20:09 UTC, guix77 commented
@danfinlay on MM 6.5.3 (FF + Chrome) under Settings > Advanced, the mobile sync is not hidden any more. Does not help with confusion about the "release" of the mobile app medias talked about and malware fake apps :)