Refactor and fix styling for first time flow. Remove seed phrase from…
MetaMask/metamask-extension pull request #5994
Opened 2019-01-04 01:02 UTC by alextsg

… persisted metamask state

2019-01-17 16:14 UTC, whymarrh requested changes
The structural changes here look pretty darn good! The styling is a bit weird in a full-screen tab, the container is a bit too narrow:

<img width="1007" alt="screen shot 2019-01-17 at 12 42 11" src="https://user-images.githubusercontent.com/1623628/51332092-a38d4e80-1a55-11e9-9e2c-a43f5ea6005e.png">

2019-01-22 17:16 UTC, danjm commented
@whymarrh can you change your review to "Approved"?

2019-01-23 14:32 UTC, whymarrh submitted a review, later dismissed

2019-01-23 14:38 UTC, whymarrh approved these changes
LGTM

2019-01-23 14:57 UTC, danjm approved these changes

2019-01-23 15:25 UTC, merged