Fix incorrectly showing checksums on non-ETH blockchains
MetaMask/metamask-extension pull request #6001
Opened 2019-01-07 20:54 UTC by jonathansmirnoff

This PR fixes the issue #5838. I did another PR (https://github.com/MetaMask/metamask-extension/pull/5973) but I have closed it because of the git's history didn't was clear.

Please @whymarrh, @danjm and @alextsg take a look of it.

Thanks!

2019-01-08 18:46 UTC, alepc253 commented
Really useful for RSK community!

2019-01-10 19:42 UTC, frankiebee submitted a review, later dismissed

2019-01-10 19:43 UTC, frankiebee commented
@jonathansmirnoff will merge once tests are fixed

2019-01-10 19:45 UTC, frankiebee commented
at the very least unit tests need to be fixed. If e2e test are still failing once unit tests are fixed i may take a look and see why

2019-01-10 19:50 UTC, jonathansmirnoff commented
@frankiebee thanks a lot for the review. The branch develop has problems with unit test, at least the version of the few days ago.
Do you know if someone fix it?

2019-01-11 14:33 UTC, jonathansmirnoff commented
@frankiebee thanks for your review. Also as @alepc253 said this PR is a big steps for RSK community.
I added an improvement in the destination address validation for non-eth network. I think now is better. Also I fixed the problem with the unit tests. 
The only issue that I couldn't resolve is the e2e tests, only one test is not passing from 20.

2019-01-14 23:17 UTC, frankiebee submitted a review, later dismissed
thanks for this

2019-01-14 23:25 UTC, frankiebee requested changes

2019-01-14 23:45 UTC, frankiebee commented on ui/app/util.js
> +  if (!netId || netId === '1' || netId === '3' || netId === '4' || netId === '42') {
this will fix e2e tests

2019-01-15 14:52 UTC, jonathansmirnoff commented
@frankiebee I included the ganache net id. Also I did a rebase from develop. But the e2e tests still failing. I think this is not related to me changes. Maybe the issue is in develop.
The error that I have is:
```
    Send ETH from inside MetaMask
      1) starts a send transaction


  20 passing (43s)
  1 failing

  1) MetaMask
       Send ETH from inside MetaMask
         starts a send transaction:
     WebDriverError: Element <button class="button btn-primary btn--large page-container__footer-button"> is not clickable at point (674,601.5) because another element <header> obscures it
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:514:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:519:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  From: Task: WebElement.click()
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.click (node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
      at Context.<anonymous> (test/e2e/beta/metamask-beta-ui.spec.js:381:24)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

2019-01-15 21:04 UTC, tmashuang commented
@jonathansmirnoff Seems I was mistaken on the default configuration between `ganache` and `ganache-cli`. We need to configure `ganache-cli network_id` in `package.json` to 5777. Please change 
https://github.com/MetaMask/metamask-extension/blob/develop/package.json#L41
 to
`"ganache:start": "ganache-cli --noVMErrorsOnRPCResponse -i 5777 -m 'phrase upgrade clock rough situate wedding elder clever doctor stamp excess tent'",
`

2019-01-16 16:03 UTC, jonathansmirnoff commented
Hi @frankiebee I did the changes. Thanks you again.

2019-01-16 21:55 UTC, tmashuang commented
@jonathansmirnoff Alright, this issue has been resolved in `develop` branch. Hopefully, one last update should get the CI to pass.

2019-01-17 17:42 UTC, jonathansmirnoff commented
@tmashuang you were right! All the tests passed!
@frankiebee I think we are good to go! 👍

2019-01-22 20:57 UTC, jonathansmirnoff commented
Hi @frankiebee, Do you know when you plan to merge this PR?

2019-01-25 17:59 UTC, jonathansmirnoff commented
@frankiebee I updated to the lasted version of develop. Also I improved the github history

2019-02-12 18:56 UTC, frankiebee approved these changes

2019-02-13 20:30 UTC, merged