the repeated getSelectedAddress() func  send.selectors.js is removed
MetaMask/metamask-extension pull request #6056
Opened 2019-01-22 17:18 UTC by Sneh1999

- getSelectedAddress() is removed from send.selectors.js and was imported from selectors.js
- All other imports were also made from selectors.js

2019-01-22 23:32 UTC, danjm commented
Looks good @Sneh1999 

Can you run `npm run lint:fix` locally, make any necessary changes and then push the code again. This should be good to merge then.

2019-01-30 04:31 UTC, danjm commented
@Sneh1999 I think the e2e tests might pass if you rebase this onto the latest develop. Let me know if you need any help with that.

2019-02-08 20:04 UTC, whymarrh requested changes
We should drop the lockfile changes before merging

2019-04-10 15:57 UTC, whymarrh approved these changes

2019-04-11 17:50 UTC, merged