Change gas labels to Slow/Average/Fast
MetaMask/metamask-extension pull request #6090
Opened 2019-02-01 06:42 UTC by chikeichan

2019-02-01 17:49 UTC, danjm approved these changes

2019-02-01 17:50 UTC, danjm requested changes
Just need to make a similar update in unit tests

2019-02-06 14:32 UTC, danjm approved these changes

2019-02-06 15:09 UTC, whymarrh approved these changes
LGTM

2019-02-06 15:10 UTC, merged