Version 6 RC1
MetaMask/metamask-extension pull request #6117
Opened 2019-02-07 17:10 UTC by danfinlay

!!!!

2019-02-07 17:18 UTC, whymarrh submitted a review, later dismissed

2019-02-07 18:44 UTC, whymarrh requested changes
@tmashuang pointed out a bug that we'll need to fix

2019-02-07 19:07 UTC, tmashuang requested changes
https://github.com/MetaMask/metamask-extension/issues/6118

2019-02-08 20:40 UTC, whymarrh submitted a review, later dismissed

2019-02-11 17:46 UTC, tmashuang submitted a review, later dismissed

2019-02-11 17:51 UTC, danfinlay commented
Oh I'm sorry, I allowed a merge on my local branch, and it was just a changelog diff and now it broke the reviews. Rolling that back w/ a force push.

2019-02-11 18:19 UTC, tmashuang approved these changes

2019-02-11 18:19 UTC, merged