Metametrics
MetaMask/metamask-extension pull request #6171
Opened 2019-02-15 14:20 UTC by danjm

This PR implements the analytics system described here https://medium.com/metamask/metametrics-an-introduction-to-metamasks-new-analytics-system-e9749e74a275

Code related to the sending of metrics can be reviewed

Outstanding UI tasks include:

- [ ] Add correct chart graphic on opt-in screen
- [ ] Update the opt-in modal (for existing users) to latest designs
- [ ] Apply the responsive design to the opt-in modal
- [ ] Make other first time flow changes on which this will depend
- [ ] Rebase this onto first time flow changes

![peek 2019-02-15 10-48](https://user-images.githubusercontent.com/7499938/52862286-7e9d0180-310f-11e9-82e5-6c14869c443d.gif)

2019-02-19 02:46 UTC, danjm commented
Now with responsive designs

![peek 2019-02-18 23-15](https://user-images.githubusercontent.com/7499938/52986729-27c74e80-33d3-11e9-80a7-133bc6e8f00e.gif)

2019-02-21 01:18 UTC, danjm commented
Will rebase onto https://github.com/MetaMask/metamask-extension/pull/6192 once merged

2019-02-28 16:55 UTC, tmashuang commented on test/e2e/beta/from-import-beta-ui.spec.js
>        await seedTextArea.sendKeys(testSeedPhrase)
<img width="894" alt="screen shot 2019-02-28 at 10 50 17 am" src="https://user-images.githubusercontent.com/13376180/53583373-13a7ed80-3b47-11e9-8c7f-70a7f9bcc853.png">

The TOS needs to be clicked after the seed phrase and password is entered.

2019-02-28 17:01 UTC, tmashuang commented
https://github.com/MetaMask/metamask-extension/blob/cb2698d20eae273d372d03e11fa765a91c330c17/test/e2e/beta/from-import-beta-ui.spec.js#L123


Might need to be 
`const tosCheckBox = await findElement(driver, By.css('.first-time-flow__checkbox-label'))
`

2019-02-28 18:22 UTC, danfinlay commented
Noticed two things:

1. When unlocking and then clicking out of the popup, the metrics prompt was not shown again until my next log in (maybe is fine).

2. I was unable to scroll down to the buttons to approve this. There were two scroll wheels visible, neither let me get to the buttons:

![metametrics-bug1](https://user-images.githubusercontent.com/542863/53588858-c3c72780-3b42-11e9-992a-1461b7890c8c.gif)

2019-02-28 18:25 UTC, danfinlay commented
Oh, and is this page going to link to any of our more detailed blog posts on the issue? I think that would be nice.

2019-02-28 19:19 UTC, bdresser commented
Looks good @danjm! Couple notes on these changes
* "privacy policy here" on opt-in step should link [here](https://metamask.io/privacy.html)
* Opt-in screen is a little text-heavy Can we remove the last line of text in the lead paragraph  ("If you care about the Usability....")
* Can we make the legalese underneath the YES/NO buttons a medium shade of gray
* I can't check the ToS checkbox on the Import Seed step, getting the below error
<img width="464" alt="screen shot 2019-02-28 at 10 54 17 am" src="https://user-images.githubusercontent.com/1016190/53590752-5cf83d00-3b47-11e9-8b00-7557c2b5d6f9.png">
* I can't change the gas default to "Fast" or "Slow" and getting this error 
<img width="633" alt="screen shot 2019-02-28 at 11 18 14 am" src="https://user-images.githubusercontent.com/1016190/53592252-b150ec00-3b4a-11e9-8da9-233bc881335b.png">

Willl keep playing around and check coorresponding behavior in Matomo!

Also, I didn't properly QA the changes to first-time flow from https://github.com/MetaMask/metamask-extension/pull/6192. That's my bad. Adding other things I noticed in https://github.com/MetaMask/metamask-extension/issues/6222

2019-02-28 20:54 UTC, danjm commented
@bdresser I fixed the errors with import ToS and the fast and slow buttons on the send screen.

2019-02-28 21:57 UTC, bdresser commented
When I organically start the send flow, then clilck "Next" to get to the confirm screen, the extension is popping open a standalone confirm modal in addition to the popup (still attached to Chrome). So there are two MM's showing the same confirmation screen

2019-02-28 22:02 UTC, bdresser commented
"Clicked Create Account" is coming through to Matomo as "Clicked Create Accoount" which is 100% my bad, I typo'd in the spec. Updated in spec.

2019-02-28 23:23 UTC, whymarrh requested changes
A few things, mostly nitpicks

2019-02-28 23:23 UTC, whymarrh commented on ui/app/actions.js
> +        console.log('!@# err, metaMetricsId', err, metaMetricsId)
We can leave this in if we switch to using `log.debug`

2019-02-28 23:23 UTC, whymarrh commented on ui/app/actions.js
> +      dispatch({
Should this action be dispatched inside the callback for `MetaMaskController#setParticipateInMetaMetrics`?

2019-02-28 23:23 UTC, whymarrh commented on ui/app/actions.js
> +      dispatch({
Similar note to above

2019-02-28 23:23 UTC, whymarrh commented on ui/app/actions.js
> +    dispatch({
Similar note to above

2019-02-28 23:23 UTC, whymarrh commented on ui/app/app.js
> +          // ...props,
Nit: can we remove this line

2019-02-28 23:23 UTC, whymarrh commented on ui/app/app.js
> +          // ...config,
Nit: can we remove this line

2019-02-28 23:23 UTC, whymarrh commented on ui/app/components/button/button.component.js
> +//
Nit: can we remove this line?

2019-02-28 23:23 UTC, whymarrh commented on ui/app/components/pages/confirm-transaction-base/confirm-transaction-base.component.js
> +      Promise.resolve(onSubmit(txData))
I don't think we need to wrap this in a `Promise` chain, as these all seem like sync calls. Could we write:

```js
try {
    onSubmit(...)
    this.setState(...)
} catch (e) {
    // ....
}
```

2019-02-28 23:23 UTC, whymarrh commented on ui/app/components/sidebars/sidebar.component.js
> +    return <div className="sidebar-overlay" onClick={() => {
Nit: can we put the props for this `div` on new lines? (And format them etc.)

2019-02-28 23:23 UTC, whymarrh commented on ui/app/metametrics/metametrics.provider.js
> +        // if (userPermission) {
Nit: can we remove this line?

2019-02-28 23:23 UTC, whymarrh commented on ui/app/metametrics/metametrics.provider.js
> +        const isSendFlow = Boolean(config.eventOpts && config.eventOpts.name && config.eventOpts.name.match(/^send|^confirm/) || overrides.pathname && overrides.pathname.match(/send|confirm/))
Nit: can we introduce some extra variable (or something) to shorten this line a bit?

2019-02-28 23:23 UTC, whymarrh commented on ui/app/metametrics/metametrics.provider.js
> +MetaMetricsProvider.propTypes = {
We should put this as a static property on the class directly

2019-02-28 23:23 UTC, whymarrh commented on ui/app/metametrics/metametrics.provider.js
> +MetaMetricsProvider.childContextTypes = {
We should put this as a static property on the class directly

2019-02-28 23:23 UTC, whymarrh commented on ui/app/metametrics/metametrics.provider.js
> +MetaMetricsProvider.propTypes = {
Also, (totally just bringing this up now, but) if we know that any of these props are necessary for this component to do its thing, we can tack on `.isRequired` to the prop type.

2019-02-28 23:23 UTC, whymarrh commented on ui/app/metametrics/metametrics.util.js
> +// function composeActionNameParamAddition (pathname, pageOpts) {
Nit: can we remove this comment?

2019-02-28 23:23 UTC, whymarrh commented on ui/app/metametrics/metametrics.util.js
> +  const action_name = '' // pageOpts && pathname && composeActionNameParamAddition(pathname, pageOpts) || ''
Nit: do we need this comment?

2019-02-28 23:23 UTC, whymarrh commented on ui/app/selectors.js
> +  const simpleAddress = identity.address.substring(2).toLowerCase()
Is there a helper function anywhere to strip a hex prefix?

2019-03-01 20:11 UTC, danjm commented
- [ ] Don't send a second opt-in event if the user goes back
- [ ] Collect events on going back and on selecting create vs import after going back
- [ ] ensure all custom variables are supported (i.e. that they have mappings to custom variable ids)

2019-03-01 22:12 UTC, bdresser commented
I think opting IN to metrics is being recorded as opting out

2019-03-01 23:23 UTC, danjm commented
> I think opting IN to metrics is being recorded as opting out

Good catch again. Fixed now.

2019-03-05 14:51 UTC, whymarrh approved these changes

2019-03-05 15:45 UTC, merged