Gas customize modal updates
MetaMask/metamask-extension pull request #6300
Opened 2019-03-14 02:51 UTC by danjm

Main purpose of this PR is to hide the gas chart when not on ethereum networks.

fixes #5900

2019-03-14 11:53 UTC, whymarrh requested changes
One small nitpick sorry

2019-03-14 11:53 UTC, whymarrh commented on app/_locales/en/messages.json
> +    "message": "Chart only available on ethereum networks."
Nit: capitalize Ethereum

2019-03-20 16:40 UTC, danjm commented on app/_locales/en/messages.json
> +    "message": "Chart only available on ethereum networks."
fixed

2019-03-22 14:39 UTC, whymarrh approved these changes

2019-03-22 14:50 UTC, merged