Folder restructure
MetaMask/metamask-extension pull request #6304
Opened 2019-03-14 06:48 UTC by chikeichan

2019-03-14 11:50 UTC, whymarrh commented
I know this I should've raised this earlier, but after looking at the image in the OP, can we drop `ui/app/`? Directories like `ui/app/components/app/` and `ui/app/ducks/app/` seem a bit redundant. We could instead have `ui/components/` and `ui/ducks/`. Thoughts?

2019-03-18 15:55 UTC, danjm requested changes
QA'd and everything seems good.

Inspected the folder structure via my text editor. Its definitely a big improvement.

One preference I have that differs from what is there:

I like having `app.js`, `root.js`, `reducers.js` and `index.js` in the same place. These pull together all the high level pieces of the app and are a good starting point to understanding the app as a whole. So I think there are benefits for code readability if they are are all together.

Independent of that concern, I would add that `app.js` and `root.js` don't really fit in `pages/`. That directory makes sense as a "directory of all components that have their own route". Whereas `app.js` is more of a routing component and `root.js` is boilerplate react needed for the app to work. Perhaps put these one directory up: `app/app.js` and `app/root.js` `app.js` may need a renaming if this is done.

Other than these relatively minor concerns, I think this is good to merge.

2019-03-19 01:47 UTC, chikeichan commented
@danjm great suggestions - based on them:
- changed `pages/app.js` to `pages/routes/index.js`
- changed `pages/root.js` to `pages/index.js`
- move all `pages/*.js` to `pages/[component-name]/index.js`
- move `store/reducers.js` to `ducks/index.js`

I `actions.js` in the `store/` directory. This is the file to be re-organize into appropriate ducks.

2019-03-20 16:02 UTC, danjm submitted a review, later dismissed

2019-03-21 12:43 UTC, danjm submitted a review, later dismissed

2019-03-21 23:03 UTC, danjm approved these changes

2019-03-21 23:03 UTC, merged