Adds a transactionCategory to txMeta for use in UI
MetaMask/metamask-extension pull request #6567
Opened 2019-05-06 16:30 UTC by danjm

Partially resolves #6380 

This PR modifies transaction controller code so that a new property - `transactionCategory` - is added to `txMeta`. This will be consumed by the UI in an associated PR.

2019-05-06 16:49 UTC, frankiebee requested changes
please remove console logs

Would it be possible to append to type instead of adding transactionCategory so something more like 
type: `'${type}#${transactionCategory}'` ? (non blocker just curious)

2019-05-06 16:49 UTC, frankiebee commented on ui/app/components/ui/error-message/error-message.component.js
> +  console.log('!!!!! props', props)
no console.log in prod please use log

2019-05-06 16:49 UTC, frankiebee commented on ui/app/pages/confirm-transaction-base/confirm-transaction-base.component.js
> +    console.log('!!!!!errorKey', errorKey)
please use log over console.log

2019-05-06 17:22 UTC, danjm commented
@frankiebee console logs removed

2019-05-07 21:43 UTC, chikeichan commented
Code LGTM - the only suggest i have is to update the in-file JS DOC to include the new `code` params.

2019-05-07 22:36 UTC, danjm commented
> Would it be possible to append to type instead of adding transactionCategory so something more like
type: '${type}#${transactionCategory}' ? 

@frankiebee yes it is possible? why do you prefer that?

2019-05-08 19:08 UTC, frankiebee approved these changes

2019-05-08 19:18 UTC, merged