Ensures that transactions cannot be confirmed if gas limit is below 21000
MetaMask/metamask-extension pull request #6625
Opened 2019-05-17 07:23 UTC by danjm

Fixes #6373.

Ensures that transactions cannot be confirmed if gas limit is below 21000.

2019-05-17 22:51 UTC, whymarrh requested changes

2019-05-17 22:51 UTC, whymarrh commented on ui/app/components/app/gas-customization/gas-modal-page-container/advanced-tab-content/advanced-tab-content.component.js
> +      console.log('------------123123123123123123----------------')
Nit: `console.log`

2019-05-22 14:26 UTC, danjm commented on ui/app/components/app/gas-customization/gas-modal-page-container/advanced-tab-content/advanced-tab-content.component.js
> +      console.log('------------123123123123123123----------------')
@whymarrh this is fixed

2019-05-23 04:53 UTC, whymarrh approved these changes

2019-05-23 13:56 UTC, merged

2023-02-02 15:34 UTC, backmen commented
We cannot send coins from desktop extension on our chain, because we have lower gas fee than Ethereum. That should be fixed..
https://github.com/MetaMask/metamask-extension/issues/16593