Added Confirmation Modal for Delete Network
MetaMask/metamask-extension pull request #6776
Opened 2019-06-30 21:46 UTC by akshitkrnagpal

2019-06-30 22:29 UTC, akshitkrnagpal commented
Hey

I have tried to add the confirmation modal using Figma as a reference. The changes might be complete but e2e test for delete network is failing right now because of the confirmation modal.

While I work on that it would be great if someone can take a look. 😄

2019-07-01 16:30 UTC, whymarrh requested changes
One small comment but otherwise this looks really good!

2019-07-01 16:30 UTC, whymarrh commented on ui/app/components/app/modals/confirm-delete-network/confirm-delete-network.component.js
> +          title={`${t('deleteNetwork')}?`}
Can we move the question mark into the localized message?

2019-07-01 18:24 UTC, akshitkrnagpal commented
Hey @whymarrh 
I have updated the PR. 😄

2019-07-01 21:24 UTC, whymarrh approved these changes
LGTM, thanks @akshitkrnagpal!

2019-07-02 12:13 UTC, merged