Rename accountManager in ui index file
MetaMask/metamask-extension pull request #6790
Opened 2019-07-03 01:26 UTC by whymarrh

This PR simply renames the `background` reference in the `ui/index.js` file that was previously called `accountManager`.

2019-07-03 01:34 UTC, Gudahtt requested changes
This parameter is referenced in the `porting_to_new_environment.md` docs, so it should probably be updated there as well.

This entity is named `accountManager` elsewhere in the code - in the `startupApp` function below this change, in `popup-core.js`, in `phishing-detect.js`. Not too many places really, but it's just as well it be changed in all of them, or it'd be even more confusing than before.

It's also in the architecture diagram. It looks like that's pretty easy to edit. I guess that can just be removed, or renamed `backgroundConnection` or something.

2019-07-10 18:20 UTC, whymarrh commented
Updated. The only remaining usages are in a file slated for deletion (#6831).

2019-07-10 18:22 UTC, Gudahtt requested changes

2019-07-10 18:22 UTC, Gudahtt commented on docs/porting_to_new_environment.md
> +You can see this in action in our file [ui/index.js](https://github.com/MetaMask/metamask-extension/blob/master/ui/index.js). There you can see an the background connection being passed in, which is
```suggestion
You can see this in action in our file [ui/index.js](https://github.com/MetaMask/metamask-extension/blob/master/ui/index.js). There you can see the background connection being passed in, which is essentially the MetaMask controller. With access to that object, the UI is able to initialize a whole React/Redux app that relies on this API for its account/blockchain-related/persistent states.
```

2019-07-10 18:25 UTC, Gudahtt approved these changes

2019-07-10 19:01 UTC, merged