Added missed phrases to RU locale (got from en locale)
MetaMask/metamask-extension pull request #7012
Opened 2019-08-14 19:25 UTC by zlocate

2019-08-14 22:01 UTC, whymarrh requested changes
Hey @zlocate, thanks a bunch of helping with translations! The JSON file currently has a few errors in its formatting—a tool/site like https://jsonlint.com can help if you want to have a go at fixing those up first.

(cc @MetaMask/translators any of y'all able to review this? 😅)

2019-08-15 05:12 UTC, zlocate commented
@whymarrh thank you for feedback. Some phrases adopted at Russian common grammar rules but i would like external review from native speakers (i'm native Russian speaker).
Sorry for breaking indent in source file. I will fix it asap

2019-08-15 12:59 UTC, zlocate commented
@whymarrh fixed. Please review current version.

2019-08-15 14:41 UTC, nujabes403 commented
@zlocate Thank you for your effort!

2019-08-21 13:42 UTC, whymarrh submitted a review, later dismissed
Thank you @zlocate! ❤️

2019-08-23 17:17 UTC, dryajov requested changes
Just a few comments/suggestions. 

Thanks for contributing.

2019-08-23 17:17 UTC, dryajov commented on app/_locales/ru/messages.json
> +    "message": "Закажите Trezor или Ledger и храните свои средства в холодильнике"
Закажите Trezor или Ledger и храните свои средства в холодном кошельке

2019-08-23 17:17 UTC, dryajov commented on app/_locales/ru/messages.json
> +    "message": "Да, давайте начнем"
Maybe - "Да, давайте попробуем" ?

2019-09-04 17:50 UTC, whymarrh approved these changes
Thanks again @zlocate!

2019-09-04 17:51 UTC, merged