Terms of Service UI Update
MetaMask/metamask-extension pull request #702
Opened 2016-10-05 04:53 UTC by Zanibas

- Updated the UI to reflect our current Terms of Service.
- Updated naming conventions to be more consistent across the application (i.e. changing 'Help' to 'Info')
- Added links in appropriate locations to legal documents on landing page.

Fixes #635

2016-10-05 05:03 UTC, Zanibas commented
Rewriting the current UI test we have to account for the fact that we have to scroll to the bottom of the ToS to activate the button.

2016-10-05 09:05 UTC, danfinlay requested changes
There are a number of slight improvements that I think would make this code a little better.

Also, I'd really like to see a mechanism by which users are shown the TOS again when it changes.

2016-10-05 09:05 UTC, flyswatter commented on ui/app/first-time/disclaimer.js
> +          if ((object.offsetHeight + object.scrollTop + 100 >= object.scrollHeight) && button.disabled) {
This condition is so long it's hard to know what it means. I'd love to see some variables defined that makes it easy to understand.

2016-10-05 09:05 UTC, flyswatter commented on ui/app/first-time/disclaimer.js
> +      h('button#agree', {
Don't use ids, they can really ruin your style sheets because they have ultimate precedence.

2016-10-05 09:43 UTC, Zanibas commented on test/integration/tests.js
> +    assert.equal(title, 'Terms of Use Version 1', 'title screen')
Ignore this: I accidentally committed this and will continue to rewrite the unit test.

2016-10-05 09:45 UTC, Zanibas commented on ui/app/first-time/disclaimer.js
> +          if ((object.offsetHeight + object.scrollTop + 100 >= object.scrollHeight) && button.disabled) {
Rewritten to be more informative and React-y...I don't know what I was doing making all this hard ><

2016-10-05 09:46 UTC, Zanibas commented on ui/app/first-time/disclaimer.js
> +      h('button#agree', {
Removed ID: the change now properly comes from the state during render-time

2016-10-07 09:17 UTC, Zanibas commented
This PR is complete, waiting for final approval.

2016-10-07 15:33 UTC, kumavis approved these changes
Looks good!

2016-10-07 15:33 UTC, kumavis commented on USER_AGREEMENT.md
> +# Terms of Use Version 1 #
i dont really like the "Version 1", keep it simple

@flyswatter thoughts?

2016-10-07 15:33 UTC, kumavis commented on app/scripts/background.js
> +const stringHash = require('string-hash')
How big is `string-hash`? We already have a gluttony of crypto libs

2016-10-07 18:44 UTC, flyswatter commented
I agree no version on the tos title.

Also I agree with Aaron on the gluttony of crypto libs. There is not really a good reason to make every user hash the tos every time they start up, it's a waste of CPU and bundle size.

We should do the hashing when we bundle, and just inject the hash as an env var.

- Dan

> On Oct 7, 2016, at 8:33 AM, kumavis <notifications@github.com> wrote:
> 
> @kumavis approved this pull request.
> 
> Looks good!
> 
> In USER_AGREEMENT.md:
> 
> > @@ -1,55 +1,181 @@
> -# Disclaimer
> +# Terms of Use Version 1 #
> i dont really like the "Version 1", keep it simple
> 
> @flyswatter thoughts?
> 
> In app/scripts/background.js:
> 
> > @@ -8,6 +8,10 @@ const messageManager = require('./lib/message-manager')
>  const setupMultiplex = require('./lib/stream-utils.js').setupMultiplex
>  const MetamaskController = require('./metamask-controller')
>  const extension = require('./lib/extension')
> +const fs = require('fs')
> +const path = require('path')
> +const disclaimer = fs.readFileSync(path.join(__dirname, '..', '..', 'USER_AGREEMENT.md')).toString()
> +const stringHash = require('string-hash')
> How big is string-hash? We already have a gluttony of crypto libs
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-10-11 22:37 UTC, danfinlay approved these changes
Oh I had a "pending review" with some stray style notes.  Review those, fix the ones you want, then LGTM.

2016-10-11 22:37 UTC, flyswatter commented on app/scripts/metamask-controller.js
> +
rando newlines

2016-10-11 22:47 UTC, Zanibas commented on test/integration/tests.js
> +    wait().then(function() {
I tried doing it the proper way, but for some reason, it keeps failing.

```
  wait().then(function() {
    app.find('button').click()
  }).then(function() {
    wait()
  }).then(function() {
    var title = app.find('h1').text()
    assert.equal(title, 'MetaMask', 'title screen')

    var buttons = app.find('button')
    assert.equal(buttons.length, 2, 'two buttons: create and restore')

    done()
  })
```

and the tests:

```
not ok 1 Chrome 53.0 - agree to terms
    ---
        actual: >
            MetaMaskTerms of Use
        expected: >
            MetaMask
        stack: >
                at http://localhost:7357/3389/test/integration/tests.js:31:12
        message: >
            title screen
        Log: |
    ...
not ok 2 Firefox 49.0 - agree to terms
    ---
        actual: >
            MetaMaskTerms of Use
        expected: >
            MetaMask
        stack: >
            @http://localhost:7357/3777/test/integration/tests.js:31:5
            
        message: >
            title screen
        Log: |
    ...

1..2
# tests 2
# pass  0
# skip  0
# fail  2
```

2016-10-11 22:48 UTC, flyswatter commented on test/integration/tests.js
> +    wait().then(function() {
In the proper way, you have to `return` a promise within the promise.  So
```
- wait()
+ return wait()
```

2016-10-11 22:49 UTC, flyswatter commented on test/integration/tests.js
> +    wait().then(function() {
https://promisesaplus.com/

2016-10-11 22:49 UTC, Zanibas commented on test/integration/tests.js
> +    wait().then(function() {
It passes now, thanks!

2016-10-11 23:13 UTC, merged