Replace `undefined` selectedAddress with `null`
MetaMask/metamask-extension pull request #7161
Opened 2019-09-12 17:07 UTC by Gudahtt

The `runtime.Port.postMessage` API will drop keys with a value of `undefined` on Chrome, but not on Firefox. This was a problem for the `publicConfig` stream, which passed the key `selectedAddress` with the value of `undefined` to communicate to dapps that the user had logged
out.

Instead a `null` is now passed for `selectedAddress` upon logout, which is correctly sent by the `runtime.Port.postMessage` API on both Chrome
and Firefox.

Relevant Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1003439

closes #7101
closes #7109

2019-09-12 17:38 UTC, danfinlay approved these changes
Safe and easy.

2019-09-12 18:15 UTC, danfinlay approved these changes

2019-09-12 18:15 UTC, danfinlay requested changes
Marking the request for an empty array.

2019-09-12 23:32 UTC, danfinlay approved these changes
Yup, I just published that version of inpage-provider.

2019-09-13 14:32 UTC, danjm approved these changes

2019-09-13 14:32 UTC, merged