Support gas limit customization on retries after transaction failure
MetaMask/metamask-extension pull request #7422
Opened 2019-11-14 16:00 UTC by danjm

Fixes https://github.com/MetaMask/metamask-extension/issues/7382

This PR ensures that the user can change the gas limit when doing a retry of a failed transaction.

2019-11-19 18:46 UTC, rickycodes approved these changes

2019-11-19 23:47 UTC, frankiebee requested changes

2019-11-19 23:47 UTC, frankiebee commented on app/scripts/controllers/transactions/index.js
please document

2019-11-19 23:47 UTC, frankiebee commented on app/scripts/controllers/transactions/index.js
> +  async createSpeedUpTransaction (originalTxId, customGasPrice) {
i thought this was documented but if it's not would you mind doing that

2019-11-19 23:47 UTC, frankiebee commented on app/scripts/metamask-controller.js
> +    return state
what? does this return the whole app state?

2020-01-30 17:43 UTC, whymarrh commented
Closing this for now, we can come back to this

2020-01-30 17:43 UTC, closed without merging

2020-01-30 20:30 UTC, Flahe commented
Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Whymarrh Whitby <notifications@github.com> Date: 1/30/20  12:43 PM  (GMT-05:00) To: MetaMask/metamask-extension <metamask-extension@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [MetaMask/metamask-extension] Support gas limit customization on retries after transaction failure (#7422) Closed #7422.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MetaMask/metamask-extension/pull/7422?email_source=notifications\u0026email_token=ALNXKRCG4PQVO4AI36CEOSTRAMGVFA5CNFSM4JNN3IE2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOWJ4UMPI#event-2994292285",
"url": "https://github.com/MetaMask/metamask-extension/pull/7422?email_source=notifications\u0026email_token=ALNXKRCG4PQVO4AI36CEOSTRAMGVFA5CNFSM4JNN3IE2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOWJ4UMPI#event-2994292285",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]