Convert SimpleDropdown component to use JSX
MetaMask/metamask-extension pull request #7540
Opened 2019-11-23 19:35 UTC by whymarrh

Refs #6291

This PR replaces the hyperscript in the `SimpleDropdown` with JSX.

2019-11-23 21:42 UTC, Gudahtt requested changes

2019-11-23 21:42 UTC, Gudahtt commented on ui/app/components/app/dropdowns/simple-dropdown.js
> +      isOpen: prevState.isOpen,
I think there's a `!` missing here

2019-11-24 05:05 UTC, whymarrh commented on ui/app/components/app/dropdowns/simple-dropdown.js
> +      isOpen: prevState.isOpen,
Thanks, this is a good catch

2019-11-24 21:12 UTC, Gudahtt approved these changes
LGTM!

2019-11-24 21:18 UTC, merged