Add optional chaining
MetaMask/metamask-extension pull request #8052
Opened 2020-02-14 18:50 UTC by rickycodes

2020-02-14 18:54 UTC, Gudahtt commented on app/scripts/metamask-controller.js
> +              errorMessage: txMeta.simulationFails?.reason || 'Unknown Reason',
```suggestion
              errorMessage: txMeta.simulationFails?.reason,
```
Is the `Unknown Reason` part required? Falling back to `null` seems perfectly fine - that's what was intended originally I suspect.

2020-02-14 19:22 UTC, Gudahtt commented on babel.config.js
> +      '@babel/plugin-proposal-optional-chaining'
```suggestion
      '@babel/plugin-proposal-optional-chaining',
```
This should fix the lint failure

2020-02-15 03:50 UTC, Gudahtt submitted a review, later dismissed
LGTM!

2020-02-15 16:33 UTC, whymarrh requested changes

2020-02-15 16:33 UTC, whymarrh commented on package.json
> +    "@babel/plugin-proposal-optional-chaining": "^7.8.3",
Can we move this into `devDependencies`?

2020-02-18 00:34 UTC, whymarrh commented
Rebasing this on the latest `develop` should help with some of the CI errors here

2020-02-18 01:36 UTC, Gudahtt approved these changes

2020-02-18 02:01 UTC, whymarrh approved these changes

2020-02-18 15:11 UTC, merged