MultiVault
MetaMask/metamask-extension pull request #806
Opened 2016-11-11 06:00 UTC by kumavis

*status: undergoing final QA*

2016-11-11 20:16 UTC, kumavis reviewed
we should have 1 or 2 comments for every method explaining what its used for

2016-11-11 20:16 UTC, kumavis commented on app/scripts/keyring-controller.js
> +  submitPassword (password, cb) {
used in both: unlocking metamask, showing seed words

calls `migrateAndGetKey` - overly close couppling of migration and controller

2016-11-11 20:16 UTC, kumavis commented on app/scripts/keyring-controller.js
> +      this.configManager.setSalt(salt)
salt should be serialized in vault, not config

2016-11-11 20:16 UTC, kumavis commented on app/scripts/keyring-controller.js
> +    const accounts = keyring.getAccounts()
not sure if accounts is available synchronously? should keyring be an event emitter and emit new keys that we then push to setup

2016-11-11 20:16 UTC, kumavis commented on app/scripts/keyring-controller.js
> +    const accounts = ring.addAccounts(1)
potentially async

2016-11-11 20:16 UTC, kumavis commented on app/scripts/keyring-controller.js
> +  loadBalanceAndNickname (account) {
"loadBalance" is confusing with "loading a balance"

2016-11-11 20:16 UTC, kumavis commented on app/scripts/keyring-controller.js
> +  createNickname (address) {
should this be the role of the keyring?

2016-11-11 20:16 UTC, kumavis commented on app/scripts/keyring-controller.js
> +  persistAllKeyrings () {
I think persistence and encryption should happen outside this controller

2016-11-11 20:16 UTC, kumavis commented on app/scripts/keyring-controller.js
> +    function analyzeForDelegateCall (cb) {
ideally move to transaction manager

2016-11-11 20:42 UTC, kumavis commented on app/scripts/keyrings/hd.js
> +const type = 'HD Key Tree'
move to after requires

2016-11-11 20:42 UTC, kumavis commented on app/scripts/keyrings/hd.js
> +module.exports = class HdKeyring extends EventEmitter {
we should have a generic base class

2016-11-11 20:42 UTC, kumavis commented on app/scripts/keyrings/hd.js
> +  static type () {
static properties are done  like this
```js
Point.ZERO = new Point(0, 0)
```

2016-11-11 20:42 UTC, kumavis commented on app/scripts/keyrings/hd.js
> +  initFromMnemonic (mnemonic) {
organize into standard KeyRing method overrides and type-specific methods

2016-11-11 20:42 UTC, kumavis commented on app/scripts/keyrings/hd.js
> +  getWalletForAccount (account) {
what is a `wallet`

2016-11-11 20:42 UTC, kumavis commented on app/scripts/keyrings/hd.js
> +  getWalletForAccount (account) {
not sure that this can be part of the keyring standard as we cant extract a private key from remote id mgmt like treznor

2016-11-11 20:42 UTC, kumavis commented on app/scripts/keyrings/hd.js
> +function normalize (address) {
extract to util fn

2016-11-11 20:42 UTC, kumavis commented on app/scripts/lib/encryptor.js
> +// Takes a Pojo, returns encrypted text.
`cypher text`

2016-11-11 20:42 UTC, kumavis commented on app/scripts/lib/encryptor.js
> +var ethUtil = require('ethereumjs-util')
* we dont need to do anything ethereum specific
* we shouldnt follow ethereums lead of inefficient encoding of binary as hex (prefer base64)
* this should be a seperate module, in fact we should likely use some off-the-shelf module

2016-11-11 20:42 UTC, kumavis commented on app/scripts/lib/sig-util.js
> +const ethUtil = require('ethereumjs-util')
what is this file for

2016-11-11 20:42 UTC, kumavis commented on app/scripts/metamask-controller.js
> +    this.getNetwork()
rename - this sounds like it returns the network

2016-11-11 20:42 UTC, kumavis commented on test/integration/index.js
> +var fs = require('fs')
sort of recreating our build sys here
the concerns me

2016-11-11 20:42 UTC, kumavis commented on ui/app/components/pending-tx.js
> +      ? h('.error', {
lets move the `?`s back to the previous line

2016-11-11 20:52 UTC, kumavis commented
I think we should continue this refactor to clean up large architectural problems.
This will require more weeks of effort and QA but should massively reduce the complexity of the code.

In order to not block hotfixes, we should merge this into 'dev'. However I can't change the target branch of this PR nor can i migrate the review comments to a new PR, so lets keep this PR active and finally merge it into dev.

Here are the phases of this continued work:
* address comments here
* merge into `dev`
* continue architectural refactor

2016-11-11 20:56 UTC, kumavis commented
architectural refactor points:
* turn stateful things into observable stores
* move persistence outside of controllers
* move ui state transition to background

2016-11-11 21:00 UTC, 2-am-zzz requested changes
Blocked for merging for awhile, until changes are addressed, both code-wise and architecture-wise.

2016-11-11 21:05 UTC, kumavis commented
Pardon my critical nature, im just concerned about the complexity of our code base - i think the work so far is a great step forward, and now we understand what we need, we can make the larger shifts required to have a lean, functional, intuitive codebase

2016-11-11 23:17 UTC, Zanibas commented on app/scripts/keyring-controller.js
> +      selectedAccount: address,
We need to do a clearer audit of what properties we want to keep on this object.

2016-11-15 00:50 UTC, Zanibas commented on app/scripts/keyring-controller.js
> +      isConfirmed: true, // AUDIT this.configManager.getConfirmed(),
Doesn't seem to be hiccuping right now. Tentatively putting it back in until we determine why we set it to true in the first place.

2016-11-15 03:37 UTC, kumavis commented
@Zanibas nice nice

2016-11-15 21:28 UTC, kumavis commented on app/scripts/keyring-controller.js
> +    console.log(seedWords)
pls remove console log

2016-11-15 21:29 UTC, Zanibas commented
Whoops

On Tue, Nov 15, 2016, 13:28 kumavis <notifications@github.com> wrote:

> *@kumavis* commented on this pull request.
> ------------------------------
>
> In app/scripts/keyring-controller.js
> <https://github.com/MetaMask/metamask-plugin/pull/806#pullrequestreview-8700378>
> :
>
> >      const seedWords = firstKeyring.serialize().mnemonic
> +    console.log(seedWords)
>
> pls remove console log
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/MetaMask/metamask-plugin/pull/806#pullrequestreview-8700378>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABwTuWKUqrph8XBz7n1Vh37jk9Rgb1uRks5q-iP_gaJpZM4Kvc7H>
> .
>

2016-11-15 21:30 UTC, Zanibas commented on app/scripts/keyring-controller.js
> +    console.log(seedWords)
whoops~

2016-11-15 21:31 UTC, kumavis commented
@Zanibas can you solve the merge conflicts

2016-11-15 22:57 UTC, Zanibas commented
Are we able to trim down idStore to the essentials needed for migration?

2016-11-16 18:05 UTC, Zanibas commented on README.md
Starting the review!

2016-11-17 18:22 UTC, flyswatter commented on app/scripts/keyring-controller.js
> +    this.clearKeyrings()
This doesn't clear the vault (persisted, encrypted storage), it clears the unencrypted RAM storage.  We could maybe rename better, and add a comment to help clarify that goal.

2016-11-17 18:39 UTC, flyswatter commented on app/scripts/keyring-controller.js
> +    return this.migrateAndGetKey(password)
this should just be `this.loadKey(password)` instead since we never need to care about an old vault when creating a new vault.

2016-11-17 18:44 UTC, flyswatter commented on app/scripts/keyring-controller.js
> +    .then(() => {
I'm ok with the adapter lib, but `then(cb)` would throw error to cb.

2016-11-17 19:33 UTC, closed without merging