feature for get gasPrice for custom json rpc
MetaMask/metamask-extension pull request #8160
Opened 2020-03-04 16:59 UTC by helderjnpinto

Fixes MetaMask/metamask-extension#7263
Maybe need to add calculation for fee based in gasLimit but i can't find the data to do this.

2020-03-16 17:55 UTC, danfinlay requested changes
We would prefer that this parameter be stored per-network, instead of as a global setting across all networks, to allow better multi-network handling.

2020-03-20 10:10 UTC, helderjnpinto commented
> We would prefer that this parameter be stored per-network, instead of as a global setting across all networks, to allow better multi-network handling.

yes this is one attribute by network. you can see in the code...

2020-05-21 17:58 UTC, d10r commented on ui/app/pages/send/send-content/send-gas-row/send-gas-row.component.js
> +import { hexToDecimal } from '../../../../helpers/utils/conversions.util'
newline required after this line (linter rule)

2020-05-21 18:08 UTC, d10r commented
@helderjnpinto the 3. and 4. CI failure seem to be easy to fix.
One is about a missing newline
```
/home/circleci/project/ui/app/pages/send/send-content/send-gas-row/send-gas-row.component.js
  7:1  error  Expected 1 empty line after import statement not followed by another import  import/newline-after-import
```

and the other one because of tests not having been adapter to the changes.

What causes the first 2 failures (e2e) is less clear to me.

I'd try to fix those myself, but hesitate to do so, because I've no idea how to locally test changes of a browser extension.

2020-06-01 13:35 UTC, Gudahtt commented
It's good that this new preference is configured per-network, but I don't think we're tracking the correct thing here. I also don't think we should be calling `eth_gasPrice` in the UI, because the background should already be calling that and initializing each transaction with the result. I don't think there is a need to call it from the UI in any situation.

The only per-network preference we need is whether or not to show the ethgasstation-based gas estimation UI. It should be enabled for mainnet, and disabled otherwise.

2021-01-07 22:40 UTC, Gudahtt commented
I'll close this now, since we've already mostly solved this by other means (we now use `eth_gasPrice` exclusively for custom networks).

2021-01-07 22:40 UTC, closed without merging