Fix Sentry error processing for errors missing a stack
MetaMask/metamask-extension pull request #8179
Opened 2020-03-11 13:27 UTC by Gudahtt

Errors without stack traces would break the Sentry error processing, which assumes the presence of a stack trace. Many errors don't have any stack trace though, such as uncaught promises.

This breakage resulting in the app state being missing from the error report, and a console warning.

2020-03-11 14:53 UTC, whymarrh requested changes
Could we use options chaining here?

2020-03-11 14:56 UTC, Gudahtt commented
I'm not sure how optional chaining applies 😕 This line isn't an assignment - it's looping through and mutating the array.

2020-03-11 17:13 UTC, whymarrh commented
>     item.stacktrace?.frames

Instead of adding the check for `stacktrace`, we could use [`?.`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

2020-03-11 17:24 UTC, Gudahtt commented
Ah right - it hadn't occurred to me to use optional chaining in the case where you aren't using the return value. Sure, I can update this.

2020-03-11 23:49 UTC, Gudahtt commented
Unfortunately using optional chaining without capturing the result in a variable triggers the `no-unused-expressions` eslint rule, due to [this bug](https://github.com/eslint/eslint/issues/12822). I'd rather leave this as-is for now rather than add an ignore comment.

2020-03-12 03:12 UTC, whymarrh approved these changes

2020-03-12 13:51 UTC, merged