Support using Tabs as an controlled component
MetaMask/metamask-extension pull request #8266
Opened 2020-03-31 23:11 UTC by Gudahtt

Previously the Tabs component was an 'ucontrolled' component, as it managed the current selected tab internally using component state.

Tabs now accepts optional `tabIndex` and `onClick` props that allow the parent component to fully control the current active tab state.

2020-03-31 23:17 UTC, whymarrh requested changes
`getDerivedStateFromProps` should return an empty object when its main condition isn't met

> `Warning: Tabs.getDerivedStateFromProps(): A valid state object (or null) must be returned. You have returned undefined.`

2020-03-31 23:20 UTC, Gudahtt commented
Ah, good catch. I meant to return `null`. I'll update this.

2020-03-31 23:23 UTC, whymarrh submitted a review, later dismissed
LGTM!

2020-03-31 23:31 UTC, Gudahtt commented
I've just updated this to remove some input validation that was included accidentally. It didn't work anyway (it blew up when a single child was passed in). I'll fix it and put it up as a separate PR.

2020-04-01 13:54 UTC, whymarrh approved these changes
LGTM!

2020-04-01 14:31 UTC, Gudahtt commented
Closing this as we'll no longer need to use it. We can resurrect this if we ever find a use for controlled tabs.

2020-04-01 14:31 UTC, closed without merging