Update eth-contract-metadata
MetaMask/metamask-extension pull request #8466
Opened 2020-04-29 20:02 UTC by rekmarks

Update `eth-contract-metadata` to `1.13.0`

2020-04-29 20:03 UTC, whymarrh requested changes

2020-04-29 20:03 UTC, whymarrh commented on yarn.lock
> +  integrity sha512-9CjXHX8IdXysUEvOHdbCsjdAwM1E98jaeK2HeOqm/9S/vOZ8YryaBBt/YSiBq3MkpCwf+d1pEQ53p96rsdy52w==
```suggestion
eth-contract-metadata@^1.11.0, eth-contract-metadata@^1.13.0:
  version "1.13.0"
  resolved "https://registry.yarnpkg.com/eth-contract-metadata/-/eth-contract-metadata-1.13.0.tgz#9819d0e556ea2187da91d6b49ce96abc5fce2a73"
  integrity sha512-9CjXHX8IdXysUEvOHdbCsjdAwM1E98jaeK2HeOqm/9S/vOZ8YryaBBt/YSiBq3MkpCwf+d1pEQ53p96rsdy52w==
```

2020-04-29 20:04 UTC, whymarrh commented on yarn.lock
> +  integrity sha512-9CjXHX8IdXysUEvOHdbCsjdAwM1E98jaeK2HeOqm/9S/vOZ8YryaBBt/YSiBq3MkpCwf+d1pEQ53p96rsdy52w==
(I did just do this here on GH and didn't test it at all but this seems legit)

2020-04-29 20:05 UTC, whymarrh submitted a review, later dismissed
LGTM!

2020-04-29 20:16 UTC, Gudahtt submitted a review, later dismissed

2020-04-30 10:49 UTC, whymarrh approved these changes

2020-04-30 12:50 UTC, Gudahtt approved these changes

2020-04-30 12:50 UTC, merged