fix overflowing contract names and origins
MetaMask/metamask-extension pull request #8823
Opened 2020-06-16 18:43 UTC by brad-decker

Moves heading and subtitle into divs with h3/h2 children so that the
div can be display flex and still have ellipses overflow. Only the
heading was display flex but I wanted the two to have similar structure.
this allows subheading to be display flex in the future.

Also uses stripHttpSchemes to remove that from origin in the subheading

2020-06-16 18:53 UTC, brad-decker commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix overflow of action name and origin on the transaction list](https://trello.com/c/WwpScBVg/87-fix-overflow-of-action-name-and-origin-on-the-transaction-list)

2020-06-16 20:19 UTC, rachelcope commented
This looks great to me 🚀

2020-06-16 20:55 UTC, rekmarks requested changes
This looks much better!

Following recent examples of URL overflow handling, inspired by Chrome's URL style guide, the text-direction of overflowing URLs should be `rtl`, so that the ellipsis appears on the left, and the TLD is visible.

Ref: https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/components/app/connected-sites-list/index.scss#L26-L33

2020-06-16 20:59 UTC, brad-decker commented
@rekmarks so that would result in the status label/date being truncated instead of the domain?

2020-06-16 21:00 UTC, Gudahtt commented
I was just going to suggest the same thing!

It would require moving the `origin` to a separate element, so it could be truncated separately. I don't think it makes sense to truncate the date.

2020-06-16 21:00 UTC, brad-decker commented
or, is this suggestion to simply replace the first x characters of the domain with '...' and keep the status/date intact

2020-06-16 21:04 UTC, Gudahtt commented
As an alternative, you could truncate it entirely in JavaScript, but I don't see how that could be easily done without some fancy DOM measurement, so... probably easier to use a separate element 🤔

2020-06-16 21:09 UTC, brad-decker commented
Going to take some re-thinking no matter how it's done. This change has the truncation applied at the list-item level. In order to do this, I am going to have to override those defaults from the transaction-list-item level because not all list-items will have domains in the subtitle...

This means I'll likely need to change the type of the subtitle prop from just being a standard string to being an element.. which might be okay because currently there is the subtitleStatus node prop which may not be used outside of the transaction-list-item.

The next complexity is that not every type of transaction-list-item has an origin in the subtitle so we'd then have to do some checking...

Would anyone be opposed to the work involved in this being moved to a separate PR? I can open an issue to track it. The behavior in this PR is the correct default for everywhere there isn't a domain in the subtitle. cc @rekmarks @Gudahtt

2020-06-16 21:11 UTC, Gudahtt commented
I think it's fine to address separately. I don't like truncating the more-important part of the origin anywhere if we can help it, but in this case it's really not a security-sensitive part of the UI so... it's not the end of the world.

2020-06-16 21:11 UTC, Gudahtt submitted a review, later dismissed

2020-06-16 22:00 UTC, brad-decker commented
Meh i guess it wasn't as difficult as i expected... 

<details>
<summary>Screenshot</summary>

Before:
<img src="https://user-images.githubusercontent.com/4448075/84832325-a8f81b00-aff2-11ea-921b-842f9d66f59e.png" />

After:
<img src="https://user-images.githubusercontent.com/4448075/84832411-d5ac3280-aff2-11ea-9056-ec2eb4265ea6.png" />



</details>

I'm gonna clean this up. the code that produces the above screenshot is not yet a part of this PR but will be after cleanup. @Gudahtt @rekmarks

2020-06-16 23:19 UTC, rekmarks submitted a review, later dismissed
LGTM!

2020-06-17 02:02 UTC, Gudahtt commented on ui/app/components/app/transaction-list-item/index.scss
> +    direction: rtl;
```suggestion
    /*rtl:ignore*/
    direction: rtl;
```
We want this to be right-to-left even on right-to-left locales, but the build script to generate the rtl CSS file will flip this unless we tell it not to. This directive will ensure it stays as RTL for all locales

2020-06-17 16:22 UTC, Gudahtt approved these changes
LGTM!

2020-06-17 16:38 UTC, merged