New info tooltip component
MetaMask/metamask-extension pull request #9180
Opened 2020-08-11 13:47 UTC by danjm

This PR adds a component  that is an info icon with a tooltip. It can be used in places where we need to give the user information.

Demo gif:
![infotooltip](https://user-images.githubusercontent.com/7499938/89904987-28a20080-dbc4-11ea-957c-c9e7e78ae830.gif)

The gif is from the implementation in storybook, which can be seen by checking out the branch and running `yarn storybook`

2020-08-11 13:58 UTC, Gudahtt commented
I thought were were trying to deprecate this tooltip? `tooltip-v2` is being used in most places. I was hoping to get rid of this one.

2020-08-11 14:23 UTC, danjm commented
@Gudahtt Okay, I will update to use the v2 one. Meanwhile we should put comments in `ui/app/components/ui/tooltip.js` to indicate that it is being deprecated and should not be used or modified for any new work. (I didn't know that it was being depracated.)

2020-08-11 15:11 UTC, jakehaugen commented
Just mocked up these specs, can we have the text left-aligned and match this spacing / font color?

![Screen Shot 2020-08-11 at 9 11 06 AM](https://user-images.githubusercontent.com/11967476/89914700-9e04d580-dbb2-11ea-9104-fc76048a18aa.png)

2020-08-11 18:07 UTC, danjm commented
@Gudahtt updated to use tooltip-v2

@jakehaugen  updates were also made to match your image above. Updated gif:

![infotooltip-2](https://user-images.githubusercontent.com/7499938/89932700-9e1fc800-dbe8-11ea-9ff3-adc5379c2e88.gif)

2020-08-11 18:12 UTC, jakehaugen submitted a review, later dismissed

2020-08-18 16:16 UTC, brad-decker commented
@danjm work just landed that removes the old tooltip and renamed tooltip-v2 to tooltip. If you consume the component from the 'tooltip' folder it'll be the newest, sanctioned tooltip component. I hope that was English, I feel like I typed tooltip way too many times.

2020-08-18 16:18 UTC, brad-decker requested changes

2020-08-18 16:18 UTC, brad-decker commented on ui/app/components/ui/info-tooltip/info-tooltip.js
> +import Tooltip from '../tooltip-v2'
```suggestion
import Tooltip from '../tooltip'
```

2020-08-18 16:19 UTC, brad-decker requested changes

2020-08-18 16:19 UTC, brad-decker commented on ui/app/components/ui/tooltip-v2.js
> +          theme={theme}
You'll need to carry these changes over to `components/ui/tooltip/tooltip`

2020-08-18 17:54 UTC, danjm commented
@brad-decker I have rebased and updated this to reflect the latest changes on develop (as per your comments)

2020-08-18 18:00 UTC, brad-decker approved these changes
LGTM

2020-08-18 18:15 UTC, merged