Hide gas estimate on non-main network
MetaMask/metamask-extension pull request #9189
Opened 2020-08-12 14:55 UTC by PatrykLucka

This PR removes advanced gas settings option and three-button gas input (slow, average, fast) and shows the gas fields instead on all non-main networks.

Fixes: #9106 

<img width="360" alt="Screenshot 2020-08-12 at 16 49 00" src="https://user-images.githubusercontent.com/5708018/90029999-d217ed80-dcbb-11ea-9095-894d1b13f9dc.png">
<img width="359" alt="Screenshot 2020-08-12 at 16 48 50" src="https://user-images.githubusercontent.com/5708018/90030003-d6440b00-dcbb-11ea-878d-0cb03f562a9c.png">

2020-08-12 15:32 UTC, rekmarks commented
Hey Patryk 👋

To get the e2e tests passing, I _think_ we're going need to ensure that the advanced gas controls are enabled for non-Mainnet networks in tests, which can be done using the `process.env.IN_TEST` environment variable.

2020-08-13 14:58 UTC, rekmarks submitted a review, later dismissed
LGTM!

2020-08-13 16:22 UTC, whymarrh commented
Mind rebasing this on the latest `develop`? I think the `consistent-return` lint rule might want a value for the return.

2020-08-14 14:40 UTC, rekmarks commented on ui/app/pages/send/send-content/send-gas-row/send-gas-row.component.js
> +    if (advancedInlineGasShown === true && !process.env.IN_TEST) {
nit: it'd be more consistent with everything to skip the `=== true`
```suggestion
    if (advancedInlineGasShown && !process.env.IN_TEST) {
```

2020-08-14 14:41 UTC, rekmarks submitted a review, later dismissed

2020-08-14 15:05 UTC, rekmarks approved these changes

2020-08-14 22:21 UTC, rekmarks requested changes
@PatrykLucka upon review, I'm afraid I've failed to give you good advice on this PR. I'm sorry for the back-and-forth.

We should _not_ set the feature flag in order to implement this behavior. Rather, we should do this:
- If the network is Mainnet, the advanced gas controls showed be shown instead of the gas estimation _only if_ the `advancedInlineGas` feature flag is set to `true`.
- If the network is _not_ Mainnet, we should show the advanced gas controls, _regardless_ of the state of the `advancedInlineGas` feature flag.
  - _Unless_ we're in a test, in which case we should show the gas estimate.
    - We should only override the feature flag in tests if we have to. I think it's possible that we can leave it alone, and just make all networks behave like Mainnet in tests.

2020-08-14 22:25 UTC, Gudahtt commented on ui/app/store/actions.js
> +      dispatch(setFeatureFlag('advancedInlineGas', type !== 'mainnet'))
Wouldn't this have the effect of _enabling_ advanced inline gas for all users when they switched to mainnet? We'd still want this to be disabled unless the user turns it on.

2020-08-14 22:26 UTC, Gudahtt commented on ui/app/store/actions.js
> +      dispatch(setFeatureFlag('advancedInlineGas', type !== 'mainnet'))
:sweat_smile: @rekmarks this is covered by your comment

2020-08-17 07:41 UTC, PatrykLucka commented
Makes sense, thanks!

2020-08-17 14:40 UTC, rekmarks commented on ui/index.js
>    backgroundConnection.on('update', function (metamaskState) {
nit: unrelated whitespace deletion

2020-08-17 14:47 UTC, rekmarks submitted a review, later dismissed
LGTM!

2020-08-18 19:35 UTC, Gudahtt requested changes
Almost there! In my local testing, there is only one place remaining where ETH Gas Station data needs to be hidden.

2020-08-18 19:35 UTC, Gudahtt commented on ui/app/components/app/gas-customization/gas-modal-page-container/gas-modal-page-container.container.js
> +  const hideBasic = state.appState.modal.modalState.props.hideBasic || (!isMainnet && !process.env.IN_TEST)
Unfortunately the gas chart shown on the 'Advanced' tab is _also_ built using information from Eth Gas Station, so hiding the basic tab isn't especially helpful. It's the 'Edit' button on the transaction confirmation screen that leads here that needs to be hidden:

![advanced-gas-confirm](https://user-images.githubusercontent.com/2459287/90556931-11d54e00-e170-11ea-9087-42bca0c2bb2c.png)

2020-08-18 19:35 UTC, Gudahtt commented on ui/app/pages/confirm-transaction-base/confirm-transaction-base.component.js
> +            {advancedInlineGasShown || (!isMainnet && !process.env.IN_TEST)
The `ConfirmDetailRow` component above is where the "Edit" button is that we need to hide.

It looks like the `ConfirmDetailRow` component expects the `headerText` prop to always be passed in. I'd suggest making that prop optional, and omitting all three related props (`headerText`, `headerTextClassName`, and `onHeaderClick`) when on testnets.

2020-08-19 13:52 UTC, Gudahtt approved these changes
LGTM, thanks!

2020-08-19 14:03 UTC, merged