move footer buttons to scrollable area
MetaMask/metamask-extension pull request #9228
Opened 2020-08-14 12:37 UTC by PatrykLucka

Adds the confirm/cancel buttons to the scrollable region, so they cannot be clicked until all errors/warnings have been seen.

Fixes #9136

2020-08-14 13:52 UTC, tmashuang commented
Seems this change also effected the ConfirmApprove Screen which will not render the footer for that transaction screen. 
<details>
<summary>CI Failure Screenshot</summary>
<img src='https://user-images.githubusercontent.com/13376180/90256422-90419100-ddfa-11ea-9555-008e1cc4768e.png'>
</details>

The screenshot is not explicitly clear that the buttons for the footer are missing, but they are.

2020-08-17 15:30 UTC, brad-decker commented
Thanks @PatrykLucka! I'm pulling this down to review now.

2020-08-17 15:51 UTC, brad-decker commented
@tmashuang Your feedback has been resolved by the latest commit: 

<details> 
<summary>GOOD: Long error message</summary>

<img src="https://user-images.githubusercontent.com/4448075/90415329-8d52d480-e076-11ea-9799-59fdd1db4203.png" />


</details>

<details>
<summary>GOOD: Confirm approve screen</summary>

Horizontal scroll bar is pre-existing: <br />
<img src="https://user-images.githubusercontent.com/4448075/90415727-1ff37380-e077-11ea-92ce-7775becfd636.png" />

</details>

moving onto code review.

2020-08-17 16:07 UTC, brad-decker requested changes
Looks good, just one minor request

2020-08-18 11:18 UTC, PatrykLucka commented on ui/app/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
> +          onCancel={() => onCancel()}
Yup, you're right, it's cleaner, thanks!

2020-08-18 14:10 UTC, brad-decker approved these changes
Great, thanks @PatrykLucka!

2020-08-18 14:10 UTC, merged