Add hidden tokens to store
MetaMask/metamask-extension pull request #9320
Opened 2020-08-28 09:29 UTC by PatrykLucka

PR adds hidden tokens to store, to prevent adding them automatically if balance > 0 is detected.
Fixes #5055

2020-09-09 04:29 UTC, Gudahtt reviewed
The code looks good to me!

The only reservation I have is that this list of hidden tokens isn't visible to the user. This could be confusing, especially considering our old behaviour. Maybe we could add it in settings somewhere? :thinking:

Or perhaps this is fine for now, and we can add UI later as an enhancement?

2020-09-09 04:29 UTC, Gudahtt commented on app/scripts/controllers/preferences.js
> +  _updateAccountTokens (tokens, assetImages, hiddenTokens) {
Nit: it would be better to document this new parameter in the JSDoc block comment, and `assetImages` (which is also missing)

2020-09-21 02:27 UTC, miranda76 submitted a review, later dismissed

2020-11-05 23:08 UTC, rekmarks reviewed
Regardless of how this goes, we have some follow-up work to do:
- https://github.com/MetaMask/metamask-extension/issues/9813
- https://github.com/MetaMask/metamask-extension/issues/9814

2020-11-05 23:12 UTC, rekmarks requested changes

2020-11-05 23:12 UTC, rekmarks commented on app/scripts/controllers/preferences.js
> +      this.store.updateState({ tokens, hiddenTokens })
Shouldn't this call `_updateAccountTokens`?

2020-11-05 23:12 UTC, rekmarks commented on app/scripts/controllers/preferences.js
> +    this.store.updateState({ tokens, hiddenTokens })
Shouldn't this call `_updateAccountTokens`?

2020-11-09 16:24 UTC, darkwing commented
Oops, this is failing one test.  Please have another look @PatrykLucka !  Thank you!

2020-11-20 16:21 UTC, brad-decker commented
@rekmarks I think this is ready for another look

2020-11-20 21:09 UTC, rekmarks requested changes
There are a number of methods in the preferences controller related to adding, removing, or otherwise modifying identies/accounts, and they modify `accountTokens`. Shouldn't we also modify `accountHiddenTokens` in these cases?

2020-12-08 09:44 UTC, PatrykLucka commented
@rekmarks you're right, I updated preferences controller, please take a look.

2020-12-08 20:11 UTC, tmashuang commented
From a behavior stand point this PR fixes the issue with tracking, and persisting, tokens that the user hides. Whether we can/should optimize this to prevent duplicates of the accountHiddenTokens and hiddenToken is a point of contention, but we already do that for rendering tokens and accountTokens. 

Also to note, for tokens under a custom network there is no way to distinguish two different custom network sets of hidden tokens, they are all under the `rpc` property, same as accountTokens. 

LGTM!

2020-12-08 20:11 UTC, tmashuang approved these changes

2020-12-08 20:37 UTC, rekmarks approved these changes

2020-12-08 20:38 UTC, merged