Update swaps network fee tooltip
MetaMask/metamask-extension pull request #9614
Opened 2020-10-15 09:57 UTC by danjm

This PR updates the network fee tooltip in the fee card to match the latest designs https://www.figma.com/file/fDtda1cs3MmPXw1MgKswZc/Development---MetaSwaps?node-id=1315%3A1308

The tooltip has been moved from the max fee row to the estimated fee row and its content has been changed.

Demo gif:

![fee-card-gas-tooltip-update](https://user-images.githubusercontent.com/7499938/96108227-e5ac2400-0eb7-11eb-92b0-421acc728955.gif)

2020-10-15 14:18 UTC, brad-decker requested changes

2020-10-15 14:18 UTC, brad-decker commented on ui/app/pages/swaps/fee-card/fee-card.js
> +                    <div>{ t('swapGasFeeSummary') }</div>
Should these divs be paragraphs instead of divs to maintain semantic HTML?

2020-10-15 14:18 UTC, brad-decker commented on ui/app/pages/swaps/fee-card/fee-card.js
> +            <div className="fee-card__row-label fee-card__info-tooltip-container">
`Tooltip` exposes two props that would make two of these divs obsolete if we add them to `InfoTooltip`. `containerClassName` could be set to `fee-card__info-tooltip-content-container` and `wrapperClassName` could be set to `fee-card__row-label fee-card__info-tooltip-container` and then two extra divs are no longer necessary.

2020-10-15 14:18 UTC, brad-decker commented on ui/app/pages/swaps/fee-card/index.scss
> +    > div {
rather than relying on tag names I think I would prefer a classname be added to those `p` tags (if suggestion is taken, `div` if not)

2020-10-16 16:19 UTC, danjm commented
@brad-decker your comments have been addressed in the latest commit

2020-10-16 16:56 UTC, brad-decker approved these changes
Thank you @danjm looks good!

2020-10-19 08:25 UTC, merged