Add a minimumGasLimit to the original gas customization modal
MetaMask/metamask-extension pull request #9623
Opened 2020-10-16 17:35 UTC by danjm

An alternative to https://github.com/MetaMask/metamask-extension/pull/9600 that directly updates the existing gas customization modal, as opposed to the new swaps customization modal added in https://github.com/MetaMask/metamask-extension/pull/9599

We will still want to do https://github.com/MetaMask/metamask-extension/pull/9600, but doing it this way allows us to get this fix into prod faster, which will help reduce failed swaps.

2020-10-16 18:14 UTC, rekmarks requested changes
This PR does not account for the usage of the `gasLimitTooLow` locale message, which we find under the constant `GAS_LIMIT_TOO_LOW_ERROR_KEY` in `error-keys.js`, which is used to produce error messages in the `ConfirmPageContainerContent` component via the `getErrorKey` method of `ConfirmTransactionBase`.

Perhaps the simplest solution is to preserve the original `gasLimitTooLow` and create a new locale message that accepts a substitution?

2020-10-16 21:08 UTC, Gudahtt requested changes

2020-10-16 21:50 UTC, danjm commented on ui/app/components/app/gas-customization/advanced-gas-inputs/advanced-gas-inputs.component.js
> +    minimumGasLimit: PropTypes.number.isRequired,
Addressed in 466e4debb

2020-10-16 21:51 UTC, danjm commented
@rekmarks I've addressed your comment in 42cd1091c

2020-10-16 23:04 UTC, rekmarks approved these changes
LGTM!

2020-10-19 12:59 UTC, Gudahtt approved these changes
LGTM!

2020-10-19 13:11 UTC, merged