Savings tooltip and column
MetaMask/metamask-extension pull request #9666
Opened 2020-10-21 15:28 UTC by danjm

![Peek 2020-10-21 12-57](https://user-images.githubusercontent.com/7499938/96742114-1b13ae80-139d-11eb-97dd-3d05aca9e54f.gif)

2020-10-22 21:29 UTC, brad-decker requested changes

2020-10-22 21:29 UTC, brad-decker commented on ui/app/pages/swaps/fee-card/index.scss
> +    width: 294.95068359375px;
this is making the div *bigger* than its allowed screen size... I also don't think it's strictly necessary to make it look good. not a blocker, but these oddly specific pixel values are prone to breaking later.

2020-10-23 16:31 UTC, jakehaugen commented
Looking great. Gal and I discussed a few small tweaks:

- Remove verbal explanation of savings. 
- Adjust formatting of line item view (no parent container with border, HR on bottom and top of "Estimated savings" line)
- Add clarification of calculation below savings calculation (i.e. "Savings are calculated by comparing the best quote to the median quote.")
- Change negative values to UI4 (dark gray) vs. red.

![Screen Shot 2020-10-23 at 10 29 08 AM](https://user-images.githubusercontent.com/11967476/97029380-96e73580-151a-11eb-8cb4-aaa75ec74c4e.png)

2020-10-23 17:16 UTC, jakehaugen commented
We'll also need to cover the scenario when there are no savings. If there are no savings:
- Replace the "Saving ..." text and piggy bank icon with "Using the best quote".
- Do not show the savings tooltip.
- In the view all quotes table, do not show the "Overall savings" column, just highlight the best quote with the "Best" tag. 

![Screen Shot 2020-10-23 at 11 13 28 AM](https://user-images.githubusercontent.com/11967476/97033586-d022a400-1520-11eb-8e14-caaf5a99ed97.png)

2020-10-26 17:19 UTC, danjm commented
The updates to the tooltip designs most recently been requested by @jakehaugen have been added to this PR:
![Screenshot from 2020-10-26 11-14-06](https://user-images.githubusercontent.com/7499938/97205281-3403d180-179a-11eb-9e4d-28244eeb0779.png)

2020-10-26 17:21 UTC, danjm commented
The update to show the "Using best quote message" when there are no savings has been added to https://github.com/MetaMask/metamask-extension/pull/9629

2020-10-26 18:04 UTC, brad-decker commented
@danjm can you rebase this and i'll do another QA/review round

2020-12-07 17:45 UTC, danjm commented
Closing in favour of https://github.com/MetaMask/metamask-extension/pull/9905

2020-12-07 17:45 UTC, closed without merging