Swaps keyboard dropdown
MetaMask/metamask-extension pull request #9702
Opened 2020-10-23 19:35 UTC by darkwing

Explanation:  

At present the dropdowns used in swaps are not accessible via keyboard.  This PR makes it so that:
- Users can tab to the dropdown, press Enter, and then press tab to get from item to item, then press Enter to select one
- Pressing Escape closes the dropdown

Manual testing steps:  
  - Open each dropdown via Enter key, press Tab to move from item to item
  - Press Enter to select items
  - Open each dropdown via Enter key, press Escape to close the dropdown

Would be good for @danjm to review as I'd like to ensure everything looks good on Linux.

![Keyboard](https://user-images.githubusercontent.com/46655/97046387-e8a0b780-153c-11eb-95fd-5a2e3cf4ce89.gif)

2020-10-23 20:50 UTC, brad-decker requested changes
LGTM, just one suggested update

2020-10-23 20:50 UTC, brad-decker commented on ui/app/pages/swaps/dropdown-search-list/dropdown-search-list.js
> +  }, [onSelect])
```suggestion
  }, [close, onSelect])
```

without close being in the dependency array, `useCallback` would only get called anytime onSelect changes, which could result in holding onto a reference to the close function from previous renders (and also anything that also uses that reference to the close function).

2020-10-26 13:51 UTC, darkwing commented
This should be good to go.

2020-10-26 16:09 UTC, brad-decker approved these changes
Thanks, LGTM!

2020-10-26 16:10 UTC, merged