Add documentation and improve validation for swaps quotes and some of its properties
MetaMask/metamask-extension pull request #9730
Opened 2020-10-27 13:34 UTC by danjm

This PR does the following:

- improves the validation of `quote.trade.value`, `quote.sourceAmount` and `quote.destinationAmount` as returned by the metaswap-api `/trades` endpoint
- adds documentation for the objects returned by the the `/trades` endpoint
- corrects the type of the default values of `destinationAmount` and `sourceAmount` in quotesToRenderableData
- corrects the base parameter used when creating a BigNumber from `quote.trade.value` in view-quote.js (note that this previously did not cause any error/bug because if the first parameter to BigNumber is `0x` prefixed, then it will treat it as a hex, even if the second parameter is not 16)

2020-10-30 14:36 UTC, darkwing commented on ui/app/pages/swaps/swaps.util.js
> +    validator: (trade) => trade &&
Just for clarity, do we want to add this as a function like `stringIsValidDecimalNumber` is on line 38?  Maybe `const tradeIsValid = ....`.  Maybe just for clarity.

2020-11-03 17:53 UTC, darkwing commented on ui/app/pages/swaps/swaps.util.js
> +const stringIsValidDecimalNumber = (string) => !isNaN(string) && string.match(/^[.0-9]+$/u) && !isNaN(parseFloat(string))
`string.match(/^[.0-9]+$/u)` allows more than one "."; also, do we need both `!isNan` checks?  Doesn't one identify a problem?

Also, I think we should try to make these functions that we can write tests for.

2020-11-03 18:04 UTC, darkwing requested changes
Have an idea for improvement, also a question about testing.

2021-04-27 18:19 UTC, danjm commented
Closing for now. We should revisit this when we have time. @dan437 may wish to pick up some parts of this.

2021-04-27 18:19 UTC, closed without merging