Optimizing zh_CN translation
MetaMask/metamask-extension pull request #9772
Opened 2020-11-01 13:56 UTC by wanshan1024

Fixes: #

Explanation:  Optimizing zh_CN translation：
- Retain ”Gas“ instead of literal translation of ’天然气‘
- Fix Contract translation  to "合约"

2020-11-01 14:04 UTC, wanshan1024 commented
I have read the CLA Document and I hereby sign the CLA

2020-11-04 09:42 UTC, DDDDDanica commented on app/_locales/zh_CN/messages.json
> +    "message": "* 设定更高 Gas 价格，加快交易完成进度，提高网络快速处理机率，但无法保证每次均能够实现提速。"
Suggestion: `"message": "* 设定更高的 Gas 价格，加快交易的完成进度，提高网络快速处理机率，但无法保证每次均能够实现提速。"`

2020-11-04 09:42 UTC, DDDDDanica commented on app/_locales/zh_CN/messages.json
> +    "message": "CoinSwitch是以最优惠的价格交换超过300种加密货币的一站式平台。"
You need to add a space between english and chinese characters and numbers. 
```
"message": "CoinSwitch 是以最优惠的价格交换 300 多种加密货币的一站式平台。"
```

2020-11-04 09:42 UTC, DDDDDanica commented on app/_locales/zh_CN/messages.json
> +    "message": "请选择价格稍高的Gas，加快交易处理速度。*"
```
    "message": "请选择价格稍高的 Gas，来加快交易的处理速度。*"
```

2020-11-04 09:42 UTC, DDDDDanica commented on app/_locales/zh_CN/messages.json
> +    "message": "高级Gas控制"
```
高级的 Gas 控制
```

2020-11-04 09:42 UTC, DDDDDanica commented on app/_locales/zh_CN/messages.json
> +    "message": "请选择该选项，直接在发送和确认页面显示Gas价格和限制管理。"
```
直接在发送和确认页面显示 Gas 的价格和限制管理。
```

2020-11-04 09:42 UTC, DDDDDanica commented on app/_locales/zh_CN/messages.json
> +    "message": "使用您的硬件钱包，操作与以太坊账户制作相同。登录 dApps，发送 ETH ，购买和保存 ERC20 代币和非同质化代币如 CryptoKitties"
missing a period at the end of the sentence ~

2020-11-16 17:29 UTC, Gudahtt commented
Hey @wanshan1024 , thanks for the contribution!

Do you have time to review each of these suggestions?

2020-11-18 05:11 UTC, wanshan1024 commented on app/_locales/zh_CN/messages.json
> +    "message": "* 设定更高 Gas 价格，加快交易完成进度，提高网络快速处理机率，但无法保证每次均能够实现提速。"
Thanks DDDDDanica.

2021-01-08 03:04 UTC, rekmarks requested changes
One requested change, then this should be good to go!

2021-01-08 03:04 UTC, rekmarks commented on app/_locales/zh_CN/messages.json
> +    "message": "gasLimit 即您个人希望付出的最大 Gas 数量。"
There may be a more appropriate word than 限制, but we should definitely use the appropriate Mandarin for "limit" here:

```suggestion
Gas 的限制即您个人希望付出的最大 Gas 数量
```

In addition, we should add a message for `gasLimit`, which ought to be "Gas 的限制" or whatever is appropriate.

2021-01-08 05:03 UTC, astarinmymind commented on app/_locales/zh_CN/messages.json
> +    "message": "gasLimit 即您个人希望付出的最大 Gas 数量。"
I believe the following best captures the translation of: "Gas limit is the maximum amount of units of gas you are willing to spend."

```suggestion
    "message": "gasLimit 是您个人希望付出的最大 Gas 数量。"
```

2021-01-08 05:35 UTC, rekmarks commented on app/_locales/zh_CN/messages.json
> +    "message": "gasLimit 即您个人希望付出的最大 Gas 数量。"
越简单越好。

2021-01-08 08:22 UTC, rekmarks commented on app/_locales/zh_CN/messages.json
> +    "message": "gasLimit 即您个人希望付出的最大 Gas 数量。"
Per [this website](https://cypherpunks-core.github.io/ethereumbook_zh/13.html), I believe we should make the following changes @wanshan1024:
```
  "gasLimit": {
    "message": "Gas 限制"
  },
  "gasLimitInfoTooltipContent": {
    "message": "Gas 限制是您个人希望付出的最大 Gas 数量。"
  },
  "gasLimitTooLow": {
    "message": "Gas 限制至少要 21000"
  },
```

2021-01-08 08:23 UTC, rekmarks commented on app/_locales/zh_CN/messages.json
> +    "message": "gasLimit 即您个人希望付出的最大 Gas 数量。"
Please let me know if you disagree!

2021-01-08 08:49 UTC, wanshan1024 commented on app/_locales/zh_CN/messages.json
> +    "message": "gasLimit 即您个人希望付出的最大 Gas 数量。"
agree, thanks, I will change it later.

2021-01-08 10:09 UTC, wanshan1024 commented
translate 'Gas Limit' to 'Gas 上限'

2021-01-08 17:55 UTC, rekmarks commented on app/_locales/zh_CN/messages.json
> +    "message": "Gas 价格 (GWEI)"
```suggestion
    "message": "Gas 价格 (gwei)"
```

2021-01-08 17:56 UTC, rekmarks approved these changes
真好，太谢谢你了！

2021-01-08 18:19 UTC, merged