WIP: Fix BigNumber issues
MetaMask/metamask-extension pull request #9860
Opened 2020-11-11 23:39 UTC by darkwing

Fixes: #

Explanation:  

We switched to using `getBigNumber` in this commit:  https://github.com/MetaMask/metamask-extension/commit/24d7d1ae2add7422e7544d9a28b841d0374c5b0d ; unfortunately not all use cases are providing required parameters to guarantee expected values, so we should tidy that up.

2020-11-12 17:54 UTC, Gudahtt commented on ui/app/components/ui/token-input/token-input.component.js
> +      multiplicandBase: 16,
The multiplicand appears to be a decimal value here, not a hex value (the variable `decimalValue`).

2020-11-12 20:18 UTC, rekmarks requested changes
This is great cleanup work! There are some errors to fix and improvements to make, but all but one should be easy to implement!

2020-11-12 20:18 UTC, rekmarks commented on ui/app/helpers/utils/conversion-util.js
> +    throw new Error('No base provided to getBigNumber')
Ah, I see that we type check the base parameters in a lot of different places. We should probably create an `isValidBase(value: unknown): boolean` utility function, and use it for all the base type checks in this file.

2020-11-12 20:18 UTC, rekmarks commented on ui/app/helpers/utils/conversion-util.js
> +
See comment for `getBigNumber` above.

2020-11-12 20:18 UTC, rekmarks commented on ui/app/helpers/utils/conversion-util.js
> +  }
See comment for `gitBigNumber` above.

2020-11-12 20:18 UTC, rekmarks commented on ui/app/helpers/utils/conversion-util.js
> +  }
See comment for `gitBigNumber` above.

2020-11-12 20:18 UTC, rekmarks commented on ui/app/helpers/utils/token-util.js
> +    },
I'm still trying to figure out `contractExchangeRate`, but the base of `conversionRate` is definitely `10`.

2020-11-12 20:18 UTC, rekmarks commented on ui/app/helpers/utils/transactions.util.js
>      })
This function is called `sumHexes`, and both bases should be `16`. Following other suggestions in this review, the second parameter, `base`, should be renamed to `hexAmount`.

2020-11-12 20:18 UTC, rekmarks commented on ui/app/pages/send/send-content/send-amount-row/amount-max-button/amount-max-button.utils.js
> +        bBase: 10,
These should both be `16` (the parameters/operands are hexademical strings).

2020-11-12 20:20 UTC, rekmarks commented on ui/app/helpers/utils/token-util.js
> +    },
Update: both should be `10`. The `contractExchangeRate` comes from this data source (via the TokenRatesController): https://api.coingecko.com/api/v3/simple/token_price/ethereum?contract_addresses=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48&vs_currencies=eth

2020-11-12 20:50 UTC, rekmarks requested changes

2020-11-12 20:50 UTC, rekmarks commented on ui/app/helpers/utils/confirm-tx.util.js
> +      bBase: 16,
These lines should be deleted:
```suggestion
```

2020-11-12 20:51 UTC, darkwing commented on ui/app/helpers/utils/conversion-util.js
> +    throw new Error('No base provided to getBigNumber')
I left in the console.warn's for the sake of review debugging, but yep, I'll have those removed.

2020-11-12 20:56 UTC, rekmarks requested changes
Looking good! Just a few more things

2020-11-12 20:56 UTC, rekmarks commented on ui/app/helpers/utils/conversion-util.js
> +  return base !== undefined
Let's tighten up this type check:
```suggestion
  return base === 10 || base === 16
```

2020-11-12 20:56 UTC, rekmarks commented on ui/app/helpers/utils/conversion-util.js
> +  return base !== undefined
The alternative would be this, but I don't know if we ever want anything other than 10 and 16. Use this if you're not sure:
```javascript
return Number.isInteger(base) && base > 1
```

2020-11-12 20:56 UTC, rekmarks commented on ui/app/helpers/utils/confirm-tx.util.js
> +    return addCurrencies(acc, ethAmount, {
```suggestion
  return args.reduce((acc, fiatAmount) => {
    return addCurrencies(acc, fiatAmount, {
```

2020-11-12 21:05 UTC, rekmarks requested changes
One last thing:

For all the `Must specify [base] and [base]` messages, let's make them `Must specify valid [base] and [base]`.

2020-11-12 21:31 UTC, rekmarks approved these changes
LGTM!

2020-11-13 06:07 UTC, kumavis approved these changes

2020-11-13 06:08 UTC, merged