background - introduce observable store for configManager state
MetaMask/metamask-extension pull request #993
Opened 2017-01-11 19:23 UTC by kumavis

Updates #979
Updates #847

2017-01-11 19:29 UTC, danfinlay requested changes
Making a few changes, moving observable store into metamask controller.

2017-01-11 19:59 UTC, danfinlay approved these changes
I'm happy with this if the tests pass now. It will make metamask slightly more performant, and make it much easier to convert to async storage later on.

2017-01-11 20:01 UTC, danfinlay requested changes
Oh, thought of another way to change it:  The `loadData` method passed to `configManager` needs to pull from the observable store, not the options method, which can probably be removed.

I'll do it after lunch right now...

2017-01-11 21:00 UTC, kumavis commented
maybe better to set the `initState` from the outside after instantiating the `metamaskController` to make sure that works and is not awkward, as we will need to be able to do that from `background.js` when we move to async persistence

2017-01-11 21:03 UTC, kumavis commented on app/scripts/metamask-controller.js
> +    this.configManager.subscribe((state) => {
we will likely be replacing  `this.configManager.subscribe` with ` this.configManager.store.subscribe`, so I think doing it this way further complicates things

2017-01-11 21:31 UTC, flyswatter commented
Why wouldn't we just say "load initial state before starting MetaMask" is a requirement? That's the current situation, and it could also work with async loading.

2017-01-12 07:14 UTC, kumavis commented
created a new PR where I am experimenting with the pattern
https://github.com/MetaMask/metamask-plugin/pull/999

2017-01-17 23:03 UTC, kumavis commented
This one's going back to the drawing board a bit

2017-01-17 23:03 UTC, closed without merging