fix bug 9937
MetaMask/metamask-extension pull request #9938
Opened 2020-11-24 06:41 UTC by codeoneline

Fixes: #9937 

Explanation:  
file: `app/scripts/lib/account-tracker.js`
func: `syncWithAddresses (addresses)`
```
  syncWithAddresses (addresses) {
    ...
    this.addAccounts(accountsToAdd)             // error, it add new accouts in a async way,
    this.removeAccount(accountsToRemove)  // it remove accounts in a sync way, this should move before the async operate.
  }
```
this.addAccounts(accountsToAdd) => currentAccounts + newAccounts => wait and 'updateState(currentAccounts + newAccounts)'
this.removeAccount(accountsToRemove) => currentAccounts - abandonAccounts => immdiately updateState.
Infact, `currentAccounts + newAccounts` will finally updateState in the store. The true old is
```
1. const a = currentAccounts + newAccounts
2. const b = currentAccounts - abandonAccounts
3. updateState({accounts: b})
4. updateState({accounts: a})
```

Then `getSelectedAccount() `will be undefine, after you `removeAccounts`, so in `eth-overview.js` replace 
`const selectedAccount = useSelector(getSelectedAccount)` with
  ```
const address = useSelector(getSelectedAddress)
  let selectedAccount = useSelector(getSelectedAccount)
  if (!selectedAccount) {
    selectedAccount = {address: address, balance: '0x0'}
  }
```
to avoid crash

2020-11-24 07:18 UTC, codeoneline commented
I have read the CLA Document and I hereby sign the CLA

2020-12-01 16:54 UTC, brad-decker commented
@codeoneline could you fix up the lint issues while you're waiting for review? Thanks again for your contributions!

2021-01-21 17:50 UTC, Gudahtt requested changes
Thanks for the contribution! Most of these changes make sense to me, but I did have questions about the `eth-overview.js` part.

>Then getSelectedAccount() will be undefine, after you removeAccounts

Since `this.preferencesController.syncAddresses(addresses)` is called before `this.accountTracker.syncWithAddresses(addresses)`, it shouldn't be possible for `getSelectedAccount()` to be `undefined` anymore. The `syncAddresses` call should updated `selectedAddress` such that it's not among the accounts being removed.

Does that make sense? I think if we discard the `eth-overview.js` changes and rebase the `account-tracker.js` changes on `develop`, this PR will be good to merge. Let me know what you think!

2021-03-09 07:00 UTC, codeoneline reviewed
> Thanks for the contribution! Most of these changes make sense to me, but I did have questions about the `eth-overview.js` part.
> 
> > Then getSelectedAccount() will be undefine, after you removeAccounts
> 
> Since `this.preferencesController.syncAddresses(addresses)` is called before `this.accountTracker.syncWithAddresses(addresses)`, it shouldn't be possible for `getSelectedAccount()` to be `undefined` anymore. The `syncAddresses` call should updated `selectedAddress` such that it's not among the accounts being removed.
> 
> Does that make sense? I think if we discard the `eth-overview.js` changes and rebase the `account-tracker.js` changes on `develop`, this PR will be good to merge. Let me know what you think!

Othewise, It will give an error message like this:
`
TypeError: Cannot read property 'balance' of undefined
  at isBalanceCached (chrome-extension://opkjncnmjekcjbhhggfiaccpeokadple/ui.js:286327:85)
  at useSelectorWithStoreAndSubscription (chrome-extension://opkjncnmjekcjbhhggfiaccpeokadple/ui.js:197075:23)
  at useSelector (chrome-extension://opkjncnmjekcjbhhggfiaccpeokadple/ui.js:197151:12)
  at EthOverview (chrome-extension://opkjncnmjekcjbhhggfiaccpeokadple/ui.js:243241:55)
  at renderWithHooks (chrome-extension://opkjncnmjekcjbhhggfiaccpeokadple/ui.js:180425:18)
  at mountIndeterminateComponent (chrome-extension://opkjncnmjekcjbhhggfiaccpeokadple/ui.js:182959:13)
  at beginWork$1 (chrome-extension://opkjncnmjekcjbhhggfiaccpeokadple/ui.js:184327:16)
  at HTMLUnknownElement.callCallback (chrome-extension://opkjncnmjekcjbhhggfiaccpeokadple/ui.js:164501:14)
  at Object.invokeGuardedCallbackDev (chrome-extension://opkjncnmjekcjbhhggfiaccpeokadple/ui.js:164550:16)
  at invokeGuardedCallback (chrome-extension://opkjncnmjekcjbhhggfiaccpeokadple/ui.js:164605:31)
`

2021-03-18 18:40 UTC, Gudahtt commented on app/scripts/metamask-controller.js
> +    this.preferencesController.syncAddresses(accountsToTrack);
I don't think we want this :thinking: The accounts here are being previewed during the hardware connect process. This includes the current "page" that you're looking at. We don't want to add identities for each of these.

2022-08-16 20:54 UTC, brad-decker commented
@codeoneline did you want to carry this through to completion? You've had a few rounds of feedback and just want to make sure you saw @Gudahtt 's message.

2022-11-04 15:03 UTC, brad-decker commented
Thank you for your contribution @codeoneline. In an attempt to keep our PR queue clean and focus our review time we are closing pull requests that become stale. This doesn't mean we don't want your contribution, and we encourage you to reopen the PR once the changes/feedback requested is completed. Thank you again!

2022-11-04 15:03 UTC, closed without merging